### ISSUE TITLE
Pusher in the Web Worker scope

### ISSUE THREAD

**Issue by chrisdlangton** [pusher/pusher-js#112]
Pusher client libs cannot work in the Web Worker or Service Worker scope in the browser as its reliant on the window construct being present

I am experiencing heavy DOM lockup with Pusher due to the amount of post processing of the flat data Pusher can transport.
Our web site has peaked at 10k concurrents in Nov 2014. Needless to say the effects are widely complained about.

To eliminate the page animations lock and choppy scrolling I need to find a transport method alike to Pusher that works within the Web Worker and Service Worker scopes to put the post processing onto another thread so that it wont effect the DOM thread.

Any chance we will see this in Pusher before Nov 2015 comes around? If not we will need to invest in another product or build our own.

Thank you

**Comment by zimbatm** [comment]
Hi @chrisdlangton , what are your thoughts on handling this kind of traffic but with older browsers ? If pusher-js didn't have backward-compatible requirements it could be pretty slim.

**Comment by chrisdlangton** [comment]
@zimbatm due to the nature of these browser features there cannot be polyfill for older browsers, inherently any polyfill cannot create the feature in another thread thereby making the polyfill redundant.

Here is the implementation compatibility;
http://caniuse.com/#feat=serviceworkers

So the minimum target browsers would fall into this list.

**Comment by chrisdlangton** [comment]
@zimbatm its been a week - your thoughts on this?
I'm keen to get started on a solution here but wouldn't know where to start so your guidance here is greatly appreciated if i were to create a pull request.

Though if this issue is too great, would you raise this with your Zendesk team to get it in the official milestones?

We've paid for 24hours support in the past during our busy periods as well as a higher than premium account which needed to pass that 10k connection limit - I mention this only to get your attention on this matter that is of great importance to us.

**Comment by DanielWaterworth** [comment]
@chrisdlangton, is it the pusher-js library that is hogging CPU time or is it the your event handlers? In the latter case, could you just pass the events from the main thread to your webworkers to alleviate this load?

**Comment by leggetter** [comment]
Hi @chrisdlangton - could you please raise an issue in zendesk and provide the `app_id` for your application? Or raise the issue via your paid account? We'll be able to track this as a customer request.

Thanks.

**Comment by chrisdlangton** [comment]
@DanielWaterworth greatly appreciate your quick response.
The performance concerns locking up the browser is inheritly our own logic in the handlers and is not with the pusher-js library - which is why this issue was not raised in reference to the pusher-js library performance but rather its ability to be used in a Worker scope without access to the window object.

The first approach to solving our problem was following the MDN example of handing large structured data between broswer and worker threads via an ArrayBuffer. We experienced what appears to be the postMessage blocking the port preventing any other ArrayBuffer data being streamed in either direction, but i am not aware of any way to come to a conclusion on this observation. 
Additionally, all data is cloned and memory usage efectively doubled - this was measurable using chrome profiler.

We concluded that if we were to instanciate the WebSocket object in the Worker thread the communication between threads would be effectively halved as it would be one way, as well as the memory usage would not incure the cloned ArrayBuffer object effect keeping it to its current usage.

@leggetter I'll be sure to raise the feature request with them. Though I raised this issue with the hopes someone familiar with the source code here on Github could make a refactor to turn off access to the window object, or at the very least I was hoping to get insight as to how much work would be required to get the library working in a Worker.

Is there any chance someone familiar with the source code could look at the usage and access to the window object to see if its even a possible change and not a complete refactor or rewrite?

Just for reference: 
I've seen this sqlite implementation for the browser https://github.com/kripken/sql.js use an entirely new implementation to solve the worker scope issue - I'm hoping pusher does not have to come to that.

**Comment by DanielWaterworth** [comment]
AFAIK, the sticking point here is that our fallbacks require features present only in the main thread, (even DOM manipulation). As @zimbatm suggested, a pusher-js that only used WebSockets could be pretty slim, but that wouldn't be a minor refactor and we'd have to maintain both libraries.

**Comment by chrisdlangton** [comment]
@DanielWaterworth as the Workers do not need to worry about flash fallbacks or polling (though all 5 xhr constructs are available in Workers) due to the fact if your worker is created you have a modern browser not needing these, so, Pusher-js would only need the socket and xhr code.
If puser-js isn't modular enough to isolate the DOM access through configuration then my fears and your conclusion would be right - there would be a new library to maintain for workers.

From my understanding of the source code, from what i could follow, pusher-js looks very organised and modular. I still hope that there would be a way to compile a script using existing modules that would work in the worker if only the person assigned understood both workers and the entirety of the codebase too.

Feel free to close this issue if this ssems like an undoable task and I'll just go to support with the feature request and i just hoe they dont refer me back to the library like they did with the pusher-php issue i rased previously.

**Comment by leggetter** [comment]
* Unsupported fallbacks (SockJS - related https://github.com/sockjs/sockjs-client/issues/181) could be turned off via [enabledTransports configuration](https://github.com/pusher/pusher-js#enabledtransports-array). However, I believe we maintain our own branch of SockJS so work would be required there.
* online/offline detection - I'm not sure if this is possible within a web worker, but it can be tested
* reliance on a global `Pusher` so additional investigation would need to go into whether that is a problem. Using `self.Pusher` may be a solution.
* 20+ references to `window` that could potentially be updated to `self`
* Tests would need to be created to check the functionality within a web worker context

@chrisdlangton - we treat our libraries as part of our product so work beyond simple fixes is scheduled in the same way as as it is on our core platform. This happens during an iteration cycle. We presently have a 3.0.0 pending release which would be the first priority for work on pusher-js.

Please ask for me (Phil Leggetter) to be assigned the issue in zendesk.

**Comment by chrisdlangton** [comment]
@leggetter perfect - thank you very much for the attention to detail here. I'll be sure to refer to Zendesk support.

Thanks to everyone for your input on this matter.
