### ISSUE TITLE
Upgrade confusion

### ISSUE THREAD

**Issue by mondalaci** [pusher/pusher-js#113]
Previously, I simply downloaded 2.2.3 and it worked fine. This time I wanna use it via npm but `npm install --save pusher-js@2.2.3` outputted `Error: version not found: pusher-js@2.2.3`. When installing without specifying a version number I get 3.0.0 but there's no changelog entry for this version so I'm clueless about the breaking changes. Please clarify.

**Comment by dirkbonhomme** [comment]
I don't think Pusher < 3.0 is available on npm

**Comment by mondalaci** [comment]
Thanks for the info, @dirkbonhomme! Regardless, I could use a changelog for transitioning to 3.0

**Comment by dirkbonhomme** [comment]
https://github.com/pusher/pusher-js/blob/r3.0.0/CHANGELOG.markdown

**Comment by mondalaci** [comment]
Thanks!
