### ISSUE TITLE
Handshake error

### ISSUE THREAD

**Issue by mashhoodr** [pusher/pusher-js#114]
Im getting a weird HandShake error while using the 2.1.6 version of the PusherJS library.

Pusher : Error : {"type":"HandshakeError","error":{}}

Followed by two JS errors attached below:
<img width="1517" alt="screen shot 2015-07-03 at 16 23 39" src="https://cloud.githubusercontent.com/assets/890800/8498478/8d63a070-21a0-11e5-8f1b-afcef384333a.png">

Any ideas on what could be causing this? It has been working fine before, this just started happening recently.

**Comment by zimbatm** [comment]
Can you check that you are using the `new` keyword to instantiate the Pusher object ?
```js
// bad
var pusher = Pusher(/*...*/)
// good
var pusher = new Pusher(/*...*/)
```

**Comment by mashhoodr** [comment]
Yes I am using the new keyword when initialising the object.

**Comment by zimbatm** [comment]
How come there is both a `pusher_2.1.6.js` and a `pusher.min.js` file in the logs ? Is it possible that two competing and different versions are included on the page ?

**Comment by mashhoodr** [comment]
Oh, I thought the pusher library was including pusher.min, turns out it was the chatlio widget which is in conflict. Will investigate on this. Thanks!

**Comment by zimbatm** [comment]
Great ! Please re-open this issue if the issue isn't solved.

**Comment by mashhoodr** [comment]
It was because of a version conflict. I updated to 2.2 (same as their pusher version) which fixed the issue.

**Comment by zimbatm** [comment]
Great :)
