### ISSUE TITLE
Private channel callback data on subscription:succeeded

### ISSUE THREAD

**Issue by RMK147** [pusher/pusher-js#115]
I am trying to get the data sent back from the server, after connecting to a private Pusher channel. The following code works for a presence channel:

this.presenceChannel = this.pusher.subscribe('presence-chat');

this.presenceChannel.bind('pusher:subscription_succeeded', function(data){

   //I can access all of the data here as expected
   console.log(data);

});

But when I try the same approach with a private channel:

this.privateChannel = this.pusher.subscribe('private-user');

this.privateChannel.bind('pusher:subscription_succeeded', function(data){

    //This returns an empty Object {}
    console.log(data);

});

The interesting thing is, in the POST request data I can see the data that I am trying to access, but I can't figure out why I can't access it like I can for presence channels:

{"auth":"a146722cb55df886314f:7326fb3e1c807a679b4d4d5e5742fddc121d5ec18f5f078d054962b0267972a4","channel_data"
:"{\"data\":\"test\"}"}

**Comment by pl** [comment]
Hi @RMK147,

`channel_data` is a field that contains user's data for a given channel, so it's a presence-only feature. Private channels don't have a concept of users, the signature is only used for authorization.

https://pusher.com/docs/client_api_guide/client_events#subscription_succeeded
https://pusher.com/docs/authenticating_users#implementing_presence_endpoints

**Comment by RMK147** [comment]
Hello,

Thanks for the response, I was just interested as I could see the data I wanted in the response being sent back. Is there anyway to access this data?

**Comment by pl** [comment]
For the time being there's no way to access this data - it's passed internally between the authorizer and the channel before being sent to Pusher. You'd have to patch the Channel object to emit it somehow.

Can I ask why you need the data from the auth callback? Maybe there's a simpler solution that won't require changing the library.

**Comment by RMK147** [comment]
I wanted to send the user the last X messages sent, once they have connected. Would I have to send an AJAX request on the subscription_succeeded event to be able to this?

**Comment by pl** [comment]
At the moment we don't support retrieving archival events (and it will probably have an API that won't work for your use-case), so you have to handle it in your application.

**Comment by RMK147** [comment]
I am using the PHP Pusher library and there is this function for when joining a presence channel:

	public function presence_auth( $channel, $socket_id, $user_id, $user_info = false )
	{

		$user_data = array( 'user_id' => $user_id );
		if($user_info == true)
		{
			$user_data['user_info'] = $user_info;
		}

		return $this->socket_auth($channel, $socket_id, json_encode($user_data) );
	}

Even though I am sending back some $user_data and I can see it in the response, I can't access it in the callback. Is this a limitation or am I doing something wrong?

**Comment by pl** [comment]
Hi,

Can you share your client code for the presence channel callback and show how the auth response looks like? I am not aware of any bug in pusher-js or in the PHP library, so the problem is probably somewhere in the integration.

**Comment by RMK147** [comment]
Here is my client side code:

var chat = {

        init: function(){


                this.pusher = new Pusher('key', {authEndpoint: 'chat/join'});
                this.presenceChannel = this.pusher.subscribe('presence-chat');
                this.privateChannel = this.pusher.subscribe('private-user1');

                this.bindEvents();

        },

        bindEvents: function(){

            var that = this;

            this.presenceChannel.bind('pusher:subscription_succeeded', function(data){
                console.log(data) //contains all the data I want
            });

            this.privateChannel.bind('pusher:subscription_succeeded', function(data){
                console.log(data); //doesn't contain anything, but I can see it in the response in developer tools
            })

        }
    };

    chat.init();

And the PHP is as follows: (my previous snippet was wrong)

return $this->pusher->socket_auth('private-user1', $socketId, json_encode(['data' => 'see this in the response but cant access it from the javascript callback']));

**Comment by pl** [comment]
I see - you're trying to submit user data to a private channel and receive it on subscription succeeded. This is not supported by private channels.

You'd need to either use a presence channel (which might be an overkill) or retrieve the auth data outside of Pusher context by sending a separate auth request or intercepting one for the presence channel.
