### ISSUE TITLE
not defined error

### ISSUE THREAD

**Issue by ImranAhmed** [pusher/pusher-js#116]
Great library, used it a few times.

This time I decided to install via Bower. I am initialising as follows:

require("pusher");

However I am getting the following error on page load.

Uncaught ReferenceError: Pusher is not defined

Any ideas. If I add a reference to the library via a script tag it works fine but would be nice to get working with require.

**Comment by leggetter** [comment]
@ImranAhmed - If you install via Bower then I'd generally expect you to still have to include a script tag unless you're using some form of custom build process.

If you install version 3.0 via NPM (`npm install pusher-js`) you can...

```js
var Pusher = require('pusher-js');
```

The `pusher` package in Bower is the Pusher-browser focused JS library. The `pusher` package in NPM is the library for interacting with the Pusher HTTP API. `pusher-js` is the browser-focused library.

**Comment by ImranAhmed** [comment]
Thanks, makes sense.

**Comment by RizwanBlogger** [comment]
D:\xampp\htdocs\NewOfficeBoy>npm install pusher-js
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'echo@0.1.9',
npm WARN EBADENGINE   required: { node: '0.2.6' },
npm WARN EBADENGINE   current: { node: 'v18.17.0', npm: '9.6.7' }
npm WARN EBADENGINE }

up to date, audited 62 packages in 6s

6 packages are looking for funding
  run `npm fund` for details

3 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.

this error
