### ISSUE TITLE
Encrypt connection by default

### ISSUE THREAD

**Issue by leggetter** [pusher/pusher-js#118]
Right now this needs to be manually configured:

``` js
var pusher = new Pusher(KEY, {encrypted:true});
```

Encrypted should now be the default.

**Comment by hph** [comment]
Updating the library to be encrypted by default requires a surprising amount of changes. I've added this to a list of things to do, but I've not started working on it. If someone feels strongly about this, let me know and we can collaborate on a PR. I'm closing this PR to remove noise.
