### ISSUE TITLE
Can not subscribe to channel when origin is NOT none

### ISSUE THREAD

**Issue by cjmling** [pusher/pusher-js#120]
Looking into "debug console" I when I see origin as something www.MYWEBNAME.dev I can not subscribe to the channel. ( there is no error as well )  But when i see origin as NONE i can successfully subscribe.

I found this when I was making chat box and I open chrome in incognito modes.  The incognito mode one was seeing origin as NONE and was successfully subscbribe but the other one was seeing origin as "www.mywebname.dev" it could not subscribe.  

Later my incognito browser start seeting origin as "www.mywebname.dev" too so then that too can not subscribe.

Later then I try firefox which see origin as NONE and then it could subscribe.  So I am wondering is there any issue with origin to able to subscribe or not ?

// The origin thing i see as NONE or www.mywebname.dev  I see in debug console

**Comment by leggetter** [comment]
Could you please provide the debug output from the Pusher JavaScript library:
https://pusher.com/docs/debugging#pusher_logging

It'll provide us with internal information regarding what the pusher-js library is doing.

**Comment by cjmling** [comment]
Ok now since posted this issue , I stopped working on my codes. ( I didn't edit anything )  I resume my work to do debugging as you said above and I am seeing origin as NONE and pusher seems to able to subscribe successfully.  Here is the output what it is showing now.

Pusher : State changed : initialized -> connecting
app.js:150 Pusher : Connecting : {"transport":"xhr_streaming","url":"http://sockjs.pusher.com:80/pusher/app/50beae64856e06065a8f?protocol=7&client=js&version=2.2.4"}
app.js:150 Pusher : State changed : connecting -> connected
app.js:155 connected
app.js:150 Pusher : Event sent : {"event":"pusher:subscribe","data":{"auth":"50beae64856e06065a8f:ff72fcb711d7dba28ec889448e6958219176486255c3aed55dea697fc09c464c","channel":"private-messaging"}}
app.js:150 Pusher : Event recd : {"event":"pusher_internal:subscription_succeeded","data":{},"channel":"private-messaging"}
app.js:162 subscription_succeeded

![screen shot 2558-09-14 at 8 01 51 pm](https://cloud.githubusercontent.com/assets/1612187/9850259/9b680094-5b1b-11e5-87dc-fb2e33db3ad4.png)
![screen shot 2558-09-14 at 7 57 48 pm](https://cloud.githubusercontent.com/assets/1612187/9850261/9eab9b62-5b1b-11e5-8879-dc0d673e397a.png)


I will post look into logs again later and post the logs here again when it stop working or I don't see origin as NONE

**Comment by cjmling** [comment]
OK now it is no longer subscribing and origin is NOT none. it is something like www.websitename.dev.  Here are the logs

```
Pusher : State changed : initialized -> connecting
app.js:150 Pusher : Connecting : {"transport":"ws","url":"ws://ws.pusherapp.com:80/app/50beae64856e06065a8f?protocol=7&client=js&version=2.2.4&flash=false"}
app.js:150 Pusher : State changed : connecting -> connected
app.js:155 connected
app.js:150 Pusher : Event sent : {"event":"pusher:subscribe","data":{"auth":"50beae64856e06065a8f:51d526645eff53728866ebc8b88c3ef3a463aea1419b13afee5209c1434becfd","channel":"private-messaging"}}
```

![screen shot 2558-09-14 at 8 49 11 pm](https://cloud.githubusercontent.com/assets/1612187/9851343/60b756b4-5b22-11e5-9000-4a5f97860092.png)

**Comment by cjmling** [comment]
Can router be creating issue with this? Because I just try this example http://progress-bar-tutorial.herokuapp.com/ with me connected with router network and it doesn't work either.

But when I switch to use 3G network it works fine. 

Any setting would you suggest to look into my router setting ?

**Comment by cjmling** [comment]
As it was requested through support, i am posting here as well. The screen shots of the test page when  I was at office ( which seems to be working ) and when I was at home ( which doesn't seems to be able to subscribe )

![screen shot 2558-09-21 at 5 43 32 pm](https://cloud.githubusercontent.com/assets/1612187/10014212/fbcdf304-6141-11e5-99e2-e370f85b9597.png)

2nd pic

![screen shot 2558-09-22 at 3 42 42 pm](https://cloud.githubusercontent.com/assets/1612187/10014220/060487d4-6142-11e5-9643-f842493f842e.png)

**Comment by vivangkumar** [comment]
Hi @cjmling I'm closing this issue as it isn't an issue with the pusher-js library and more of a support ticket, which you've already raised and is being looked at.

Thanks!

**Comment by amerikan** [comment]
@cjmling did you get a solution for this? Having similar problem. Thanks!

**Comment by cjmling** [comment]
@amerikan  this problem had long conversation with the support team and they could not help either.

**Comment by RyanMustofa** [comment]
hallo im have same problem
![2020-05-19-124839_1366x768_scrot](https://user-images.githubusercontent.com/56658441/82394078-3424d600-9a72-11ea-8c6c-bb6959938e86.png)
