### ISSUE TITLE
Document CDNJS CDN

### ISSUE THREAD

**Issue by zimbatm** [pusher/pusher-js#122]
https://cdnjs.com/libraries/pusher is an alternative CDN that our users can use.

Reasons to use:
- js.pusher.com is down or they just want a fallback
- they already source other libraries from CDNJS, meaning the browser can re-use existing TCP connections.

CDNJS automatically updates the library when it's pushed to NPM.

/cc @leggetter

**Comment by leggetter** [comment]
My reasons against this were:

1. We have our own CDN that we control and can instantly push to. ~~We can't control when CDN JS is updated.~~
2. ~~If we are going to list CDNJS then we should push updates to it as part of the release process. This isn't part of the release process right now.~~

The fact that CDNJS update from NPM nullifies my arguments against it. We should add it back.

**Comment by zimbatm** [comment]
Yup. Previously the updates where manual but they started using npm and recently switched our lib to it: see https://github.com/cdnjs/cdnjs/commit/65d5b229cc0b99c644c1e1e504bb45b3ca96cd00 (13 days ago)

**Comment by michael-go** [comment]
current Pusher version in cdnjs in 3.0.0, can you please update it to the already released 3.1.0?

thanks!

**Comment by hph** [comment]
[This commit](https://github.com/pusher/pusher-js/commit/4f06772af4c4d2877c8fcf9938111652fa574319) should address the issue.
