### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'this._callbacks')

### ISSUE THREAD

**Issue by froodian** [pusher/pusher-js#125]
Unfortunately we don't have a ton of info on this but some of our users (looks like a couple users repeatedly across the span of the past few months) have been getting an unhandled javascript error of `TypeError: undefined is not an object (evaluating 'this._callbacks')`, which appears to be coming from the pusher.js library. Is it possible this is a bug in the pusher js library?

**Comment by zimbatm** [comment]
Hi @froodian,

we do have a `this._callbacks` in `src/events_dispatcher.js`. I had a cursory look and didn't see anything obvious.

Can you give me a bit more info on the affected browser and pusher-js version that you are using ?
I recommend installing something like Sentry ( https://docs.getsentry.com/hosted/clients/javascript/ ) to collect backtraces as well if you can.

**Comment by froodian** [comment]
Hi @zimbatm - thanks for the sentry recommendation, it looks like it has some good features especially in regards to sourcemaps, I'll look into that.  In the mean time, I can give you some info - the browser user agent is `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/601.2.4 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.4`, and we're using pusher-js 3.0.0.  I also have a stack trace that unfortunately is a little obfuscated by our requirejs setup, but at least gives you the method chain that got to the error:

```
https://dashboard.appboy.com/assets/dashboard-require-init-62a34b59011dc0bb2db5300933e5f9576f9c90bd9423a34fea2d72b096a28260.js:1:2184667
apply@https://dashboard.appboy.com/assets/dashboard-require-init-62a34b59011dc0bb2db5300933e5f9576f9c90bd9423a34fea2d72b096a28260.js:1:2178191
remove@https://dashboard.appboy.com/assets/dashboard-require-init-62a34b59011dc0bb2db5300933e5f9576f9c90bd9423a34fea2d72b096a28260.js:1:2184610
unbind@https://dashboard.appboy.com/assets/dashboard-require-init-62a34b59011dc0bb2db5300933e5f9576f9c90bd9423a34fea2d72b096a28260.js:1:2183933
c@https://dashboard.appboy.com/assets/dashboard-require-init-62a34b59011dc0bb2db5300933e5f9576f9c90bd9423a34fea2d72b096a28260.js:1:2195624
abort@https://dashboard.appboy.com/assets/dashboard-require-init-62a34b59011dc0bb2db5300933e5f9576f9c90bd9423a34fea2d72b096a28260.js:1:2195834
abort@https://dashboard.appboy.com/assets/dashboard-require-init-62a34b59011dc0bb2db5300933e5f9576f9c90bd9423a34fea2d72b096a28260.js:1:2194698
abort@https://dashboard.appboy.com/assets/dashboard-require-init-62a34b59011dc0bb2db5300933e5f9576f9c90bd9423a34fea2d72b096a28260.js:1:2194356
i@https://dashboard.appboy.com/assets/dashboard-require-init-62a34b59011dc0bb2db5300933e5f9576f9c90bd9423a34fea2d72b096a28260.js:1:2191035
apply@https://dashboard.appboy.com/assets/dashboard-require-init-62a34b59011dc0bb2db5300933e5f9576f9c90bd9423a34fea2d72b096a28260.js:1:2178191
abort@https://dashboard.appboy.com/assets/dashboard-require-init-62a34b59011dc0bb2db5300933e5f9576f9c90bd9423a34fea2d72b096a28260.js:1:2190820
abort@https://dashboard.appboy.com/assets/dashboard-require-init-62a34b59011dc0bb2db5300933e5f9576f9c90bd9423a34fea2d72b096a28260.js:1:2192600
abortConnecting@https://dashboard.appboy.com/assets/dashboard-require-init-62a34b59011dc0bb2db5300933e5f9576f9c90bd9423a34fea2d72b096a28260.js:1:2210504
disconnectInternally@https://dashboard.appboy.com/assets/dashboard-require-init-62a34b59011dc0bb2db5300933e5f9576f9c90bd9423a34fea2d72b096a28260.js:1:2210580
https://dashboard.appboy.com/assets/dashboard-require-init-62a34b59011dc0bb2db5300933e5f9576f9c90bd9423a34fea2d72b096a28260.js:1:2211020
https://dashboard.appboy.com/assets/dashboard-require-init-62a34b59011dc0bb2db5300933e5f9576f9c90bd9423a34fea2d72b096a28260.js:1:2176995
https://dashboard.appboy.com/assets/dashboard-require-init-62a34b59011dc0bb2db5300933e5f9576f9c90bd9423a34fea2d72b096a28260.js:1:2176757
```

**Comment by zimbatm** [comment]
@froodian : How hard would it be for you to reproduce the issue with the JavaScript unminified ?
It looks like the user agent is the Safari from the beta OSX El Captain. Maybe they changed something in their JavaScript engine, or maybe it's the minification.

**Comment by andrewk** [comment]
We get this on 99designs as well. Exclusively Safari 9 + OSX 10.10.

**Comment by bradleypriest** [comment]
We've had this 12,000 times in the last 2 months. Doesn't seem to be restricted to Safari either (although it is the main culprit

![screen shot 2015-11-22 at 2 27 18 pm](https://cloud.githubusercontent.com/assets/167215/11322409/3933b0f4-9125-11e5-9608-97b1cd5c61e7.png)

**Comment by zimbatm** [comment]
I have upgraded to El Captain but am still not able to reproduce the issue. If anyone is able to or has a URL that I can that has the error please let me know. If you'd rather not share the URL publicly you can send a [support request](https://support.pusher.com/hc/en-us) and mention my name and/or link to this issue and I will take a look at it tomorrow.

**Comment by jackfranklin** [comment]
@bradleypriest out of interest, are you running your JS in strict mode? That wouldn't stop the site working or not, but it looks like the error might be down to `this` being `undefined` on the line `this._callbacks`. 

Looking at the code I can't envisage a situation where that would happen (the `this._callbacks` code resides in a function that explicitly applies the fn with the scope), which makes it all the more weirder. In your code that calls into Pusher and triggers this, are you doing anything to change the scope, by binding the function, etc?

**Comment by bradleypriest** [comment]
Most of our code is running in strict mode, I'm not sure if the pusher script is.

I've had a dive into it myself, and I agree there is no obvious cause for `this` being undefined.

```
TypeError: undefined is not an object (evaluating 'this._callbacks')
  at nrWrapper(/:6:13615)
  at apply(raven.js:1251:28)
  at disconnectInternally(/3.0/pusher.min.js:81:171)
  at abortConnecting(/3.0/pusher.min.js:81:95)
  at abort(/3.0/pusher.min.js:46:511)
  at abort(/3.0/pusher.min.js:50:221)
  at abort(/3.0/pusher.min.js:51:53)
  at abort(/3.0/pusher.min.js:53:148)
  at q(/3.0/pusher.min.js:52:451)
  at unbind(/3.0/pusher.min.js:29:459)
  at remove(/3.0/pusher.min.js:31:116)
  at apply(/3.0/pusher.min.js:18:431)
  at ? (/:6)
```

I'm not sure if it's a coincidence, but the last few incidents I see had session durations of multiple hours, so it may be due to sleep/wake or something?

**Comment by dennis27** [comment]
Just curious if anyone is still having this problem?

**Comment by bradleypriest** [comment]
Yep. Still hitting us just as often. 






On Mon, Feb 8, 2016 at 6:08 AM -0800, "Dennis Vaughn" <notifications@github.com> wrote:












Just curious if anyone is still having this problem?

**Comment by dennis27** [comment]
Our users are saying that the entire page "locks up".  I have not been able to verify this is the bug that is causing this but everything points to this at the moment.  It is isolated to our users that are using a feature of our app that uses pusher and its only users on safari.  We see this error in our error reporting app but we have tried unsuccessfully to reproduce it.

**Comment by rastasheep** [comment]
We have experienced this issue too (very frequently).

It seems that occurs only on Safari 9.0 and 9.1.
We're using version 2.2 of PusherJS.

```
TypeError: undefined is not an object (evaluating 'this._callbacks')
  at i(/assets/application-937de655dc9b5f258096b74f1ca50d0ef5830dd23064c203b8e19df2bdc69fdc.js:47:1685)
  at disconnectInternally(/2.2/pusher.min.js:98:235)
  at abandonConnection(/2.2/pusher.min.js:103:193)
  at unbind(/2.2/pusher.min.js:32:316)
  at remove(/2.2/pusher.min.js:33:482)
  at apply(/2.2/pusher.min.js:20:24)
```

**Comment by jrr** [comment]
Affecting us too, using pusher-js 3.0.0 via ember-pusher. I don't have a good non-minified repro, but I can provide a little more telematics data:

_Browsers_
```
Safari 9.0.1
Safari 9.0.2
Safari 9.0
Safari 9.0.3
```

_Browser engines_
```
AppleWebKit 601.2.7
AppleWebKit 601.3.9
AppleWebKit 601.1.56
AppleWebKit 601.4.4
AppleWebKit 601.1.46
```


_Browser platforms_
```
Intel Mac OS X 10_10_5 Macintosh
Intel Mac OS X 10_9_5 Macintosh
Intel Mac OS X 10_11_2 Macintosh
Intel Mac OS X 10_11_3 Macintosh
Intel Mac OS X 10_11_1 Macintosh
CPU OS 9_1 like Mac OS X iPad
Intel Mac OS X 10_11 Macintosh
CPU iPhone OS 9_1 like Mac OS X iPhone
CPU OS 9_0_2 like Mac OS X iPad
```

**Comment by colindresj** [comment]
Also running into this quite often. 1.1k times in the past month. Pretty much the same browser stats as @jrr above

**Comment by jackfranklin** [comment]
Is anyone able to consistently reproduce this? We're trying to get this sorted but reproducing it is tricky. If anyone can provide a detailed stack trace that'd be great, any extra info on this one would be much appreciated and help us track it down.

**Comment by jpatel531** [comment]
@jrr is your usage of ember pusher minified too?

I have a feeling it might be due to minification, but still I can't reproduce the issue :/

**Comment by jpatel531** [comment]
It's not minification. I've managed to reproduce this locally. It's utterly bizarre. 

Before the offending line in CallbackRegistry#remove, I simply type `console.log('hello')`, it gets fixed. Any ideas @jackfranklin ? I'm 99% sure it's a bug in Safari

**Comment by zimbatm** [comment]
Maybe it doesn't like the `name` variable being shadowed. Try renaming the inner `name` variable to `name_`

**Comment by esetnik** [comment]
I'm having the same issue. I've seen hundreds of exceptions with this signature in Safari 9 on Rollbar. Please let me know if there's anything I can do to help.

**Comment by zimbatm** [comment]
pusher-js 3.1.0 is going to be released tomorrow and it contains a fix for this

**Comment by jpatel531** [comment]
3.1 is released - hopefully this issue should be gone

**Comment by kevinleeTCA** [comment]
We also suffered from this issue on safari 9.1.
We will try refresh pusher to 3.1 to see whether it will fix the problem, thank you guys

**Comment by jamesmfriedman** [comment]
3.1 does not fix this problem 
![image](https://cloud.githubusercontent.com/assets/975256/16047566/86a9b974-321e-11e6-93d2-d930f206df3c.png)
