### ISSUE TITLE
IOS9: Enable App Transport Security.

### ISSUE THREAD

**Issue by Moussawi7** [pusher/pusher-js#127]
Dear, 
I have a mobile application that use pusher to communicate with my server.
Anyway, Now Apple introduced [App Transport Security](https://developer.apple.com/library/prerelease/ios/technotes/App-Transport-Security-Technote/index.html) so the developer have to whitelist the domains.
Please I need to know all domains used by pusher?(i cannot find them in the documentation).
Thanks.

**Comment by zimbatm** [comment]
Hi @Moussawi7,

are you getting any errors on iOS9 ?

In my understanding the domains only need to be whitelisted if they don't follow the security standards enforced by iOS9. I just updated the SSL certs list on Monday so everything should work now. I didn't directly check with iOS9 so let me know if you're having any issues.

Best,
z

**Comment by Moussawi7** [comment]
Hi @zimbatm ,
Yes you are right, "domains only need to be whitelisted if they don't follow the security standards enforced by iOS9".
And I already tested my application without whitelisting any of **pusher** domains, and everything gonna fine.
Sorry for bothering you.

**Comment by zimbatm** [comment]
No worries, it's good to know that it's working :)
