### ISSUE TITLE
Not connection to AUTH endpoint

### ISSUE THREAD

**Issue by fotoKrille** [pusher/pusher-js#131]
I am having problem that pusher is not triggering AUTH endpoint.
```
var pusher = new Pusher("#{PUSHER_KEY}", {
            authEndpoint: "http://example.com/pusher/auth",
        });
```

I can se in my node js server that is has not try to connect to my endpoint. Also in the browser there is no AJAX request to that endpoint.

**Comment by hamchapman** [comment]
Are you then calling `pusher.subscribe('[private|presence]-`...)` at some point?

It's the call to `subscribe` that will trigger a call to your auth endpoint

**Comment by hamchapman** [comment]
Hey @fotoKrille, is this still a problem?

**Comment by fotoKrille** [comment]
Yes i got it to work, i do not think there where pusher fault tho...

**Comment by JoKeRxbLaCk** [comment]
Hi @fotoKrille I have the same issue, how did you get it work?

**Comment by Zolboo05** [comment]
Hi @fotoKrille I have the same issue, how did you get it work?

**Comment by shubham-jangid** [comment]
Hey @Zolboo05 , did you get it work ? I'm also facing this issue.
