### ISSUE TITLE
Provide a pure Websocket based javascript client for HTML5 cross platform desktop application frameworks

### ISSUE THREAD

**Issue by rock59** [pusher/pusher-js#133]
HTML5 cross platform desktop application frameworks like Atom-Electron , NWJS and CEF are becoming popular. These frameworks use Chromium Content Module thus websocket is always available.
Could you provide an official pure Websocket based javascript client for using by these framewokrs? I think testing and debugging websocket transport is easier than http based transports...

**Comment by pl** [comment]
Hi @rock59,

HTTP-based transports are required not only for fixing browser-compatibility issues, but also to work around some network configurations that break WebSockets. Even though modern browsers expose the WebSocket API, some clients have to fall back to HTTP anyway.

You can always whitelist only WebSocket-based transports in the Pusher constructor, but then you're risking some of your clients not being able to connect to Pusher:
https://github.com/pusher/pusher-js#enabledtransports-array
