### ISSUE TITLE
NS_ERROR_UNEXPECTED: NS_ERROR_UNEXPECTED:

### ISSUE THREAD

**Issue by simaranjitsingh** [pusher/pusher-js#134]
## Error

NS_ERROR_UNEXPECTED: NS_ERROR_UNEXPECTED:

Location

Pusher.js line number 2188
# Seems in this function:

```
    /** Sends data over the open connection.
     *
     * @param {String} data
     * @return {Boolean} true only when in the "open" state
     */
    prototype.send = function(data) {
        var self = this;

        if (self.state === "open") {
            // Workaround for MobileSafari bug (see https://gist.github.com/2052006)
            Pusher.Util.defer(function() {
                if (self.socket) {
                    self.socket.send(data); // (Line number 2188)
                }
            });
            return true;
        } else {
            return false;
        }
    };
```
# 

Exact line is: self.socket.send(data);

**Comment by jackfranklin** [comment]
Hey,

Are you using the latest version of the PusherJS library? If you could share your code that is causing this error to occur that would be useful too.

Thanks :)

**Comment by esetnik** [comment]
I see the same error in Rollbar

**Comment by amackera** [comment]
I'm also seeing this error, but coming from this pusher code
> pusher.js in callback at line 1410:0
```javascript
	    TransportConnection.prototype.send = function (data) {
	        var _this = this;
	        if (this.state === "open") {
	            util_1["default"].defer(function () {
	                if (_this.socket) {
	                    _this.socket.send(data); // <---- THIS IS THE LINE 1410
	                }
	            });
	            return true;
	        }
	        else {
...
```

**Comment by davidhariri** [comment]
Adding to my colleague's note:

<img width="680" alt="screen shot 2017-02-01 at 9 54 00 am" src="https://cloud.githubusercontent.com/assets/5245670/22511679/6b7ed93e-e864-11e6-92a8-69a8c0213074.png">

**Comment by dgcoffman** [comment]
Not to "me too" but add nothing, but...

We've seen about 15k of these errors in the last 3 months -- from Firefox alone.

The socket is breaking in all other browsers as well, but it only warns -- no exceptions is thrown.

Does anyone have any information at all about this?

**Comment by hph** [comment]
Do you have any more context that would help in reproducing this issue? For instance, do you know whether it happens after a user loses their connection or after a tab has been idle for a long time? Depending on the circumstances, it may not matter that the error was thrown at all and we can simply catch it and ignore it (for instance, if it happens when the connection is closed). If that's not the case, however, this might be a bit more tricky. As far as I'm aware, Firefox is behaving differently than the other browsers here and throwing a non-spec-compliant error.

> @dgcoffman The socket is breaking in all other browsers as well, but it only warns -- no exceptions is thrown.

Could you expand on this?

**Comment by davidhariri** [comment]
@hph here's all the data we have from Sentry:

<img width="328" alt="screen shot 2017-08-22 at 1 18 28 pm" src="https://user-images.githubusercontent.com/5245670/29578291-c1804d0a-873c-11e7-9b4c-d6fa7ed3d31f.png">

Looks like it happens in Firefox on mobile phones

**Comment by dgcoffman** [comment]
We see Firefox on desktop and mobile.

<img width="1268" alt="screen shot 2017-08-22 at 12 48 35 pm" src="https://user-images.githubusercontent.com/1711204/29584350-4cbcc7ea-8738-11e7-9f87-005d50ed104f.png">

**Comment by 2rist** [comment]
![screen shot 2018-03-09 at 10 11 05](https://user-images.githubusercontent.com/2572190/37199552-3b516b8c-2382-11e8-8b62-a7f778848eaf.png)
Still happens :( Are there any updates?

**Comment by kylemellander** [comment]
still happening for us
