### ISSUE TITLE
[REQUEST] Event listener wildcards

### ISSUE THREAD

**Issue by rbhalla** [pusher/pusher-js#135]
Title says it all, I'd like to be able to be able to listen to events like `*:created` or `user:*`. Maybe allow regex?

Or would it just be better to `bind_all` and then manually filter by event name?

**Comment by jackfranklin** [comment]
@rbhalla for now `bind_all` and manual filtering should work. I don't see why we couldn't encapsulate that logic inside the lib to allow wildcards - but @pl is way more familiar with this lib than I so I'll wait for his thoughts :)

**Comment by pl** [comment]
I agree with Jack - for now you'll need to use bind_all and implement filtering yourself. This shouldn't be difficult to integrate into the library, but we'd need to consider expression format first. 

I think there are ways to add event pattern matching without requiring a major release:
* add a new method, e.g. `bind_pattern`
* allow passing RegExp as the event name to `bind`

Interpreting `*` in `bind` event name as a wildcard would require a major release, but it has some advantages:
* it's easier to use
* unbinding from events is simpler

**Comment by rbhalla** [comment]
Can I assume from the closed issue this is now supported? Or is it something that now can't be supported?

**Comment by jackfranklin** [comment]
@rbhalla it's not supported currently - for now the recommendation is `bind_all`. I believe we're still considering this as an approach but @jpatel531 is the person to ask here.

**Comment by jpatel531** [comment]
Sorry i closed this by mistake, got confused with another issues. This doesnt look too difficult. Ill add it to our backlog for the lib

**Comment by hph** [comment]
I'm closing "feature request" issues, including this one. This does not mean that the feature will not be implemented, we just want to reserve open GitHub issues to bugs that need to be addressed.

Feel free to comment here to keep the discussion going. People watching the repository will still receive notifications.
