### ISSUE TITLE
NS_ERROR_NOT_CONNECTED: 

### ISSUE THREAD

**Issue by soundrussian** [pusher/pusher-js#136]
We're having occasional NS_ERROR_NOT_CONNECTED: error when using pusher.js in production.

Backtrace (if it helps):

```
https://js.pusher.com/3.0/pusher.min.js:57:225 in c.send/<
https://js.pusher.com/3.0/pusher.min.js:16:241 in Pusher.Timer/<
https://js.pusher.com/3.0/pusher.min.js:16:10 in a/this.timer<
```

My naive guess is that this may be browser specific problem, as it happens always with the same user:

```
"userAgent": "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0",
"userAgentInfo": {
    "browserName": "Firefox",
    "browserVersion": "43.0",
    "engineName": "Gecko",
    "engineVersion": "20100101",
    "isBot": false,
    "isMobile": false,
    "os": "Windows 7",
    "platform": "Windows"
}
```

**Comment by zdennis** [comment]
@soundrussian, any luck identifying the cause? We are seeing this to occassionally (in Firefox 46 and 47), but it's across the board in terms of the OS.

**Comment by roelvan** [comment]
Having the same error with FF 51.0 (Windows 8.1)
