### ISSUE TITLE
Pusher slow

### ISSUE THREAD

**Issue by canfiax** [pusher/pusher-js#137]
I'm trying to set up Pusher / Socket connection for my Laravel application using pusher-js.

I can now successfully send events, and listen on the channel through javascript for a specific event. However! It is EXTREMLY slow. I think $.ajax() calls would be 10x faster. I thought Pusher would be lightning fast?

From I send the event, till pusher-js registers is, it takes around 1-4 seconds.

**Comment by zimbatm** [comment]
Hi @canfiax,

where are you located on the earth ? Depending on your distance with our cluster you might get an added 300 - 600 ms latency for each side. 4 seconds is definitely too slow.

If you want a follow-up on that discussion please contact support@pusher.com with a link to that issue.

**Comment by canfiax** [comment]
Sorry, your server is extremly fast. My issue was that I was sending the messages through my own queue system which made the responses seem slower. But no, they are lightning fast :)

**Comment by zimbatm** [comment]
Great ! I'm glad that you found the source of the issue :)

**Comment by xsmartweb** [comment]
Same issue!

My pusher service is slow , it takes 1 or 2s to send message.

Hi @simplenotezy , how did you solve that issue?

**Comment by mrextreme** [comment]
Only a few seconds? I get 10.4 seconds delay every time.

**Comment by xmaydin** [comment]
> Only a few seconds? I get 10.4 seconds delay every time.

Same here and i cant solve this problem :(

**Comment by ben-pusher** [comment]
Hi, 
This issue is closed and is not the best place to investigate increased latencies. I would advise that you reach out to support using the form at https://support.pusher.com/hc/en-us/requests/new. Please provide as much information about the latency, including how you are measuring the latency.

**Comment by mrextreme** [comment]
BTW, as it turned out, it was because of the VPN. Once i turned it off it was near instantaneous.

**Comment by houssamHADELAMOUS** [comment]
Hi! i have a chat app using **laravel/ReactJS/pusherJS** and when i send message it's too lazy to display in my chat space after 6 seconds
