### ISSUE TITLE
React native support

### ISSUE THREAD

**Issue by adrienbrault** [pusher/pusher-js#138]
Currently getting the following error:

<img width="487" alt="screen shot 2016-01-25 at 18 12 26" src="https://cloud.githubusercontent.com/assets/611271/12558330/3f07dcd4-c38f-11e5-8e53-c73962be6041.png">

**Comment by hamchapman** [comment]
For react native support please use this library: https://github.com/pusher-community/pusher-websocket-js-iso#react-native

Thanks!

**Comment by tarifrudrapur** [comment]
Use pusher 4.0.0 version as may be you are using a old react native version
