### ISSUE TITLE
Private conversation with JSONP broken in chrome

### ISSUE THREAD

**Issue by Sparkmasterflex** [pusher/pusher-js#141]
I'm trying to implement [JSONp authentication for private channels](https://blog.pusher.com/jsonp-authentication-for-private-channels/) for a React component I'm building to be used in a few of my company's apps.

Here's what I got:

```
  # rails controller
  def auth
    auth = Pusher["private-channel-xyz"].authenticate(params[:socket_id], {
      :user_id => current_user.id,
      :user_info => {:name => current_user.name}
    })

    render text: "#{params['callback']}(#{auth.to_json})"
  end
```

```
   module.exports = React.createClass
     # ... omitted ...
     componentDidMount: ->
        this.pusher = new Pusher this.settings.pusher_key, {
          encryped: true
          authEndpoint: "#{this.settings.url}/pusher/auth"
          authTransport: 'jsonp'
        }
        channel = pusher.subscribe("private-channel-xyz")
        channel.bind "my-event", (data) =>
          # do something here

     # ... omitted ...
```

and on page load I'm getting this error:

```
  Refused to execute script from 'http://localhost:3000/pusher/auth?callback=Pusher.auth_callbacks%5B%271%27%5D&socket_id=178149.360446&channel_name=private-lm-notifications-6930' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled
```

going to that url (.../pusher/auth) gives me a plain text string of the callback alright and appears to be working just fine in Firefox, but in chrome is not. Any ideas how to get around this?

**Comment by dirkbonhomme** [comment]
`because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled`

Your /pusher/auth endpoint should return the proper MIME type. I'm not sure what your backend runs on but in PHP it would be something like this:

`header('Content-Type: application/json');`

**Comment by Sparkmasterflex** [comment]
@dirkbonhomme Thank you for your response. I'm using rails and have updated this as you suggested and now it's just giving the same error but with `application/json`

```
Refused to execute script from 'http://localhost:3000/pusher/auth?callback=Pusher.auth_callbacks%5B%271%27%…l_name=private-lm-admin-notifications-42cc1d70-c912-11e0-8a75-001cc45fad02' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.
```

the updated Rails code:

```
# rails controller
  def auth
    auth = Pusher["private-channel-xyz"].authenticate(params[:socket_id], {
      :user_id => current_user.id,
      :user_info => {:name => current_user.name}
    })

    render text: "#{params['callback']}(#{auth.to_json})", content_type: "application/json"
  end
```

**Comment by jpatel531** [comment]
@Sparkmasterflex  - could you change `content_type: 'application/json'` to `content_type: 'application/javascript'` and get back to us?

**Comment by Sparkmasterflex** [comment]
@jpatel531 was literally typing this up when you posted. Thanks.

yes application/javascript mime type was the trick. 

Thanks again guys!

**Comment by dirkbonhomme** [comment]
Ahah missed the callback parameter in your call so assumed it had to be JSON. :+1:

**Comment by Sparkmasterflex** [comment]
Sorry to close and reopen this issue but I'm still having trouble. I'm getting the following error as a JS warning and my JS is not receiving anything from my other app.

```
Pusher : Error : {"type":"WebSocketError","error":{"type":"PusherError","data":{"code":null,"message":"Invalid signature: Expected HMAC SHA256 hex digest of xxxxxx.xxxxxx:private-&lt;channel-name>, but got &lt;big hash>"}}}
```

It appears that the _big hash_ is just the second part of the auth returned (after the colon)

**Comment by zimbatm** [comment]
This is an issue with the signature that rails is returning. Make sure it's signing the right content and double-check that you're using the right key pair (and that you didn't swap the key with the secret)

**Comment by Sparkmasterflex** [comment]
@zimbatm thank you! I have two channels one for admins and one for other users and I was subscribing to the admins' channel but authenticating for the users' channel.
