### ISSUE TITLE
Multiple instances of Pusher on page

### ISSUE THREAD

**Issue by Sparkmasterflex** [pusher/pusher-js#146]
I apologize if this has already come up elsewhere, I've looked and couldn't find anything.

I have a npm module that I've built to handle incoming activities from an application. This is all setup and works perfectly fine in all but one case.

The application that I'm implementing it in has a header bar that is on every page and in the body of a 'dashboard' page of the application. On the dashboard there are 2 instances of the npm module one in the main content of the page and in that header bar. It seems that the two are not playing well together as far as the pusher integration goes.

Each instance of the module instantiates a the pusher JS library and subscribes to the same channel. But it seems that the header is the one that get's instantiated first and is the one that does not work.

**Comment by jackfranklin** [comment]
You should try to avoid having multiple instances of Pusher, it may not work (as you're seeing) and even if it did it would open two connections to Pusher, and use up more of your connection limits than it should.

What you need to try to do is only ever instantiate the Pusher library once, and pass that instance around to the different components on the page.

A very simple way to do this is to store the instance of pusher on the window:

```
window.pusher = new Pusher(...)
```

But I wouldn't recommend that - you'd be better off (if you're using AMD / CommonJS / ES2015 modules) creating a module that has an instance of Pusher, and any other part of your code that needs Pusher can require it in,

I hope that helps - let me know if I can help further :)

**Comment by Sparkmasterflex** [comment]
@jackfranklin thank you for your reply. I've implemented a fix so that if one of the modules has instantiated a Pusher object that it becomes accessible to the other module. This second module just sets its Pusher instance to the one from the first module.

But I am still not getting any activity from for one of the modules. Both ways before the above change and after it is the first instantiated module that no longer receives any events from pusher.

Both modules are exactly the same code base and the first which is not working on this dashboard (w/ the second) is working on every other page.

**Comment by jackfranklin** [comment]
@Sparkmasterflex it's hard to help really without some code to look at; if you can point me in the right direction.

Because you say PusherJS is working as expected on every other page I'd expect something on your dashboard page is conflicting or causing issues.

**Comment by Sparkmasterflex** [comment]
@jackfranklin I'm sorry for the delay in answering you. It actually just _magically_ started working a day after configuring the two instances to share the same pusher instance.

I honestly do not know how it worked a day later but it was not working when I made the change originally. If I find anything further, I'll post it here for others having the same issue.

Thanks
