### ISSUE TITLE
Pusher.warn function duplicates each log statement

### ISSUE THREAD

**Issue by edwardotis** [pusher/pusher-js#148]
Expected behavior: 
single log statement at warn level

Actual behavior:
single log statement at warn level
followed immediately by
single log statement using console.log

Example:

Pusher : Error : {"type":"WebSocketError","error":{"type":"PusherError","data":{"code":1006}}}
background.js:228
Pusher : Error : {"type":"WebSocketError","error":{"type":"PusherError","data":{"code":1006}}} background.js:228

 Pusher.warn = function() {
    var message = Pusher.Util.stringify.apply(this, arguments);
    if (window.console) {
      if (window.console.warn) {
        window.console.warn(message);
      } else if (window.console.log) {
        window.console.log(message);
      }
    }
    if (Pusher.log) {
      Pusher.log(message);
    }
  };

https://github.com/pusher/pusher-js/blob/567076130149a5ca88fc6deb19f0603247c62160/src/pusher.js#L116

**Comment by jackfranklin** [comment]
Good spot - thank you!

**Comment by hph** [comment]
Fixed in 0bd142fd630aa66ceb4dd0a622819f1bda473b9b.
