### ISSUE TITLE
Hosted files should contain the git hash of the commit they were built from

### ISSUE THREAD

**Issue by jameshfisher** [pusher/pusher-js#151]
E.g. https://js.pusher.com/3.0/pusher.min.js - there is no way, from looking at it, to see what its provenance is

**Comment by jameshfisher** [comment]
Looks like we use https://github.com/ismasan/jbundle (which hasn't been updated in 5 years)

**Comment by jackfranklin** [comment]
I think @pl has some ideas here - we should really look to update this library with more modern conventions and probably go for Webpack or similar to produce all the builds.

Agree that the minified build having the commit in a comment would be nice, although it does have the full version number so it's easy enough to track back from there.

**Comment by hph** [comment]
We have started using Webpack for builds since this PR was opened and I think it's more than enough to see the version number in the file and compare that with the releases here on GitHub (please correct me if I'm wrong).
