### ISSUE TITLE
 Couldn't get auth info from your webapp : 201

### ISSUE THREAD

**Issue by yozzz** [pusher/pusher-js#154]
I'm connecting to private channel as client, it goes to my app API with authentication process, and the response I have is:
<pre>
{"auth":"3h23kjh322kknkjsad:ea5dc004619ccg23s2e059f740h66684dd887fbexc8d8e56ae23b788cdafa1b"}</pre> response status 201.

But console log says next:
<pre>
Pusher : State changed : initialized -> connecting
Pusher : Connecting : {"transport":"ws","url":"wss://ws.pusherapp.com:443/app/3h23kjh322kknkjsad?protocol=7&client=js&version=3.0.0&flash=false"}
Pusher : State changed : connecting -> connected
Pusher : Couldn't get auth info from your webapp : 201
Pusher : Couldn't get auth info from your webapp : 201
Pusher : No callbacks on private-live_admin for pusher:subscription_error
Pusher : Event sent : {"event":"pusher:ping","data":{}}
Pusher : Event recd : {"event":"pusher:pong","data":{}}
Pusher : Event sent : {"event":"pusher:ping","data":{}}
Pusher : Event recd : {"event":"pusher:pong","data":{}}
</pre>

When i debugging <pre>var channel = pusher.subscribe('private-live_admin');</pre>
It returns <pre>{callbacks: c, global_callbacks: Array[0], name: "private-live_admin", pusher: b, subscribed: false}</pre>
Can you give me some advise? Can't find any information about this.

**Comment by dirkbonhomme** [comment]
I think the Pusher lib expects a 200 status code instead of 201

**Comment by yozzz** [comment]
Yes, i just notice that, so problem was with status code, my app returns status 201. What about this issue #17 ?

**Comment by dirkbonhomme** [comment]
Well I guess because 201 is not the proper response for this kind of request ;) Each HTTP status code has its own meaning that should be followed as closely as possible imo.

**Comment by yozzz** [comment]
Well yes, I agree, maybe we can add this small notice somewhere inside readme?

**Comment by jpatel531** [comment]
Yeah, I'll add to the README. As @dirkbonhomme said - I don't think 201 is the semantic status code to send.

**Comment by yozzz** [comment]
Cool, thanks @jpatel531
