### ISSUE TITLE
Wrap net::ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by marcbachmann** [pusher/pusher-js#157]
If you pass an invalid cluster config into the client initialization, it just accepts it.
A wrong configuration will result in a lowlevel chrome error and is a bit nasty to debug. You can't make sure weren't sure whether it was actually a dns or a configuration problem.

A cluster whitelist might improve that.
The connection handler could log a warning if the configured cluster isn't a valid one.

Here's the code

``` js
var client = new Pusher('PUSHER_KEY', {
      encrypted: true,
      authTransport: 'ajax',
      cluster: 'us'
})
```

``` bash
WebSocket connection to 'wss://ws-us.pusher.com/app/APPID?protocol=7&client=js&version=3.0.0&flash=false' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED
tracker.js:17 POST https://sockjs-us.pusher.com/pusher/app/APPID/833/ufmtkbaq/xhr_streaming?protocol=7&client=js&version=3.0.0&t=1460469367364&n=5 net::ERR_NAME_NOT_RESOLVED
```

**Comment by marcbachmann** [comment]
the cluster config for `mt1` or `us-east-1` are also not working properly. I get also a dns error.

**Comment by hph** [comment]
We currently don't have a reliable list of clusters and adding one might prove problematic, due to custom plan clusters.

**Comment by kanchanp20** [comment]
I was getting the same error,
It's just that when you write your router details, say as in eg.
{
		path: '/',
		component: () => import(/* webpackChunkName: "pages/main" */"./components/pages/main"),
		name: 'main'

	},

here while mentioning the chunk name, i by mistake added a hash in front of folder name i.e
component: () => import(/* webpackChunkName: "/pages/main" */"./components/pages/main"),

By removing that hash, it started working.
Hope it helps :)
