### ISSUE TITLE
Binding to events with Context not working

### ISSUE THREAD

**Issue by alex-alfaro** [pusher/pusher-js#159]
context is undefined in following code:

```
var PUSHER_APP_KEY = '...';
var pusher = new Pusher(PUSHER_APP_KEY);
var channel = pusher.subscribe("test-channel-x");
var context = { title: 'Pusher' };
var handlerSucess = function() {
  alert("Subscription succeded with " + this.title);
};
channel.bind("pusher:subscription_succeeded",handlerSucess ,context);

var handlerNew = function() {
  alert("new event with " + this.title);
};

channel.bind("new",handlerNew ,context);
```

**Comment by jackfranklin** [comment]
As a work around for now, you could do:

`channel.bind(..., handlerSucess.bind(context)`

But we should get this fixed. Thanks for letting us know. Are you on PusherJS V3?

**Comment by alex-alfaro** [comment]
That's right I'm using

`<script src="http://js.pusher.com/3.0/pusher.min.js"></script>`

Thank you for the workaround, it works fine.

**Comment by jpatel531** [comment]
I'm sure this is a minification thing. I've never known this not to work in the unminified build. This is probably related to #125

**Comment by jpatel531** [comment]
@alex-alfaro - do you have any steps to reproduce? i can't reproduce it :/

**Comment by alex-alfaro** [comment]
Strange :confused: it works now
I just tested with the same code-pen I used yesterday to confirm the issue,
http://codepen.io/anon/pen/Xdxywj?editors=1011
_Perhaps a server issue yesterday? sounds absurd but is the only thing I can think of_

**Comment by jpatel531** [comment]
Hey @alex-alfaro - were you perchance using Safari 9.1 on El Capitan?

**Comment by alex-alfaro** [comment]
No, it was Firefox on Windows 10
