### ISSUE TITLE
Handling 1006 errors and unexepected disconnections

### ISSUE THREAD

**Issue by ccnokes** [pusher/pusher-js#160]
Pusher version: 2.2.4

My organization has been using Pusher for awhile and we've noticed that occasionally it'll just stop working. In most cases, it logs a 1066 error like so: 

```
Pusher : Error : {"type":"WebSocketError","error":{"type":"PusherError","data":{"code":1006}}}
```

and will not send/receive any more events. Another error I've seen with less frequency is: 

```
Pusher : Error : {"type":"WebSocketError","error":{"type":"PusherError","data":{"code":4201,"message":"Pong reply not received"}}}
```

Usually this event occurs if the user's computer has been put to sleep and then re-awoken -- but not always. I'm only occasionally able to reproduce it on my machine.

Any ideas on what I could do to ensure that Pusher connections stay alive or refresh them when they die? Also any recommendations on testing error/disconnected/fail scenarios with Pusher? 

Sorry for the really vague issue but it's all I have to work with.

**Comment by jpatel531** [comment]
When your computer next gets connectivity, the library should reconnect automatically. Does this still occur on pusher-js 3.0.0? Could you check the debug console on another device while the computer in question is asleep? What is the output of the duration of its sleep?

**Comment by ccnokes** [comment]
Sorry for the late response (especially because you responded so quickly, thanks for that btw). 

I'm at a conference and haven't been able to play around with it more. I'll get back to you with more info by Monday/Tuesday. 

> Does this still occur on pusher-js 3.0.0?
May not be feasible to upgrade to 3 right now, but I'll still try it out. Is there a change log or migration guide for this? I'd like to check that out to make sure it'll work before just dropping it in.

**Comment by jpatel531** [comment]
I think between 2.x -> 3 there is only the removal of the flash fallback. In terms of the developer-facing API, it's backwards compatible

**Comment by ccnokes** [comment]
Thanks for your help, the connectivity issues I've seen are hard to reproduce but I've seen good improvements with our upgrade to 3.0. So I'll go ahead and close this.

**Comment by ccnokes** [comment]
Actually, I just saw an issue this morning where a user was able to send events but not receive them. The  logs said that pusher was connected, although there were some warnings that "pusher could not get auth info from webapp". It seems like an authentication issue is unlikely if a client is receiving events but not sending. 

This all happened on the same machine. The client was sending events from one chrome browser to an electron app (running the same code). The electron app was able to send events but not receive them. Chrome was fine sending and receiving. No errors or warning in the Chrome logs. 

Any idea on what could be happening there? Is this related to authentication.

**Comment by aeolusheath** [comment]
same problem

**Comment by tquiroga** [comment]
I'm trying to use a TV screen with real-time data, data seems to be received on the screen for a certain duration after that I see the `Pusher : Error : {"type":"WebSocketError","error":{"type":"PusherError","data":{"code":1006}}}` in the console and data is not received anymore.

Do we need to use a ticker to re-auth/refresh the status of the web socket after a certain amount of time?

**Comment by aeolusheath** [comment]
@tquiroga  pusher has auto-reconenct func

**Comment by amrendraw3** [comment]
The `code 1006` error occurs mostly because of missing cluster key while initializing pusher client. It should something like:

`var client = new Pusher('YOUR_APP_KEY', {cluster: 'CLUSTER_VALUE', encrypted: true});`
