### ISSUE TITLE
Would an automatic rate limiting patch be welcomed?

### ISSUE THREAD

**Issue by randallb** [pusher/pusher-js#163]
WebRTC signaling requires serious rate limiting. It's going to need to be implemented at the library level since i could have 5 connections each trying to fire off ice candidates on their own. I'm planning to fork and build. Is there any interest upstream if I get it working? Happy to PR, etc.

**Comment by jpatel531** [comment]
Hey @randallb  - is this regarding rate limiting with client events? On multi-tenancy plans, client events are limited to 10 per second. Only on dedicated clusters can we raise this. 

But then again I might be confused, as I've never personally used Pusher with WebRTC. What kind of changes do you have in mind?

**Comment by randallb** [comment]
I built a queueing system where when it hits the 10 / sec limit, it queues up the rest, then gzips, sends as one message, then the other clients process.

I'm thinking about making it a plugin ala pusher-auth instead of trying to merge into core.

**Comment by zimbatm** [comment]
Yeah something on top sounds good. I did build something similar in one of my hacks which I can dig out if you want.

**Comment by jpatel531** [comment]
Yeah it sounds like a good idea for a plugin - I'd definitely be interested in seeing it.
