### ISSUE TITLE
Looping connection with (101 Switching Protocols) Response

### ISSUE THREAD

**Issue by adamjacob** [pusher/pusher-js#164]
I've been trying to debug this all morning.  While trying to connect to pusher I'm getting a loop, it connects then disconnects.  On the connection request the status code is `101 Switching Protocols`.  I'm not if that could be causing issues?

When logging on status change I get this, looping forever.
```
Object {previous: "connected", current: "connecting"}
Object {previous: "connecting", current: "connected"}
Pusher : Error : {"type":"HandshakeError","error":{}}
```

I've made sure I'm using the most up to date library 3.0.  Anyone have any ideas?  It's driving me crazy.

**Comment by jpatel531** [comment]
Hi there - this is fixed in #162 . Will be releasing as soon as possible
