### ISSUE TITLE
Configurable authentication

### ISSUE THREAD

**Issue by sandstrom** [pusher/pusher-js#165]
If the pusher js-client could take a function `authAdapter` returning a promise, then it could be left to the user to perform the authentication in any way fit (different endpoints, headers handling, withCredentials switch, etc).

Should solve https://github.com/pusher/pusher-js/issues/83 and https://github.com/pusher/pusher-js/issues/99.

``` js
new Pusher(apiKey, {
  authAdapter: function(channel, ...) {
    return Promise(resolve, reject) {
      // ...
    };
  },
  // other conf...
});
```

**Comment by jpatel531** [comment]
I like the idea. I might be sceptical about Promises as we'd have to add another dependency to polyfill older browsers. Auth adapters is definitely something we'd like to tackle after the coming release is out

**Comment by sandstrom** [comment]
It has wide support (http://caniuse.com/#search=promise) and the shim is small: 
https://github.com/stefanpenner/es6-promise (3.4 kb gzip + minified)

Entirely up to you of course. Callbacks works too!

**Comment by jackfranklin** [comment]
Although I'd personally prefer promises, I would stick to callbacks given our commitment to supporting a bunch of older browsers as well as newer ones.

Or we could make it work with both and ask those who want to use Promises to provide their own polyfill.

Like the idea though 👍

**Comment by sandstrom** [comment]
@jpatel531 friendly ping

**Comment by hph** [comment]
I'm closing "feature request" issues, including this one. This does not mean that the feature will not be implemented, we just want to reserve open GitHub issues to bugs that need to be addressed.

Feel free to comment here to keep the discussion going. People watching the repository will still receive notifications.

**Comment by sandstrom** [comment]
AFAIK this was implemented (contrary to hph's message above): #211

**Comment by thecodecafe** [comment]
Hi, so I'm setting up pusher but can't seem to find a way to define the domain for authentication, I'm using pusher on a  react-native app, and what to create a private channel but need the user authenticated before creating a private channel, below is my config code.

```
let pusher new Pusher(
        PUSHER_KEY, {
            cluster: 'eu',
            forceTLS: true,
            authEndpoint: `/pusher/auth`,
            auth: {
                headers: {
                    Authorization: `Bearer ${user && user.token}`
                }
            }
        }
    )
```

how can I define a domain for that endpoint, have tried adding the domain to the endpoint but that didn't work, also I'm not so sure if the request is being made from the device or from Pusher's server?

Really stuck here, thanks.

**Comment by 360disrupt** [comment]
> Hi, so I'm setting up pusher but can't seem to find a way to define the domain for authentication, I'm using pusher on a react-native app, and what to create a private channel but need the user authenticated before creating a private channel, below is my config code.
> 
> ```
> let pusher new Pusher(
>         PUSHER_KEY, {
>             cluster: 'eu',
>             forceTLS: true,
>             authEndpoint: `/pusher/auth`,
>             auth: {
>                 headers: {
>                     Authorization: `Bearer ${user && user.token}`
>                 }
>             }
>         }
>     )
> ```
> how can I define a domain for that endpoint, have tried adding the domain to the endpoint but that didn't work, also I'm not so sure if the request is being made from the device or from Pusher's server?
> 
> Really stuck here, thanks.

Late, but maybe interesting for others:

1st you don't pass the token because `${user && user.token}` will resolve to true/false. The request is made from where the code is executed e.g. the browser or your server. In my case I have a frontend app (browser) and a backend app (node.js server) sending the request. See the code example of my backend below. 

## pusher.routes.js

```
module.exports = (app) => {
    const pusherAuth = (req, res) => {
        const socketId = req.body.socket_id;
        const channel = req.body.channel_name;
        const auth = pusher.authenticate(socketId, channel);
        res.status(HttpStatus.OK).send(auth);
    };
    // route for frontend pusher-js auth with session cookie via oauth
    app.post('/pusher/auth', routesMiddleware.userChannel, pusherAuth);
    // route for backend pusher-js auth with bearer token
    app.post('/pusher/auth/bearer', passport.authenticate('bearer', { session: false }), pusherAuth);
```

## load pusher-js in my backend

```
userRead.getAdmin( (err, admin) => {
    if(err || !admin) throw new Error('Couldn\'t load admin');
    if(!admin.bearerToken) throw new Error('Admin has no bearerToken');
    socket = new Pusher(process.env.PUSHER_KEY, {
        cluster: process.env.PUSHER_CLUSTER,
        authEndpoint: `http://localhost:${process.env.PORT || 3000}/pusher/auth/bearer`,
        auth: {
            headers: {
                Authorization: `Bearer ${admin.bearerToken}`
            }
        },
        forceTLS: true
    });
    socket.connection.bind('connected', ()=>{
        console.log('Pusher connected');
    });
});
```
