### ISSUE TITLE
Published dist folder doesn't match that on npm

### ISSUE THREAD

**Issue by jackfranklin** [pusher/pusher-js#167]
If you look inside the `dist` folder on GitHub of the react-native build (https://github.com/pusher/pusher-js/blob/master/dist/react-native/pusher.js), you see the comment at the top 'PusherJS v3.1.0'.

I just did `npm install pusher-js@3.1` and the banner for the react-native dist there lists 'PusherJS v3.1.0-pre11'. Are they out of sync?

**Comment by jpatel531** [comment]
Yeah they are - I accidentally forgot to rebuild before publishing. There's no code change but the license header and version params will say 3.1.0-pre11. It's a silly mistake but doesn't make any difference really. Got too nervy!

**Comment by jpatel531** [comment]
You're a good man for noticing, Frank
