### ISSUE TITLE
Pusher client library does not play nice with CSP unsafe-eval setting

### ISSUE THREAD

**Issue by chrisnicola** [pusher/pusher-js#169]
I'm getting a CSP security error at this code:

`var r = Function("return this")();`

Which seems to be used throughout pusher-js.
https://github.com/pusher/pusher-js/search?utf8=%E2%9C%93&q=Function%28%22return+this%22%29+in%3Afile+&type=Code

**Comment by chrisnicola** [comment]
So I just figured out why we were not seeing this error in all our environments. It seems 3.0.0 doesn't have this problem, but I am seeing it with 3.1.0-pre11. Not sure why this change is being made, but for the sake of improving security I don't think eval's should be used on the client.

**Comment by zimbatm** [comment]
Hi @chrisnicola, thanks for reporting. A lot of internal changes have been introduced in 3.1 to support multiple platforms (see the [blog post](https://blog.pusher.com/announcing-pusherjs-3-1-supporting-reactnative-service-workers-and-nodejs/). With all these changes this regression was introduced. Somebody else already reported and we will be working on a fix shortly. See #168

**Comment by zimbatm** [comment]
Closing as it's a duplicate of #168

**Comment by chrisnicola** [comment]
Thanks, I'm sorry I missed that. I tried to search for unsafe-eval in the issues, I guess I should have searched a little harder.

**Comment by zimbatm** [comment]
No worries at all. The pusher-js library has a lot of corner cases and important for us to have reports like yours even if they sometimes duplicate.
