### ISSUE TITLE
Unbind not available

### ISSUE THREAD

**Issue by lvegerano** [pusher/pusher-js#170]
I have a connection that looks like so:
```javascript
self.io = new Pusher(self.pusher_api, {
        encrypted: self.pusher_encrypted,
        authEndpoint: self.pusher_auth_endpoint,
        authTransport: self.pusher_auth_transport,
      });
```

I can `bind` from `this.io` but cannot `unbind` an event. Looking at the prototype noticed that `unbind` is not available but under the `global_emitter`. 

<img width="720" alt="coschedule" src="https://cloud.githubusercontent.com/assets/2464593/15280132/88316cda-1af2-11e6-9edf-18d8194aaee5.png">

Is it possible to add an alias like bind to the Pusher class?

**Comment by jackfranklin** [comment]
You can call `unbind` on a channel - are you asking for a function to unbind to an event that's being listened to across all channels? I don't see why we couldn't consider adding that @jpatel531 ? I'm happy to work on the PR.

**Comment by jpatel531** [comment]
Yeah that's a fair point. Feel free @jackfranklin

**Comment by lvegerano** [comment]
@jackfranklin Yes, right now we're not using channels and events are bound at the room level.

**Comment by jackfranklin** [comment]
@lvegerano great, #171 should provide this.
