### ISSUE TITLE
Auth params are not passed in the query string

### ISSUE THREAD

**Issue by jameshfisher** [pusher/pusher-js#174]
The README says:

``````
#### `auth` (Hash)

Allows passing additional data to authorizers. Supports query string params and headers (AJAX only). For example, following will pass `foo=bar` via the query string and `baz: boo` via headers:

```js
var pusher = new Pusher(API_KEY, {
  auth: {
    params: { foo: "bar" },
    headers: { baz: "boo" }
  }
});
```
``````

However it seems that the `params` hash is not passed as a query string. It is passed as form data in the request body, along with the two other values, `channel_name` and `socket_id`.

**Comment by sandstrom** [comment]
This PR (configurable authentication) should help: https://github.com/pusher/pusher-js/issues/165

**Comment by hph** [comment]
This is now configurable with custom auth.
