### ISSUE TITLE
How to stub PusherJS

### ISSUE THREAD

**Issue by jackfranklin** [pusher/pusher-js#175]
The PusherJS Test Stub has become something that a lot of people rely on to test their Pusher integration and with 3.1 we broke the stub.

This is because PusherJS 3.0 exposed its dependencies (like EventDispatcher) so the stub could simply override them with fake equivalents.

Now PusherJS doesn't expose them.

@jpatel531 I would really like to chat about how we can fix this - I'm happy to do the work but I am not sure on the best approach.

One thing to consider might be to build another version of PusherJS specifically for testing (`import pusher from 'pusher-js/pusher-test'), and have that version expose some internals that would allow a new version of the stub to mock it.

WDYT?

**Comment by jpatel531** [comment]
I don't mind producing a new build for stubbing. Especially as I don't really want to expose dependencies like the library used to do, and think it would be easier to continually update the stub if it was a build of the library.

General ideas about this:

* Keep the stub files in a completely separate folder to src. These things shouldn't get mingled up
* Create interfaces for exposed classes: `Pusher`, `Channel`, `Connection`, `PrivateChannel`, `PresenceChannel`. You can keep these interfaces in `src/`.
* Make files in `stub/` implement those interfaces.
* Create a new webpack config file called stub, with stub/pusher.ts or stub/index.ts as the entry point. 
* Create a `stub.js` on the top level that links to `dist/stub/pusher.js` so they can do `import 'pusher-js/stub'` like you mentioned.
* GG

**Comment by jackfranklin** [comment]
@jpatel531 sounds good 👍 I agree that we should have an explicit build for the stub version and that it shouldn't be the main build, I'm +1 on not exposing internals.

This way the stub can be a first class citizen too and be easier to keep in sync with the lib.

Hopefully I can take a stab at this soon

**Comment by karlos1337** [comment]
How about this? Any progress?

Thx

**Comment by hph** [comment]
@karlos1337 Unfortunately nobody is working on this internally and there are no plans to do so. If you (or other people) feel like this would be very valuable, feel free to contribute (I can help out with the PR).
