### ISSUE TITLE
OSX Sierra Safari not connecting to pusher

### ISSUE THREAD

**Issue by beckmx** [pusher/pusher-js#176]
Hello guys, there is an issue with safari which doesnt connect to pusher in the new version of OS X, I guess this has to be with safari implementing new html5 tags. The error the browser gives me is:

[Error] Refused to connect to wss://ws.pusherapp.com/app/cb83ffb2e230419bfaeb?protocol=7&client=js&version=3.0.0&flash=false because it appears in neither the connect-src directive nor the default-src directive of the Content Security Policy.

Failed to load resource: WebKit found and error

**Comment by jpatel531** [comment]
Thanks a lot for bringing this up! I'll look into it asap

**Comment by beckmx** [comment]
I did this as a workaround, but still sometimes the browser keeps telling,
there is an error although it seems it connects ok like this

<meta http-equiv="Content-Security-Policy" content="default-src * 'wss://
ws.pusherapp.com/app/cb83ffb2e230419bfaeb?protocol=7&client=js&version=3.1.0&flash=false';
script-src 'wss://
ws.pusherapp.com/app/cb83ffb2e230419bfaeb?protocol=7&client=js&version=3.1.0&flash=false'
'self' 'unsafe-inline' 'unsafe-eval' *; style-src  'self' 'unsafe-inline'
*">

2016-06-18 1:59 GMT-05:00 Jamie Patel <notifications@github.com>:

> Thanks a lot for bringing this up! I'll look into it asap
>
> Sent from my iPhone
>

**Comment by sandstrom** [comment]
I'm seeing this too. Did you find anything? Only in Safari.

**Comment by trippytango** [comment]
Hi guys,

I'm looking at pusher.js in my next project and this issue raises some concerns for myself.

Is this still an issue?

If its still an issue, is it been looked at or potentially have an ETA on been fixed?

**Comment by hph** [comment]
@trippytango In short, you don't need to worry about this unless your website has a CSP configuration, in which case you should update it to allow Pusher connections.

To the others, unless I'm misunderstanding something, this is an issue with your [Content Security Policy (CSP)](https://developer.mozilla.org/en/docs/Web/Security/CSP) that needs to be fixed and there is nothing wrong on our end.

The way CSP works is that if your web server sends HTTP headers including a restrictive CSP policy, or if you have similarly restrictive `<meta http-equiv="Content-Security-Policy" ...>` tags in your website, the browser will simply block the requests.

If you run into this issue you can either relax the restrictiveness of your CSP or add a rule to allow Pusher domains & requests.

I'll close this issue so there's no confusion for other people that might see this and I'll be updating the README for others that might have a strict CSP.

If you run into any issues, related to this or not, feel free to open an issue here or contact support directly.

**Comment by sandstrom** [comment]
*I investigated this, so can add some more details for others with this issue*

Yes, nothing wrong with Pusher!

This is an issue with Safari 10 and how they parse the CSP policy.

One work-around is to add `ws://*` and `wss://*`to `connect-src` (use * for everything, or restrict to hostname, the important piece is that the protocol must be specified).

**Comment by jaspal747** [comment]
I used 
`connect-src 'self' *.pusherapp.com *.pusher.com ;` to whitelist my domain and pusher.
