### ISSUE TITLE
react-native: expected dynamic type 'string' but had type 'int64'

### ISSUE THREAD

**Issue by Et3Ali** [pusher/pusher-js#177]
Hello,
When i try to subscribe to presence channel i got the following error :

> expected dynamic type 'string' but had type 'int64'

Where the channel name is **presence-server_439**
Note that if i remove the dash it will work fine.

react-native: 0.28
pusher-js:3.1.0
Thank you.

![pusher](https://cloud.githubusercontent.com/assets/12428904/16379467/6506d5ca-3c7a-11e6-8156-4f7fa9661308.jpg)

**Comment by RakanNimer** [comment]
Having the same issue, is there any more detailed info I can provide to help with this ?

**Comment by jackfranklin** [comment]
@RakanNimer the channel names you're using would be useful - from @Et3Ali's report it suggests that that is causing the issue.

Also pinging @jpatel531

**Comment by jpatel531** [comment]
It smells like an auth request issue. Could either of you send me a detailed stacktrace?

**Comment by RakanNimer** [comment]
Hey @jackfranklin  and @jpatel531 ,

Thank you so much for your respective answers. Very much appreciated :)
Happy to say I just found the issue 💃  : 
I was authenticating with Pusher using code that looks like the following :
```javascript
let a = new Pusher(MY_APP_KEY, {
        encrypted: true,
        auth: {
            headers: {
              "x-access-id": 44332,
              "x-bla-bla-bla-as":'b4a5bb7cb11d3f5a2d9529b0bd6bbd04ccaf3294',
              "x-foo-bar":'android',
              "x-bar-version":"2.2"
            }
        },
        authEndpoint: 'http://MY_URL/pusher/authChannel'
        });
    var channel = a.subscribe('private-my_channel');
```
The problem turned out to be in the header : 
``` "x-access-id" :44332 ```
It was expecting 44332 as a string and I was passing it as an integer ! 
Solved it with the following code : 
```javascript
let a = new Pusher(MY_APP_KEY, {
        encrypted: true,
        auth: {
            headers: {
              "x-access-id": "44332",
              "x-bla-bla-bla-as":'b4a5bb7cb11d3f5a2d9529b0bd6bbd04ccaf3294',
              "x-foo-bar":'android',
              "x-bar-version":"2.2"
            }
        },
        authEndpoint: 'http://MY_URL/pusher/authChannel'
        });
    var channel = a.subscribe('private-my_channel');
```

Thanks again for your answers and your great work on the Pusher library :)

**Comment by jpatel531** [comment]
ah excellent! glad to hear it :) @Et3Ali is this helpful for you too?

**Comment by Et3Ali** [comment]
Hi,
Thank you @RakanNimer, @jpatel531 .
@RakanNimer 's solution worked for me too.

**Comment by jpatel531** [comment]
No problem! I'm glad it's being used for react-native. One of the things that excited me about the new version  :)
