### ISSUE TITLE
React Native Android - Converting circular structure to JSON 

### ISSUE THREAD

**Issue by peterpme** [pusher/pusher-js#182]
React Native 0.27.2
Pusher-JS 3.1.0
Android Nexus 5 6.0.1

Hello!

After I subscribe to a channel and exactly one minute passes, I get this "Converting circular structure to JSON" issue coming from an Object.stringify command within the codebase.

I'm using Pusher.log to listen to all the events available to me and nothing appears before/after I receive this error.

On the server, it says that I've been disconnected/vacant. My app crashes when this happens.

![screenshot_20160712-215145](https://cloud.githubusercontent.com/assets/1211905/16790396/2b7e4d3a-487b-11e6-868b-b5c6d0bac914.png)

Thanks for the help!

**Comment by peterpme** [comment]
Hey @jackfranklin any chance you can help me debug this issue? Thank you :)

**Comment by jackfranklin** [comment]
@peterpme sorry for a lack of response here. This should be fixed now #186 is all done. Let us know if it's not.

**Comment by jpatel531** [comment]
Yeah - planning to make a release today!
