### ISSUE TITLE
Please update pusher-js on npm to include safe-stringify

### ISSUE THREAD

**Issue by peterpme** [pusher/pusher-js#185]
Hey @jpatel531! Thank you for being awesome and maintaining this library.

I noticed that the version published on npm doesn't reflect your latest change. Do you mind publishing a new version to include this? I would greatly appreciate it.

Thanks!

**Comment by jpatel531** [comment]
Yeah absolutely - I'm going to prioritize getting the library out Monday end of play at the latest

**Comment by peterpme** [comment]
Thank you!

**Comment by peterpme** [comment]
Hey @jpatel531 is this still a possibility today?

Thanks!

**Comment by jpatel531** [comment]
Hey! Ran into some problems with safe stringify and IE<9 yesterday. Resolved. Just going through some (unfortunately) manual tests now and will keep you updated. Thanks for your patience!

**Comment by jpatel531** [comment]
Released as 3.2.0 @peterpme !

**Comment by peterpme** [comment]
Thank you!!!!
