### ISSUE TITLE
How can I display to the user when Pusher is going to reconnect?

### ISSUE THREAD

**Issue by hakunin** [pusher/pusher-js#189]
Hey guys,
I am using Pusher to detect if the user is offline, since it has persistant connection.

How can I display a message to the user, who is offline that says "Reconnecting in X seconds"?

I've seen the `connecting_in`  event, but its not being fired when I disconnect my computer from the internet.

So, how can I display the retry interval to the user?

**Update**: Added SO question, feel free to answer it:
http://stackoverflow.com/questions/39019163/how-can-i-display-to-the-user-when-pusher-is-going-to-reconnect

**Comment by hph** [comment]
@hakunin Given that @bookercodes has answered your question on StackOverflow I think we can close this issue (please correct me if I'm wrong).
