### ISSUE TITLE
User authentication with CORS and headers?

### ISSUE THREAD

**Issue by JonasDoebertin** [pusher/pusher-js#192]
I'm trying to connect to a privat channel here. My API, which also handles the authorization for the private channels as descripbed in the docs, lives under a different domain _(api.example.com)_ while the frontend lives under _example.com_.

The API authorizes requests using JWT, so each request to the API needs to have an `Authorization` header. The problem is: if I'm using `authTransport: jsonp` to make CORS work, I get the console message _Warn : To send headers with the auth request, you must use AJAX, rather than JSONP._

If I use the `authTransport: ajax` setting, I should be able to send the headers, but authorization fails due to this transport not supporting CORS.

Is there a way to get around this limitations?

**Comment by sandstrom** [comment]
Please comment in this issue and request support: https://github.com/pusher/pusher-js/issues/165

**Comment by hph** [comment]
I'm closing "feature request" issues, including this one. This does not mean that the feature will not be implemented, we just want to reserve open GitHub issues to bugs that need to be addressed.

Feel free to comment here to keep the discussion going. People watching the repository will still receive notifications.

**Comment by Nischal-shrestha** [comment]
I have the same exact issue right now. Is there a way to overcome this limitation yet? I see that this feature request is more than 2 years old.

**Comment by gahabeen** [comment]
Same here, any way to make it work?

**Comment by Mentat-Radnor** [comment]
I didn't find the right answer
