### ISSUE TITLE
"fetch is not defined" with use as SharedWorker

### ISSUE THREAD

**Issue by balugege** [pusher/pusher-js#193]
I am trying to implement pusher as a sharedWorker.

I get the "ReferenceError: fetch is not defined" error when i add the cluster option to the pusher init:

```
importScripts("https://js.pusher.com/3.1/pusher.worker.min.js");

// throws no error
var pusher = new Pusher('<%= ENV["PUSHER_KEY"] %>', {
      encrypted: true
});

// throws an error
var pusher = new Pusher('<%= ENV["PUSHER_KEY"] %>', {
      cluster: 'eu',
      encrypted: true
});
```

**Comment by jpatel531** [comment]
ah! which browser is this?

**Comment by balugege** [comment]
Iceweasel which is basicly firefox

**Comment by jpatel531** [comment]
mmmm, you could add the https://github.com/github/fetch polyfill as a quick fix. i chose to support only fetch in the worker build, as i was designing mainly for service workers (which do not support XHR). in light of this, i might add a way to choose between xhr and fetch in the worker build for the future

**Comment by balugege** [comment]
Thanks, that worked.
