### ISSUE TITLE
Bower install doesn't install all files

### ISSUE THREAD

**Issue by curiosity101** [pusher/pusher-js#197]
I've tried doing a bower install and it installs as "pusher-websocket-iso": "pusher#^3.2.1" when I'd have expected  "pusher": "pusher^3.2.1"

Also when it installs I don't get any of the min.js files.

**Comment by hph** [comment]
@curiosity101 I recommend using NPM/Yarn for installing the library instead of Bower, if you can help it. However, I'll take a look into your issue shortly and report back. You're right that the package should be installed as `pusher` instead of `pusher-websocket-iso`. The minified file should also be included.

**Comment by curiosity101** [comment]
@hph Thanks for the quick response. Unfortunately we have a set of coding standards that mean we're meant to use bower for our 3rd party library dependencies. However thanks for the idea, worst case maybe I can convince people we can make an exception this time for this particular case (if turns out to be the fix to the issue).

Why would you recommend NPM / Yarn by the way?

Looking forward to seeing what result you get when you try with the bower install.

**Comment by hph** [comment]
@curiosity101 I got the same result as you doing a bower install, so it's definitely something that needs to be fixed.
 
There are several reasons why I would personally use NPM / Yarn to track dependencies, but some of them might not apply to your use case:
- If you're using Node.js it's nice to only have one package manager for everything. NPM is not only for backend libraries, [see here](http://blog.npmjs.org/post/101775448305/npm-and-front-end-packaging). Things have been going in this direction for some time.
- NPM packages work better with module bundlers like Webpack (which can, for instance, minify libraries and exclude parts you're not using, which you seem to be interested in).
- Bower doesn't (or didn't?) handle nested modules well, so for instance if package `a` and `b` depend on different versions of package `c`, you will run into problems.
- Yarn is just faster than NPM, but other than that it's more or less the same thing. Your dependencies are listed in `package.json`.

Again, the above are just the reasons why I would do it this way and may not apply to your use case. However, we will continue supporting Bower and I'll get back to you after looking into the issue.

**Comment by trippytango** [comment]
@hph Is there an ETA on this working?

**Comment by hph** [comment]
@trippytango I'll try to fit it in this week, so it should be released by Friday.

**Comment by curiosity101** [comment]
@hph Is there any news on this?

**Comment by wawyed** [comment]
Hi, any news on this issue? We are going to start using this library in production and we need the minified file.

**Comment by hph** [comment]
I'm not sure how to address this issue. Bower doesn't seem to come with any built-in support for multiple versions of a file (correct me if I'm wrong). You can always do something like this, though:

    bower install https://js.pusher.com/4.0/pusher.min.js

This will install the minified Pusher lib in `bower_components/pusher.min/index.js`. You can get all the files from the CDN.

Does this solve your problem? If not, do you know what the best way to do it is?

**Comment by wawyed** [comment]
@hph The following PR should fix the issue. I tested it by pointing my pusher-js on my project to my forked version and it included all the files in dist.

**Comment by hph** [comment]
@wawyed's PR has been merged and this will be fixed in the next version released.
