### ISSUE TITLE
Local Notifications

### ISSUE THREAD

**Issue by b8ne** [pusher/pusher-js#199]
Just wondering if adding local notifications is in the pipeline?
Currently using this with RN and being able to receive and create notifications together would be helpful.

**Comment by jpatel531** [comment]
Hey! I did think about this at the time of setting the lib up for react - though I was unsure what the use case was. What stuff in particular do you want to use it for?

**Comment by b8ne** [comment]
Heya, yeah so im using pusher for push notifications. However it only really works for notifications when the app is closed. They allow for when the app is open, but has to be implemented natively. So ive used this package to receive via websocket which is working nicely, but want to be able to convert it to a native local notification. Ive implemented https://github.com/zo0r/react-native-push-notification to send a local notification which also worka nicely. It would be better to use minimal packages though. 
Sorry if that doesnt make sense ill post some screenshots tomorrow.

**Comment by b8ne** [comment]
Sorry completely missed your point - use case. Im building a sports club app, that will send sponsor push notifications as well as training reminders etc. I want the user to receive the same message content whether the app is open or closed, to ensure they dont miss out. Could use websockets alone however that would mean id have to implement a notifications view, which will further complicate the simple app.

**Comment by hph** [comment]
Hi @b8ne, could it be that [Pusher Push Notifications](https://pusher.com/docs/push_notifications) is what you're looking for?

**Comment by b8ne** [comment]
hey @hph yep im already using that. Pusher's intentions are for their push notification service to complement their existing service. Unfortunately their existing service via sockets has no implementation for native local notifications, hence the request here.

**Comment by hph** [comment]
Hi again, @b8ne. We may release a new product with "local notifications" in the future, but it's not strictly in the pipeline right now. In the future, you may get better answers by contacting the sales or support teams for such enquiries.
