### ISSUE TITLE
After ERR_NETWORK_IO_SUSPENDED the connection is restored in different protocol.

### ISSUE THREAD

**Issue by AlexanderVangelov** [pusher/pusher-js#200]
Scenario:
Initial connection is
`wss://ws.pusherapp.com/app/<ID>?protocol=7&client=js&version=3.2.2&flash=false`

Computer is going to sleep mode and then wakeup. 
Log:
* `WebSocket connection to 'wss://ws.pusherapp.com/app/<ID>?protocol=7&client=js&version=3.2.2&flash=false' failed: WebSocket opening handshake was canceled`
* POST `https://sockjs.pusher.com/pusher/app/<ID>/29/j4ietqqd/xhr?protocol=7&client=js&version=3.2.2&t=1478320511260&n=2 net::ERR_NETWORK_IO_SUSPENDED`

Network is up and connection is restored, but in long polling mode:
200 OK: `https://sockjs.pusher.com/pusher/app/<ID>/29/a8prjb9o/xhr?protocol=7&client=js&version=3.2.2&t=1478356724620&n=6`

**Comment by hph** [comment]
Hi @AlexanderVangelov. If you want to control what transports are used you can use [`enabledTransports`](https://github.com/pusher/pusher-js#enabledtransports-array) and/or [`disabledTransports`](https://github.com/pusher/pusher-js#disabledtransports-array). Does this solve your issue?

**Comment by AlexanderVangelov** [comment]
Yes, the issue is solved by updating pusher library to latest version and forcing the protocol with `enabledTransports`.
Thank you.
