### ISSUE TITLE
Channels lose the subscription when reconnects.

### ISSUE THREAD

**Issue by ali32b** [pusher/pusher-js#203]
pusher loses all subscribed channels when reconnects and doesn't receive events. I am using v3.2.3
I've never had this problem with v3.2.1

**Comment by hot-leaf-juice** [comment]
Thanks for reporting this, we've managed to reproduce it and are looking in to it. In the meantime (if you aren't already) you can get v3.2.1 from https://js.pusher.com/3.2.1/pusher.min.js

**Comment by hot-leaf-juice** [comment]
We've tracked down the problem. Going to release 3.2.4 imminently with a fix.

**Comment by hph** [comment]
@ali32b Version 3.2.4 has been released now and the bug introduced in 3.2.3 has been fixed. The CDN at [`http://js.pusher.com/3.2/pusher.min.js`](http://js.pusher.com/3.2/pusher.min.js) is set to the latest version as well.

**Comment by ali32b** [comment]
I'm glad I was able to help.Thank you for the fix.
