### ISSUE TITLE
Triggering event returns true when internet is disconnected.

### ISSUE THREAD

**Issue by ali32b** [pusher/pusher-js#204]
I just noticed when I disconnect internet and then trigger event it returns true while it should return false.
It sends event when internet reconnects again.

**Comment by hot-leaf-juice** [comment]
@ali32b thank's for reporting this.

I have been able to reproduce this under certain conditions. Interestingly I can't reproduce this on Safari, but on Chrome there is a window between losing the internet and pusher-js realising that the connection has been lost. If we try to trigger an event in the interim we get `true` when we should get `false`. After `connected -> connecting` it behaves as expected.
