### ISSUE TITLE
pusher.authenticate is not a function in Node.js

### ISSUE THREAD

**Issue by abachuk** [pusher/pusher-js#208]
When trying to authenticate user, getting `TypeError: pusher.authenticate is not a function`

```
app.post('/pusher/auth', (req, res) => {
  const socketId = req.body.socket_id;
  const channel = req.body.channel_name;
  console.log(pusher); // returns pusher object
  const authenticate = pusher.authenticate(socketId, channel);
  res.send(authenticate);
});
```

Is there an additional step for authenticating users in Node?

My client side code is:

```
const push = new Pusher('app_key_xxx', {
     authEndpoint: '/pusher/auth',
     encrypted: false, // local only
 });
```

**Comment by hph** [comment]
Hi @abachuk. You're probably importing `pusher-js` instead of `pusher` in your server code. This repository is for `pusher-js`. [Here's](https://github.com/pusher/pusher-http-node) the repository for the `pusher` NPM package.

**Comment by abachuk** [comment]
That was it. Thanks @hph
