### ISSUE TITLE
'jsonp' is not a recognized auth transport - React Native

### ISSUE THREAD

**Issue by win45** [pusher/pusher-js#209]
**Do you want to request a *feature* or report a *bug*?**
Is 'jsonp' not intended to work with React-Native when using `authTranport: 'jsonp'`? Is this behavior expected with android and iOS?

**What is the current behavior?**
When authorizing a subscription I'm getting `'jsonp' is not a recognized auth transport` before the endpoint is called

My code simplified:

```
      var pusher = new Pusher('xxxxxxxxxxxxxxxxxxxx', 
        { 
          authTransport: 'jsonp', 
          authEndpoint: 'http://myapi.ngrok.io/pusher/auth',
          auth: {
              params: {
                'id_token': token
              }
          } 
        });

      var channel = pusher.subscribe('private-channel');

     channel.bind('pusher:subscription_succeeded', function() {
	console.log('subscription succeeded')
    }.bind(this));

```
**What is the expected behavior?**
I've tested my code outside of react-native in a web application with success (the endpoint is called and I receive a callback).

**Which versions of Pusher**
` "pusher-js": "^4.0.0",`
`"react-native": "0.39"`

**Comment by rasu007** [comment]
'jsonp' is not a recognized auth transport, I got the same error in React Native Project. Can You help me out how to solve this?

"pusher-js": "^5.1.1",
