### ISSUE TITLE
React Native: unexpected url: /auth/pusher

### ISSUE THREAD

**Issue by win45** [pusher/pusher-js#210]
Platform: (Android)
When subscribing to a private channel I immediately get an `unexpected url: /pusher/auth` error. 

```
componentDidMount() {
     var pusher = new Pusher('xxxxxxxxxxxxxxxxxxxx');
     var channel = pusher.subscribe('private-channel');
}
```

[![Screen Shot 2017-01-02 at 12.20.13 AM.png](https://s29.postimg.org/pgo9hen6v/Screen_Shot_2017_01_02_at_12_20_13_AM.png)](https://postimg.org/image/qiyfzy603/)

However, the logs show a successful connection
Pusher Log:
```
> Pusher : State changed : initialized -> connecting
> index.android.bundle:72883Pusher : Connecting : {"transport":"ws","url":"ws://ws-eu.pusher.com:80/app/xxxxxxxxxxxxx?protocol=7&client=js&version=4.0.0&flash=false"}
> index.android.bundle:72883Pusher : State changed : connecting -> connected with new socket ID 122905.82xxxxx
```

Versions I've tried (clean projects):
React-Native 0.39.2 and Pusher-js 4.0.0
React-Native 0.39.2 and Pusher-js 3.2.4
React-Native 0.39.0 and Pusher-js 3.2.4

**Comment by RakanNimer** [comment]
Hey ! 
You're trying to subscribe to a private channel, so Pusher expects you to provide an auth url and defaults to "/pusher/auth". 

If you don't want to add auth just subscribe to a public channel. 

Hope that helps,

**Comment by win45** [comment]
Wow what a silly oversight. Thanks @RakanNimer.  

I've got auth working with my apis' endpoint on my web application, but I use the `authTransport: jsonp` in that case. My current understanding is that jsonp doesn't work with react-native, but is also required when using an endpoint on another domain (as is my case). I don't think I understand this correctly.
