### ISSUE TITLE
*BUG* IE Edge Pusher WebWorker fails to connect on subsequent loads in the same tab

### ISSUE THREAD

**Issue by cookiesowns** [pusher/pusher-js#214]
Pusher will fail to connect when in WebWorker context on subsequent loads in IE Edge 38.14393.0.0

It fails to connect to pusher, and will start from WS, to WSS, to xhr_streaming, to xhr_polling and fail. 
Error code is: "State changed : connecting -> unavailable", then it repeats the process

Here's helpful test code to reproduce this bug...

Worker.js: https://gist.github.com/cookiesowns/12b91204d478f36d12d09de2d6dde91c

Index.html: https://gist.github.com/cookiesowns/5041c6a28c6d2cefece86f0628d7cf8a

Node script to easily trigger notifications: https://gist.github.com/cookiesowns/03c9cb2c8434af81c97c90780bc7b3f2

Steps:

1. Load Index.html with Worker.js
2. Find that the connection succeeds just fine
3. Refresh the page
4. Notice the connection to pusher will not re-establish..
5. Refresh again...
6. Still not working...
7. You can then open a new tab and note that the first page load will work.

**Comment by sleaze** [comment]
@hph Is IE Edge not a first-class supported browser by Pusher?  I'm a little surprised to find this issue filed with no real response for 10 months.. now I feel a little bit afraid to rely on Pusher.

**Comment by sleaze** [comment]
@hph Is IE Edge not a first-class supported browser by Pusher?  I'm a little surprised to find this issue filed with no real response for 10 months.

..Now I feel a little bit afraid to rely on Pusher.

**Comment by hph** [comment]
Sorry for the late response here, but to be clear this issue only affects you if you're using web workers and an old version of Edge. You can use Pusher inside a worker in Edge 15 and beyond. Regular builds of the library (i.e., when not running in a web worker) work as expected across all versions. That said, we would also like the web worker build to work in Edge 14 and I will update this issue once we've resolved the problem.
