### ISSUE TITLE
[Feature] Add support for Nativescript

### ISSUE THREAD

**Issue by Cayan** [pusher/pusher-js#215]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Add support for Nativescript

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.

**What is the expected behavior?**
To be able to run the javascript pusher library in native android/ios apps.

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
No, just testing the master

**Comment by hph** [comment]
@Cayan pusher-js is built for and relies on browser APIs but (correct me if I'm wrong) NativeScript does not allow you to use these, it's meant to enable you to use JavaScript (the language as opposed to the web platform itself) to build applications for iOS/Android. Please check out the [Swift](https://github.com/pusher/pusher-websocket-swift) and [Java](https://github.com/pusher/pusher-websocket-java) Pusher client libraries instead.
