### ISSUE TITLE
Custom builds

### ISSUE THREAD

**Issue by dvdplm** [pusher/pusher-js#218]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
The pusher client contains code for all fallbacks.

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.

**What is the expected behavior?**
It would be truly amazing to be able to build a custom version of the Pusher with only the transports that needed for the particular project. Lean builds!

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**

**Comment by hph** [comment]
@dvdplm I'm going to close this issue just to reduce noise, but I think this is a good idea and it's one of the build improvements I'd like to make soon.
