### ISSUE TITLE
Accept Application/JSON as an authorization header

### ISSUE THREAD

**Issue by charliesbox** [pusher/pusher-js#219]
When we set the header as 'application/json', in the network tools is show as 'application/x-www-form-urlencoded', 'application/json'

If there is a way to set application/json as the content-type of pusher's auth process, we haven't found it yet :)

**Comment by mautematico** [comment]
Same issue here.
@charliesbox did you found any way to send the request as a `application/json`, instead of `application/x-www-form-urlencoded`?

**Comment by charliesbox** [comment]
@mautematico nope :( we changed our server to support  form-url-encoded.

**Comment by mautematico** [comment]
Sad. May be it's time to dive deep in the source code and start a PR? :)

**Comment by hph** [comment]
If this is something that makes a big difference to you I'm happy to help with a pull request. The implementation should not be very difficult, but here are some things to consider:

- The payload itself is set in `Authorizer.composeQuery`. This would need to be updated to conform to the new content type (when applicable).
- The content type header is set in each of the auth transport mechanisms.
- This new functionality should probably be opt-in (via configuration).

**Comment by hph** [comment]
Closing since #211 has been merged.
