### ISSUE TITLE
On Chrome beta - websocket can go stale

### ISSUE THREAD

**Issue by wdoyle** [pusher/pusher-js#220]
On the Version 57.0.2987.98 beta of Google Chrome - if you restart your browser you can sometimes create a stale web socket connection. Which presents itself with the following error:  Connection interrupted (0)
The only fix for this is to use the following options when creating your pusher connection:
`            disabledTransports: ["xhr_streaming"],
            enabledTransports: ['wss','ws']`

It might be worth looking into this, however this is more of a guide for anyone else stuck with this issue

**Comment by hph** [comment]
@wdoyle Is this still the case for you on the non-beta v57?

**Comment by leesio** [comment]
I'm going to close this issue as there hasn't been an update for a long time. I assume this is no longer an issue.
