### ISSUE TITLE
windows phone

### ISSUE THREAD

**Issue by ryuken** [pusher/pusher-js#221]
**Do you want to request a *feature* or report a *bug*?**
Bug on Lumia 625 (Cyan) 3.7.16, Windows 8.1

**What is the current behavior?**
Nothing happens (on all other browsers it does work.

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.
<script>
      var pusher = new Pusher('aa0a412eb7908f24bd6b', {
          cluster: 'eu',
          encrypted: true
      })

      pusher.connection.bind('connected', () => {
          alert("connected html!")
      })
  </script>

**What is the expected behavior?**
It should print the alert box

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
pusher 4.0 === <script src="https://js.pusher.com/4.0/pusher.min.js"></script>

**Comment by hph** [comment]
Hi @ryuken, and thanks for reporting this issue. I don't have a Windows phone here but I tried running https://test.pusher.com on a Windows device on Browserstack and it appears to be working correctly. Can you confirm whether the test page works on your phone? Thanks!

**Comment by ryuken** [comment]
Thanks! It works, but HTTPS/SSL doesn't work.
It works when I use `<script src="http://js.pusher.com/4.0/pusher.min.js"></script>`
Instead of `<script src="https://js.pusher.com/4.0/pusher.min.js"></script>`
Also with `encrypted: false` in the options
