### ISSUE TITLE
Pusher doesn't receive messages after a network change

### ISSUE THREAD

**Issue by vkulov** [pusher/pusher-js#223]
I'm having issues with pusher sometimes not receiving messages on a channel it is subscribed to. It happens randomly for our clients. We managed to reproduce it consistently by changing the network adapter we use for internet connectivity. The test was conducted on both Windows 10 and a Mac OS X machine under Chrome browser. We use your test page on https://test.pusher.com

First we open the test page and verify that both Ajax and Client triggers work properly.

![image](https://cloud.githubusercontent.com/assets/134308/24883819/4e3cee4e-1e4f-11e7-82b6-9543e38f2a40.png)

Then we disconnect the network by unplugging the cable connection. Pusher detects that there's no connection.

![image](https://cloud.githubusercontent.com/assets/134308/24883862/77c69d1e-1e4f-11e7-9b27-bfd8589f1f31.png)

Then we connect to a wi-fi network backed by a mobile hotspot.

![image](https://cloud.githubusercontent.com/assets/134308/24883920/c5f1665e-1e4f-11e7-98f1-b4f29af5925c.png)

Pusher successfully re-connects and we verify that it works. We try this one more time. Going back and forth between the cable connection and the wi-fi mobile hotspot (until we get the 1006 error message.)

![image](https://cloud.githubusercontent.com/assets/134308/24883978/002511fe-1e50-11e7-923c-9c3e87d6b66a.png)

After the network is reconnected pusher discovers that and says 'connected'. However the Ajax Trigger button doesn't print anything in the log. And clicking the Client Trigger shows an error message "Cannot broadcast client event (connection not subscribed to channel presence-channel)"

![image](https://cloud.githubusercontent.com/assets/134308/24884037/4abbb6d2-1e50-11e7-8649-ed2f2d701b47.png)

Clicking Disconnect and then Connect buttons doesn't recover Pusher. It prints out [status] disconnected and then [status] connected but the Ajax Trigger button still doesn't work and the Client Trigger button still prints the same error.

We verify in Network tab on chrome that the Ajax Trigger button successfully sends the 'hello' request to pusher server and received a response from server 'ok' but the we get nothing printed in the logs.

We are able to reproduce this consistently. Let me know if we can get any more debug info for you.

**Comment by hph** [comment]
@vkulov Thanks for reporting this issue and describing the steps to reproduce it in detail. I'm looking into the matter and I will get back to you soon.

**Comment by andefred** [comment]
This looks like a very clear description a the problem that we are too experiencing and it is really frustrating. Would love any update on this issue. We have pusher implemented in a chrome extension, and whenever you switch network it doesn't recover like it used to. The only way I've been able to make it reconnect again is to reload the entire extension and start the connect and auth calls from scratch.

Is there a way to catch this and then trigger some notification to the user to force a reload?

**Comment by andefred** [comment]
I just tested this exact scenario with our application too. I connect while on my regular wifi connection, then disconnect and connect to my cellphone tether network. Pusher still says that I'm connected, but the websocket is lost and stopped at a ping.

Then if I from the console bring up the current Pusher instance and manually run .connect() it starts working again. it's a bit too much internal info to share the full trace here, but would love to help solve this issue if @hph or someone would like some live triggering of this problem.

**Comment by hengwoon** [comment]
We at Reamaze are seeing this issue as well. For now we'll try to manually re-establish the pusher connection and run through all subscriptions again, but would be really helpful if this could be fixed as it's been really frustrating for our users.

As others have mentioned it happens when network changes, or if I turn on my laptop in the morning after having it put to sleep the prev night.

**Comment by Bartalog** [comment]
Same here, in slightly different use case: if the user happens to visit my page with a mobile device, it is expected that the Pusher connection works fine, like on desktop browser. But as soon as the mobile changes network (e.g. 3g -> wifi), the Pusher connection is lost.

**Comment by brubbel** [comment]
Possibly related to this: dangling event handlers on socket of previous connection.
https://github.com/websockets/ws/issues/1142

**Comment by hph** [comment]
I haven't been able to reproduce this issue after @hengwoon's changes, so it looks like the issue is fixed. If you're having problems, make sure that you're using the latest version of the library (4.2.2).

**Comment by Bartalog** [comment]
4.2.2 doesn't seem to solve my mobile-network-change problem, I'd better create a new issue for this.
