### ISSUE TITLE
Don't export Pusher on window object (optionally)

### ISSUE THREAD

**Issue by stevenmusumeche** [pusher/pusher-js#225]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
When importing pusher-js in a webpack-built project...

`import Pusher from 'pusher-js';`

The Pusher object is exported on the global window namespace.

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.

**What is the expected behavior?**

There is an option, similar to [jQuery's `noConflict`](https://api.jquery.com/jQuery.noConflict/), that does not export the Pusher object into the global window namespace.

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**

Version 4

---------------
I am building a Javascript widget that is embedded on third-party websites.  In cases where Pusher is already included on the website (out of my control), there is no way for me to use Pusher within my widget without overwriting the global window.Pusher object and breaking the third-party website.

**Comment by hph** [comment]
Hi @stevenmusumeche,

There have been requests about this feature [before](https://github.com/pusher/pusher-js/issues/158) and there are some ugly workarounds. The best solution would probably be to use a different build (that doesn't pollute the global namespace) for NPM imports. This would still be a breaking change, however. I haven't looked into this much but, if you're interested, `window.Pusher` is set [here](https://github.com/pusher/pusher-js/blob/master/src/runtimes/web/runtime.ts#L44). I'm not sure whether the comment on that line is accurate, but there should be ways around it.

**Comment by stof** [comment]
The affected line says that `Pusher` needs to be available as a global for the jsonp transport. Maybe it could be done only if the jsonp one is used (defining it on first usage).
Another option would be to have the JSONP wrapper defining its callback elsewhere than in the `Pusher` object

**Comment by hph** [comment]
@stof Unfortunately, JSONP is also used internally so at the moment we're not able to remove it completely. I looked into this the other day and came to a conclusion similar to yours, that it might just be easiest to keep JSONP support but to optionally change the global variable used. However, I'm not really happy with this conclusion and I'd like to find a better solution.

**Comment by da1z** [comment]
Is there recommended approach to work around it? Version conflict happens when host page using different version of pusher unlike injected app.
