### ISSUE TITLE
Documentation is inaccurate

### ISSUE THREAD

**Issue by blittle** [pusher/pusher-js#226]
**Do you want to request a *feature* or report a *bug*?**
*bug*
**What is the current behavior?**
The documentation references a feature that is not yet released: https://github.com/pusher/pusher-js#authorizer-function 

I spent a couple hours debugging the problem and then realized the feature is in master but not yet released. This is frustrating because the docs don't provide much in and of themselves (other than a getting started guide) other than a link to this repo.

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
No

**What is the expected behavior?**
If it gets merged into master, a timely release would be best, (or host the docs somewhere else).

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**

**Comment by hph** [comment]
Hi @blittle,

I'm sorry for the troubles this caused. Releasing a new version is unfortunately a slow and rather tedious process, so I wanted to try to get as many things in as I could (e.g., the single currently open PR).

I'm going to release a new version now. In the future, I can merge PRs into a `next` branch, or something similar. Thanks for bringing this up, and again, I'm sorry about that!

**Comment by blittle** [comment]
@hph thank you for publishing a new release. I figured I should make you aware because others might be encountering the same problem.

**Comment by hph** [comment]
@blittle Absolutely, and thank you!
