### ISSUE TITLE
react_native_1.NetInfo.fetch(...).done is not a function

### ISSUE THREAD

**Issue by tvkhoa** [pusher/pusher-js#227]
**Do you want to request a *feature* or report a *bug*?**

I want to report a bug

**What is the current behavior?**

react_native_1.NetInfo.fetch(...).done is not a function

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.

I use pusher.js for react-native

`import Pusher from 'pusher-js/react-native';`

**What is the expected behavior?**

If I change .done to .then, it works as normal

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**

React native 0.42.0
iOS simulator 10.0
pusher-js 4.0.0

**Comment by hph** [comment]
Hi @tvkhoa,

You're in luck! I just released a new version that should fix your issue, v4.1. Please don't hesitate to let me know if it doesn't solve your problem.

Best,
Haukur

**Comment by tvkhoa** [comment]
Thank you, @hph 👍
