### ISSUE TITLE
Bug with encrypted

### ISSUE THREAD

**Issue by ryuken** [pusher/pusher-js#229]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Encrypted = true works correctly on all platforms except Windows phone.
So we put encrypted to false, then it worked on all platforms.
But there is a new bug now that encrypted is on false.
When encrypted is true, reconnecting is fast.
When encrypted is false, reconnecting takes too long time.

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.
For example on Android when encrypted: true, and you leave your browser or put the screen on standby and reopen the screen after a few min, the reconnecting is fast.

When encrypted is false on the same device, the reconnecting takes too long.

**What is the expected behavior?**
It should reconnect fast on non-encrypted too.

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
Pusher 4.0, didn't test on older Pusher versions
All browsers, all OS

**Comment by hph** [comment]
Hi @ryuken,

After a cursory review I haven't been able to reproduce this on desktop and Android Chrome, using https://test.pusher.com. Could you please define what you mean by "too long"? Also, is this something you can reproduce consistently or does it just happen sometimes? After being disconnected, pusher-js will try to reconnect on a predefined interval, so reconnecting might not always take the same time. That said, to me there doesn't seem to be a discernible difference between reconnect timings for `encrypted=false` and `encrypted=true`. However, the library employs connection "strategies" and these are different depending on whether encrypted is set to true or false. This might be the source of the problem, but it seems weird, as the list of possible transports is shorter when `encrypted` is set to `false`. This will require digging a bit deeper. If you can provide an example of the issue it would be really helpful.

**Comment by ryuken** [comment]
Could it be that it has to do with ports?
Encrypted is on 443 and non-encrypted on port 80?
Most firewalls block 80 (our customers are government and have a heavy firewall).
How does the reconnecting strategy work when port 80 is blocked?

**Comment by leesio** [comment]
I'm going to close this ticket as I assume it's stale. If it's still a problem please feel free to reopen.
