### ISSUE TITLE
Cannot receive events in react native client 

### ISSUE THREAD

**Issue by harishsn** [pusher/pusher-js#231]
Bug

Laravel application broadcasts event name 'App\Events\NewMessage' however react native pusher client is not receiving event. I can receive event when I send an event from pusher console like 'NewMessage' and listen for 'NewMessage' but not when i send 'App\Events\NewMessage'. I think the issue is with `\` Does not work when event name has `\`

Try to send event as 'App\Events\NewMessage' and listen for same

pusher react native v4.1.0
OS :MacOs Seirra

**Comment by harishsn** [comment]
Upon debugging found out pusher client is ignorning `\` in event name. Strange but this works `AppEventsNewMessage`

**Comment by riskteria** [comment]
Hello, i also had the same problem.
How to bind the event on react-native?
