### ISSUE TITLE
Keep getting error message "null is not an object (evaluating 'this.connection.handlesActivityChecks')"

### ISSUE THREAD

**Issue by cowardcalf** [pusher/pusher-js#233]
Hi, our production have this error. 

We've been using Pusher-js in our production for a long time.
Since about 6 months ago, we keep receiving an error like
`null is not an object (evaluating 'this.connection.handlesActivityChecks')`.

The errors have been reported by our Raygun service, may not be able to reproduce that.

Looks like it happens for some particular users using Safari.

The users' environments is
    Mac OS 10.11.6 / 10.10.5 / 10.12.3 etc.
    Safari 10.0.3

The version of pusher-js is from ^3.0.0 to ^4.0.0.

This issue could be similar to #82

**Comment by cowardcalf** [comment]
The error stack is like this:
![image](https://cloud.githubusercontent.com/assets/7615269/26189693/3946f5d6-3be9-11e7-8311-41e57d34d6a8.png)

**Comment by cowardcalf** [comment]
Hi, @pl, @jpatel531, would you guys be able to help or give any advice?

**Comment by Sparkmasterflex** [comment]
I'm currently getting this issue too. Any progress on this?

<img width="1217" alt="screen shot 2017-10-23 at 8 51 51 am" src="https://user-images.githubusercontent.com/726129/31907437-83e381b0-b7cf-11e7-8696-c64fc9556fb6.png">

<img width="1210" alt="screen shot 2017-10-23 at 8 52 15 am" src="https://user-images.githubusercontent.com/726129/31907438-8408d8ca-b7cf-11e7-8c47-f40411cef609.png">

**Comment by cowardcalf** [comment]
@Sparkmasterflex, I've talked with them via submitting a support ticket.

They reckon that could be a racing issue but not affecting the normal use.
It's more like an unnecessary error message.
They said they would fix that in the future. 😅

**Comment by hph** [comment]
Hi, are you using the latest version of the library (4.2.1)?

**Comment by Sparkmasterflex** [comment]
I am not. I believe there was a reason that we're stuck at 3.0.0

Does one of the later releases specifically correct this? I have a number of external React components that I would have to upgrade and I believe the last time I tried a minor 3.x upgrade it completely broke one.

I can try to upgrade but don't want to spend the time if it's just a "it could help"

Thanks for the replies

**Comment by hph** [comment]
@Sparkmasterflex It was fixed in [this commit](https://github.com/pusher/pusher-js/commit/b1216aceda01efe40916f7fb19f09bdfae491dc6) and is included in version 4.2.0 and above (see [release notes](https://github.com/pusher/pusher-js/releases/tag/v4.2.0)). I completely forgot to close this issue and notify subscribers about it. Sorry about that.
