### ISSUE TITLE
support websocket connections via proxy

### ISSUE THREAD

**Issue by tonygaetani** [pusher/pusher-js#235]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
pusher-js does not support websocket connection via proxy

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
pusher version: 4.1.0
platform: nodejs
I do not believe this ever worked with pusher-js

pusher-js uses faye-websockets for nodejs websockets and [faye-websockets supports websocket connections via proxy](https://github.com/faye/faye-websocket-node#using-the-websocket-client) but pusher-js does not allow you to pass the proxy information to the constructor of a faye-websockets WebSocket

I am currently working on implementing this and I would be happy to contribute to the project

**Comment by tonygaetani** [comment]
Okay unfortunately I don't have time to implement this, but there's some info on how I plan on working around this issue here: https://github.com/6RiverSystems/pusher-js/pull/4 

...but beware: it's not pretty

**Comment by hph** [comment]
Hi, @tonygaetani! Did you end up using your implementation, or a version of it? If you did, I'd be happy to review a PR and help tweaking it. Still, I think the use case is a bit uncommon, so I'm a bit on the fence here.

**Comment by tonygaetani** [comment]
Hi, thanks for the response. I never put the time and effort into a proper solution, at the time that I was working on this I couldn't afford to, so instead I sketchily patched my fork to support proxies only in nodejs, and I did it in a way that is not maintainable. I regret not having the time to properly contribute back to your library :-/

If I'm not mistaken, basically all you need to do is make it possible to use https://github.com/beuckm/node-XMLHttpRequest instead of https://github.com/ykzts/node-xmlhttprequest and then make it possible to pass proxy config to the library somehow. I think that's it.

You can see my sketchy version here https://github.com/6RiverSystems/pusher-js/pull/4/files#diff-03ba53ce9cc91bdd9aa0c223944cf78fR347

**Comment by tonygaetani** [comment]
If you want to close this ticket, that's fine with me
