### ISSUE TITLE
Invalid key in subscription auth data: 'INSERT_YOUR_KEY_HERE'

### ISSUE THREAD

**Issue by KumailHussain** [pusher/pusher-js#237]
I have created my app at Pusher and also enabled Enable client events from the App settings menu 
i used my authentication provided at https://dashboard.pusher.com/apps/350337/getting_started but when I am receiving error  
**pusher.min.js:8 Pusher : Error : {"type":"WebSocketError","error":{"type":"PusherError","data":{"code":null,"message":"Invalid key in subscription auth data: 'INSERT_YOUR_KEY_HERE'"}}}** on browser
while on My app dashboard I am receiving the error:
[
![capture](https://user-images.githubusercontent.com/22370036/26973317-6bead28a-4d2f-11e7-9a98-415eb714ff22.PNG)
](url)
I am using Java script for client side

**Comment by hph** [comment]
Hi @KumailHussain. The error message you shared is saying that `INSERT_YOUR_KEY_HERE` is not a valid key. If you find where you're setting the key to that value in your codebase you should be able to replace it with the correct value.

**Comment by KumailHussain** [comment]
[
![capture](https://user-images.githubusercontent.com/22370036/27013354-cd23a3b6-4e96-11e7-8b7b-e6bc9a8a9244.PNG)
]
I am using this key as mentioned in my App dashboard but still receiving error
