### ISSUE TITLE
message":"Invalid key in subscription auth data:

### ISSUE THREAD

**Issue by KumailHussain** [pusher/pusher-js#238]
https://github.com/ankeetmaini/collaborative-text-editor
I am using this example and set the api key as my own app key but receiving this warning:
**pusher.min.js:8 Pusher : Error : {"type":"WebSocketError","error":{"type":"PusherError","data":{"code":null,"message":"Invalid key in subscription auth data: 'INSERT_YOUR_KEY_HERE'"}}}
warn	@	pusher.min.js:8**
as pusher stated my key as :
![capture](https://user-images.githubusercontent.com/22370036/27013478-5e4baf6c-4e99-11e7-9a91-0e63b774098b.PNG)
and my code chunk is:
  **var pusher = new Pusher('1e902b59383516699a76', {
          cluster: 'ap2',
          encrypted: true
      });**
even i tried this too 
**      var pusher = new Pusher('1e902b59383516699a76');
**
can you suggest me what i am doing wrong
the error log in my app dashboard is stating :  
![capture](https://user-images.githubusercontent.com/22370036/27013487-b1ecfb80-4e99-11e7-896a-378c3955c6cf.PNG)
i dont know whats going wrong

**Comment by hph** [comment]
Hi @KumailHussain,

I checked out the project you linked and I believe you also have to update the keys [here](https://github.com/ankeetmaini/collaborative-text-editor/blob/master/server.js#L13-L15), in the server file. The server uses [pusher-http-node](https://github.com/pusher/pusher-http-node) while the front-end uses pusher-js (this repository). In any case, you should be able to find the file that's causing this issue by searching for `INSERT_YOUR_KEY_HERE` and replacing it with your key.
