### ISSUE TITLE
React-Native potential Android performance issues

### ISSUE THREAD

**Issue by justinmstuart** [pusher/pusher-js#239]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
React-Native is showing a warning when Pusher-js is included in the project and the client is created. See the following:
![screenshot_1498748682](https://user-images.githubusercontent.com/1878176/27694797-297708c4-5cbb-11e7-8fad-679435966cf3.png)

**If the current behavior is a bug, please provide the steps to reproduce and
Create React-Native project with React-Native 0.45.1 and include pusher-js 4.1.0. Implement basic pusher client and observe warning.

I wanted to make sure that you were aware of this issue and ask if this is something that will be fixed in future releases?

**Comment by hph** [comment]
I don't think this is something we can (or should) fix. `setTimeout` is required for background checks for things such as pings & reconnection logic. If React Native provides another interface for connection timers then we could use that instead, but I'm not aware of that being the case.

It's worth noting that if you need to, you can always close the connection to prevent these timers from being set.

**Comment by OleksandrKucherenko** [comment]
solution: https://github.com/pusher/pusher-js/issues/248#issuecomment-334711886
