### ISSUE TITLE
Presence channel does not trigger member_added

### ISSUE THREAD

**Issue by tejinderss** [pusher/pusher-js#24]
For the past 4-5 days, the member_added event is not being triggered when the new member joins in the channel. Below are the events that are received:

Pusher : Event recd : {"event":"pusher_internal:subscription_succeeded","data":{"presence":{"count":1,"ids":["tejinder"],"hash":{"tejinder":{"image":{"url":"/media/images/placeholder.png"}}}}},"channel":"presence-test34"}
Pusher : Event recd : {"event":"sketch-stroke","data":{"value":"[]"},"channel":"presence-test34"} 
Pusher : Event sent : {"event":"pusher:ping","data":{}} 
Pusher : Event recd : {"event":"pusher:pong","data":{}}

**Comment by Coding-007** [comment]
Did you find your issue?
