### ISSUE TITLE
the person who is moderator of the channel, should have the ability to disconnect any one by passing his user_id

### ISSUE THREAD

**Issue by chnauman** [pusher/pusher-js#242]
**What is the expected behavior?**
In the presence channel when Pusher asks for authentication from server, where server sends him back userID and name. I think there should be another parameter for member_type: moderator or attendee. Later on moderator can trigger for disconnection of any attendee by passing its ID to Pusher and the attendee should get disconnected from server side. Because If moderator triggers a msg asking the specific user to call on a pusher.unsubscribe() function in JS. Any user with a little bit of JS experience can simply uncomment those lines and will remain in the channel for as long as he like... 
and is there a way to send a msg to a specific person by passing an array of userIDs, other should not get that msg.

**Comment by hph** [comment]
Hi @chnauman. We currently don't support forcing clients to unsubscribe or preventing them from re-subscribing to presence channels. I've added your use case to an internal list of feature requests, but I can't promise we will deliver this feature or when. As for sending messages to specific users, you can publish an event that only that particular client is subscribed to.
