### ISSUE TITLE
Connections events are not triggered in Chrome

### ISSUE THREAD

**Issue by josuemontano** [pusher/pusher-js#243]
**Do you want to request a *feature* or report a *bug*?**
A bug.

**What is the current behavior?**
When the network connection is temporarily lost the `disconnected` event is never triggered. When the network connection is back a `connected` event isn't triggered either. This bug doesn't happen in the latest version of Firefox, only in Chrome (just tested versions >= 59).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
1. Open https://codepen.io/josuemontano/pen/XgwPpp in latest version of Chrome.
2. Open the Codepen console
3. Disconnect from internet (either physically or through the Developer Tools)

**What is the expected behavior?**
The `connected` and `disconnected` event should be triggered.

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
I tested with versions 3.x and 4.x of pusher-js in macOS. These events used to be triggered properly in Chrome 57.

These GIFs show the different behavior in Firefox and Chrome.

Correct:
![2017-07-19 12 02 03](https://user-images.githubusercontent.com/1854377/28386023-479e13d2-6c98-11e7-885f-a963ea88aa37.gif)

Incorrect:
![2017-07-19 15 03 48](https://user-images.githubusercontent.com/1854377/28386022-479aec52-6c98-11e7-9c2d-b489c5c904f4.gif)

**Comment by hengwoon** [comment]
This is working for me (in Chrome 60). The transition from Connected -> Unavailable does take a while (close to a minute) after turning off internet. I would try using http://test.pusher.com/ to see if you can reproduce this issue

**Comment by hph** [comment]
Hi @josuemontano. I just tried your codepen and while I did have to wait for a while, both the unavailable and connected messages were logged to the console, so everything appears to be working as expected. Sorry for the delay in answering. If you do have any further problems, please do let us know.
