### ISSUE TITLE
Initializing Pusher blocks the UI for more than 100ms

### ISSUE THREAD

**Issue by stof** [pusher/pusher-js#244]
I'm using the latest version of Pusher (4.1 loaded from your CDN).

when I instantiate pusher in my code (`new Pusher(API_KEY, {encrypted: true})`), this blocks the UI for more than 100ms (I'm running profiling with a 5x CPU throttling enabled in the Chromium DevTools, to simulate a computer less powerful than mine). During this time, the UI is unresponsive (and none of my code can reduce this time except dropping the usage of Pusher entirely, which is not good).
A bit more than half of the time is spent in `createConnectionManager`, most of it being spent by `ConnectionManager#updateStrategy`.

It would be great if this code could be optimized (or broken down into several blocks, to allow the UI to respond sooner)

**Comment by hph** [comment]
Thanks for raising this issue, @stof. In most cases you should be able to alleviate this by waiting until the page is fully loaded and ready before connecting to Pusher. If this doesn't work for your use case, could you provide more context about what you're trying to do? Thanks!

**Comment by stof** [comment]
Well, I was connecting to Pusher in a jQuery ready callback. and I was trying to reduce the time blocking the UI in the frame where jQuery was running the ready callbacks (several seconds due to all the code running in it).
I'm now delaying the Pusher subscription into the next frame (using `setTimeout(..., 0)`). But it still means that this next frame will take time due to spending 150ms initializing Pusher.
It would be great to at least try optimizing Pusher before closing the issue. A profile spending 100ms to create the connection manager looks like something to investigate (at this point, it has not yet started to connect to the remote server AFAICT).

Btw, it seems to spent lots of time in `Collections.extend`.

**Comment by hph** [comment]
@stof You're absolutely right, and it may have been a bit premature to close this. I'm happy to reopen it and take a better look at this.

**Comment by stof** [comment]
The time spent downloading and parsing the JS is not the issue here. pusher-js is now bundled in my webpack build, so I'm 100% sure that the code is already downloaded by that time (and anyway, using `new Pusher()` could not work before downloading and parsing the code anyway).

On a desktop computer, the call to `updateStrategy` (inside the creation of the connection manager) takes 52ms *without any throttling*.
It looks like most of the time is spent in `evaluateArray`

**Comment by stof** [comment]
Maybe using actual code rather than a DSL would work better here, by allowing the JS engine to apply any optimization it can apply.
If this DSL is considered easier to maintain for you (which I'm not convinced personally as it requires learning it), a solution to get both world would be to convert the DSL to JS/TS at build time

**Comment by stof** [comment]
I tried this approach, and the usage of the DSL was indeed the cause of the issue...
