### ISSUE TITLE
React Native Android Long Timer Problem

### ISSUE THREAD

**Issue by omeraplak** [pusher/pusher-js#248]
Android app throwing this warning;

ReactNativeJS: Setting a timer for a long period of time, i.e. multiple minutes, is a performance and correctness issue on Android as it keeps the timer module awake, and timers can only be called when the app is in the foreground. See https://github.com/facebook/react-native/issues/12981 for more info.

I look the pusher-js config and i saw it;

Pusher-js - activity_timeout is 120000

How we can solve this issue?

Versions;
React: 16.0.0-alpha.12
React-Native: 0.46.4
Pusher-js: 4.1.0

**Comment by hph** [comment]
This was previously raised in #239 and unfortunately nothing has changed since then. You can always [configure timers yourself if necessary](https://github.com/pusher/pusher-js#activitytimeout-integer) (you can try setting it to 60000, for instance). Hopefully this solves the issue for you.

**Comment by chocky335** [comment]
@omeraplak @hph Try to use that lib for android [react-native-background-timer](https://github.com/ocetnik/react-native-background-timer) :
import BackgroundTimer from 'react-native-background-timer';

setTimeout = BackgroundTimer.setTimeout.bind(BackgroundTimer)
setInterval = BackgroundTimer.setInterval.bind(BackgroundTimer)
clearTimeout = BackgroundTimer.clearTimeout.bind(BackgroundTimer)
clearInterval = BackgroundTimer.clearInterval.bind(BackgroundTimer)

**Comment by omeraplak** [comment]
@chocky335 thank you!

**Comment by greatwitenorth** [comment]
Is there any solution for those of us using Expo and not wanting to have to eject our app?

**Comment by omeraplak** [comment]
This was previously raised in #239
<https://github.com/pusher/pusher-js/issues/239> and unfortunately nothing
has changed since then. You can always configure timers yourself if
necessary <https://github.com/pusher/pusher-js#activitytimeout-integer> (you
can try setting it to 60000, for instance). Hopefully this solves the issue
for you.

**Comment by 2rist** [comment]
@omeraplak @hph 
The issue is still there. Is there any plan to use  https://github.com/ocetnik/react-native-background-timer or fix the issues somehow else?

**Comment by RSSfeed** [comment]
+1

**Comment by elizamaria** [comment]
+ 1

**Comment by markymc** [comment]
+1

**Comment by MUllman** [comment]
+1

**Comment by cpmech** [comment]
+1

**Comment by massivebrains** [comment]
+1

**Comment by madhudskumar** [comment]
+1

**Comment by madhudskumar** [comment]
```js
const socket = new Pusher('xxx', {
  cluster: 'mt1',
  activityTimeout: 6000
});
```

this worked for me
