### ISSUE TITLE
pusher:subscription_succeeded doesn't fire on re-subscribe

### ISSUE THREAD

**Issue by Hypnopompia** [pusher/pusher-js#256]
If I subscribe to a private channel, then unsubscribe from it, then subscribe to it again, my callback function for pusher:subscription_succeeded is only triggered on the first subscription. I would expect this to fire every time I successfully subscribe.

**Comment by hph** [comment]
Hi @Hypnopompia,

I think you may have mixed up the `channel.subscribe` and `channel.unsubscribe` with `channel.bind` and `channel.unbind`. If you call `channel.unsubscribe` it should remove the subscription and no bound callbacks should be called. I think what you're looking for is `channel.unbind` instead.

For instance compare these two snippets:

```javascript
const channel = pusher.subscribe('my-channel');
channel.bind('my-event', data => {
  alert(data.message);
  channel.unsubscribe(); // Binding will not work after this
  channel.bind('my-event', data => {
    alert(data.message); // This will never fire.
  });
});
```

And:

```javascript
const channel = pusher.subscribe('my-channel');
channel.bind('my-event', data => {
  alert(data.message);
  channel.unbind('my-event'); // This unbinds this callback.
  
  // But now, we rebind:
  channel.bind('my-event', data => {
    alert(data.message); // This will fire.
  });
});
```

If you paste the first example into an HTML snippet with your credentials and emit an event in the debug console, you'll notice that only one event shows an alert. If you try the second example, it should show an alert for as many events as you emit.

I do think this API is a bit confusing, and at least we should emit a warning when this happens. We're aware of this issue and might improve this in a future release.

Do let me know if this does not solve your issue. If you have a code snippet showing your use case it might also be a bit easier to give relevant feedback.
