### ISSUE TITLE
Uncaught TypeError: Pusher.auth_callbacks.1 is not a function

### ISSUE THREAD

**Issue by Sparkmasterflex** [pusher/pusher-js#258]
**Do you want to request a *feature* or report a *bug*?**
Possible Bug or I'm doing something wrong

**What is the current behavior?**
more than 50% of the time I receive 2 errors that don't appear to actually break anything as far as our functionality but it is filling up our Sentry JS logs and have made the sentry completely un manageable.

```
  Uncaught TypeError: Pusher.auth_callbacks.1 is not a function
  Uncaught TypeError: Pusher.ScriptReceivers[1] is not a function
```

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.
The only thing I can think of is we have 2 different Pusher instances that auth to 2 different endpoints and must be separate. I believe I was getting an issue before due to this, but that was completely breaking the functionality

**What is the expected behavior?**

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**

Every browser, both windows and osx and Pusher 3.0.0

**Comment by Sparkmasterflex** [comment]
So I've recently upgraded all the things to use `pusher-js@4.2.1` and I'm still getting these errors all the time. 

<img width="1255" alt="pusher-error" src="https://user-images.githubusercontent.com/726129/32195911-f222c404-bd62-11e7-8597-423b644be403.png">

does anyone know how to fix this?

**Comment by hph** [comment]
Hey @Sparkmasterflex! While it does not fix this issue, you could try using `'ajax'` as the value for `authTransport`, instead of `'jsonp'`. In any case, this issue won't be closed until the underlying issue has been fixed.

**Comment by jasiu001** [comment]
I have the same issue for 4.2.2. There is any chance it will be fix soon?

**Comment by bhayanihitesh** [comment]
Is this issue fixed?

**Comment by leesio** [comment]
@hitesh-rg are you experiencing this issue now? Are you able to provide any more information on it?
