### ISSUE TITLE
npm package contains a copy of the source code

### ISSUE THREAD

**Issue by nebirhos** [pusher/pusher-js#262]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Releases v4.2.0 and v4.2.1 contain a copy of the source code inside `dist/*/Users/haukur`. Not sure if it's intentional or not, but v4.1.0 doesn't have it.

**Steps to reproduce**

```
wget `npm view pusher-js@4.2.1 dist.tarball`
tar xfz pusher-js-4.2.1.tgz
du -sh package/dist/*/Users/haukur/Code/pusher-js
372K    package/dist/node/Users/haukur/Code/pusher-js
344K    package/dist/react-native/Users/haukur/Code/pusher-js
384K    package/dist/web/Users/haukur/Code/pusher-js
348K    package/dist/worker/Users/haukur/Code/pusher-js
```

**What is the expected behavior?**

`dist/*` containing only compiled javascript, not source code.

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**

v4.2.1 and v4.2.0 are affected.
v4.1.0 works as expected.

**Comment by hph** [comment]
Thanks for reporting this, @nebirhos - this was not intended. The next version of the library will not include these directories.
