### ISSUE TITLE
Error: Pusher.ScriptReceivers[1] is not a function

### ISSUE THREAD

**Issue by iw-jway** [pusher/pusher-js#263]
**Do you want to request a *feature* or report a *bug*?**

*bug*

**What is the current behavior?**

I repeatedly get the error: https://www.screencast.com/t/Di3E0qO9

It looks like the issue is caused by this: https://www.screencast.com/t/fJbp6tn4, trying to reach: stats.pusher.com.

The response from stats.pusher.com returns 
"Pusher.ScriptReceivers[1](null, { host: 'timeline31-clientstats1.pusher.com' });", which I think is causing the error, see: https://www.screencast.com/t/8XCzANCkQA38

Running that manually in the console, also generates an error: https://www.screencast.com/t/glThi23Mq9Zj

The Pusher.ScriptReceivers object looks like this: https://www.screencast.com/t/3k3ifOVYWjEe

Note, I am not using any authentication object for Pusher.

**What is the expected behavior?**

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**

v4.2.1

**Comment by hph** [comment]
Hi, @iw-jway. Are you using two or more instances of the library in your project? I've managed to reproduce your issue by loading Pusher twice on the page. Lamentably, this is currently not supported (but it will be). The reason is that the library makes use of the global namespace (`window.Pusher`) for some of its functionality and if a second instance is loaded it will override any previous instances.

**Comment by sathishkumar94** [comment]
Hi, @hph . I'm using one instances of library in my project. Seems facing that same issue.

**Comment by thegnuu** [comment]
I just ran into this issue using pusher in my angular-cli project using es6 imports to add pusher and webpack it. "Fixed" it by setting pusher to undefined in my index.html head. Might not be ideal, but at least it prevents this error from happening and showing up in my sentry logs ;)

```
<script>
  // "fix" to prevent pusher error on reload
  window.Pusher = undefined;
</script>
```

**Comment by leesio** [comment]
I'm going to close this issue as it looks fairly stale.

**Comment by Khuram007** [comment]
please comment to require('./bootstrap') on the second app.js file, I have 3 files 1) admin_app.js 2) admin_search.js and app.js ,this error show on multiple instances of the root. 
![image](https://user-images.githubusercontent.com/36439994/103076895-8faed780-45f0-11eb-91ee-37676105fa6f.png)
