### ISSUE TITLE
How to use Pusher-JS within VS Code's Angular workflow?

### ISSUE THREAD

**Issue by FateTrader** [pusher/pusher-js#264]
I've got this following short piece of JavaScript code from a company that offers market data through Pusher and it works well as it is.

    <script src="https://js.pusher.com/4.2/pusher.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script>
    	var placeholder = document.getElementById('trades_placeholder'),
    		pusher = new Pusher('xxxxxxxxxxxxxxxxxxxx'),
    		tradesChannel = pusher.subscribe('live_trades');
    
    	tradesChannel.bind('trade', function (data) {
    		placeholder.innerHTML = "Price: " + data.price + "<br>Timestamp: " + data.timestamp;
    	});
    </script>

I'm trying to make it work within the Vs Code's Angular-TypeScript workflow but I'm getting these following errors:

[![enter image description here][1]][1]

I've installed pusher-js through npm.

Here's the image with all the code I've made in my Angular project files, I've marked all the relevant Pusher-JS changes in yellow:

[![enter image description here][2]][2]

it's obvious I'm missing something but I can't figure out what it is. Below I have attached both the JavaScript and Angular (only relevant not the whole project) files in the zip so you can have a look, unfortunately I couldn't provide the pushers key number but it doesn't matter as I only need to know how to properly set the project up.

**ATTACHEMENT:** [JavaScript file and Angular TypeScript files ZIP][3]

  [1]: https://i.stack.imgur.com/W082e.png
  [2]: https://i.stack.imgur.com/qQMur.png
  [3]: https://drive.google.com/file/d/1BLqSOHobU3k43sv5wfYfufEJguGp9Dc8/view?usp=sharing

**Comment by hph** [comment]
Hi, @FateTrader! It looks like the import statement is wrong:

```diff
-import { Pusher } from 'pusher-js';
+import Pusher from 'pusher-js';
```

Let me know if that doesn't solve your problem.

**Comment by FateTrader** [comment]
You were close, I've just stumbled somewhere upon this and it worked
`import * as Pusher from 'pusher-js';`

**Comment by hph** [comment]
Ah, indeed - the import syntax is different in TypeScript and ES6.

**Comment by trusktr** [comment]
```ts
import Pusher = require('pusher-js')
```
