### ISSUE TITLE
[React Native] "react_native_1.NetInfo.getConnectionInfo is not a function" causing a crash.

### ISSUE THREAD

**Issue by Soni96pl** [pusher/pusher-js#267]
**Do you want to request a *feature* or report a *bug*?**
A bug.

**What is the current behavior?**
Pusher causes the React Native app to crash during startup.
<img width="358" alt="screen shot 2018-01-15 at 2 05 42 pm" src="https://user-images.githubusercontent.com/3409889/34931337-da055ef6-fa00-11e7-92c2-8deff756c8f2.png">

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
Unfortunately not able to provide a demo at the moment. 

**What is the expected behavior?**
App initializing correctly.

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
pusher-js@4.2.2 is affected.
pusher-js@4.2.1 and pusher-js@4.1.0 are not affected by this bug.
Tested on iOS 11 iPad Mini device and iPad Air 2 simulator.

**Comment by sksahil030** [comment]
@hph Getting the same error on "import Pusher from 'pusher-js/react-native';"

**Comment by sksahil030** [comment]
Installing the version "4.2.1" worked for me

**Comment by hph** [comment]
Hi @Kuba77 & @sksahil030,

Are you using the latest version of React Native? In the last release we made some changes ([see here](https://github.com/pusher/pusher-js/pull/259)) due to the usage of deprecated modules. Let me know if updating `react-native` to `0.52` fixes your issues. I was not aware that using the recommended (i.e., not deprecated) module would be a breaking change - sorry about that.

**Comment by mstange22** [comment]
Using React Native 45.1 and getting this same error with pusher-js versions 4.1.0, 4.2.1 & 4.2.2.

**Comment by AmmarHasan** [comment]
working for me with `react-native v0.42.0` and `pusher-js v4.0.0`

**Comment by Johnsalzarulo** [comment]
I'm getting this error running `react-native v0.47.1` and  `pusher-js 4.2.2`

<img width="357" alt="screen shot 2018-07-18 at 1 37 12 pm" src="https://user-images.githubusercontent.com/3476109/42906320-b174009e-8a8f-11e8-8a67-b7af8d7282a6.png">

**Comment by congy15** [comment]
"Cannot read property 'getConnectionInfo' of undefined"
Error running react-native v0.60 - pusher-js 4.4.0.
How to fix it?

**Comment by congy15** [comment]
> @congy15 Were you able to resolve this issue? I'm facing the same and on the same versions.

I found a temporary method, here [https://github.com/pusher/pusher-js/issues/334#issuecomment-512694177](url)
Maybe pusher team will resolve this issue on next version.

**Comment by leesio** [comment]
I think the best place for this discussion is this issue: https://github.com/pusher/pusher-js/issues/334. That being said, I just created a PR to resolve this issue. #365

**Comment by tevonsb** [comment]
If anyone is still running into an issue similar to this, I found that I had not followed the pusher install instructions for react native

https://github.com/pusher/pusher-js#react-native

**Comment by leesio** [comment]
@tevonsb thanks for adding that info. Just to confirm, was the issue that you didn't have the `@react-native-community/netinfo` library installed as a dependency?

**Comment by dark-theme-programmer** [comment]
TypeError:
_netinfo.default.getconnectioninfo is not a function
How to fix this bug?

**Comment by yunau** [comment]
I have the same error.
[Unhandled promise rejection: TypeError: _netinfo.default.getConnectionInfo is not a function. (In '_netinfo.default.getConnectionInfo()', '_netinfo.default.getConnectionInfo' is undefined)]
- node_modules/@redux-offline/redux-offline/lib/defaults/detectNetwork.native.js:96:14 in _callee2$
- node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
- node_modules/regenerator-runtime/runtime.js:274:30 in invoke
- node_modules/@babel/runtime/helpers/asyncToGenerator.js:2:6 in asyncGeneratorStep
- node_modules/@babel/runtime/helpers/asyncToGenerator.js:24:6 in _next

**Comment by mehulkhoiwal** [comment]
In the new update getConnectionInfo() is replaced with fetch(), you can use fetch() instead of getConnectionInfo()...
This will definitely work.
