### ISSUE TITLE
Subscribe to channel with wildcard

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [pusher/pusher-js#269]
Is possibile to subscribe to a channel with a wildcard?
For example, if I have 1000 auction I would like to have 1000 channel and for each channel I need to subscribe to It.
It will be amazing if I can subscribe only one times to a channel with a wildcard like `auction-` so I don't need to subscribe to every channel.

Is possible?

**Comment by hph** [comment]
Hi @AlessandroMinoccheri. There's no built-in support for this in the library, but you could use `bind_all` and apply any filtering necessary within that callback.

**Comment by mdpye** [comment]
`bind_global` binds too all *event_names* on a specific channel. This might be useful to the OP, but it isn't what they were asking about.

Whether publishing all auction events to a single channel is a reasonable solution or not depends on the use case. If all events are sent to a single channel, then all clients subscribed to that channel must receive them, whether they have a handler bound for that particular event name or not.

In general, queries like this (which are not specific the the implementation of this library) are better handled by contacting support. @AlessandroMinoccheri I suggest you do that if you'd like to talk in a bit more depth about your requirements so someone can help with a subscription scheme which acheives them. You can contact here https://support.pusher.com/hc/en-us/requests/new, or via support@pusher.com

**Comment by AlessandroMinoccheri** [comment]
Thanks a lot!
