### ISSUE TITLE
Receiving Data Problem

### ISSUE THREAD

**Issue by ekartal** [pusher/pusher-js#270]
Hello there;

i have a problem when getting event data, our receiving data is missing, it is json formated data. This 
incomplete data is not coverted to json object..

Platform : android
React version : 0.53
Puser version : 4.2.2

**Comment by hph** [comment]
Hi @ekartal. I'm sorry that you're having trouble with the library. From what you've described, I think there's probably something incorrect in how you're sending or receiving the event. Could you share the relevant code where you emit the event and the relevant subscription handler?

**Comment by ekartal** [comment]
Hello @hph;

Pusher.logToConsole = true;
        var pusher = new Pusher('xxxxx', {
        cluster: 'eu',
        encrypted: true
        });

        var channel = pusher.subscribe('tickers');
        channel.bind('update', function(data) {
            //console.log(data)
        });

we are developing mobile application now, there is production on web (html5) it is working. 'tickers' is sending bitcoin market data. this code is working correctly on react native ios platform. But on react native android platform incoming data is incompleted. I have just sent a screen shot from android studio you can see json data structer

![screen shot 2018-02-17 at 12 01 57](https://user-images.githubusercontent.com/1275799/36381974-72de0cba-1598-11e8-91df-77297e5cfb1b.png)

I have tested on react native ios platform and html5 javascript, there ise no problem. incoming data is full.

I think so the problem is about json data is contain turkish letters and utf8 convert problem or wrong packet length calculate.

**Comment by leesio** [comment]
I'm going to close this issue as there hasn't been any update in a long time. If you're still experiencing a problem like this, please feel free to reopen in.
