### ISSUE TITLE
1006 Error: Noticed its being ignored in your library. Best way to handle?

### ISSUE THREAD

**Issue by ImTheDeveloper** [pusher/pusher-js#271]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
No more data is received when hitting a 1006 error.
```
Error { type: 'WebSocketError', error: 'close code 1006' }
```
**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.
Currently utilising pusher to listen to slanger1.chain.so web socket via pusher.
**What is the expected behavior?**
Unsure why hitting 1006 error, but if I do I would expect to attempt a reconnection. This however does not happen and has been specifically left out of your library as per this comment:
https://github.com/pusher/pusher-js/blob/0ef56995ed9605b79ba4b22d1a13c84652d47793/src/core/connection/protocol/protocol.ts#L95
and this line ignores:
https://github.com/pusher/pusher-js/blob/0ef56995ed9605b79ba4b22d1a13c84652d47793/src/core/connection/protocol/protocol.ts#L99

Firstly, I'm unsure why this error is being ignored and also I can't quite work out why it is being emitted in the first place. If I adjust the code on line 99 to include 1006 the connection restarts and everything works as normal.

I'm wondering if you could give a view on:
1. Why is this ignored and is there a reason why I should not be attempting a reconnect?
2. Is there a better way for me to handle the reconnection aside from editing package in node_modules directly e.g. replace 1004 with 1006 on line 99. I was wondering if I can detect this error and do a reconnect?
**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
Using this server side with node.js and latest pusher-js.

**Comment by yarcub** [comment]
Any follow-up on 1. and 2.?

**Comment by leesio** [comment]
@yarcub, @ImTheDeveloper sorry this has taken so much time for any kind of response.

Could I just clarify a couple of things about your case?

Is the issue that you're not seeing an error, or that the library isn't reconnecting as you expect it should?

**Comment by leesio** [comment]
I'm going to close this issue as it seems to have gone stale
