### ISSUE TITLE
documentation request: working example for custom authorizer

### ISSUE THREAD

**Issue by cainlevy** [pusher/pusher-js#272]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

The README mentions an `authorizer` but does not provide much detail about `options` or the expected function signature of `callback`. Even if these [had types](https://github.com/pusher/pusher-js/issues/252), developers without TypeScript would still be left wondering.

**What is the expected behavior?**

Some description of what to do with `options` and why the callback receives `false` (when would it be true?) would be nice. Maybe a short example that uses fetch would be illustrative?

**Comment by skellock** [comment]
Apologies in advance for being `+1` guy, but this really needs some love.

For future travelers of the internet, here's what I ended up doing that worked for me.  

```js
const PUSHER_KEY = 'abcdef0123abcdef0123' // your 20 hex digits api key
const PUSHER_CLUSTER = '' // e.g. 'mt1'

new Pusher(PUSHER_KEY, {
  cluster: PUSHER_CLUSTER,
  encrypted: true,
  authorizer: ({ name }) => ({
    authorize: async (socketId, callback) => {
      // acquire the token somehow (fetch, or whatever)
      // let pretend this returns a string or null
      // a channel token looks like this:  '<20 hex digits>:<64 hex digits>'
      const channelToken = await loadPusherToken(name)

      if (channelToken) {
        // tell pusher about the token with this format:
        callback(false, { auth: channelToken })
      } else {
        // tell pusher we fail... null is probably not required, i just need symmetry.  :|
        callback(true, null)
      }
    },
  }),
})
```

FWIW, this was using `pusher-js@4.2.2` and `react-native@0.53.0`.

Docs matter.  And given my track record writing 'em, I'm probably the worst person to be dishing up that advice.

**Comment by cainlevy** [comment]
@skellock That matches where I ended up as well. Here's another version:

```
new Pusher(PUSHER_KEY, {
    cluster: PUSHER_CLUSTER,
    authorizer: (channel, _options) => ({
    authorize: async (socketID, callback) => {
        try {
            const authData = await getPusherAuth(name, socketID);

            callback(false, authData);
        } catch (e) {
            callback(true);
        }
    }
})
```

This is my best understanding of the authorizer API expressed as a TypeScript interface:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/9f4c75126167d0d8af759f58405d53d983e94ad0/types/pusher-js/index.d.ts#L126-L128

**Comment by leesio** [comment]
I'm curious whether people think current authorizer in the README combined with the types I just released with 5.1.0 sufficient to describe the `authorizer` option?

I'm interested in thoughts about how we can make it easier to describe. I see that adding the async `getPusherAuth` function may help.

**Comment by seobrain** [comment]
I managed to implement it to Vue with the following approach

```
Vue.prototype.pusher = new Pusher(process.env.VUE_APP_PUSHER_KEY, {
  cluster: 'eu',
  encrypted: true,
  authorizer: ({name}) => ({ authorize: async (socketId, callback) => {
    try {
      let { data } = await Vue.axios.post(process.env.VUE_APP_BROADCAST_ENDPOINT, {socket_id: socketId, channel_name: name});
      callback(false, {auth: data.auth})
    } catch (e) { callback(true) }
  }})
});
```

Works as expectred for `pusher-js@5.1.1` and `vue@2.6.11`

**Comment by exonis** [comment]
@seobrain Your example can't work because the callback expects AuthInfo as shown here:
```
interface AuthInfo {
        auth: string;
        channel_data?: string;
    }

    type Authorizer = (channel: Channel, options: Config) => {
        authorize: (socketId: string, callback: (errored: boolean, authInfo?: AuthInfo) => void) => void;
    };
```

What works:
```
const data: AuthInfo = await yourPusherAuthService(...);
callback(false, data);
```

**Comment by leesio** [comment]
@exonis the callback function in the example @seobrain outlined *is* called with a type matching `AuthInfo`

```
callback(false, {auth: data.auth})
```

**Comment by exonis** [comment]
My bad, I didn't realize channel_data was optional. It just didn't work for me without it...

**Comment by leesio** [comment]
Oh really? That's interesting. With the latest version of pusher-js?

**Comment by leesio** [comment]
I think the example in [the readme](https://github.com/pusher/pusher-js#authorizer-function) is sufficient now. If anybody diagrees feel free to comment, and I'll reopen this ticket.
