### ISSUE TITLE
Timestamp errors

### ISSUE THREAD

**Issue by snips11** [pusher/pusher-js#275]
Are your timestamps correct? Sending from Europe/London and all my times are correct but in the debug console the connections seem to be UTC, even when I manually create an event. This is, in turn, giving me a 401 error.

**Comment by leesio** [comment]
This doesn't seem like an issue with pusher-js. For general issues with pusher please contact [support](https://support.pusher.com/hc/en-us). I'd like to restrict the issues in pusher-js to problems just concerning the pusher-js library.
