### ISSUE TITLE
Plz give an opportunity to set the proxy to avoid the blocking of your service!

### ISSUE THREAD

**Issue by drfenixion** [pusher/pusher-js#277]
**Do you want to request a *feature* or report a *bug*?**
Feature.

**What is the current behavior?**
There is no config for the proxy.

**What is the expected behavior?**
To have an opportunity set proxy for Pusher (for websockets). Because in Russia we have blocked (due to Telegram) some AWS ips (Pusher use aws).

**Which versions of Pusher, and which browsers / OS are affected by this issue?**
Pusher 4.2.2, OS Xubuntu (Ubuntu 16.04), Google Chrome 65.0.3325.181 (64 bit),

**Did this work in previous versions of Pusher? If so, which?**
No.

**Comment by drfenixion** [comment]
It will work via proxy if I fix your code.

```
	    createWebSocket: function (url) {
	        var Constructor = this.getWebSocketAPI()
                
               //added code
	        return new Constructor(url
				, [], {
				  proxy: {
				    origin:  'http://ip_of_proxy:8888',
				  }
				}
	        );
                //end of added code
	        
	        //return new Constructor(url); //was before
	    },
```
But I do not know the side effects and whether it is supported by all browsers.

**Comment by foqler** [comment]
proxy is a good idea, very much forward

**Comment by fedorkk** [comment]
We are very interested in this feature too. Maybe this PR https://github.com/6RiverSystems/pusher-js/pull/4 already included necessary functional?

**Comment by travisbell** [comment]
It seems like many (most?) ad blockers out there are blocking connections to stats.pusher.com now, so getting proxy support would be real nice. I use Eero at home and even their network level ad blocking seems to be blocking it (no whitelist, it's just on or off).

It would be real nice to have proxy support so we can avoid these problems.

**Comment by jameshfisher** [comment]
I believe [the `wsHost` and `httpHost` config options](https://github.com/pusher/pusher-js#wshost-wsport-wssport-httphost-httpport-httpsport) could be used to set a proxy? Could you describe what you would like the API for this feature to look like?

**Comment by leesio** [comment]
I'm going to close this issue, it's been inactive for a while and I'm still not totally clear how the solution proposed [here](https://github.com/pusher/pusher-js/issues/277#issuecomment-579692248) wouldn't work.

If anybody can shed any more light on this, I can reopen the issue.

**Comment by AndreSilva1993** [comment]
Hi @leesio @jameshfisher, could you elaborate how those two `wsHost` and `httpHost` would help setting up a proxy? The documentation seems to indicate something like changing the destination of the requests (like pointing to your staging servers as the documentation states) instead of "please go to the same destination but use this proxy URL instead of requesting directly".
