### ISSUE TITLE
How do i use react native app as server?

### ISSUE THREAD

**Issue by 7772** [pusher/pusher-js#279]
![image](https://user-images.githubusercontent.com/22615385/39819962-a4d25df4-53df-11e8-9496-c1723f65d164.png)

As you see, Pusher provides this features above, React Native - Client / Web - Server.
But, I want to use react native app as server, React Native - Server / Web - Client.

I have tried to use Pusher like this..

#### React Native App
```
import Pusher from 'pusher-js/react-native';

const pushser = New Pusher({ 
    // ...
});

pusher.trigger('my-channel', 'my-event', {
    "message": "hello world"
});
```

#### Web
```
    var pusher = new Pusher('MY-KEY', {
      cluster: 'ap1',
      encrypted: true
    });

    var channel = pusher.subscribe('my-channel');
    channel.bind('my-event', data => {
      alert(data.message);
    });
```

But This did not work.

Please let me know how to use react native app as server!

**Comment by leesio** [comment]
Unfortunately there is no server library for react-native. I believe that's quite an unusual use case.

The pusher-js library is a client library and supports subscribing to channels and binding to events, it supports different runtimes (web/node/react-native) etc.

The server library in your screenshot is pusher-http-node, which only runs on the node runtime.

You could trigger events to other clients using [client events](https://pusher.com/docs/client_api_guide/client_events) though.
