### ISSUE TITLE
how to disconnect pusher connection

### ISSUE THREAD

**Issue by PriyankaSinghChauhan** [pusher/pusher-js#281]
i am using pusher-js library in my react application. i am unable to disconnect pusher connection.
To disable it we are using pusher.disconnect() but still number of connection showing at pusher dashboard is same.

**Comment by Rohanhacker** [comment]
pusherInstance.disconnect()

**Comment by leesio** [comment]
`pusher.disconnect` should close the websocket connection. There may be some delay while the stats filter through to your dashboard, but the connection should be closed.

**Comment by leesio** [comment]
I'm going to close this issue, as I don't know what more I can do.

If you can provide more information, feel free to re-open
