### ISSUE TITLE
Typescript problem of importing pusher-js/react-native

### ISSUE THREAD

**Issue by ikzjfr0** [pusher/pusher-js#283]
**Do you want to request a *feature* or report a *bug*?**
It's a bug. 

**What is the current behavior?**
`import * as Pusher from "pusher-js/react-native";` coming following warning/error in Typescript:

> [ts]
Could not find a declaration file for module 'pusher-js/react-native'. '/Users/liang.wang/Documents/Project/lb-core/node_modules/pusher-js/react-native.js' implicitly has an 'any' type.
  Try `npm install @types/pusher-js` if it exists or add a new declaration (.d.ts) file containing `declare module 'pusher-js';`
[tslint] Submodule import paths from this package are disallowed; import from the root instead (no-submodule-imports)

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

- step1: create a demo from https://github.com/Microsoft/TypeScript-React-Native-Starter
- step2: install latest `npm install @types/pusher-js@latest --dev` and 'npm install pusher-js@latest`
- step3:create a .ts file and addd `import * as Pusher from "pusher-js/react-native";`
- then you can see errors:

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
I'm using the latest version:
1. RN: 0.55
2. push-js:4.2.2

**Comment by leesio** [comment]
@ikzjfr0 I'm afraid I lost track of this issue somehow. Sorry about that. I assume this issue is no longer relevant, but just in case it isn't or if anybody else is experiencing the same issue.

Are you actually installing the pusher-js library, your example shows you installing the types only.

You should also be able to import with

```
import Pusher from 'pusher-js/react-native
```
**Not**
```
import * as Pusher from 'pusher-js/react-native
```

**Comment by leesio** [comment]
I'm going to close this issue. If anybody is experiencing the same issue. Please feel free to reopen it.
