### ISSUE TITLE
Sending a client event before pusher:subscription_succeeded should fail loudly and explain how to fix it

### ISSUE THREAD

**Issue by jameshfisher** [pusher/pusher-js#288]
**What is the current behavior?** `channel.trigger(...)` returns `false` to indicate that it has failed to send the event, at least when the failure reason is that the event was triggered before the subscription had succeeded. Steps to reproduce:

```js
const channelsClient = new Pusher(...);
const channel = channelsClient.subscribe("private-foo");
console.log(channel.trigger("client-bar", {x:5}));
```

It's extremely not obvious that this is even a failure code, let alone how to fix it. It's a very common mistake, especially because our low-context code snippets encourage people to write this.

Instead, the `channel.trigger(...)` call should raise an exception, or log an error to the console, saying:

> Client event triggered before `pusher:subscription_succeeded` event. Bind to that event on the channel before triggering client events.

**Comment by leesio** [comment]
Proposed a solution to this in #324
