### ISSUE TITLE
Tree shaking unused features

### ISSUE THREAD

**Issue by marksamman** [pusher/pusher-js#298]
Would it be possible to organize this package so that the E2E-encryption implementation isn't bundled by tree-shaking capable bundlers if it's not used? My projects are not using end-to-end encrypted channels and upgrading from 4.2.2 to 4.3.0 resulted in my JS bundles increasing by 60KB post-minification (UglifyJS). It is significant enough that I will pin my projects to 4.2.2 for now.

**Comment by leesio** [comment]
Hi @marksamman, thanks for bringing this up. This is something we're considering at the moment.

I think we'd have to update the build process to enable tree shaking, but we're not happy with the increase int he bundle size either.

**Comment by joker-777** [comment]
That would be great! I think the pusher package

![screenshot_20190118_122754](https://user-images.githubusercontent.com/378859/51402814-912a1800-1b1c-11e9-83ad-ca0445c8b165.jpeg)
 is too big.

**Comment by stof** [comment]
As the E2E encryption is based on the prefix of the channel name, I don't see any way to tree-shake it though

**Comment by stof** [comment]
Idea to allow tree-shaking in a new major version of the library (as that involves BC breaks): expose an API like `pusher.subscribe(new Pusher.Channel(name))`, exposing `Channel`, `PrivateChannel`, `PresenceChannel` and `EncryptedChannel` as exports.
Then, if a module build is provided, this would allow tree-shaking to happen (webpack is much better at tree-shaking ESM builds than CJS ones).

**Comment by leesio** [comment]
As @stof says, it's unlikely we can solve the bundle size increase with tree shaking. We're planning on splitting the end to end encryption functionality into a separate helper library at some stage.

I created an issue to track that #403

In the meantime, I'm going to close this issue.
