### ISSUE TITLE
Presence member not removed when locking phone

### ISSUE THREAD

**Issue by Fyb3roptik** [pusher/pusher-js#299]
We are using a mobile web version of our site to handle some pusher stuff for arcade games. I can authenticate a user just fine, but when the user locks their phone, I do not get a member_removed event and the user is not getting any of the public channel events.

For Angular it goes from Active to Hidden. Hidden should trigger member remove right? Is there something I am missing here?

**Comment by Fyb3roptik** [comment]
Ok so apparently I have to disconnect pusher completely and re-initialize pusher when they become active. Is there not a simpler way to do this without killing pusher??

**Comment by rmiller-sgntr** [comment]
Member also isn't removed on internet connection loss. Thought I'd try here before opening a separate issue.

**Comment by Fyb3roptik** [comment]
So to update this ticket a bit. I am using the presence channel mixed with a webhook to my api. 
```
Member joins -> Webhook calls my API -> Add them to session in API
```

```
Member disconnects -> Webhook calls API -> session is ended
```

**Comment by rmiller-sgntr** [comment]
Does this actually happen for you?
`Member disconnects -> Webhook calls API `

**Comment by Fyb3roptik** [comment]
Yes, but you have to use the presence channel, not public

**Comment by leesio** [comment]
@Fyb3roptik could you not `unsubscribe` from the presence channel? When the application is backgrounded or the phone is locked? Then `subscribe` again when it becomes active?

```
pusher.unsubscribe(PRESENCE_CHANNEL_NAME);
```

**Comment by Fyb3roptik** [comment]
You dont need to do that as it does that automatically. When you lock your phone it will trigger presence removed and when you turn it back on it will trigger presence joined

**Comment by Fyb3roptik** [comment]
I setup a webhook to call my API endpoint on removal and join and handle sessions that way

**Comment by leesio** [comment]
@Fyb3roptik oh sorry! I think I misunderstood the issue you're having.

> I do not get a member_removed event and the user is not getting any of the public channel events.

Where do you not get a `member_removed` event?

**Comment by Fyb3roptik** [comment]
Disregard it is working now. Sorry for the confusion! Closing the ticket

**Comment by leesio** [comment]
Ahh perfect. Glad it was resolved. Sorry for my tardy response.
