### ISSUE TITLE
Subscribe to disconnect event

### ISSUE THREAD

**Issue by ewal** [pusher/pusher-js#302]
**Do you want to request a *feature* or report a *bug*?**
Bug, maybe? :)

**What is the current behavior?**
Can't subscribe to the socket disconnect event.

**What is the expected behavior?**
I have events bound to all socket states (connecting, connected etc.) but also want to handle `disconnected` in the same manner to trigger a side effect.

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
Pusher version 4.3.0 with react-native.

Cheers!

**Comment by lmenus** [comment]
Hey @ewal , would this work for you?

```js
const socket = new Pusher(config);
const disconnect = socket.disconnect.bind(socket);
socket.disconnect = () => {
  // your custom hook 🎉
  return disconnect();
};
```

**Comment by leesio** [comment]
You can also just bind directly to the event on `socket.connection`, since the `Connection` class extends `Dispatcher`.

```
const socket = new Pusher(config);
socket.connection.bind('disconnected', () => {
  //
})
```

**Comment by ewal** [comment]
I'd forgotten about this issue. Found my own solution but thanks for your help, @lmenus and @leesio.

**Comment by lmenus** [comment]
No problem @ewal! What was your solution?

**Comment by ewal** [comment]
It's very app specific so I don't think it would help anyone if I'd tell :)
