### ISSUE TITLE
Missing events from Reddit feed

### ISSUE THREAD

**Issue by richardpeng** [pusher/pusher-js#303]
I have the following code and I only ever receive events from the `AskReddit` subreddit and not the `politics` subreddit. I'm not sure why this isn't working.

```
import Pusher from 'pusher-js';

const pusher = new Pusher('50ed18dd967b455393ed');

const channels = ['AskReddit', 'politics'];

const scan = (listing) => {
  console.log(JSON.stringify(listing));
};

Pusher.log = function (message) {
  console.log(message);
};

channels.forEach(channel => pusher.subscribe(channel.toLowerCase()));
pusher.bind('new-listing', scan);
```

I'm running Pusher v4.3.1.

**Comment by richardpeng** [comment]
Update: I watched the `politics` sub using the [demo app](http://realtime-reddit-demo.herokuapp.com/) and the demo app also doesn't show any items when someone posts.

**Comment by richardpeng** [comment]
For future reference, I emailed support and this was their response:

> The backend code for this service is available [here](https://github.com/pusher-community/pusher-realtime-reddit). It's quite an old project. The service regularly polls the new.json endpoint on reddit, limiting the responses to 50 entries, and then sends the new listings to all subscribed clients via Pusher. It may be that certain subreddits aren't included in this feed (this might have changed since this demo was created), or messages might be being missed because the response is limited to 50 listings per poll. In time we may try to update the service but if you need it for your own project then you could replicate the service yourself. You would need to create a Pusher account to send the realtime messages, and set up a backend to poll the reddit service for new listings and send them down your Pusher channels.

> We won't be updating the Reddit demo any time soon, unfortunately. It was intended to be a demo. I would recommend polling it yourself as you say.

You can feel free to close this ticket.

**Comment by leesio** [comment]
Thanks for getting back to me @richardpeng

**Comment by ServiceSector** [comment]
Hi richardpeng, were you able to resolve this?

**Comment by richardpeng** [comment]
@ServiceSector  I ended up building an integration with the Reddit API directly without Pusher by polling a multireddit of the subs I wanted to follow for new posts.
