### ISSUE TITLE
It seems like bind_global callbacks don't apply to events from presence channels & Pusher.bind('pusher:subscription_error',...) can't be used

### ISSUE THREAD

**Issue by guillaume-miara** [pusher/pusher-js#304]
**Question**

First of all, we use Pusher extensively and love the product. Thanks a lot for your work!

**What is the current behavior?**
We suspect some strange-unexpected unsubscription/resubscription to our private and presence channels. It is something we'd like to verify. Our limitations is that we cannot use the debugger and enable logging to console as mentioned here: https://pusher.com/docs/debugging

So we are instead building a debugging view. 

Our client is connected to 1 private channel and 3 presence channels
With 
```
        pusherManager._client.bind_global(event =>
            window._pusherDebug.events.push({ event, timestamp: Date.now() }));
```
I see that we are appending the events pushed to the private channels. But not the internal events:
`pusher_internal:subscription_succeeded`

Fair enough, these are internals. 

So instead, we would be hoping to bind the subscription event to the pusher client 
```
        pusherManager._client.bind('pusher:subscription_succeeded', () =>
            window._pusherDebug.presenceEvents.push({ 'event': 'success', timestamp: Date.now() }));
        pusherManager._client.bind('pusher:subscription_error', () =>
            window._pusherDebug.presenceEvents.push({ 'event': 'error', timestamp: Date.now() }));
```
But that doesn't do it either. 

The binding only works on the channels, not on the client themselves. 

**If the current behavior is a bug, please provide the steps to reproduce and
- Create a private and a presence channels
- bind_global any function on the pusher client
- emit an event to the private channel
- emit an event to the presence channel
- bind the subscription events to the pusher client
- emit an event to the presence channel
- bind the subscription events to the presence channel
- emit an event to the presence channel

**What is the expected behavior?**
Not quite sure. We thought that the presence subscriptions events would be also ran through the callback of `bind_global`. But also, we thought we could make bindings at the client levels as this lets you think: `You can also bind to events regardless of the channel the event is broadcast to. By using the pusher.bind() method rather than channel.bind(), you can listen for an event on all the channels that you are currently subscribed to.` (from https://pusher.com/docs/client_api_guide/client_events#bind-events)

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
Chrome , Pusher JavaScript Library v4.2.2

**Comment by leesio** [comment]
@guillaume-miara I had a quick look at this and can confirm the behaviour you're experiencing:

`pusher_internal:subscription_succeeded` events are received by the `client` and "routed" to the `channel`. The `channel` then emits a `pusher:subscription_succeeded` event.

If you really wanted to `bind` to **all** messages, you could bind to the `message` event on the `connection`:

```
pusher.connection.bind('message', (msg) => {

})
```

You will receive *everything* though including internal messages, `pings`/`pongs` etc. This is *not* a public API though, so I can't guarantee it won't change in the future, but it might be useful for debugging.

**Comment by leesio** [comment]
@guillaume-miara did you have any luck with this?

I'm going to close this issue as the behaviour you're seeing is the desired behaviour.
