### ISSUE TITLE
README does not mention "client events" or "trigger"

### ISSUE THREAD

**Issue by jameshfisher** [pusher/pusher-js#305]
See https://pusher.com/docs/client_api_guide/client_events#trigger-events - this should be documented here

**Comment by jameshfisher** [comment]
Doesn't affect me nowadays but it's affecting you! 😉

**Comment by leesio** [comment]
I think we should let the docs do the heavy lifting, but agree it's good to mention it along with some common issues people run into. Added this in #515

**Comment by leesio** [comment]
Fixed in #515

**Comment by jameshfisher** [comment]
🎉
