### ISSUE TITLE
TypeError: Cannot set property 'key' of undefined

### ISSUE THREAD

**Issue by ARMATAV** [pusher/pusher-js#307]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
pusher is blocked when instantiating a new client

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.

1. install pusher

2. add this code

> import React, {
>     Component
> } from 'react'
> import { setPusherClient } from 'react-pusher'
> import Pusher from 'pusher-js'
> 
> const pusherClient = new Pusher(/* key */)
> 
> setPusherClient(pusherClient)
> 
> class App extends Component {
>     state = {
>         listOfArticles: [
>             { title: "Why memes are good" },
>             { title: "Why memes are good" },
>             { title: "Why memes are good" },
>             { title: "Why memes are good" },
>             { title: "Why memes are good" },
>             { title: "Why memes are good" },
>             { title: "Why memes are good" },
>             { title: "Why memes are good" },
>             { title: "Why memes are good" },
>             { title: "Why memes are good" },
>             { title: "Why memes are good" },
>             { title: "Why memes are good" },
>             { title: "Why memes are good" },
>         ]
>     }
> 
>     componentDidMount() {
> 
>     }
> 
>     render() {
>         const { listOfArticles } = this.state
> 
>         return (
>             <div>
>                 <h1>NDN</h1>
>                 <hr />
>                 {
>                     listOfArticles.map(article => {
>                         return <h3>{article.title}</h3>
>                     })
>                 }
>                 <Pusher
>                     channel="my-channel"
>                     event="my-event"
>                     onUpdate={data => console.log(data)}
>                 />
>             </div>
>         )
>     }
> }
> 
> 
> 
> export default App

3. run

4. `TypeError: Cannot set property 'key' of undefined`

5. open chrome network tab, refresh - session status is blocked

**What is the expected behavior?**

it works out of the box

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
 n/a

**Comment by ARMATAV** [comment]
Yikes

**Comment by dooburt** [comment]
Was there a solution found/commit for this?
