### ISSUE TITLE
Pusher subscribes to unsubscribed channels after a re-connect

### ISSUE THREAD

**Issue by katranci** [pusher/pusher-js#308]
**pusher-js: 4.3.0**

If I unsubscribe from a channel with [Channel#unsubscribe](https://github.com/pusher/pusher-js/blob/807b778463851f3a9b02114abf06f00f65e94d8f/spec/javascripts/unit/core/channels/channel_spec.js#L232) then Pusher automatically subscribes to the channel after a re-connect. Here are the events I see in DevTools console:

```
Pusher : Event sent : {"event":"pusher:unsubscribe","data":{"channel":"private-message"}}

Pusher : State changed : connected -> connecting

Pusher : State changed : connecting -> connected with new socket ID 245176.13182560

Pusher : Event sent : {"event":"pusher:subscribe","data":{"auth":"...","channel":"private-message"}}
```

**Comment by leesio** [comment]
Closing this issue as I believe it to be resolved.

**Comment by marcaaron** [comment]
Curious, what might be the use-case for having `channel.unsubscribe`? It seems very easy to make this mistake.
