### ISSUE TITLE
net::ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by lionleo1374** [pusher/pusher-js#311]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.

**What is the expected behavior?**

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**

**Comment by leesio** [comment]
I'm closing this issue as it doesn't seem to have any content!
