### ISSUE TITLE
authEndpoint is not being called

### ISSUE THREAD

**Issue by JoKeRxbLaCk** [pusher/pusher-js#313]
Hi guys, 
I'm developing a mobile app with React Native and SailsJS (node MVC framework) as backend.
I'm trying to subscribe clients to a private-channel (/presence-channel) like this in React Native:

    constructor(props) {
        super(props);
        this.pusher = new Pusher('my_key', { authEndpoint: 'http://localhost:1337/api/v1/pusher/auth' });
        console.log(this.pusher);
        this.chatChannel = this.pusher.subscribe('presence-chat_channel');
        console.log(this.chatChannel);
    });

The first console log shows this in the config section:

`activity_timeout:120000`
`authEndpoint:"http://localhost:1337/api/v1/pusher/auth"`
`authTransport:"jsonp"`
`httpHost:"sockjs.pusher.com"`
`httpPath:"/pusher"`
`httpPort:80`
`httpsPort:443`
`pong_timeout:30000`
`statsHost:"stats.pusher.com"`
`unavailable_timeout:10000`
`wsHost:"ws.pusherapp.com"`
`wsPath:""`
`wsPort:80`
`wssPort:443``

The second one this:

    PresenceChannel {callbacks: CallbackRegistry, global_callbacks: Array(0), failThrough: ƒ, name: "presence-chat_channel", pusher: Pusher, …}

So the channel has been created but with no members inside ...

If I look at the node server, I see that the endpoint has never been called ... This is an extract of the enpoint:

    const socketId = this.req.body.socket_id;
    const channel = this.req.body.channel_name;
    const presenceData = {user_id: this.req.me.id,user_info: {name: this.req.me.fullName, } }
    const auth = sails.config.globals.pusher.authenticate(socketId, channel, presenceData);
    console.log(auth);
    return this.res.send(auth);`

This API is working through Postman but not with the real lifecycle on react native...

So I think the problem is that the authEndpoint is never being called, do you know what I'm doing wrong?
Thank you,

**Comment by leesio** [comment]
Are you seeing any errors when you enable `logToConsole` as [here](https://github.com/pusher/pusher-js#pusherlogtoconsole-boolean)

**Comment by leesio** [comment]
@JoKeRxbLaCk are you still experiencing this issue? I'm inclined to close this issue as it seems to be stale.
