### ISSUE TITLE
React-Native iOS auto reconnection always resolves to "unavailable" state 

### ISSUE THREAD

**Issue by ravirajn22** [pusher/pusher-js#317]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behaviour?**

Change pusher state from  `connected`  -> `unavailable` by turning off the wifi. Then,

**iOS**
Turn on the wifi, pusher-js will try to auto-reconnect, the state will change from `unavailable` -> `connecting` -> `unavailable`. The pusher connection always resolves to `unavailable`.

**Android**
Turn on the wifi, the status will change from `unavailable` -> `connecting` -> `connected`. Which is as expected.

**What is the expected behaviour?**

Like Android, iOS must also get `connected` status when auto-reconnecting.

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**

Just now started using pusher, so don't know about previous versions.

Affects only iOS.

react-native: 0.57.4
react: 16.6.0-alpha.8af6728
pusher-js: 4.3.1

**Comment by zek** [comment]
I got the same problem.

**Comment by leesio** [comment]
Are you both still experiencing this issue? I just tested with the latest version of pusher-js and react-native and I wasn't ablt to recreate it.

**Comment by ravirajn22** [comment]
I will test again and post it in the edit.

**Comment by zek** [comment]
@leesio client successfully connects to server on first open then I disconnect from wifi and reconnect but then it never reconnects again. If I close the app then reopen everything is fine. I do have the same problem on production. So this is not happening only on emulator also real phones having problem.

+ If I activate/deactive developer console, it works again. But disconnecting via closing wifi, just causes problem again.

**Comment by zek** [comment]
~~~

Pusher : Connecting : {"transport":"wss","url":"wss://localhost.test:6001/app/EUgNdRG3rGFE46jJqW7BQwdK?protocol=7&client=js&version=5.0.1&flash=false"}
RCTLog.js:47 SocketRocket: In debug mode.  Allowing connection to any root cert
pusher.js:8 Pusher : State changed : connecting -> unavailable
pusher.js:8 Pusher : State changed : unavailable -> disconnected
pusher.js:8 Pusher : State changed : initialized -> connecting
pusher.js:8 Pusher : Connecting : {"transport":"ws","url":"ws://localhost.test:6001/app/EUgNdRG3rGFE46jJqW7BQwdK?protocol=7&client=js&version=5.0.1&flash=false"}
pusher.js:8 Pusher : Connecting : {"transport":"wss","url":"wss://localhost.test:6001/app/EUgNdRG3rGFE46jJqW7BQwdK?protocol=7&client=js&version=5.0.1&flash=false"}
RCTLog.js:47 SocketRocket: In debug mode.  Allowing connection to any root cert
pusher.js:8 Pusher : State changed : connecting -> unavailable
pusher.js:8 Pusher : State changed : unavailable -> disconnected
pusher.js:8 Pusher : State changed : initialized -> connecting
pusher.js:8 Pusher : Connecting : {"transport":"ws","url":"ws://localhost.test:6001/app/EUgNdRG3rGFE46jJqW7BQwdK?protocol=7&client=js&version=5.0.1&flash=false"}
pusher.js:8 Pusher : Connecting : {"transport":"wss","url":"wss://localhost.test:6001/app/EUgNdRG3rGFE46jJqW7BQwdK?protocol=7&client=js&version=5.0.1&flash=false"}

~~~

This is what I see on console. BTW I use local pusher server.

**Comment by ghasemikasra39** [comment]
I have the same issue
