### ISSUE TITLE
How to change member info from the client directly?

### ISSUE THREAD

**Issue by lanlin** [pusher/pusher-js#318]
The user object in Pusher presence channels is initiated from the auth callback.
 
This object is persisted and contains user info.

But how can I update this user info and have it keep that persistent state?

I want to update user info directly from the client, so that other members can see it.

I have many states that need to save, like typing status, or online status: 'busy, available, offline, leaving...' and some other data.

**Comment by leesio** [comment]
The data you provide as part of the auth process can't really be changed until the next auth request. The advantage of this approach is that the data received here is 'verified' by the auth endpoint, and can be trusted by the clients.

If you'd like to share data that changes frequently or data that doesn't need to be 'verified' by the server, I'd recommend sending it directly between clients in the data payload.

**Comment by lanlin** [comment]
though it's not I want, but thanks anyway
