### ISSUE TITLE
Web workers doesn’t allow the support of any version of Internet Explorer

### ISSUE THREAD

**Issue by damdo** [pusher/pusher-js#321]
**What is the current behavior?**
The current implementation of *web workers* doesn’t allow us to support any version of Internet Explorer.
It appears that the `Headers` interface, used here: https://github.com/pusher/pusher-js/blob/807b778463851f3a9b02114abf06f00f65e94d8f/src/runtimes/worker/auth/fetch_auth.ts#L6
is not supported by IE as can be seen here: https://developer.mozilla.org/en-US/docs/Web/API/Headers#Browser_compatibility even though there is basic support for Web Workers in IE: https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API#Browser_compatibility

**Comment by pbcraig** [comment]
:+1:

**Comment by stof** [comment]
that's because the fetch API is not supported at all in IE: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API#Browser_compatibility

You probably need to load the fetch polyfill in your worker

**Comment by ben-pusher** [comment]
The same is true for iOS Safari - https://developer.mozilla.org/en-US/docs/Web/API/Headers#Browser_compatibility shows the same incompatibility as IE.
