### ISSUE TITLE
A newer webpack version should be used to build the dist files

### ISSUE THREAD

**Issue by stof** [pusher/pusher-js#327]
Currently, the build pipeline is based on webpack 1.

Webpack 4 made a lot of optimization compared to webpack 1 regarding the build (concatenating internal modules reduces the size a lot for instance). Migrating to it might help improving the size of the library.

**Comment by stof** [comment]
another alternative is to use rollup too.

**Comment by leesio** [comment]
Hi @stof this is definitely something we want to do.

Ideally we'd like to invest some time into modernising everything in the build pipeline.

**Comment by benjamincombes** [comment]
Would love that, today Pusher package is really big, I need it but it is about 15% of my app size...

**Comment by troch** [comment]
I was looking at that: there was a significant bump in size from v4.2.2 and 4.3.0: https://bundlephobia.com/result?p=pusher-js@4.4.0

**Comment by leesio** [comment]
@troch that's right. The increase in size was, I believe, a result of adding end to end encryption functionality into the library. There's more discussion about this here: https://github.com/pusher/pusher-js/issues/298

**Comment by benjamincombes** [comment]
I just reverted to version 4.2.2, and my app went 9% smaller... I really hope something can be done for that, this is really a major problem and we unfortunately began considering alternatives to Pusher because of this, as size really matters for our app.

**Comment by leesio** [comment]
It may be of interest to people in this issue that I started work on moving to Webpack 4. The PR can be found here

https://github.com/pusher/pusher-js/pull/344

**Comment by stof** [comment]
@leesio the changes done in #352 are enabling webpack optimizations only for the minified files. But the package.json points to the unminified dist files, so anyone using a module bundler (webpack, rollup, etc...) will end up using the unoptimized build.
If you want to produce a dist file which does not get minified, you should still turn on other webpack optimization (the module concatenation being one which will have a big impact when minifying a full build containing pusher-js).

**Comment by leesio** [comment]
@stof nice catch. I guess the best thing to do is make the normal build use webpack's production mode but with minification disabled.

**Comment by leesio** [comment]
@stof #361

**Comment by stof** [comment]
Closing this, as things seem to be done now.
