### ISSUE TITLE
Uncaught You must pass your app key when you instantiate Pusher.

### ISSUE THREAD

**Issue by princedacy** [pusher/pusher-js#330]
I keep getting this error in my browser's console. even though i've well configured Pusher in my Angular project

Here's my code in the Angular project

`this.pusherClient = new Pusher("f3224ccead46a2736119", {
      cluster: "ap2",
      forceTLS: true
    });
    let channel = this.pusherClient.subscribe('purchases');
    channel.bind('App\\Events\\PurchaseMade', function (data) {
      console.log(data);
    });`

**Comment by richard457** [comment]
I am facing the same issue when using the library in angular too, any fix please?

**Comment by leesio** [comment]
Hmm, this is very strange. Could you confirm how you're using the library in angular, @richard457, @princedacy

**Comment by leesio** [comment]
I'm going to close this issue, as there's very little to go on. If this is still a problem and you're able to supply more information, please feel free to re-open

**Comment by jpruiz114** [comment]
How was this solved?
