### ISSUE TITLE
NetInfo has been extracted from core in react-native 0.59

### ISSUE THREAD

**Issue by oblador** [pusher/pusher-js#334]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When using pusher in React Native 0.59 throws this warning: 
```
Warning: NetInfo has been extracted from react-native core and will be removed in a future release. It can now be installed and imported from '@react-native-community/netinfo' instead of 'react-native'. See https://github.com/react-native-community/react-native-netinfo
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
Install pusher in a fresh react native project. 

**What is the expected behavior?**
No warning.

**Which versions of Pusher, and which browsers / OS are affected by this issue?**
Latest

**Comment by harikrishnanp** [comment]
Install package `@react-native-community/netinfo` to suppress the warning. 

`yarn add @react-native-community/netinfo`
`react-native link @react-native-community/netinfo`
`react-native run-android` or `react-native run-ios`

Change
`import { NetInfo } from "react-native";`

to:

`import NetInfo from "@react-native-community/netinfo";`

**Comment by oblador** [comment]
@harikrishnanp That migration must be applied to this package and not just your own project. That would in itself be a breaking change and introduce a new hard dependency that needs to be managed consciously. 

Actually, just applying your change will make things worse since the new community package share event name, but not event data schema, resulting in double events and a crash. So safest thing to do in projects that is using pusher _right now_, is to ignore the warning and not migrate.

**Comment by leesio** [comment]
Hi @oblador,

I was able to replicate the behaviour you describe (i.e. the deprecation warning). I'm not 100% sure of the best way to resolve it at the moment.

I don't see any sensible way to bundle the `@react-native-community/netinfo` package with pusher-js since it contains native code. Perhaps I'm mistaken about this.

The current behaviour of the library is to assume that the `react-native` package is available as a global and import `NetInfo` from it. We could do the same for the `@react-native-community/netinfo` package but having these kind of implicit environmental dependencies is very error prone IMO.

Might I ask, how do you import pusher-js into your react-native project?

**Comment by jefflewis** [comment]
One way around this would be to add an option for passing in NetInfo library as part of the pusher config. 

I import Pusher as follows:

```ts
import Pusher from "pusher-js/react-native";
import PusherLink from "graphql-ruby-client/subscriptions/PusherLink";
...
const pusher = new Pusher(Config.pusherApiKey, {
  cluster: "us2",
  forceTLS: true
});
const pusherLink = new PusherLink({ pusher });
```

I'd be fine if I could instantiate pusher with:

```
import NetInfo from "@react-native-community/netinfo";

const pusher = new Pusher(Config.pusherApiKey, {
  cluster: "us2",
  forceTLS: true
  NetInfo
});

```

**Comment by oblador** [comment]
@leesio Any updates?

**Comment by leesio** [comment]
Hey @oblador,

Thanks a lot for your patience on this one. I've spent a bit of time looking into this.

First some good news: although there is a new API, it seems like the old API will be supported for a while, so I think we can swap this out without changing much code.

From the [react-native-netinfo README](https://github.com/react-native-community/react-native-netinfo)

>Note that the API was updated after it was extracted from NetInfo to support some new features, however, the previous API is still available and works with no updates to your code.

We still, ofcourse need to update the dependency. As far as I can tell, the only way we can reasonably do this is by:

- making @react-native-community a 'peer dependency' of pusher-js (it's not clear to me yet whether it's better to do this 'officially' in package.json, or just state it in the documentation of pusher-js)
- updating the build of pusher-js to assume that @react-native-comminity/netinfo is available as an external

I've tested this in an example build, but I'd be really interested to see whether it solves the problem in your app. Do you think it would be viable to try and build your application with a non-master build of pusher-js, just to test?

**Comment by oblador** [comment]
Yeah, I think they made it backwards compatible last week with v3 which is good news. If you decide to make it a peer dependency, just have in mind that this will apply for web installs too. 

I'd happily test a custom build!

**Comment by leesio** [comment]
> just have in mind that this will apply for web installs too

Yeah, this is a downside. I don't think it would affect application bundles, since the dependency will never be referenced by the web `Runtime` but it's still sub-optimal.

> I'd happily test a custom build!

Great! Perhaps we could organise this on Tuesday (Monday is a national holiday in London)?

**Comment by oblador** [comment]
It's fine as long as your package manager doesn't install peer dependencies (which neither latest yarn nor npm does afaik), but otherwise you might get `react-native` and its dependencies too which is kinda heavy. Regardless users will get warnings about missing peer dependency although it might be totally valid not to have it. I mainly meant that you should consider breaking out the react-native lib to a separate package. 

Tuesday works for me!

**Comment by leesio** [comment]
@oblador could you try the following?
Install `@react-native-community/netinfo` and link it

```
npm install @react-native-community/netinfo
react-native-link @react-native-community/netinfo
```

Install pusher-js from the [`net-info-test-build` branch](https://github.com/pusher/pusher-js/pull/348)

```
npm install git://github.com/pusher/pusher-js#netinfo-test-build
```

**Comment by oblador** [comment]
@leesio Forgot about this, but tried it out now and it works in our app! 👍

**Comment by leesio** [comment]
That's great @oblador. I'm going to be working on pusher-js for the next few days, so I should be able to get this released

**Comment by it-crafter** [comment]
> @react-native-community/netinfo

please where can i change the import ???

**Comment by AndrewJack** [comment]
Hi 👋 @leesio, when can we expect this to be fixed? What's the timeline for RN 0.60 support?

**Comment by congy15** [comment]
> > @react-native-community/netinfo
> 
> please where can i change the import ???

Are you did it? I have same problem with RN v0.60 about "react_native_1.NetInfo.getConnectionInfo()"

**Comment by dihan** [comment]
I'm getting this error and not using Netinfo...

**Comment by leesio** [comment]
@AndrewJack I'm hoping to resolve this in the next couple of days. We have a couple of options to consider and I'd like to choose the best one.


@dihan This is because pusher-js assumes that the react-native library in the project contains NetInfo as an export. It looks like this was removed as of 0.60.

**Comment by usrbowe** [comment]
###  ℹ️ For those, who want temporary fix

1. Install `patch-package` & `@react-native-community/netinfo`
2. Update `pusher-js` file
```js
// FILE: node_modules/pusher-js/dist/react-native/pusher.js
// add this bellow line: var react_native_1 = __webpack_require__(27);
var _netInfo = require('@react-native-community/netinfo');
// find&replace: "react_native_1.NetInfo" with "_netInfo"
```
3. This works as quick temporary hotfix, without forking this package.

**Comment by congy15** [comment]
> ### ℹ️ For those, who want temporary fix
> 1. Install `patch-package` & `@react-native-community/netinfo`
> 2. Update `pusher-js` file
> 
> ```js
> // FILE: node_modules/pusher-js/dist/react-native/pusher.js
> // add this bellow line: var react_native_1 = __webpack_require__(27);
> var _netInfo = require('@react-native-community/netinfo');
> // find&replace: "react_native_1.NetInfo" with "_netInfo"
> ```
> 
> 1. This works as quick temporary hotfix, without forking this package.

yes, I had try this and working ^^ but after install new package and RN auto linking, I need do it again

**Comment by usrbowe** [comment]
> > ### ℹ️ For those, who want temporary fix
> > 
> > 1. Install `patch-package` & `@react-native-community/netinfo`
> > 2. Update `pusher-js` file
> > 
> > ```js
> > // FILE: node_modules/pusher-js/dist/react-native/pusher.js
> > // add this bellow line: var react_native_1 = __webpack_require__(27);
> > var _netInfo = require('@react-native-community/netinfo');
> > // find&replace: "react_native_1.NetInfo" with "_netInfo"
> > ```
> > 
> > 
> > 
> > 1. This works as quick temporary hotfix, without forking this package.
> 
> yes, I had try this and working ^^ but after install new package and RN auto linking, I need do it again

I have added: `patch-package` in my `postinstall`

example:
```json
//package.json
"scripts": {
  "postinstall": "patch-package"
}
```

**Comment by leesio** [comment]
I created [this pr](https://github.com/pusher/pusher-js/pull/365) with a fix for this. I'm hoping to merge today and release a new version (v5.0.0) of the library.

**Comment by leesio** [comment]
I just merged the v5.0.0 release and pushed a new release to npm.

**Comment by BenQoder** [comment]
Currently Facing This Issue On React Native Expo

**Comment by leesio** [comment]
@BenQoder there is some discussion about this issue with expo in #371 
I'm going to close this issue now, since I believe the core issue (netinfo being removed from react-native core) has been resolved

**Comment by Dhrupal** [comment]
Where is pusher.js file?
