### ISSUE TITLE
Subscribe to multiple channels in one connection (Multiplexing)

### ISSUE THREAD

**Issue by markogrbic95** [pusher/pusher-js#336]
**Do you want to request a *feature* or report a *bug*?**
Request a feature

**What is the current behavior?**
There isn't a way to subscribe to multiple channels in one connection and get data from different channels through it

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
Not a bug

**What is the expected behavior?**
Passing an array of channels on which I wish to subscribe to and subscribing to all of those channels in a single connection. Example:
`var channel = pusher.subscribe(['first-channel', 'second-channel', 'third-channel']);`

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
/

**Comment by leesio** [comment]
I'm not convinced this API is necessary, and I think it adds lots of potential for confusion (i.e. receiving subscription errors from some of the channels etc

Is there a reason you can't keep track of multiple channels like this?

```
let channels = ['first-channel', 'second-channel', 'third-channel'].map(pusher.subscribe);
```

Then if you want to bind the same callback to many channels

```
for channel of channels {
  channel.bind('name', callback)
}
```

**Comment by jameshfisher** [comment]
Hey @markogrbic95 - I just wanted to clarify your multiplexing question:

> There isn't a way to subscribe to multiple channels in one connection and get data from different channels through it

Your `pusher` object corresponds to one connection, and you can subscribe to as many channels as you like using that single connection, using `pusher.subscribe`. That is, we already multiplex many subscriptions over a single connection.

@leesio's suggested way to map `pusher.subscribe` over your channels is good. But whichever way you do it, it will go over the same connection. You should see this in your connection count in your dashboard.

**Comment by markogrbic95** [comment]
Oh I see, thanks for the clarification. It's all clear now.
I'll just have to create a wrapper around pusher so my clients can ask from multiple channels in an array, and then subscribe to multiple channels using `pusher.subscribe` under the hood.
