### ISSUE TITLE
Dependencies are wrong in the package.json

### ISSUE THREAD

**Issue by stof** [pusher/pusher-js#341]
The package.json declares runtime dependencies on `faye-websocket`, `tweetnacl`, `tweetnacl-util` and `xmlhttprequest`. But these dependencies are wrong. They are not runtime dependencies but build-time dependencies, as webpack bundles them with your source code.

**Comment by leesio** [comment]
@stof I think you're right. I'm planning on making some changes to the build process today, so I'll try to address that.

**Comment by leesio** [comment]
I update this in https://github.com/pusher/pusher-js/pull/352/commits/5c43ea3eccb4ef494ef9b03686e0bbc3674bfcf1

Hopefully it will be merged and released soon

**Comment by leesio** [comment]
This should be resolved in v5.0.0. @stof are you happy for me to close this ticket?
