### ISSUE TITLE
Uncaught TypeError: Cannot read property 'apply' of undefined...... Laravel/pusher laravel echo

### ISSUE THREAD

**Issue by moesyzlack8** [pusher/pusher-js#342]
I am building a private chat app with laravel 7 pusher and laravel echo... i have it connecting to pusher and showing when a new sesison is created.. also what message has been sent.. but when i type in the chat box and send i recieve this error. in the console

/*Error
==========================*/
app.js:39163 Uncaught TypeError: Cannot read property 'apply' of undefined
    at PrivateChannel.Dispatcher.emit (app.js:39163)
    at PrivateChannel.Channel.handleEvent (app.js:40826)
    at app.js:37694
    at ConnectionManager.Dispatcher.emit (app.js:39163)
    at message (app.js:45768)
    at Connection.Dispatcher.emit (app.js:39163)
    at message (app.js:40556)
    at TransportConnection.Dispatcher.emit (app.js:39163)
    at TransportConnection.onMessage (app.js:39060)
    at WebSocket.socket.onmessage (app.js:39077)

I have tried creating a new app in pusher with php backend framework because i read somewhere that works also explicitly put the cluster id into the script. with no joy whats so ever i am baffled as i am following a tutorial and the code is to the letter.

I do not know what is causing this error.

Please help i have been pulling my hair out for the last few days now

**Comment by moesyzlack8** [comment]
was a few things before i got to the best of it............

if your brain says be hopeful thenkeep doing that!!

//NEVER GIVE UP!! happens whan it does bro

**Comment by leesio** [comment]
This doesn't look like an issue with pusher-js and it seems like it was resolved. I'd like to close this issue, if that's OK @moesyzlack8

**Comment by agonqorolli** [comment]
this happens because the **scope of apply property** (which probably is a function in your case) and the **scope of Echo** are NOT the same. Thus when invoking the callback, it fails.

Changing the apply function, to an array function (binding it), will solve it.
