### ISSUE TITLE
channel.unbind(event, handler) doesn't seem to unbind from the callback

### ISSUE THREAD

**Issue by frankcalise** [pusher/pusher-js#343]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I'm dispatching an action to unbind event in componentWillUnmount that hits my middleware keeping track of channel event subscriptions in React 16.8.0 like so: 
`const { event, handler } = action.payload;
          if (channel) {
              channel.unbind(event, handler);
          }`

When I navigate away, the method properly gets called. However if I make an event from console or a separate instance of the app, I get a error about not being able to setState on an unmounted component (which is carried out by the class method that is no longer mounted).

If I change this above snippet to just `channel.unbind(event)` - I do not get the error about a memory leak.

**What is the expected behavior?**
I was expecting to bind a specific event name with handler on a channel (which works) and unbind it in the same fashion according to the documentation. I didn't necessarily want to unbind all handlers for this event (by not providing the second argument to unbind).

**Which versions of Pusher, and which browsers / OS are affected by this issue?**
React 16.8.0
"pusher-js": "^4.2.2",
Chrome: Version 74.0.3729.131 (Official Build) (64-bit)
Windows 10

**Comment by leesio** [comment]
Are you able to reproduce this in a minimal example? Is it possible that the `handler` you're providing is not the same `handler` as you provided in the `bind` call?

**Comment by frankcalise** [comment]
I'll try and work on a contrived example for you.

In the mean time, this is what the component looks like:

```
  componentDidMount() {
    this.props.pusherBindEvent(
      api.PUSHER_EVENT_NAME_MEMBER_SUB_UPDATED,
      this.handleSubscriptionUpdated,
    )
  }

  componentWillUnmount() {
    this.props.pusherUnbindEvent(
      api.PUSHER_EVENT_NAME_MEMBER_SUB_UPDATED,
      this.handleSubscriptionUpdated,
    )
  }

  handleSubscriptionUpdated = data => {
    // ...
  }
```

Maybe it's possible the component unmounts before the middleware action is hit and it's no longer around to unbind? From middleware:

```
else if (action.type === UNBIND_EVENT) {
  const { event, handler } = action.payload
  if (channel) {
    channel.unbind(event, handler)
  }
  return
}
```

which gets hit from this action

```
const pusherUnbindEvent = (event, handler) => {
  return { type: UNBIND_EVENT, payload: { event, handler } }
}
```

**Comment by leesio** [comment]
@frankcalise did you get anywhere with reproducing this in a simple example?

**Comment by leesio** [comment]
I'm going to close this issue for now. Please feel free to re-open it if you have more information to share!
