### ISSUE TITLE
Pusher typescript Property 'members' does not exist on type 'Channel'.

### ISSUE THREAD

**Issue by 2n2n** [pusher/pusher-js#346]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
I'm using typescript and pusher, I get an issue when I try to get the members of  a channel via `presence-` channel. [see example link](https://pusher.com/docs/channels/using_channels/presence-channels#example)

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
```
let _pusher = new Pusher(key);
let channel = _pusher.subscribe('presence-lobby');
channel.bind('pusher:subscription_succeeded', () => {
            console.log('subscription succeeded');
            console.log(channel.members) //<- I'm getting an error here  saying "Property 'members' does not exist on type 'Channel'"
})
```
**What is the expected behavior?**
when I try to console.log the `channel.members` it returns an object with members in it. I was able to remove the error thru editing the interface for `Pusher.subscribe()` type on `node_modules/@types/pusher-js/index.d.ts` (See comment below)

```
interface Pusher extends EventsDispatcher {
        channel(name: string): Channel;
        allChannels(): Channel[];
        connect(): void;
        disconnect(): void;
        subscribe(name: string): Channel; // <- modified this to: subscribe(name: string): Channel | PresenceChannel | PrivateChannel; as fallback
        subscribeAll(): void;
        unsubscribe(name: string): void;
        isEncrypted(): boolean;
        key: string;
        config: Config; // TODO: add GlobalConfig typings
        channels: any; // TODO: Type this
        global_emitter: EventsDispatcher;
        sessionID: number;
        timeline: any; // TODO: Type this
        connection: ConnectionManager;
    }
```
**Which versions of Pusher, and which browsers / OS are affected by this issue?

I'm using macOS mojave version 10.14.5 and Chrome Version 74.0.3729.169 (Official Build) (64-bit)

Did this work in previous versions of Pusher? If so, which?**
I haven't tried yet but Im using the current latest version for typescript `"@types/pusher-js": "^4.2.2"` & `"pusher-js": "^4.4.0",`

**Comment by 2n2n** [comment]
Need help please if this is still existing? Or how to contribute with the typing for this?

**Comment by leesio** [comment]
@2n2n are you able to share the `tsconfig.json` you're using? I'm not able to reproduce this issue.

**Comment by leesio** [comment]
I'm going to close this issue as I can't reproduce it and it seems to have gone stale. Please feel free to re-open if you're experiencing the same issue and can shed more light on it!

**Comment by mrlectus** [comment]
it is not completed as i am having the same issue too

**Comment by ITSJORDAN-TFA** [comment]
Just an FYI on this one - I was getting this issue on 8.4.0
You can typecase it if you know the type of channel, in my case a presense one.
```ts
if((channel as PresenceChannel).members.count < 2) return;
```
