### ISSUE TITLE
This will not work in the service worker

### ISSUE THREAD

**Issue by curt6815463** [pusher/pusher-js#349]
https://github.com/pusher/pusher-js/blob/807b778463851f3a9b02114abf06f00f65e94d8f/src/runtimes/worker/runtime.ts#L51-L55

XMLHttpRequest in Service Worker will be undefined

**Comment by leesio** [comment]
You're right. We should update the `isXHRSupported` method for the worker runtime to consider this.

We'll get to this as soon as possible.

**Comment by leesio** [comment]
This should probably be included in #396
