### ISSUE TITLE
Trigger in React native doesn't work

### ISSUE THREAD

**Issue by HenriqueMata** [pusher/pusher-js#351]
1)I'm trying to send an event but returns a message: 'error', in console and crashes the app.
2)Another way returns error in error log: 'Unsupported event received on socket:'example_event''.

1)
```
pusherClient.send_event('event', {
            name: 'John',
            age: 20
        }, 'channel');
```

2)
```
const channel = pusherClient.subscribe('channel');
        channel.trigger('event', {
           name: 'John',
            age: 20
        });
```

**Comment by leesio** [comment]
Hi,
Client Events can only be triggered on private channels, and only if they're enabled for the app. 
Please see.

https://pusher.com/docs/channels/using_channels/events#triggering-client-events

If you still have issues, please fele free to reopen the issue.
