### ISSUE TITLE
How can I get unread message count in this api?

### ISSUE THREAD

**Issue by Mixelated** [pusher/pusher-js#357]
I am looking to get the list of rooms with the unread count. it exists on the API since v6. Can I reach this endpoint with this api? 

**Event: Initial state**
'Sent as soon as a client subscribes to the user subscription endpoint. The event data contains a list of rooms the user is a member of.'

it is a list of rooms with the unread count. I am pusher-js and pusher-client (VueJS).

**Comment by Mixelated** [comment]
solved by updating the JS client to 1.2, unread message count can be found as a room property (which can be found on the user object when connecting to chatkit)

**Comment by leesio** [comment]
@Mixelated I'm glad you resolved your issue. I assume you were looking for the chatkit js client? For future reference, that can be found [here](https://github.com/pusher/chatkit-client-js)
