### ISSUE TITLE
Add a way to add custom 'Content-Type' on auth without appending to default

### ISSUE THREAD

**Issue by neomrc** [pusher/pusher-js#359]
When creating subscribing to a private pusher channel we need to setup an authentication endpoint. On some instances we may require the requestor to make the **Content-Type** of the request set to _application/json_. But base on _src/runtimes/isomorphic/auth/xhr_auth.ts_ regardless of custom header options. It always predefine the **application/x-www-form-urlencoded** header content-type. So when a content-type will be defined on custom headers for authentication for override. It will always append to the first one which an example output on a request would be:

`Content-Type: application/x-www-form-urlencoded, <media-type>`

This would cause a confusion on the API side and must be nice to impose a single **Content-Type** for every request. https://greenbytes.de/tech/webdav/rfc2616.html#rfc.section.14.17

**Comment by neomrc** [comment]
Linking to existing PR -- https://github.com/pusher/pusher-js/pull/358

**Comment by leesio** [comment]
Hi @neomrc, thanks for this and the PR. I'm not totally sure how this would work though. If you're using the `xhr_auth` auth transport. The data will be encoded as a query string so the `application/x-ww-form-urlencoded` value for content-type is accurate.

Could you try to explain the problem you're having in a little more detail?

**Comment by neomrc** [comment]
Hi @leesio, thank you for your reply. What I am thinking is when a user defines a `Content-Type` that their API allows to receive or they created an optimistic logic for their API. A different request `Content-Type` may break their API logic or worst case is there will be no response back from the API for it will throw a bad request.

**Comment by leesio** [comment]
I'm still not convinced this is something we should implement. The `Content-Type` header accurately represents the data sent to the auth endpoint.

It is possible to implement a [cusom-authorizer,](https://github.com/pusher/pusher-js#authorizer-function) which allows you to implement whatever kind of auth request you like.

**Comment by neomrc** [comment]
oh cool! Thanks!
