### ISSUE TITLE
Unexpected token o in JSON at position 1 in pusher.js

### ISSUE THREAD

**Issue by rflatt-reassured** [pusher/pusher-js#368]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When I try to join a presence channel, I get the following error in pusher.js:
Uncaught SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at pusher.js:3131
    at XMLHttpRequest.xhr.onreadystatechange (pusher.js:595)
    at XMLHttpRequest.nrWrapper

As a result, it isn't joining the presence channel fully. It will still do whisper events, but I cannot get a list of users in the channel.

**What is the expected behavior?**
It should be able to get users in the presence channel.

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
This is happening in version 4.4.0 of pusher, using Chrome 67 on Windows 10.  I have reverted my code to where it had been working but I get this error there as well.

I am using it with Laravel (5.7) echo.

**Comment by rflatt-reassured** [comment]
Never mind, I missed a config setting.

**Comment by leesio** [comment]
@rflatt-reassured thanks for closing this issue. Would you mind sharing which configuration parameter you missed? It might help people in the future who are having the same issue.

**Comment by rflatt-reassured** [comment]
It's a bit embarrassing - I had unintentionally overwritten my .env file and BROADCAST_DRIVER was changed from pusher to redis.

**Comment by leesio** [comment]
@rflatt-reassured thanks for the update. Happens to the best of us 😄
