### ISSUE TITLE
crashes react native app with _nativeInterface.default.getCurrentState is not a function

### ISSUE THREAD

**Issue by tevonsb** [pusher/pusher-js#371]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Crashes react native app on startup
**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
Steps to reproduce:
1. Install pusher-js using npm install and follow instructions to install netinfo
2. Add boilerplace pusher code to react native app

`import Pusher from 'pusher-js/react-native';

// Enable pusher logging - don't include this in production
Pusher.logToConsole = true;

var pusher = new Pusher('145f9e79c1e932d355d3', {
  cluster: 'us3',
  forceTLS: true
});

var channel = pusher.subscribe('my-channel');
channel.bind('my-event', function(data) {
  console.log(JSON.stringify(data));
});`

**What is the expected behavior?**

Load pusher and subscribe to a channel

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**

using Pusher `^5.0.0` with react-native `0.59.8` and expo SDK 33.

**Comment by leesio** [comment]
This is very odd. I just bootstrapped a new project and it worked fine.

The steps I took were:

```
react-native init example-project
cd example-project
yarn add pusher-js @react-native-community/netinfo
react-native link @react-native-community/netinfo
cd ios && pod install && cd -
```

Then I opened the project in Xcode, it built and ran first time. Could you share a bit more about the process you followed to see this error?
Thanks

**Comment by AndreasHerss** [comment]
I'm getting the same error as you @tevonsb could be
 due to the message i get when i run the project.

```
Some of your project's dependencies are not compatible with currently installed expo package version:
 - @react-native-community/netinfo - expected version range: ~2.0.10 - actual version installed: ^4.1.4
Your project may not work correctly until you install the correct versions of the packages.
To install the correct versions of these packages, please run: expo install [package-name ...]
```

Seems like Expo wants to install netinfo V2 and pusher-js expects V4 :/

**Comment by gianemi2** [comment]
Same problem here.

**Comment by dorklord23** [comment]
> This is very odd. I just bootstrapped a new project and it worked fine.
> 
> The steps I took were:
> 
> ```
> react-native init example-project
> cd example-project
> yarn add pusher-js @react-native-community/netinfo
> react-native link @react-native-community/netinfo
> cd ios && pod install && cd -
> ```
> 
> Then I opened the project in Xcode, it built and ran first time. Could you share a bit more about the process you followed to see this error?
> Thanks

I think you don't use Expo while OP use it.

**Comment by dorklord23** [comment]
> Same problem here.
> 
> EDIT: I've solved.
> 
> I don't know what was the problem but I've tried to start a new project from scratch.
> I've seen that in that new project everything was working fine. I started migrate every file from the old project (where Pusher throw me the thread error) in the new project.
> Everything works fine here. I really don't know what was going on.
> 
> What I've tried in the old, not working, project was:
> 
>     * Delete `node_modules` folder and tried to reimport them with yarn.
> 
>     * Delete everything related to `pusher`and to `netinfo`
> 
> 
> Nothing resolve it.
> Started a new project and migrate all the file works.
> That's pretty strange.
> 
> Hope it helps someone!

Do you use Expo, @gianemi2?

**Comment by dorklord23** [comment]
> I'm getting the same error as you @tevonsb could be
> due to the message i get when i run the project.
> 
> ```
> Some of your project's dependencies are not compatible with currently installed expo package version:
>  - @react-native-community/netinfo - expected version range: ~2.0.10 - actual version installed: ^4.1.4
> Your project may not work correctly until you install the correct versions of the packages.
> To install the correct versions of these packages, please run: expo install [package-name ...]
> ```
> 
> Seems like Expo wants to install netinfo V2 and pusher-js expects V4 :/

@AndreasHerss Installing the new NetInfo with `expo install @react-native-community/netinfo` will remove the warning but `pusher-js` still doesn't work for Expo.

**Comment by gianemi2** [comment]
Yes I’m using Expo. Please try following exactly the steps described above. 
Also try initializing project with create-react-native-app (https://github.com/react-community/create-react-native-app)instead of expo init. 

That could be the only differences between my old project (not working) and the new one. 
Note that create-react-native-app is backwards compatible with expo, so you should not have any compatibility  problems.

**Comment by dorklord23** [comment]
@gianemi2 I still got the error even after I followed your steps. But yours inspired me to upgrade the Expo SDK from 33 to 34 and voila it worked!!

I believe Expo SDK must be updated to the latest one (34 as of now) so ```pusher-js``` could work.

**Comment by leesio** [comment]
Thanks a lot for investigating this, everybody.
From what I'm reading it seem like the latest version of the library requires at least Expo version 34. Is that a fair summary? If so I'll add something to the README explaining this contstraint.

**Comment by leesio** [comment]
I closed this issue as it seemed resolved. Feel free to re-open it if I was mistaken
