### ISSUE TITLE
v5.0.0 breaks with uglifyjs -c -m --keep-fnames --keep-classnames (v4.4.0 worked)

### ISSUE THREAD

**Issue by shanebdavis** [pusher/pusher-js#374]
This is a BUG.

Using webpack, I build this code:

```javascript
PusherClient = require("pusher-js");
new PusherClient("xxx-a-valid-key", {encrypted: true, cluster: "mt1"})
```

Then I uglify it with:

```shell
npx uglifyjs webpack-out.js -c -m --keep-fnames --keep-classnames
```

When I load it in a browser. With v4.4.0, it works. With v5.0.0 I get this error:

```
Unhandled rejection You must pass your app key when you instantiate Pusher.
```

Chrome@76.0.3809.100 
webpack@4.39.1
node@10.15.0
pusher-js@5.0.0

**Comment by leesio** [comment]
That's really odd @shanebdavis. Are you able to share your webpack config so I can try to recreate this issue locally?

**Comment by shanebdavis** [comment]
Oh! It appears to actually happen when I included the already minified pusher-js and then it gets minified again. Here is a project that fully reproduces it:

https://github.com/shanebdavis/pusher-js-5-webpack-uglify

I can just change my code to NOT included the minified version and it appears to work. Uglify should work just find. It's weird though that double-minifying it breaks things now when it didn't in v4.4.

**Comment by leesio** [comment]
@shanebdavis this is indeed weird, and a little bit worrying as the minified version of the bundle should 'work' in all the places that the non-minified build works.

Thanks for sending over the example project. I'll try to look into this soon.

I've been operating under the assumption that, since a workaround is available (using the unminified bundle, this is not hugely time sensitive). Is this fair?

**Comment by shanebdavis** [comment]
Yeah, I'm good. It's not even really a workaround. More like code cleanup!

Still, very weird.

**Comment by leesio** [comment]
I just tried this with the version `3.10.0` of uglify-js and it seems to work fine.
Since it's unclear what was causing this issue and it _seems_ to have gone away with the latest release, I'm going to close this issue.

Please feel free to reopen it, if you're still experiencing this issue.
