### ISSUE TITLE
Pusher confuse instance with event-name

### ISSUE THREAD

**Issue by dvash999** [pusher/pusher-js#378]
**Do you want to request a *feature* or report a *bug*?**
bug?

**What is the current behavior?**
when trying to register the trigger to a channel and an event, the trigger function wont accept the channel as the instance, and giving an error of:
Event 'private-chat-6' does not start with 'client-'

but if I use the event ('client-typing') it works fine. But then I only use 2 arguments instead of 3.

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

CODE:

```
    this.pusher = new Pusher(this.pusherKey, {
      cluster: 'eu',
      encrypted: true,
      authEndpoint: this.endPoint + '/broadcast/' + this.userID,
      auth: {
        headers: {
          'Authorization': this.userSession.getToken()
        }
      }
    });

    this.channel[chatID] = this.pusher.subscribe('private-chat-' + chatID);

    this.channel[chatID].bind('client-message', fullMessageInfo => {
       this.chatSubject.next(fullMessageInfo);
    });


  triggerNewMessage(fullMessageInfo): void {
    this.channel[this.chatID].trigger('client-message', fullMessageInfo);
  }
```

BUT IF I USE 3 arguments (to include the channel):
```
  triggerNewMessage(fullMessageInfo): void {
    this.channel[this.chatID].trigger('private-chat-' + this.chatID, 'client-message', fullMessageInfo);
  }
```
It gives me an error

**What is the expected behavior?**
to be able to register the channel to the trigger as the EsLint ask ('instance', 'event-name', 'context')

**Which versions of Pusher, and which browsers / OS are affected by this issue?
chrome
pusher v5

Did this work in previous versions of Pusher? If so, which?**
First time using pusher so I dont know...

**Comment by leesio** [comment]
I'm a little bit confused by this. If you check the [documentation for client events](https://pusher.com/docs/channels/using_channels/events#triggering-client-events) the only API described is:

```
var triggered = channel.trigger(eventName, data);
```

I'm not sure where the API you describe comes from:

```
// THIS WON'T WORK
channel.trigger(channelName, eventName, data);
// THIS WON'T WORK
```
Is this written in some documentation somewhere? If so can you share where? I'll try to get it fixed.

The first API is the actual API for triggering client events. It's not necessary to provide the channel name when triggering a client event, the `trigger` method is on the `channel` class, which already has access to the channel name.

**Comment by dvash999** [comment]
Thank you for commenting.
I do apologize if im confusing, so I attached images:
the first image is the build in trigger function:
![trigger](https://user-images.githubusercontent.com/38922816/64170322-82e4fe00-ce58-11e9-8ad5-f069037a990d.PNG)

the 2nd image is how I call it: 
![custom trigger](https://user-images.githubusercontent.com/38922816/64170331-88424880-ce58-11e9-8859-700785a11a28.PNG)


the trigger function clearly take 3 variables, or am I doing it wrong?

**Comment by leesio** [comment]
@dvash999 could I ask what the first screengrab is showing? i.e. where is that type signature from?

I agree that your screengrab shows a function which accepts 3 arguments but that function signature doesn't correct. If you look at the `trigger` function in pusher-js it [accepts 2 arguments only](https://github.com/pusher/pusher-js/blob/master/src/core/channels/channel.ts#L46).

**Comment by leesio** [comment]
Any update @dvash999 ?

**Comment by leesio** [comment]
I’m going to close this issue as I don’t believe it’s relevant, if you can provide more info @dvash999 feel free to reopen
