### ISSUE TITLE
Warning: RCNNetInfo - You are using the deprecated API

### ISSUE THREAD

**Issue by Deg5112** [pusher/pusher-js#382]
pusher-js lib appears to be calling a deprecated method from react-native-netinfo.

`Warning: RCNNetInfo - You are using the deprecated API...`

At a base level test case
literally just having the latest installed: "@react-native-community/netinfo": "^4.2.0"
and having a file with nothing in it other than import Pusher from 'pusher-js/react-native': "5.0.1"

i will get the warning, when deploying to ios/android simulator

i dug a little into the "@react-native-community/netinfo" specifically https://github.com/react-native-community/react-native-netinfo/blob/master/src/index.ts
line 144:
```
/**
 * Deprecated method to get the current state. You should upgrade to the new `fetch` method and
 * handle the new state type.
 *
 * @deprecated
 */
export function getConnectionInfo(): Promise<DeprecatedTypes.NetInfoData> {
  DeprecatedUtils.warnOnce();
  return DeprecatedState.latest();
}
```

Will the next update call the new fetch method, or am i missing something? Thanks!

**Comment by Deg5112** [comment]
<img width="1026" alt="React_Native_Debugger_-_Connected__port_19001_" src="https://user-images.githubusercontent.com/13839383/64406445-abc2ea00-d036-11e9-96fb-9a188add7760.png">

**Comment by leesio** [comment]
@Deg5112 thanks for letting us know about this. I understood when `NetInfo` was removed from `react-native` core that the old API would be supported for a while. Apparently I underestimated how long a while is in the `react-native` world.

I had a quick look and it seems like the new API works OK. I wonder if you'd mind trying a custom build to see if it solves your problem? You can install the custom build with

```
npm install git+ssh://git@github.com/pusher/pusher-js.git#use-new-netinfo-api
```
If this is all it takes to resolve this, it should be fine to include it in the next release

**Comment by Deg5112** [comment]
Thanks for the reply james. I installed the package at the branch you specified with that url. However, it looks like it's still calling the same deprecated getConnectionInfo method, and i still get the warning. Full stack trace below

Warning: RNCNetInfo - You are using the deprecated API. It will still work, but you must upgrade to the new API to receive the new features. The old API will be removed in the future
- node_modules/expo/build/environment/muteWarnings.fx.js:17:23 in warn
- node_modules/@react-native-community/netinfo/src/internal/deprecatedUtils.ts:79:4 in warnOnce
- node_modules/@react-native-community/netinfo/src/index.ts:145:2 in getConnectionInfo
- node_modules/pusher-js/dist/react-native/pusher.js:8:55185 in e
- node_modules/pusher-js/dist/react-native/pusher.js:8:55497 in <unknown>
- node_modules/pusher-js/dist/react-native/pusher.js:8:128 in n
- node_modules/pusher-js/dist/react-native/pusher.js:8:3445 in <unknown>
- node_modules/pusher-js/dist/react-native/pusher.js:8:128 in n
- node_modules/pusher-js/dist/react-native/pusher.js:8:10777 in <unknown>
- node_modules/pusher-js/dist/react-native/pusher.js:8:128 in n
- node_modules/pusher-js/dist/react-native/pusher.js:8:19688 in <unknown>
- node_modules/pusher-js/dist/react-native/pusher.js:8:128 in n
- node_modules/pusher-js/dist/react-native/pusher.js:8:924 in <unknown>
- node_modules/pusher-js/dist/react-native/pusher.js:8:933 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
- node_modules/pusher-js/react-native.js:1:24 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
* helpers/roleplays/EchoHelper.js:3:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
* screens/roleplays/RoleplaysScreen.js:11:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
* navigation/stacks/roleplays/RoleplaysStackNavigator.js:2:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
* navigation/tab_navigation/MainBottomTabNavigation.js:3:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
* navigation/IllumNavigator.js:14:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
* navigation/NavigationContainer.js:5:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
* App.js:14:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
- node_modules/expo/AppEntry.js:4:0 in <unknown>
- node_modules/metro/src/lib/polyfills/require.js:331:6 in loadModuleImplementation
- node_modules/metro/src/lib/polyfills/require.js:197:45 in guardedLoadModule
* null:null in global code

**Comment by subotkevic** [comment]
Any news on this? We should really fix that.

**Comment by Deg5112** [comment]
if it was fixed lemme, know, i just silenced the warning via YelloBox.. but.. don't wanna get in the habit of just silencing warnings

**Comment by subotkevic** [comment]
I’ve pushed one commit which should resolve this issue.

**Comment by leesio** [comment]
I just merged @subotkevic's commit into the feature branch and merged that branch into master #385 

This will be included in the next release.

**Comment by subotkevic** [comment]
Good news. When are you planning to draft a new release?

**Comment by leesio** [comment]
I would say Friday at the latest.

Thanks again for your contribution @subotkevic!

**Comment by leesio** [comment]
I just merged and released version 5.0.2 on npm/everywhere else. There should no longer be deprecation warnings about the netinfo API.

@subotkevic @Deg5112, could you confirm whether this solves your problem? If so I'll close this ticket.

**Comment by subotkevic** [comment]
Test branch worked for sure. Haven’t tested released version yet. But probably works too.

**Comment by Deg5112** [comment]
@leesio thanks everyone, yes no more warning!

**Comment by leesio** [comment]
Cool. I will close this issue!
Thanks both.
