### ISSUE TITLE
Create Apps Automatically

### ISSUE THREAD

**Issue by matthewsuan** [pusher/pusher-js#389]
Right now, the only way to create an app is via the dashboard.

I tried the CLI but it only allows to list apps.

How do we automate creating apps?

ty

**Comment by leesio** [comment]
Hi @matthewsuan,

Thanks for getting in touch. I'd prefer to keep github issues limited to issues with the pusher-js library.

For general support queries about pusher products, your best bet is to get in touch with our support team [here](https://support.pusher.com/hc/en-us)

Thanks
