### ISSUE TITLE
Not sending headers set by $.ajaxSetup in authorize channel call

### ISSUE THREAD

**Issue by mitulgolakiya** [pusher/pusher-js#391]
**Do you want to request a *feature* or report a *bug*?**
I think it's a bug.

**What is the current behavior?**
I'm using Pusher Channel with Laravel Echo for Broadcasting. https://laravel.com/docs/6.x/broadcasting#driver-prerequisites
After upgrading from 5.0.1 to 5.0.2, the pusher connector is not sending headers which were set by `$.ajaxSetup`.

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
It will need a full Laravel application setup so not possible via jsfiddle.net

**What is the expected behavior?**
When I use the following code, as described here, https://laravel.com/docs/6.x/csrf#csrf-x-csrf-token it should send that header and token in the call `broadcasting/auth` which is made while authorizing channels.

```
$.ajaxSetup({
    headers: {
        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
    }
});
```

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
5.0.2 is affected. It was working fine in 5.0.1.

**Comment by mitulgolakiya** [comment]
The solution I used right now to fix this is as following if anyone else is facing a problem.

As per this doc: https://laravel.com/docs/6.x/broadcasting#installing-laravel-echo

I added one more option `auth` to Echo configuration,

```
window.Echo = new Echo({
    broadcaster: 'pusher',
    key: process.env.MIX_PUSHER_APP_KEY,
    cluster: process.env.MIX_PUSHER_APP_CLUSTER,
    encrypted: true,
    auth: {
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    }
});
```

**Comment by leesio** [comment]
@mitulgolakiya thanks for describing your solution. I'm going to close this issue now.
