### ISSUE TITLE
`SameSite` attribute Warning

### ISSUE THREAD

**Issue by yofret** [pusher/pusher-js#392]
**Do you want to request a *feature* or report a *bug*?**
I think is neither of those

**What is the current behavior?**
I'm getting this warning, starting today, the date I'm creating this issue

> A cookie associated with a cross-site resource at http://pusher.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

**What is the expected behavior?**
There should not be a warning indicating that in the future the cookie won't be delivered if the attributes are not set correctly

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
```
"pusher-js": "^5.0.0"

Chrome Version 77.0.3865.90 (Official Build) (64-bit)
```

Thanks for reading this weird issue, and apologize in advance if it doesn't meets the format, I would like to know if there is something I could do from the configuration perspective, to remove this warning, I'm using this configuration https://lighthouse-php.com/4.1/subscriptions/client-implementations.html#apollo

**Comment by daveayerst** [comment]
@yofret I am seeing the same issue. We are using pusher-js in an "old-fashioned" html and javascript site.

**Comment by yofret** [comment]
@leesio Hi James!, that is correct, the issue appears in my application which has pusher-js as a dependency.

Looks like chrome is warning us about a new near-future cookie policy for cross-site request, and it is enforcing the usage of the `SameSite` flag.

**Comment by BrandonMathis** [comment]
Yes, this is surely being caused by a recent release of chrome. I am using pusher-js with the pusher rubygem on a rails application. Perhaps a setting needs to be made on the backend side of things? I  am going to continue investigating and will post here if a discover a fix to handle this warning.

**Comment by leesio** [comment]
I had a look at this issue this morning. I was able to see the warning in a normal Chrome window but not in an Incognito window. This, along with the fact that pusher-js doesn't really use cookies directly, leads me to suspect that this is an issue with one of the cookies set by the pusher dashboard, rather than a specific issue with pusher-js.

I'm going to take this to the appropriate team. I'll post an update when I have one.

**Comment by leesio** [comment]
It seems there's not an easy 'fix' for this issue at the moment. One workaround that you might try is disabling stats using the [`disableStats` option](https://github.com/pusher/pusher-js#disablestats-boolean).
This should prevent the library from sending the only request it makes to a `pusher.com` domain and should suppress the error. Could anybody confirm whether setting that parameter solves their issue?

**Comment by briantical** [comment]
Hey @leesio  this solves the problem.

**Comment by paxha** [comment]
i get the reason behind this issue. but what is the solution to control it????? how can i fix it in my application ??????

**Comment by leesio** [comment]
@paxha did you try disabling stats as described in https://github.com/pusher/pusher-js/issues/392#issuecomment-542166471

**Comment by paxha** [comment]
@leesio  yes. but still not effect.
this is my code

 var pusher = new Pusher('{{ config('broadcasting.connections.pusher.key') }}', {
        cluster: '{{ config('broadcasting.connections.pusher.options.cluster') }}',
        encrypted: true,
        authEndpoint: '/broadcasting/auth',
        disableStats: false,
        auth: {
            headers: {
                'X-CSRF-Token': '{{ csrf_token() }}', // CSRF token
            }
        }
    });

**Comment by paxha** [comment]
i am trying for many days but all in vain

**Comment by paxha** [comment]
if i set disableStats: true, it also not working.

**Comment by leesio** [comment]
@paxha setting `disableStats`  to `true` *should* disable this problem.

Can you confirm it still doesn't work when your config is

```
var pusher = new Pusher('{{ config('broadcasting.connections.pusher.key') }}', {
  cluster: '{{ config('broadcasting.connections.pusher.options.cluster') }}',
  encrypted: true,
  authEndpoint: '/broadcasting/auth',
  disableStats: false,
  auth: {
    headers: {
      'X-CSRF-Token': '{{ csrf_token() }}', // CSRF token
    }
  }
}); 
```

**Comment by paxha** [comment]
yes the warnings are gone but i still not getting any response from channel.
here is code

```
    // Subscribe to the channel we specified in our Laravel Event
    var channel = pusher.subscribe('private-user.' + '{{ auth()->user()->id }}');

    // Bind a function to a Event (the full Laravel class)
    channel.bind('App\\Events\\NewNotificationEvent', function (data) {
        console.log(data);
        toastr.success(data.notification.message, data.notification.heading);
    });
```

**Comment by leesio** [comment]
@paxha that sounds unrelated to this issue.

You'll be better off contacting [Pusher Support](https://support.pusher.com/hc/en-us/categories/360001491213-Channels) with your issue

**Comment by AdamKyle** [comment]
Is this issue still being looked at? I recently opened an issue on a laravel package that makes use of this library: [see me for issue](https://github.com/beyondcode/laravel-websockets/issues/302) and even by setting disableStats to true, I still get the warning in chrome. Whats the status of this issue aside from being "closed"

**Comment by nilsringersma** [comment]
@AdamKyle [in your issue](https://github.com/beyondcode/laravel-websockets/issues/302) you are passing the `disabledStats` options to Echo. The correct option name is `disableStats` not `disabledStats`. Try passing that into your Echo options and it should work!

**Comment by TeamballDev** [comment]
What happens is that the Pusher domains request that the route be verified with an SSL certificate for more security, if it does not block it, after you upload your project to a server with an SSL certificate, everything works normally, meanwhile you can use,https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf?hl=es   regards

**Comment by leesio** [comment]
As of release version 5.1.0 https://github.com/pusher/pusher-js/releases/tag/v5.1.0 stats are disabled by default.
This means this issue should not occur unless `enableStats` is specifically set.

I'm going to close this issue now. Please feel free to reopen it if this doesn't resolve the issue for you

**Comment by eriknyk** [comment]
I'm using v6.0 and still happening, also disabling `enableStats` not worked

```
A cookie associated with a cross-site resource at http://pusher.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
:3000/invoices/payment?id=1#:1 A cookie associated with a cross-site resource at https://pusher.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
utils.js:67 Pusher :  : ["The disableStats option is deprecated in favor of enableStats"]
```
