### ISSUE TITLE
React-Native android not connecting to channel

### ISSUE THREAD

**Issue by aplau95** [pusher/pusher-js#393]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

![image](https://user-images.githubusercontent.com/20978812/66525958-f0b1c480-eaab-11e9-9e64-6eadb3d97f92.png)

Unable to connect to pusher when creating new Pusher object

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

Create new project with React Native CLI

`react-native init AwesomeProject && cd AwesomeProject && npm install --save @react-native-community/netinfo && npm install --save pusher-

###### In App.js ######
Add `Pusher.logToConsole = true` 
initialize new pusher object

Open up an android simulator
`react-native run-android`

**What is the expected behavior?**

![image](https://user-images.githubusercontent.com/20978812/66526409-6a967d80-eaad-11e9-8b3b-5ccbf9ff3960.png)

iOS version is able to connect

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**

"@react-native-community/netinfo": "^4.4.0",
    "pusher-js": "^5.0.2",
    "react": "16.9.0",
    "react-native": "0.61.2"

**Comment by andrewschenk-linx** [comment]
What was the resolution?  I am seeing this same behavior using pusher-js 6.0.0

**Comment by eng-osman** [comment]
Is there any solution

**Comment by Muhammad1200** [comment]
Did you find any solution to this problem because I am also facing this problem

**Comment by fansilva1991** [comment]
You could try 

```xml
android:usesCleartextTraffic="true"
```

Inside the <application> tag in your AndroidManifest file.

@Muhammad1200
