### ISSUE TITLE
Server SSL verification with a custom certificate

### ISSUE THREAD

**Issue by dpinol** [pusher/pusher-js#397]
I'd like to connect to a custom pusher server secured with a self-signed SSL certificate.
Is it possible to specify my CA to the pusher options in the same way that can be specified with the python client? https://github.com/pusher/pusher-http-python/blob/master/pusher/requests.py#L33

thanks

**Comment by leesio** [comment]
Hey @dpinol, I’m afraid that functionality isn’t available right now and we have no specific plans to implement it.

**Comment by leesio** [comment]
I'm going to close this issue as I doubt it will be prioritised
