### ISSUE TITLE
Can not find variable buffer.

### ISSUE THREAD

**Issue by BaiMaoLi** [pusher/pusher-js#398]
After i've install pusher and import in my react native app, 
It shows "can not find variable buffer"
I've followed installation guide.
I've installed react native netinfo,
If anyone has idea, please let me know. thanks.

**Comment by kgpasta** [comment]
I'm also having this issue. I think its related to https://github.com/pusher/pusher-js/pull/376 I think the polyfill is still necessary in RN builds

**Comment by leesio** [comment]
@BaiMaoLi are you still experiencing this issue? What version of react-native are you using?

**Comment by leesio** [comment]
I'm going to close this issue, as I think the most likely issue is an incorrect import.

**Comment by pmn4** [comment]
Could y'all re-open this issue?
I use Pusher (through a third party) in an Expo application, and `Buffer` is not a native library the way it is in node. I think the fix is as simple as adding `buffer` to package.json and importing where needed

**Comment by akhzarna** [comment]
> I was also having this issue, but I fixed it by:

No Luck Yet

**Comment by karmatradeDev** [comment]
im currently having this problem. i tried all the solutions up top. im running expo 47 pusher-js 7.5.0

**Comment by WhidRubeld** [comment]
This problem appeared in version expo 47. Due to an update to the React package which has updated working with Hermes.

To fix this problem you need a hard version 7.4.0 for pusher-js

```
yarn add pusher-js@7.4.0
```

Thus, this package flies into legacy support. In future you should also consider a new library for React Native:
https://github.com/pusher/pusher-websocket-react-native


If you are using the EAS build from Expo, then you will need to create a config for this package. It will look something like this:
```
const { createRunOncePlugin } = require('@expo/config-plugins')
const pkg = require('@pusher/pusher-websocket-react-native/package.json')

module.exports = createRunOncePlugin((config) => config, pkg.name, pkg.version)
```

**Comment by WhidRubeld** [comment]
> im currently having this problem. i tried all the solutions up top. im running expo 47 pusher-js 7.5.0

This problem appeared in version expo 47. Due to an update to the React package which has updated working with Hermes.

To fix this problem you need a hard version 7.4.0 for pusher-js

```
yarn add pusher-js@7.4.0
```

Thus, this package flies into legacy support. In future you should also consider a new library for React Native:
https://github.com/pusher/pusher-websocket-react-native


If you are using the EAS build from Expo, then you will need to create a config for this package. It will look something like this:
```
const { createRunOncePlugin } = require('@expo/config-plugins')
const pkg = require('@pusher/pusher-websocket-react-native/package.json')

module.exports = createRunOncePlugin((config) => config, pkg.name, pkg.version)
```

**Comment by Stevemoretz** [comment]
> > im currently having this problem. i tried all the solutions up top. im running expo 47 pusher-js 7.5.0
> 
> This problem appeared in version expo 47. Due to an update to the React package which has updated working with Hermes.
> 
> To fix this problem you need a hard version 7.4.0 for pusher-js
> 
> ```
> yarn add pusher-js@7.4.0
> ```
> 
> Thus, this package flies into legacy support. In future you should also consider a new library for React Native: https://github.com/pusher/pusher-websocket-react-native
> 
> If you are using the EAS build from Expo, then you will need to create a config for this package. It will look something like this:
> 
> ```
> const { createRunOncePlugin } = require('@expo/config-plugins')
> const pkg = require('@pusher/pusher-websocket-react-native/package.json')
> 
> module.exports = createRunOncePlugin((config) => config, pkg.name, pkg.version)
> ```

Not true it happens on SDK 45 too and that other library is not a replacement for this one
 https://github.com/pusher/pusher-websocket-react-native/issues/75

**Comment by Stevemoretz** [comment]
> I'm going to close this issue, as I think the most likely issue is an incorrect import.

That's not right this is correct and it doesn't work:

```
import Pusher from "pusher-js/react-native";
```

**Comment by WhidRubeld** [comment]
> Also you don't need a config plugin, that's not true either.
The configuration file is required if you are developing in a managed workflow within the Expo platform... See - https://docs.expo.dev/guides/config-plugins/

If you are using native code, you can only include it in the development build.

**Comment by Stevemoretz** [comment]
> > Also you don't need a config plugin, that's not true either.
> 
> The configuration file is required if you are developing in a managed workflow within the Expo platform... See - https://docs.expo.dev/guides/config-plugins/
> 
> If you are using native code, you can only include it in the development build.

That is only required if the library you are installing needs manual changes the library you mentioned is automatic other than the [desugaring](https://developer.android.com/studio/write/java8-support#library-desugaring).(https://github.com/pusher/pusher-websocket-react-native/issues/74) which should need a custom config other than that it doesn't.

**Comment by patrykczubek** [comment]
Not an replacement, with the pusher native library, you’re not able to connect to a custom host.

**Comment by Stevemoretz** [comment]
> Not an replacement, with the pusher native library, you’re not able to connect to a custom host.

Exactly. Even worse you can't even connect to their own api using existing libraries like `laravel-echo` and `apollo graphql` and many more!! You don't go around deprecate stuff that your product needs, without providing a usable alternative!

Can't remember the last time I was so mad about a company's SDK.

**Comment by patrykczubek** [comment]
The only bad thing for me about 7.4.0 is that it doesn't have the watchlist implemented yet, but shouldn't be too hard to implement.
