### ISSUE TITLE
A cookie associated with a cross-site resource at http://dashboard.pusher.com/ was set without the `SameSite` attribute.

### ISSUE THREAD

**Issue by paxha** [pusher/pusher-js#400]
i am getting cross site issue in local machine as well as production server.
![Capture](https://user-images.githubusercontent.com/38579192/68928408-d0aca980-07ab-11ea-93a4-d7a548b2ca8d.PNG)

due to this warnings i am not getting notifications

 **this is my pusher configuration code**

  var pusher = new Pusher('{{ config('broadcasting.connections.pusher.key') }}', {
        cluster: '{{ config('broadcasting.connections.pusher.options.cluster') }}',
        encrypted: true,
        authEndpoint: '/broadcasting/auth',
        auth: {
            headers: {
                'X-CSRF-Token': '{{ csrf_token() }}', // CSRF token
            }
        }
    });

 var channel = pusher.subscribe('private-user.' + '{{ auth()->user()->id }}');

channel.bind('App\\Events\\NewNotificationEvent', function (data) {
        toastr.success(data.notification.message, data.notification.heading);
    });

**Comment by volkanmetin** [comment]
#392

**Comment by leesio** [comment]
Indeed. This is a duplicate. Thanks for mentioning that @volkanmetin
