### ISSUE TITLE
Handling subscribe attempt to private channel when session expired

### ISSUE THREAD

**Issue by andrewoh531** [pusher/pusher-js#402]
**Do you want to request a *feature* or report a *bug*?**
Potentially a bug

**What is the current behavior?**
No pusher message/event when our server returns a 401 Unauthorized HTTP response to the PusherJS library after an attempt to subscribe to a private channel.

We want to disconnect the socket connection on the client when the server auth step ([step 6 in the diagram](https://pusher.com/docs/channels/server_api/authenticating-users)) returns a 401 HTTP status response. Unfortunately I don't seem to receive any events from PusherJS library when this happens.

I have tried the following to see what message is received when the PusherJS library receives a 401 on an auth attempt but none of them seem to be triggered:

```coffeescript
pusher.connection.bind 'message', (msg) ->
# ... 

pusher.connection.bind "error", (err) ->
#...

pusher.connection.bind "state_change", (states) ->
# ...
```

```typescript
this.channel.bind_global((event, data) => {
```

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
1. User navigates to our app and uses it. This will establish a connection to Pusher
1. User completes what they're doing and walks away but leaves their browser and the page open
1. The user's session expires
1. Our app may still be running and we have a background task that attempts to subscribe to a private channel
1. The subscription attempt will result in our server returning a 401 HTTP response as session is expired
1. We were hoping/expecting that Pusher would send a message that we can act on, or that the library may receive the 401 and disconnect the socket altogether.

**What is the expected behavior?**
To receive an event so we can act on it and disconnect the socket. Either that or the Pusher library to do that for us.

Or perhaps we have configured something incorrectly.

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
```
"pusher": "3.0.0",
"pusher-js": "5.0.3",
```

Firefox, Chrome (but do not believe it is a browser specific issue)

**Comment by tomfotherby** [comment]
I think we have the same problem. This shows `401`'s in our web app since 10/Sep/19:

![Selection_232](https://user-images.githubusercontent.com/140179/70706899-ca3c1f80-1cce-11ea-9f01-33e9e45db063.png)

My theory is that when our UK users started work that day, their Google Chrome auto-upgraded to v77, and there is something related to pusher-js and Chrome v77 that is causing many more `401`'s for us. We reproduced it by logging into our website and opening multiple tabs, then we Log out in one tab, the other tabs will hit our API to request a new pusher token for a private channel every 30 secs, but we return a 401 due to the expired session. This doesn't happen on Mac or Linux, it seems to happen only for Windows Users. We upgraded our `pusher-js` npm module from `4.2.1` to `5.0.3` - it didn't help.

**Comment by leesio** [comment]
That's an interesting theory, @tomfotherby. It's not immediately clear what could be happening, but I'll try and look into this issue soon.

**Comment by tomfotherby** [comment]
Our `401` issue seems to have gone away on it's own. Our improvement seems to have started a day after Chrome v79 came out ([source](https://en.wikipedia.org/wiki/Google_Chrome_version_history)) but I can't justify why that could be related:
![Selection_276](https://user-images.githubusercontent.com/140179/71937347-08304480-31a4-11ea-9fa0-72fd8e2bf6ce.png)

**Comment by leesio** [comment]
@tomfotherby glad to hear the new release fixed your issue. Though it isn't immediately obvious to me what change in that release might have solved your issue 🤔

**Comment by tomfotherby** [comment]
@leesio , just in case it helps, these were our PR notes:

> `pusher-js` fixed the issue of continuously calling our auth-endpoint (`getRtmToken`) after a failed call. After upgrading to the newest version of pusher-js, it errors and stops calling after it gets an error response from our api. Previously it polled the auth-endpoint every 30sec resulting in many many log entries.
> The cause was our users often had more than one browser tab open and logged out of one, so the other tabs polled auth endpoint endlessly in 30sec intervals. This had the effect of bloating our kibana logs with `401` and of `403` errors on our `getRtmToken` endpoint.

**Comment by leesio** [comment]
@andrewoh531 I just revisited your issue and think I may have misread it first time around.

I think your issue could be solved by binding to the `pusher:subscription_error` event on the `channel` object.

```
let channel = pusher.subscribe('private-my-channel')
channel.bind('pusher:subscription_error', (err) => 
  console.log(err)
})
```

At the moment this handler will be called with *just* the status code when the auth endpoint returns a non-200 response but I'm planning on merging this PR soon https://github.com/pusher/pusher-js/pull/412 which should clarify that error message.

Really sorry for the delay in getting back to you. Hope this helps

**Comment by andrewoh531** [comment]
> @andrewoh531 I just revisited your issue and think I may have misread it first time around.
> 
> I think your issue could be solved by binding to the `pusher:subscription_error` event on the `channel` object.
> 
> ```
> let channel = pusher.subscribe('private-my-channel')
> channel.bind('pusher:subscription_error', (err) => 
>   console.log(err)
> })
> ```
> 
> At the moment this handler will be called with _just_ the status code when the auth endpoint returns a non-200 response but I'm planning on merging this PR soon #412 which should clarify that error message.
> 
> Really sorry for the delay in getting back to you. Hope this helps

Thanks @leesio. Tried your suggestion but it didn't work.

Not sure if it makes any difference but we're using JSONP as the protocol.

We've also upgraded `pusher-js` to version `5.1.1` so fairly up to date.
