### ISSUE TITLE
Split out end to end encryption into separate helper library

### ISSUE THREAD

**Issue by leesio** [pusher/pusher-js#403]
At the moment the pusher-js library contains full support for end to end encryption. The encryption primitives included increase the size of the bundle significantly for everybody.

We should split out the end to end encryption functionality into a separate helper library.

**Comment by rafa-as** [comment]
@leesio some news here? Can we help you with this task?

**Comment by jameshfisher** [comment]
Options here that I can think of:

1. Allow user to pass it in via config, e.g. `new Pusher(..., { tweetnacl: X })`
2. Assume tweetnacl exists in global scope; user must import it somehow
3. Provide a separate `pusher-with-e2ee.min.js` which bundles `tweetnacl`

I prefer Option 1.

**Comment by rafa-as** [comment]
@jameshfisher you mean the X should be a class/service instance or something similar?

**Comment by jameshfisher** [comment]
@rafa-as I imagine it being an object that exposes functionality like this: https://github.com/pusher/pusher-js/blob/87e173d6f87074c95add7c6377adf149519be823/src/d.ts/tweetnacl/index.d.ts#L8-L11

**Comment by rafa-as** [comment]
@jameshfisher sounds good

**Comment by leesio** [comment]
I started work on this and created a draft PR  in #445

**Comment by leesio** [comment]
I released a [new version](https://github.com/pusher/pusher-js/releases/tag/v6.0.0) which should solve this issue.

**Comment by rafa-as** [comment]
Thanks @leesio I will try this noon

**Comment by leesio** [comment]
@rafa-as any updates?
