### ISSUE TITLE
pusher subscriptionPending always true without error message

### ISSUE THREAD

**Issue by innawy** [pusher/pusher-js#406]
**Do you want to request a *feature* or report a *bug*?**
Might be a bug 
**What is the current behavior?**
I'm trying to deploy an app with presence channels on firebase. In the subscribeToPusher step, the status of **subscriptionPending** is always true and it does not return any error. I was wondering if you could possibly help identify the issue.
**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

**What is the expected behavior?**
once a client subscribes to a channel, the status should turn to **subscribed**
**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
impacting all browsers

<img width="230" alt="Screen Shot 2019-12-18 at 9 16 32 PM" src="https://user-images.githubusercontent.com/43102453/71139256-aea7ac00-21db-11ea-995d-512e24a87dc1.png">

**Comment by leesio** [comment]
@innawy are you able to share some example code? It's hard to tell what the problem might be without a little more context.

**Comment by Asadbekinha** [comment]
Same problem. Please share if you found answer
