### ISSUE TITLE
Warnings are not logged by default

### ISSUE THREAD

**Issue by stof** [pusher/pusher-js#430]
The library logs some warnings to highlight wrong config or some other case. And for instance, this is used to report the deprecation of the `disableStats`. But these warnings go through the same logging stack than debug message, which is disabled by default. This means that these deprecations are actually not reported.

**Comment by stof** [comment]
Also, I don't see a way to enable logging warnings to the console but not debug messages.

**Comment by leesio** [comment]
Yeah. This is a bit annoying. It seems to me that we do the hard work of logging things at the appropriate level (warn/debug/error) but don't let custom loggers access it.

A couple of things we could do:

- allow a log level to be passed in the `options` object
or
- pass a level into the custom logger function, that way consumers of the library can write their own level aware logger.

**Comment by stof** [comment]
I'm not even interested in using a custom logger. The built-in logger using `console.log` is fine for me if warnings were logged there. So the log level in options seems good to me (and I think `warn` should be the default rather than logging nothing, so that deprecation warnings are visible by default).

**Comment by stof** [comment]
this is still relevant IMO. Having invisible deprecation warnings is not useful
