### ISSUE TITLE
should params in AuthOptions be optional?

### ISSUE THREAD

**Issue by chrisdrackett** [pusher/pusher-js#433]
https://github.com/pusher/pusher-js/blob/3e49245daea296f97b8ab439a7a9efa3a4367fa8/src/core/auth/options.ts#L4

We only need and are only passing the headers, curious if this should be 

```
export interface AuthOptions {
    params?: any;
    headers?: any;
}
```

**Comment by leesio** [comment]
@chrisdrackett I just pushed a new release where this should be fixed. Thanks for pointing it out

**Comment by leesio** [comment]
I'm going to close this issue now because I think it's resolved. If I'm mistaken, please feel free to reopen.
