### ISSUE TITLE
Default to connect over TLS

### ISSUE THREAD

**Issue by jameshfisher** [pusher/pusher-js#434]
**Do you want to request a *feature* or report a *bug*?**

A feature?

**What is the current behavior?**

When configuring with `new Pusher(..., { })`, i.e. with https://github.com/pusher/pusher-js#forcetls-boolean unset, the connection defaults to HTTP (non-TLS)

**What is the expected behavior?**

When configuring with `new Pusher(..., { })`, i.e. with https://github.com/pusher/pusher-js#forcetls-boolean unset, the connection should default to HTTPS (i.e. use TLS)

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**

Affects all versions, AFAIK.

Presumably the change should be around: https://github.com/pusher/pusher-js/blob/210853d42fdc72736a6e1bf7fab02f26bd6bc10a/src/core/pusher.ts#L261

**Comment by leesio** [comment]
@jameshfisher I just pushed a [new release](https://github.com/pusher/pusher-js/releases/tag/v6.0.0) which changes the default of `forceTLS` to `true`
