### ISSUE TITLE
Client events are not currently supported for encrypted channels

### ISSUE THREAD

**Issue by gmrchk** [pusher/pusher-js#435]
This is more of a question... As mentioned in [docs](https://pusher.com/docs/channels/using_channels/encrypted-channels#limitations) and in [code](https://github.com/pusher/pusher-js/blob/0d718adf06566766e0f544d74565d2ff3dcc0ff8/src/core/channels/encrypted_channel.ts#L43), client events are not supported for encrypted channels. 
Is there some reason for it? Is there a plan to support it?

**Comment by jameshfisher** [comment]
Thanks @gmrchk - you're right that it's not supported yet, and that we haven't explained why.

I've just added the explanation to [the docs page for E2EE](https://pusher.com/docs/channels/using_channels/encrypted-channels#limitations).

Internally, we're discussing a possible key rotation mechanism which would enable encrypted client events. But we don't have a timeline for this yet.

Could you describe what you would like to use encrypted client events for? And whether this key rotation problem would be a problem for your use-case? This would help us prioritize supporting this feature.

**Comment by gmrchk** [comment]
Thanks, @jameshfisher, I understand the technical problem behind it. I'm quite curious about the final solution you guys will come up with, as keeping the key consistent across machines sounds like an interesting problem. 

Actually, we are using `private-encrypted` as well as `present` channels at the same time, so we are able to send these events through the `presence` channel instead. We wanted to use it for events such as "user typing".

**Comment by jameshfisher** [comment]
Most likely solution, from internal discussion, would be to extend the protocol to allow distributing at least two keys at the same time, so that the old key can be gradually phased out. We don't have timelines for this extension, though.

If we were to allow sending encrypted client events, would you still use it for your "user typing" feature, knowing the described limitation around key rotation? I'm open to the possibility of removing the restriction, and just adding a clear warning instead, if the feature is sufficiently useful.

**Comment by gmrchk** [comment]
I see. That sounds sufficient and reasonably simple to implement. Well played. 👍 
Just a thought - would an introduction of an internal event that would force all clients connected to the channel refetch the key help? The event would be triggered by a client that was first forced to refetch a new key, but I guess there would still be a moment of inconsistent keys on clients tho. 

We are already in the process of implementing the events through `presence` channel, so we likely won't use it on our side. Also, we would like to rotate the master key regularly, so this would be a problem for us. 
However, I think removing the restriction is the way to go. It would give users much more freedom, and many people likely use the service with very rare, or no master key rotation at all, so this limitation doesn't apply to them. 
In the worst case, failing decryption could (maybe already does?) trigger an error that people could handle with their own "drastic" solution like hard-reload of browser.

**Comment by jameshfisher** [comment]
Hey - yes, I think that's one way to do it:

1. if a client fails to decrypt a client event, it triggers a new client event e.g. `client-encryption-failed`
2. if a client receives `client-encryption-failed`, it re-auths to get the latest shared secret

Your proposal is similar to how we handle key rotation at the moment, for non-client events. If a client fails to decrypt an event, it will re-auth to get the latest shared secret.

But this design has at least one problem: it causes a storm of clients all re-authing at once. If you have a lot of clients, this can DDoS your auth server. The "multiple keys" design doesn't have this problem, which is one reason we'd like to move towards that.

Thanks for your feedback on removing the restriction. I'll discuss it with the team.

**Comment by Brenneisen** [comment]
Hi, are there any news here? We would like to use encrypted channels. But we use client events to inform the backend about successful channel subscriptions via webhooks to send initial information then.
