### ISSUE TITLE
disable Logger.DEBUG: ?

### ISSUE THREAD

**Issue by neuropass** [pusher/pusher-js#436]
Is there a way to disable completely the Logger.DEBUG? In production I get random:

Logger.DEBUG:  error when cancelling message subscription chunk-vendors.js:16:40642
Logger.DEBUG:  Error: "Subscription has already ended"

seems like a bug but I cannot pin point this. 
Please advice! 

Thanks!

**Comment by leesio** [comment]
@neuropass are you sure these logs are coming from pusher-js? I don't recognise them and searching the codebase doesn't throw anything up
