### ISSUE TITLE
TypeScript types don't match actual node code

### ISSUE THREAD

**Issue by jordanryanmoore** [pusher/pusher-js#439]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When using pusher-js-5.1.1 with node, the bundled TypeScript types match the readme, but the actual node code artifacts do not.

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
```
import Pusher from "pusher-js";
import * as PusherTypes from "pusher-js";

console.log(Pusher);
console.log(PusherTypes);
```

The output for `Pusher` is `undefined` (expected to be a class) and the output for `PusherTypes` is the `Pusher` class (`[Function: Pusher] {…}`, but expected to be all of the other types).

**What is the expected behavior?**
See above.

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
I'm using Pusher v5.1.1 with node 12.13.1. This worked prior to v5.1.0 when using the external types library (@types/pusher-js).

**Comment by leesio** [comment]
Hmm, thanks for pointing this out @jordanryanmoore I think I have an idea why this may be.

Have you managed to work round the issue in the meantime?

**Comment by jordanryanmoore** [comment]
The only successful “workaround” I found was to downgrade the package and revert to using the separate @types definitions package.

**Comment by leesio** [comment]
Could you possible confirm whether this behaviour is still the same in the new release? (v6.0.0)

It seems to work fine in a typescript node project I have here so would be a good bit of info to help debug.

**Comment by jordanryanmoore** [comment]
I’ll try to check in the next day or so.

**Comment by jordanryanmoore** [comment]
Unfortunately, I'm still seeing the same (broken) behavior with `6.0.0`, except that `PusherTypes` is now `[Function: PusherWithEncryption]`. `Pusher` is still `undefined`.

**Comment by jordanryanmoore** [comment]
Still a problem with 6.0.3…

**Comment by jordanryanmoore** [comment]
Eureka! It works if I enable the TypeScript `esModuleInterop` compiler option.

**Comment by whitecolor** [comment]
Have to use:
`
import { default as Pusher } from 'pusher-js'
`

**Comment by leesio** [comment]
@jordanryanmoore thanks a lot for letting me know. I'll close this issue now.
