### ISSUE TITLE
Encrypted

### ISSUE THREAD

**Issue by dima-bzz** [pusher/pusher-js#440]
When I set encrypted = true I have transport: ws. 
`Pusher :  : ["Connecting",{"transport":"ws","url":"wss://...`
If encrypted = false
`Pusher :  : ["Connecting",{"transport":"wss","url":"wss://`

Maybe wss_loop should be here?

https://github.com/pusher/pusher-js/blob/0d718adf06566766e0f544d74565d2ff3dcc0ff8/src/runtimes/web/default_strategy.ts#L170

**Comment by leesio** [comment]
Although the naming is a little confusing. I can assure you that the library uses `wss` when `encrypted`/`forceTLS` is set.

When `encrypted`/`forceTLS` are set, the only `ws_loop` is `wss`. When `encrypted`/`forceTLS` is *not* set the library will try to connect with `ws` and `wss`.

An easy way to check this is to open the network tab of your browser and check the protocol used in the connection to pusher. As you can see from this example from test.pusher.com -> the library uses `wss`

![Screenshot 2020-03-31 at 21 48 06](https://user-images.githubusercontent.com/7124883/78073831-83ffee80-7399-11ea-9d7e-6f3055b8b1ea.png)
