### ISSUE TITLE
Pusher not connecting when 2 different apps are open on the different tabs on the same browser

### ISSUE THREAD

**Issue by divee789** [pusher/pusher-js#441]
**Do you want to request a *feature* or report a *bug*?**
a bug

**What is the current behavior?**
pusher does not connect

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
1. Open a react app using pusher in 2 different tabs on chrome
2. Try to send a message from one app to the other
3. Only one connects to pusher at a time...(I think this is due to local storage). When pusherTransportTLS is deleted from local storage. the other app on the chrome browser then connects to pusher successfully

**What is the expected behavior?**
the 2 apps should connect at the same time 
**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**

**Comment by leesio** [comment]
This sounds like a very strange issue and it isn't something I've seen/heard of before.
I tried to recreate it by creating a react app with `create-react-app`

```
npx create-react-app test-react-app
cd test-react-app/
npm install --save pusher-js
```

Adding a pusher instance to `App.js`

```
Pusher.logToConsole = true;
const pusher = new Pusher($KEY, {...config...});
let channel = pusher.subscribe("test-channel");
channel.bind("test-event", data => {
  console.log(data);
});
```

Then starting the server with
```
npm run start
```

Then opening the app in 2 tabs and triggering some test messages.

You can see from the screengrabs each browser window and each tab in the window on the right maintained their connections and received all of the messages. Are you able to identify what's different between your application and this simple example?

![Screenshot 2020-04-29 at 13 37 09](https://user-images.githubusercontent.com/7124883/80596601-88faa100-8a1e-11ea-96de-b0bd871ad5ca.png)

![Screenshot 2020-04-29 at 13 33 10](https://user-images.githubusercontent.com/7124883/80596532-6ec0c300-8a1e-11ea-8978-53ec07da9e13.png)

**Comment by divee789** [comment]
Yeah.
The react app in question has a mock database with 2 users. So I was using pusher in a way that when user A does something that concerns user B or vice versa.. a notification is sent to the affected user

`const transfer_channel = pusher.subscribe('channel_name');
      if (user) {
        transfer_channel.bind(
          `${user._id}-transfer`,
          async (data) => {
            console.log('pusher working', data.notification_data);
            await dispatch(success(data.notification_data));
            await Request.makeNotifications({ ...data.notification_data, beneficiary: user.phone_number });
            await dispatch(new_notifications());
          },
          this,
        );
      }`

**Comment by leesio** [comment]
I'm still struggling to understand this issue

> You can see that in this case, the browser is trying to connect to 2 instances of pusher at the same time when both users do concurrent actions and they both need to be notified. Therein lies the problem, pusher can not connect to 2 instances from the same app on the same browser.

Why do you need 2 instances of pusher? It seems like this could be solved with multiple channels or event types? Maybe you could share a bit more of your js code?

**Comment by divee789** [comment]
Bless you, @leesio , I don't know how that bypassed me, it may actually have been the cause of the issue. But I moved to socket.io, so I wouldn't know. But a million thanks for the pointer. I appreciate it.

**Comment by davidkutas** [comment]
I have the same issue. Once I empty the localstorage things start to work.

**Comment by linecept** [comment]
I'm facing the same issue as above. 

Specifically, I open two tabs with the same page in a React application (> 16.8). Channel subscription is connected. I can update the value on the UI correctly with setState. Then, if I move to the other tab, and want to do the same thing. It is not working anymore. I move back to the previous tab, and even this one isn't working anymore. Although, I can console log all the changes and everything goes through, only the mapping to the UI not. What could be the issue?

I was wondering if I do not understand something regarding how to set the state in React, but I tried a number of ways and it seems to be OK.
