### ISSUE TITLE
“Existing subscription to channel” while only subscribing once

### ISSUE THREAD

**Issue by dirkbonhomme** [pusher/pusher-js#45]
As posted on http://stackoverflow.com/questions/17833502/existing-subscription-to-channel-while-only-subscribing-once

I have a small snippet that throws an "Existing subscription to channel" exception even though I only call the subscribe method once.

This can be avoided by moving the subscribe request outside of the "state_change" handler, but I'm wondering what might cause this? Maybe a bug in the Pusher library?

``` html
<!doctype html>
<html>
<body>
    <h1>Pusher subscribe testcase</h1>
    <p>Tip: check your console</p>
    <script src="https://d3dy5gmtp8yhk7.cloudfront.net/2.1/pusher.min.js"></script>
    <script>
        var pusher, channel;
        pusher = new Pusher('xxxxxxxxxxxxxxxxx');
        pusher.connection.bind('state_change', function(change){
            if(change.current === 'connected'){
                console.log('connected');
                channel = pusher.subscribe('test-channel');
                channel.bind('pusher:subscription_succeeded', function() {
                    console.log('subscribed');
                });
            }
        })
    </script>
</body>
</html>
```

This results in:

```
connected
subscribed
Pusher : Error : {"type":"WebSocketError","error":{"type":"PusherError","data":{"code":null,"message":"Existing subscription to channel test-channel"}}}
```

**Comment by mansishah278** [comment]
<img width="1059" alt="screen shot 2017-06-12 at 6 25 25 pm" src="https://user-images.githubusercontent.com/22022743/27034720-6b3e1684-4f9c-11e7-9527-e48306926858.png">
