### ISSUE TITLE
Error "Cannot find module 'tweetnacl'" with TypeScript compilation

### ISSUE THREAD

**Issue by yykamei** [pusher/pusher-js#451]
**Do you want to request a *feature* or report a *bug*?**

I want to report a bug when using it with TypeScript.

**What is the current behavior?**

I cannot build a module with pusher-js v6.0.0 on [this](https://github.com/yykamei/test-pusher-20200428) repository. The error message "Cannot find module 'tweetnacl'" will appear when using `tsc`.

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

Clone [this](https://github.com/yykamei/test-pusher-20200428) repository, and run `npm run tsc`. you can get the following output:

```

> test-pusher@0.1.0 tsc /tmp/test-pusher
> tsc

node_modules/pusher-js/types/src/core/config.d.ts:3:23 - error TS2307: Cannot find module 'tweetnacl'.

3 import * as nacl from 'tweetnacl';
                        ~~~~~~~~~~~

node_modules/pusher-js/types/src/core/options.d.ts:3:23 - error TS2307: Cannot find module 'tweetnacl'.

3 import * as nacl from 'tweetnacl';
                        ~~~~~~~~~~~


Found 2 errors.
```
**What is the expected behavior?**

The TypeScript compilation should succeed.

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**

* Pusher version: **6.0.0**
* Browser: **None** (This occurs at compilation)
* OS: Arch Linux
* The previous version **5.1.1** worked well

**Comment by leesio** [comment]
@yykamei thanks for highlighting this. I've been able to reproduce it.

**Comment by leesio** [comment]
I see the reason for this now and why I didn't see this in testing.

The new release added support for injecting the `tweetnacl` library we use for encrypted channels. We include tweetnacl in the bundle in _most_ places (except for in the default web/worker builds which omit it to keep the bundles small).

This change means the `tweetnacl` type is referenced in exported types. This is why the typescript compiler is suddenly complaining.

There are a few solutions to resolve this, I'm currently undecided which to go for:
- hide the `tweetnacl` dep in internal only types
- make `tweetnacl` a dependency (as opposed to just a dev dependency)
- force the compiler to treat `Options` as a different type when taking the `nacl` dep

I'm interested whether anybody has any preference between the above.

**Comment by yykamei** [comment]
> * make `tweetnacl` a dependency (as opposed to just a dev dependency)

I prefer the second suggestion because it's explicit what the library depends on.

**Comment by leesio** [comment]
I just pushed a new release v6.0.1. @yykamei I'd be interested to hear whether this solves your problem

**Comment by yykamei** [comment]
Thank you for your quick action! I confirmed our service worked well with the new release.
