### ISSUE TITLE
Why the major release bump?

### ISSUE THREAD

**Issue by npomfret** [pusher/pusher-js#452]
Are there release notes? What has changed from 5.x to 6?

**Comment by leesio** [comment]
Hi,
The major version bump was because we:
- removed support from encrypted channels in the default web/worker builds.
- made `forceTLS` the default

You can see details about the release here: https://github.com/pusher/pusher-js/releases/tag/v6.0.0

Does this answer your question?

**Comment by npomfret** [comment]
thanks
