### ISSUE TITLE
modifying the document object on android 3.2 prevents pusher object from connecting

### ISSUE THREAD

**Issue by jvanaert** [pusher/pusher-js#46]
Testpage which tries to connect to pusher. Works on all devices except on android 3.2 stock browser. (gets a unavaillable state change).

I think that the problem is the document object manipulation ? If you change the document.write to an alert, no problem at all.

I ran against this problem with our code dynamically injecting an audio tag in the document, this also broke the pusher connection.

```
<!DOCTYPE html>
<head>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
  <script src="http://js.pusher.com/2.1/pusher.min.js"></script>
  <script>
    (function($){
     Pusher.log = function(message){
      // This code fails on android 3.2 (GT-P6210) stock browser (gets a state change to unavailable)
      // If you change the document.write to an alert, the pusher object can connect without any problem
      document.write("pusher message " + message + "<br/>") 
     }
     var pusher = new Pusher('apikey');
     pusher.connection.bind('state_change', function(states){
      alert("Pusher State change " + states.current);
     })
    })(jQuery);
  </script>
</head>
<body>
  <h1>pusher and document manipulation on android 3.2</h1>
</body>
```

**Comment by hph** [comment]
@jvanaert I'm going to close this issue since it has been open for over two years without any new activity. If this is still a problem, please open a new issue and we'll take a look at it.
