### ISSUE TITLE
Typescript Error: Could not find a declaration file for module 'pusher-js/with-encryption'. TS7016

### ISSUE THREAD

**Issue by gitbugr** [pusher/pusher-js#460]
**Do you want to request a *feature* or report a *bug*?**
bug

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
1. create new typescript project.
2. npm install pusher-js
3. add 
```js
import Pusher from 'pusher-js/with-encryption';
```
to your project.

**What is the current behavior?**
'../node_modules/pusher-js/with-encryption/index.js' implicitly has an 'any' type.   Try `npm install @types/pusher-js` if it exists or add a new declaration (.d.ts) file containing `declare module 'pusher-js/with-encryption';`  TS7016

**What is the expected behavior?**
No error.

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
6.0.2

**Comment by leesio** [comment]
Thanks for highlighting this. I think you're right about this being a bug. I added declarations in 793cc37eab365879d32f03ea9786f1ca9642b0d6.

I wonder if you'd be able to confirm this solves your problem? You can install the package directly from the github branch with:
```
npm install git+ssh://git@github.com:pusher/pusher-js#type-decs-encryption
```

**Comment by gitbugr** [comment]
> I wonder if you'd be able to confirm this solves your problem? You can install the package directly from the github branch

Yep, that works! Thanks for the swift action!

**Comment by leesio** [comment]
@gitbugr I just pushed 6.0.3 which included this commit.

**Comment by leesio** [comment]
I'm going to close this issue as I assume it's now resolved. If this is not the case please feel free to open it again.
