### ISSUE TITLE
Can't connect to pusher custom host in react native

### ISSUE THREAD

**Issue by Davete0302** [pusher/pusher-js#466]
pusher version is 6.0.3.
Did I miss  something?  

     import Pusher from 'pusher-js/react-native';

     componentDidMount() {
         this.willFocusSubscription = this.props.navigation.addListener(
           'willFocus',
            () => {

            try {
                this.pusher = new Pusher('DOCKOTO_KEY', {
                        wsHost: 'test.dockoto.com',
                        wsPort: 6001,
                        enabledTransports: ['ws'],
                        disableStats: true,
                        forceTLS: false,
                    });
                Pusher.log = (msg) => {
                    console.log('Pusher message ' + msg);
                };
            } catch (error) {
                console.log('error', error)
            }

            this.group_channel = this.pusher.subscribe('groupchat.' + session_id);
            this.pusher.connection.bind('GroupMessageSent', (data) => {
                console.log('connected', data)
            });
            this.group_channel.bind('GroupMessageSent', (data) => {
                console.log('data', data)
            });

        })
      }
![image](https://user-images.githubusercontent.com/52650624/84227030-f3baf400-ab15-11ea-96c2-4862b9368ef6.png)

**Comment by leesio** [comment]
That _should_ work. It looks from your logs that it tries to connect with the `wsPort` and `wsHost` you've configured, fails, then falls back to the defaults. Is that accurate?
Are you seeing any connection on your pusher server.

**Comment by leesio** [comment]
I'm going to close this issue. Feel free to reopen it if you're able to provide more information
