### ISSUE TITLE
[React Native] Pusher going to the failed status after second time going offline

### ISSUE THREAD

**Issue by dmitrybirin** [pusher/pusher-js#467]
**Do you want to request a *feature* or report a *bug*?**
Looks like a bug. Or I don't understand the options of enabledTransports.
**What is the current behavior?**

**Current behavior**
1. Use `enabledTransports: ['ws', 'wss']`, cause why not, seems logical
2. Connect to the pusher and check everything is fine
3. Go to airplane mode
4. Pusher recovering
5. Go to airplane mode again
6. Pusher going to the status `failed` and never recovering.

Repro (too much code for that example, but it works if you have Pusher key):
https://snack.expo.io/@dmitrybirin/70d96d

**Expected behavior**
Pusher recovering everytime
or 
There is note in the documentation, that the `enabled transports` options could lead to not recovering from disconnection

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
Platforms: iOS and Android
React Native 0.62.2
Pusher-js 6.0.3

It's not a big of a problem itself, but really confusing and maybe could be indicator of other problems.

**Comment by leesio** [comment]
This is very odd. It definitely isn't the expected behaviour. I'll have a look into this today.

**Comment by kasperwandahl** [comment]
@leesio I'm not related to Dmitry, but I am currently debugging an issue that sounds very much like this.

**Comment by kasperwandahl** [comment]
Possibly related: https://support.pusher.com/hc/en-us/articles/360019096474-What-is-meant-by-Channels-error-1006-
> When pusher-js detects that two WebSocket connections failed after less than a few minutes, it decides to disable WebSocket-based transports (including Flash) and fall back to HTTP. This way clients won't waste any more time trying to use a broken transport.

**Comment by leesio** [comment]
I had a quick look at this was able to reproduce the issue. It is related to what you've described @kasperwandahl.

Different transports are given a number of "lives". If a connection closes uncleanly within the `activityTimeout` (default 2 minutes) a "life" is removed. When the transport runs out of "lives" it's considered unsupported.

By default the ws manager has 2 lives, so I suspect each time you close the connection uncleanly by cutting the network you take a life from the transport.

You should be able to confirm whether this is the issue you're seeing by waiting for the connection to be active for at least 2 minutes (or whatever you have `activityTimeout` set to, if you're providing a value).

If you're able to confirm that this is indeed you're problem, I can start thinking about implementing a solution that works for you. It does seem strange to me that transports don't "get a life back" after a connection succeeds and lasts longer than `activityTimeout`. I think implementing that would be reasonable.

**Comment by leesio** [comment]
Any update on this @dmitrybirin ?

**Comment by dmitrybirin** [comment]
Hey @leesio! 👋  Sorry, missed the question.
I've reproduced the same behaviour above with more than 2 minutes wait in the connected state. So, looks like, some transports missed life)

**Comment by dmitrybirin** [comment]
👋  Hello! @leesio JFYI: It's still reproducible in the last v7.0.0.
Sometimes it's even handy, cause when I want to test cases when pusher is failing:), I just put enabledTransports there and going offline couple of times. 
But it's still weird as fudge.

**Comment by dmitrybirin** [comment]
I'm generally wondering, is it possible and could it be some aid, to set the lives of the connections or have reconnect accessible publicly from the API? Cause in React Native world, shitty network and background states could bring pusher to failed state pretty easy, we're currently trying recreating the client couple of times to get through it. I can create separate issue for that, if it'll be helpful.

**Comment by leesio** [comment]
Hey @dmitrybirin,
I agree it might be useful to be able for the library user to configure these types of things. I suspect it would be quite tricky to design an API to express these options that wasn't very complex though.

I think for this specific issue my preference is to reset the failed connection count once a connection succeeds.

**Comment by dmitrybirin** [comment]
thanks for the answer @leesio 
Could it be done outside the library (is there some API) 
or should it be done inside, I can probably help with PR then.

**Comment by leesio** [comment]
I don't believe it could be done outside the library. The problem is that the transport manager keeps track of the number of "lives" it has remaining.

Each time the connection fails, this number is decremented:

https://github.com/pusher/pusher-js/blob/c42937380cf5705dcdaa4198f336a17083d278c6/src/core/transports/assistant_to_the_transport_manager.ts#L76-L78

https://github.com/pusher/pusher-js/blob/c42937380cf5705dcdaa4198f336a17083d278c6/src/core/transports/transport_manager.ts#L49-L51

This life count is used to determine whether or not a transport is supported

https://github.com/pusher/pusher-js/blob/c42937380cf5705dcdaa4198f336a17083d278c6/src/core/transports/assistant_to_the_transport_manager.ts#L101-L103

I think the think we need to increment this counter when a connection succeeds!

**Comment by dmitrybirin** [comment]
Thanks for the work! 🙇  It would be nice if we just put the default number of lives after reconnection, but depends of all the different situations, of course. Made some comments to the PR.
