### ISSUE TITLE
1006 Error, 4201 Error: a lot of errors in a bug tracker for the last few months

### ISSUE THREAD

**Issue by max-zu** [pusher/pusher-js#470]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
We constantly caught thousands of errors with status codes `4201` and `1006`. We started to observe them a few months ago after one of the updates.
![image](https://user-images.githubusercontent.com/22217379/84388758-c5b0df00-abfd-11ea-8ea9-e9ed99ab88b0.png)
it looks like `4201` error is being thrown  when app goes from `background` to `active` state.

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

**What is the expected behavior?**

**Which versions of Pusher, and which browsers / OS are affected by this issue?
```
    "pusher-js": "^6.0.3",
    "react-native": "0.62.2",
```

Did this work in previous versions of Pusher? If so, which?**
```
    "pusher-js": "5.0.1",
    "react-native": "0.61.2",
```

**Comment by max-zu** [comment]
#467 might be related

**Comment by leesio** [comment]
@max-zu what makes you think this may be related to #467? I'm not sure anything significant changed in that part of the code base between versions 5 and 6. 🤔

**Comment by leesio** [comment]
@max-zu are you still seeing these errors with the same frequency? Are you able to share when exactly you started receiving the errors?

I'm interesting to understand whether this is an issue with the library or the pusher channels api

**Comment by leesio** [comment]
I'm going to close this issue as it seems to have gone stale. Please feel free to reopen if you're still experiencing problems

**Comment by max-zu** [comment]
Hi. Sorry. I missed notifications.
> @max-zu what makes you think this may be related to #467?

this might be related because we experience almost the same behavior.
steps to reproduce looks like  : 
1. open an app
2. create Pusher connection
3. send few messages to device via Pusher 
4. send app to the `background` state
5. open app
6. send few messages to device again
7. error with `1006` code is being thrown
