### ISSUE TITLE
Request: ability to set xmlHttpRequest.withCredentials

### ISSUE THREAD

**Issue by jeffstephens** [pusher/pusher-js#471]
**Do you want to request a *feature* or report a *bug*?**
*Feature*

**What is the current behavior?**
`xmlHttpRequest.withCredentials` takes on the default value (`false`) and I can't use Pusher auth calls to set cookies.

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

Example code:
```typescript
const pusher = new Pusher(REACT_APP_PUSHER_KEY, {
  cluster: REACT_APP_PUSHER_CLUSTER,
  authEndpoint: `${REACT_APP_BACKEND_HOST}/pusher/auth/web`,
  auth: {
    headers: {},
    params: {
        // [irrelevant]
    },
  },
});

pusher.connect();
```

`REACT_APP_BACKEND_HOST` is potentially on a different origin. When the backend sends
```
Set-Cookie: connect.sid=s%3AKjPBOeBYzc705H7vq4qnkSXPHV2zF1qi.x7N8w9e2sCc0Z2hQHeWaBy9b73M04gI0qi0WkY%2F%2BbYc; Path=/; Expires=Tue, 22 Sep 2020 03:11:57 GMT; HttpOnly
```

The cookie is not persisted in the browser.

**What is the expected behavior?**
Expose the internal `xmlHttpRequest` config so I can set `withCredentials = true`. I'm using this in the Web runtime.

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
This hasn't been an option in the past to my knowledge. I'm using Pusher JS `6.0.3`.

I've seen the workarounds suggested in https://github.com/pusher/pusher-js/issues/62, but I'd rather not have to keep up with private API changes and I think this is a widely applicable use case! 🙂

Thank you so much!

**Comment by leesio** [comment]
I agree that this is a common case we should probably think about supporting. I'm wondering whether it would be easier to just an an `includeCredentials` option to the `auth` object rather than exposing the `xmlHttpRequest` instance.

```
const pusher = new Pusher(REACT_APP_PUSHER_KEY, {
  cluster: REACT_APP_PUSHER_CLUSTER,
  authEndpoint: `${REACT_APP_BACKEND_HOST}/pusher/auth/web`,
  auth: {
    headers: {},
    includeCredentials: true,
    params: {
        // [irrelevant]
    },
  },
});
```

Would you want to do anything else with the `xmlHttpRequest` object aside from set `withCredentials` to `true`?

If so, we could maybe consider adding a way for the user of the library to pass in a `function` which returned an `xmlHttpRequest` instance.

**Comment by jeffstephens** [comment]
@leesio I think that makes perfect sense. `withCredentials` is all I need and it might make it easier with your cross-platform solutions!

We can kind of already supply our own which is what I'm doing for now:
```javascript
Pusher.Runtime.createXHR = function () {
  var xhr = new XMLHttpRequest();
  xhr.withCredentials = true;
  return xhr;
};
```

But a first-class option would be great. Thank you!

**Comment by wardhache** [comment]
+1

**Comment by polgiron** [comment]
Hello, we were using @jeffstephens solution until now and it was working great. But now I have moved the pusher logic inside a shared worker and this solution no longer works as document is not defined in a service worker. Therefore document.cookie (used for the xhr authenticated request) is not defined.

I have tried multiple things, passing the cookie to the worker, and setting the header manually:

```
Pusher.Runtime.createXHR = () => {
  const xhr = new XMLHttpRequest();
  xhr.withCredentials = true;
  xhr.setRequestHeader('Cookie', cookie);
  return xhr;
};
```

or setting the cookie inside pusher options:

```
pusher = new Pusher(appKey, {
  cluster: 'younow',
  authEndpoint: authEndpoint,
  auth: {
    headers: {
      'Cookie': cookie
    }
  }
});
```

But none of these solutions are working, the header is not set.

Anyone would have a solution please?

**Comment by leesio** [comment]
@polgiron, the worker build of the library uses the `fetch` API for auth, it doesn't use the `XMLHttpRequest` API since it isn't available in service-worker contexts.

This is why overwriting `Pusher.Runtime.createXHR` doesn't work in a shared-worker. 

By default the `fetch` based authorized has the `credentials` option set to `"same-origin"`, are you auth server and your website on the same origin?

**Comment by polgiron** [comment]
@leesio thanks for your answer, our auth server is on another subdomain of our website so I'm guessing it's not the same origin?
Is there a way for us to add the cookie to the `fetch` request made by pusher in the worker? Similar to what we used to do with the `XMLHttpRequest` request.

**Comment by leesio** [comment]
Unfortunately there's not a _nice_ way to do this at the moment. There is a way though: you can provider an [authorizer function](https://github.com/pusher/pusher-js#authorizer-function) when you instantiate pusher-js.

If you provide a custom authorizer, the library will call out to it each time it needs to perform an auth request and you get complete control over the request that's made to your auth server.

**Comment by polgiron** [comment]
So I have tried to use the custom authorizer function and I'm still facing the same "cookie" problem.

As `document` is not accessible from the shared worker `document.cookie` is not either, and therefore the cookie cannot be added automatically during the fetch request. I have tried to add the cookie header manually but from my testing something is removing the header each time. If I set the header to another name than `Cookie` (for example `Authorization`) then the header is not removed and added properly to the request. Unfortunately my backend engineers are telling me that this header needs to be called `Cookie` as it's handled automatically by their PHP logic.

As you can see in the commented fetch options, I have also tried to pass `mode: 'no-cors'` and `credentials: 'include'`. I have also tried to define a global variable named `document` and assigned the cookie to `document.cookie`, without luck either.

```
const authorizer = (channel, options) => {
  return {
    authorize: (socketId, callback) => {
      const data = new URLSearchParams();
      data.append('socket_id', socketId);
      data.append('channel_name', channel.name);

      fetch(authEndpoint, {
          method: 'POST',
          // mode: 'no-cors',
          // credentials: 'include',
          headers: new Headers({
            'Cookie': cookie
          }),
          body: data
        })
        .then(res => {
          if (!res.ok) {
            throw new Error(`Received ${res.statusCode} from ${authEndpoint}`);
          }
          return res.json();
        })
        .then(data => {
          callback(null, data);
        })
        .catch(err => {
          callback(new Error(`Error calling auth endpoint: ${err}`), {
            auth: ''
          });
        });
    }
  };
};

pusher = new Pusher(appKey, {
  cluster: 'xxx',
  authorizer: authorizer
});
```

Have you ever faced a similar problem?

**Comment by leesio** [comment]
@polgiron I don't think it's possible to *manually* set the  `Cookie` header as you're doing in your snippet, I think the browser removes/overwrites any header you include there. `fetch` requests from inside a shared worker should include `Cookies` though, as long as the `fetch` request and the auth server are configured correctly.

I managed to get something working which I believes mirrors your configuration. As I understand it, your app is set up as follows:

- Your web application is served from a subdomain (`web-server.example.com`)
- Your channels auth server is on a different subdomain (`pusher-auth-server.example.com`)
- Your channels client is instantiated in a shared worker

**Authorizer**

Your authorizer looks basically correct, but you need to set the `credentials` setting to `include`.

```
const authorizer = (channel, options) => {
  return {
    authorize: (socketId, callback) => {
      const data = new URLSearchParams();
      data.append('socket_id', socketId);
      data.append('channel_name', channel.name);

      fetch(authEndpoint, {
          method: 'POST',
          credentials: 'include',
          headers: new Headers({
              "Content-Type": "application/x-www-form-urlencoded" },
          }),
          body: data
        })
        .then(res => {
          if (!res.ok) {
            throw new Error(`Received ${res.statusCode} from ${authEndpoint}`);
          }
          return res.json();
        })
        .then(data => {
          callback(null, data);
        })
        .catch(err => {
          callback(new Error(`Error calling auth endpoint: ${err}`), {
            auth: ''
          });
        });
    }
  };
};

pusher = new Pusher(appKey, {
  cluster: 'xxx',
  authorizer: authorizer
});
```

**Auth Server**

You'll need to make sure your auth server is setting the following headers on responses to auth requests:

- `"Access-Control-Allow-Origin: $WEB_APP_ORIGIN"` (that's the origin of your web app, not the literal string `$WEB_APP_ORIGIN`)
- `"Access-Control-Allow-Credentials: true"`

**Cookie**

The `domain` of the cookie will need to be generic enough to cover both origins. In the example with web-server and auth server at `web-server.example.com` and `pusher-auth-server.example.com` respectively, this would be `.example.com`

If it would help, I can tidy up the example I used and create a repo, just let me know.

**Comment by polgiron** [comment]
@leesio we have managed to do a fetch authenticated request from the service worker, as you were saying it is not possible to add the cookie manually to the fetch request, but it is possible de pass it to the service worker file when you create it (that was what we were missing), you need to do:

`new SharedWorker('worker.js', {
      credentials: 'include'
    });`

And of course also set `credentials: 'include'` to the fetch request.

Thank you very much for your help.

**Comment by leesio** [comment]
Ahh, strange. In my example I didn't include that `options` object when instantiating the worker but my example still worked.

Thanks for the update.

**Comment by FadhiliNjagi** [comment]
For people using typescript + Axios like me, use this:

```
import Pusher, { Channel, ChannelAuthorizationCallback, Options } from 'pusher-js'
import axios from 'axios'

const authorizer = (channel: Channel, options: Options) => {
  return {
    authorize: (socketId: string, callback: ChannelAuthorizationCallback) => {
      axios({
        method: 'GET',
        url: options.authEndpoint,
        params: {
          channel_name: channel.name,
          socket_id: socketId
        },
        withCredentials: true
      })
        .then((response) => {
          callback(null, response.data)
        })
        .catch((error) => {
          callback(new Error(`Error authenticating with server: ${error}`), {
            auth: ''
          })
        })
    }
  }
}
```
I hope it saves someone the trouble of googling all those types :)

**Comment by hayata-suenaga** [comment]
Is `authorizer` function only for channel authorization endpoint? How about user authentication endpoint?
