### ISSUE TITLE
Cannot bind to `subscription_succeeded` event on a public channel

### ISSUE THREAD

**Issue by apasov** [pusher/pusher-js#474]
In the docs it is said that 
>>You can bind to the following `pusher:` events on a public channel:
>>    `pusher:subscription_succeeded`

https://pusher.com/docs/channels/using_channels/public-channels

But I can't bind to this event.

I'm using pusher-js 6.0.3 with Laravel Echo in the client and [Laravel Websockets](https://beyondco.de/docs/laravel-websockets/basic-usage/pusher) on the server.

```js
const channel = window.Echo.channel('update')
channel.pusher.bind_global((eventName, data) => {
  console.log(`The event ${eventName} was triggered with data ${JSON.stringify(data)}`)
})
channel.pusher.bind('pusher:subscription_succeeded', (data) => {
  console.log('subscription_succeeded => ', data)
})
channel.pusher.bind('pusher:pong', (data) => {
  console.log('pong => ', data)
})
```

I can see the `subscription_succeeded` event in the message log:

![image](https://user-images.githubusercontent.com/28765662/86352326-eb159380-bc65-11ea-8bdd-5012e906022b.png)

But not in the console output:

![image](https://user-images.githubusercontent.com/28765662/86352481-257f3080-bc66-11ea-8900-f7eb0e790df3.png)

Only `pong` event works, both with `bind_blobal` and `bind`

Is this a bug or am I doing something wrong?

**Comment by leesio** [comment]
I think the problem here is that you're trying to bind to the `pusher:subscription_succeeded` event on the `pusher` instance rather than the `channel` instance.

Maybe try this?

```
const channel = window.Echo.channel('update')

// access the pusher channel using the channel method
// https://github.com/pusher/pusher-js#accessing-channels
channel.pusher.channel('update').bind('pusher:subscription_succeeded', (data) => {
  console.log('subscription_succeeded => ', data)
})
```

**Comment by apasov** [comment]
@leesio Yes, it works. Thank you!
