### ISSUE TITLE
Auth info required to subscribe to private-events : WebSocketError

### ISSUE THREAD

**Issue by tkskumar** [pusher/pusher-js#478]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
I am getting error and getting out of connection saying  `Auth info required to subscribe to private-events` not sure what i am missing as i have authz api endpoint getting auth token from pusher and the setting it in proper way, Earlier i was able to connect to this private channel 
- Getting now 
scripts.987b46925560e1102d80.js:8 Pusher :  : [{"type":"WebSocketError","error":{"type":"PusherError","data":{"code":null,"message":"Auth info required to subscribe to private-events"}}}]

 Note - `Enable authorized connections is enabled in app settings`

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
My code looks like this: Client-side 
```
@Injectable({
  providedIn: 'root'
})
export class PusherService {
  pusher: any;
  channel: any;
  public pusherConfig: PusherConfig;
  constructor() {
    this.pusherConfig = environment.pusher;
    this.pusher = new Pusher(this.pusherConfig.key, {
      cluster: this.pusherConfig.cluster,
      encrypted: this.pusherConfig.pusherAppSecure,
      auth: {
        preAuth: {}
      },
      // set the transport to use our custom authorizer
      authTransport: 'preAuthenticated',
    });
  }
  public async load(token: string): Promise<Response> {
    const options = {
      method: 'GET',
      headers: new Headers({ 'content-type': 'application/json', authorization: `Bearer ${token}` })
    };
    const { socket_id } = this.pusher.connection;
    return fetch(`${this.pusherConfig.authEndpoint}/${socket_id}`, options)
      .then(r => r.json())
      .then(({ auth }) => {
        // used by the authoriser later
        const channelName = 'private-events';
        console.log(auth, channelName);
        this.pusher.config.auth.preAuth[channelName] = auth;
        // calls the autoriser
        return this.pusher.subscribe(channelName);
      }).catch(err => {
        console.log(err);
      });
  }
}
```
Server Side 

```
var express = require('express');
var bodyParser = require('body-parser');
var cors = require('cors');
var Pusher = require('pusher');

var pusher = new Pusher(`required config object`);

setInterval(() => {
  pusher.trigger('private-events','test', {}, () => {
    console.log('processed');
  })
},2000 )


var app = express();
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(cors());

app.get('/pusher/auth/:socketid', function(req, res) {
  var socketId = req.params.socketid;
  var auth = pusher.authenticate(socketId, 'private-events');
  console.log(auth)
  res.status(200).json(auth);
});

var port = process.env.PORT || 5000;
app.listen(port);
```
**What is the expected behavior?**
I should be able to connect to a private channel as I am doing authorization in an expected way 

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**

  `"pusher": "^3.0.1"`

**Comment by leesio** [comment]
Hi @tkskumar , I'm not aware of anything changing on the channels API side that would cause this issue. Are you able to check whether the subscription messages sent to channels contain an auth string?

You should be able to do that by looking at the websocket frames in chrome/firefox developer tools.

![Screenshot 2020-07-13 at 10 59 11](https://user-images.githubusercontent.com/7124883/87291874-e7043400-c4f7-11ea-905c-ad2d5e87f89a.png)

**Comment by tkskumar** [comment]
yes this is fixed now I was missing auth string in subscription payload
