### ISSUE TITLE
Is chatkit sill avaliable?

### ISSUE THREAD

**Issue by HomyeeKing** [pusher/pusher-js#479]
I look up the docs and there're two parts: CHANNELS & BEAMS ， I don't find CHATKIT, so  the CHATKIT changed to CHANNELS?

**Comment by leesio** [comment]
Hi there,

Unforunately Chatkit was discontinued back in March to allow us to focus on Channels. You can find more information about that decision in [this blog post](https://blog.pusher.com/narrowing-our-product-focus/) from the time.

Lots of people are still using Channels to build chat products though, you can find more info about that [here](https://blog.pusher.com/building-chat-applications-with-pusher-channels/).

**Comment by HomyeeKing** [comment]
> Hi there,
> 
> Unforunately Chatkit was discontinued back in March to allow us to focus on Channels. You can find more information about that decision in [this blog post](https://blog.pusher.com/narrowing-our-product-focus/) from the time.
> 
> Lots of people are still using Channels to build chat products though, you can find more info about that [here](https://blog.pusher.com/building-chat-applications-with-pusher-channels/).

OK , just find a tutorial about Web Chat which used CHATKIT , nothing big deal, I am going to  explore the CHANNEL DOCs anyway

**Comment by leesio** [comment]
Would you mind sharing the tutorial you found? It would be good to highlight that chatkit is no longer available.

**Comment by HomyeeKing** [comment]
> Would you mind sharing the tutorial you found, @HomyeeKing? It would be good to highlight that chatkit is no longer available.

[](https://www.sitepoint.com/pusher-vue-real-time-chat-app/)

**Comment by HomyeeKing** [comment]
> Would you mind sharing the tutorial you found, @HomyeeKing? It would be good to highlight that chatkit is no longer available.

[https://www.sitepoint.com/pusher-vue-real-time-chat-app/](url)
