### ISSUE TITLE
How to bind?

### ISSUE THREAD

**Issue by corysimmons** [pusher/pusher-js#480]
```js
const channel = pusher.subscribe('presence-xyz')

channel.bind('pusher:subscription_succeeded', () => {
    channel.bind('client-foo', data => console.log(777, { data })) // never happens

    setTimeout(() => {
        channel.trigger('client-foo', { someData: 123 }) // happens
    }, 2000)
})
```

What am I doing wrong?

**Comment by corysimmons** [comment]
Never mind, presence channels don't let you bind custom events. They exclusively have a few events on them as defined here: https://pusher.com/docs/channels/using_channels/presence-channels#events

**Comment by leesio** [comment]
Hey @corysimmons, I just noticed this before you closed it. You can actually bind custom events to presence channels.

I think you're getting tripped up by the fact that client events are *not* delivered to the socket that sent them ([see here](https://pusher.com/docs/channels/using_channels/events#message-routing))

**Comment by corysimmons** [comment]
Ah okay thank you @leesio
