### ISSUE TITLE
got undefined error on pusher:subscription_error event.

### ISSUE THREAD

**Issue by chenghung** [pusher/pusher-js#485]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

got undefined error on pusher:subscription_error event.

```
pusher:subscription_error { type: 'AuthError', error: undefined } undefined
```

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

```
const pusher = new Pusher(env.PUSHER_APP_KEY, {
  cluster: env.PUSHER_APP_CLUSTER,
  authEndpoint: 'https://my-server/channels/auth',
  auth: {
    headers: {
      'Authorization': 'Bearer token',
    },
  },
});

  const channelName = 'presence-agents';
  const channel = await pusher.subscribe(channelName);
  console.log('subscribed channel', channelName);

  channel.bind('pusher:subscription_error', (error, data) => {
    console.error('pusher:subscription_error', error, data);
  });
```

**What is the expected behavior?**

the error param should not be undefined.

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**

pusher-js: 7.0.0
node: v12.16.0

**Comment by leesio** [comment]
Thanks for raising this @chenghung. Are you able to look at the network tab in your browser's developer tools to analyse the response from your auth endpoint?
I'm interested to see what's causing this empty error.

**Comment by chenghung** [comment]
@leesio thanks for reply,

I'm using pusher-js package in a node environment so there is no browser network data to show.

you can reproduce this issue by calling channel auth API that response invalid data.

for example:

```
POST /api/channels/auth

response status 200 with empty json response body
{ }
```

then pusher-js will emit a "pusher:subscription_error" event with undefined error.

**Comment by Nickbahson** [comment]
I have the same issue, on chrome and firefox.
Tried upgrading to pusher-js 7.03 from 7.02, but still the same.
No error on PHP backend after,
`
/** @var \Pusher\Pusher $pusherInstance */

$pusherInstance->presence_auth($channelName, $socketId, $user_id);
`

![pusher_presence_error](https://user-images.githubusercontent.com/22325357/130019598-96f722ca-41f8-405a-8d72-fc2057bafa5a.PNG)

**Comment by melvin78** [comment]
same problem here even after downgrading still shows undefined
![ih](https://user-images.githubusercontent.com/67906796/146723759-5365d55d-7939-4c41-8364-061929d64095.PNG)

**Comment by jeremiahlachica** [comment]
I get this too when using custom authorizer:
`error: {type: "AuthError", error: undefined}`

Were you able to resolve the issue?

**Comment by Nickbahson** [comment]
I guess the other option is to handle active (persistent) sessions from within your application, to compliment the pusher api for this issue [https://github.com/pusher/pusher-js/issues/485](https://github.com/pusher/pusher-js/issues/485)
