### ISSUE TITLE
Two tabs, same page in a React application, subscription to UI values cannot be mapped to UI

### ISSUE THREAD

**Issue by linecept** [pusher/pusher-js#487]
Specifically, I open two tabs with the same page in a React application (> 16.8). Channel subscription is connected. I can update the value on the UI correctly with setState. Then, if I move to the other tab, and want to do the same thing. It is not working anymore. I move back to the previous tab, and even this one isn't working anymore. Although, I can console log all the changes and everything goes through, only the mapping to the UI not. What could be the issue?

I was wondering if I do not understand something regarding how to set the state in React, but I tried a number of ways and it seems to be OK, but the state change still does not cause render to the UI.

Do you have any ideas what might be the issue or where I could see some React(> 16.8) implementations to try on my code?

**Comment by ben-pusher** [comment]
It seems as though your Pusher Channels implementation is correct as you are sending and receiving data correctly - the issue appears to lie with how you consume the data and present the changes to your user. Have you been able to resolve this? 
Can you confirm that this understanding is correct?

**Comment by linecept** [comment]
> It seems as though your Pusher Channels implementation is correct as you are sending and receiving data correctly - the issue appears to lie with how you consume the data and present the changes to your user. Have you been able to resolve this?

No, still not, I was unable to solve it.

> Can you confirm that this understanding is correct?

Yes, your understanding is correct.

**Comment by leesio** [comment]
From your description, it sounds like this isn't really an issue with this library, so I'm going to close this issue.

If you're still struggling with your integration it's best to head to [pusher support](https://support.pusher.com/hc/en-us) and raise an issue there.
