### ISSUE TITLE
Integration for Quasar [vue.js] 

### ISSUE THREAD

**Issue by realtebo** [pusher/pusher-js#490]
**Do you want to request a *feature* or report a *bug*?**

Feature / Request for Documentation

**What is the current behavior?**

n/a

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

n/a

**What is the expected behavior?**

I'd like to have documentation on how to integrate pusher with ios and android hybrid app made with Quasar, the actual top  [for me] framework to make hybrid app using vue.js

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**

n/a

**Comment by leesio** [comment]
Thanks for this request. 

I'm going to raise this with the relevant team.

Since this is not really an issue with pusher-js, I'm going to close this issue.
