### ISSUE TITLE
Connections blocked by uBlock Origin

### ISSUE THREAD

**Issue by shash7** [pusher/pusher-js#495]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
Pusherjs connections are blocked by uBlock Origin

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
Not sure if its a bug on pusherjs's side. However I would urge you to work this out with the ublock team.

**What is the expected behavior?**
Pusher connections worked fine before. Recently, I'm seeing failed connections due to ublock blocking pusher websocket connections.
Here's the ruleset which is probably causing this:
https://easylist.to/easylist/easyprivacy.txt

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Its affecting the latest js library.

**Comment by EntropyAu** [comment]
Second this - would be great if this could be worked out with UBlock / EasyList teams - 
This appears related to a change in easylist/easyprivacy https://github.com/easylist/easylist/issues/6097

**Comment by ben-pusher** [comment]
We are working on identifying what can be done to prevent the domain being included in the list.

**Comment by ben-pusher** [comment]
The listing at EasyList has been updated to block pusher.min.js instead of a blanket ban on the entire domain. If you have installed the lib using Yarn/NPM (https://github.com/pusher/pusher-js#web) rather than the CDN then you should see some success. You can also self host the js file to work around this, see https://github.com/pusher/pusher-js#self-serving-js-files for instructions.

**Comment by shash7** [comment]
Its working now. For posteriority's sake, use the 'state_change' event to diagnose connection errors client side and update your ui appropriately.

**Comment by ben-pusher** [comment]
Worth noting that this is still causing a problem for clients who are not using one of the two workarounds mentioned 

> The listing at EasyList has been updated to block pusher.min.js instead of a blanket ban on the entire domain. If you have installed the lib using Yarn/NPM (https://github.com/pusher/pusher-js#web) rather than the CDN then you should see some success. You can also self host the js file to work around this, see https://github.com/pusher/pusher-js#self-serving-js-files for instructions.

**Comment by ben-pusher** [comment]
For anyone still tracking this, EasyList have now removed the block entirely and so this should no longer be an issue.
