### ISSUE TITLE
TypeScript compilation issue

### ISSUE THREAD

**Issue by doug-shontz** [pusher/pusher-js#496]
**Do you want to request a *feature* or report a *bug*?**

A bug

**What is the current behavior?**

Using TypeScript 4.x and using pusher-js 7.0.0...TypeScript complains and fails to compile.

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

The problem appears to be in https://github.com/pusher/pusher-js/blob/master/types/src/runtimes/interface.d.ts.  This interface on line 36 references a type of "Document" which is not imported for that file, causing TS to complain that the type Document does not exist.

**What is the expected behavior?**

Compilation would succeed.

**Which versions of Pusher, and which browsers / OS are affected by this issue?

I would assume all in this case since the typing definitions are incorrect.  Should not be a problem if you are not using TS.

Did this work in previous versions of Pusher? If so, which?**

I had to take this back to the 5.x line with the @types/pusher-js loaded in devDependencies for this to not be an issue.

**Comment by stof** [comment]
This type comes from the DOM: https://github.com/pusher/pusher-js/blob/9152c97631d08d428d36ded807b8c81ef7c008d3/tsconfig.json#L19

**Comment by doug-shontz** [comment]
Wow!  Total bad day at the office to miss something that dumb on my part.  My apologies for any wasted time.
