### ISSUE TITLE
nitpick:

### ISSUE THREAD

**Issue by jessica02200** [pusher/pusher-js#498]
nitpick: 
`$DownloadUrl= (Invoke-RestMethod -Uri "https://api.github.com/repos/cli/cli/releases/latest").assets.browser_download_url -match "windows_amd64.msi"`

_Originally posted by @al-cheb in https://github.com/actions/virtual-environments/pull/1767#discussion_r501642866_

**Comment by leesio** [comment]
I don't understand this issue, it seems unrelated to pusher-js. If you can provide more information/explain it, please feel free to reopen.

Thanks
