### ISSUE TITLE
Status code of errors from a custom authorizer callback is not passed to pusher:subscription_error handler

### ISSUE THREAD

**Issue by akovalev** [pusher/pusher-js#501]
Since [Pusher 7.0.0 release][1], the data passed to a handler of `pusher:subscription_error` event doesnt' have a `status` property if an error was generated by a custom authorizer function. It happens because an object that is passed to `pusher:subscription_error` event handler contains information about error status [only provided that an error is an instance of `HTTPAuthError`][2], a class that is not exposed publicly via Pusher SDK and therefore cannot be instantiated by a custom authorizer function.

At the moment we found a workaround to this problem by passing an actual error data as `message` property since [the latter is passed to an subscription error handler][3], but ideally we expect error status code to be extracted for all errors, not only those that are generated by the built-in authorizer function.

[1]: https://github.com/pusher/pusher-js/blob/master/CHANGELOG.md#700-2020-07-30
[2]: https://github.com/pusher/pusher-js/blob/8dc4a9106313f930bb41e2d5426df69cb2c6b331/src/core/channels/channel.ts#L117
[3]: https://github.com/pusher/pusher-js/blob/8dc4a9106313f930bb41e2d5426df69cb2c6b331/src/core/channels/channel.ts#L115

**Comment by leesio** [comment]
Thanks for raising this @akovalev, I can see this would be really annoying.

I'm not sure why the `HTTPAuthError` class isn't exposed to library consumers. Can you confirm whether exposing the `HTTPAuthError` for use in custom authorizers would solve your problem?

**Comment by akovalev** [comment]
@leesio it could be an option of course, but as I've said we are using a custom authorizer function and that is why in my opinion it would be nice to keep the implementation of that custom auth function fully agnostic of Pusher's internal implementation details so that any error that is passed to `AuthCallback` function is merely used as a payload for `pusher:subscription_error` event. I believe it's a valid approach since in case of a custom auth function consumers of `pusher:subscription_error` expect to get access to errors that were thrown by their auth function.

This is just an idea, as I'm probably not aware of all implication of the approach I proposed.

**Comment by leesio** [comment]
@akovalev I agree that this sounds like a reasonable approach. I'll add this to our todo list for the library.

Thanks for the suggestion
