### ISSUE TITLE
Pusher-js does not work with dynamic channel name

### ISSUE THREAD

**Issue by Msangi21** [pusher/pusher-js#502]
Hello team.
I'm using pusher-js 7.0.0. The problem which I face is when I hard the channel name it works but when I get it from the user selection id does not work. 

`mounted() {
    this.fetchAllData()
    let self = this
    let channel = this.$pusher.subscribe(`${this.channel}`)
    channel.bind('new-order',function(order) {
      self.restaurant_order.data.unshift(order.order)
      const audio = document.getElementById('notificationBeep');
      audio.play()
    });
  }`
The above one does not work but the bellow one it works fine

`mounted() {
    this.fetchAllData()
    let self = this
    let channel = this.$pusher.subscribe('rot-7255c841-5159-449c-a572-afa333f90025-2')
    channel.bind('new-order',function(order) {
      self.restaurant_order.data.unshift(order.order)
      const audio = document.getElementById('notificationBeep');
      audio.play()
    });
  }`

**Comment by ben-pusher** [comment]
This doesn't look like a library issue on the face of it. Have you checked the variable is working as expected - perhaps through constructing and logging the channel name before trying to subscribe?
If you need further support then please reach out to [Pusher Support](https://support.pusher.com/hc/en-us. As this doesn't look like a library issue I'll close this.
