### ISSUE TITLE
Bug. Switching network causes pusher to not get or send messages for seconds and even minutes. It also thinks it's still connected.

### ISSUE THREAD

**Issue by epetre** [pusher/pusher-js#504]
*bug report*
Tested in chrome OSX using https://test.pusher.com/ and the latest version, 7.

**What is the current behavior?**
When switching networks from the wifi to a hotspot, it takes a while before pusher.js actually makes the change and all this time, the channel looks like it's subscribed and pusher thinks it's connected. So basically switching networks can cause pusher lose connection for seconds and even minutes until messages are sent or received.

**Important note**
If we switch networks and disconnect, reconnect and then try sending a message... There is no downtime.

**Details**
![image](https://user-images.githubusercontent.com/1010282/98159101-fd207080-1ea9-11eb-8510-0b14a2561231.png)
 
1. bottom arrow is when I switched network right after sending the message.
2. top arrow is when I was finally able to send another message again.
It looks like pusher didn't know what was going on until a ping was sent. 
 
**What is the expected behavior?**
I would expect that pusher detects changes in connection given that pusher relies on having an open socket connection for messages to come in or go out.

**Which versions of Pusher, and which browsers / OS are affected by this issue?
latest version. 7.

Did this work in previous versions of Pusher? I'm not sure, it seems to have been an issue in the past.
Another similar issue was reported in the past: https://github.com/pusher/pusher-js/issues/223

**Comment by ben-pusher** [comment]
I believe this is expected. The library uses a Ping/Pong system to determine the health of the websocket connection. You can read more about this pattern at https://pusher.com/docs/channels/library_auth_reference/pusher-websockets-protocol#detecting-that-the-connection-is-alive. 
What this means is that there can be some delay between network degradation and the connection being closed. The JS library does have some control over how frequently Ping messages are sent, and how long after a ping message it should wait before declaring the connection as dead. See [activityTimeout](https://github.com/pusher/pusher-js#activitytimeout-integer) and [pongTimeout](https://github.com/pusher/pusher-js#pongtimeout-integer) respectively.

**Comment by epetre** [comment]
I did some further tests on iOS safari and Android chrome and both of those browsers detected the connection change much faster.

OK, so you are saying that this is a limitation of the service. To be honest, I would consider this a pretty big limitation if it wasn't picked up almost instantly on mobile browsers. Users switching networks on mobile browsers happens quite frequently and not getting messages for a few seconds to minutes is a big problem for a service like pusher.
