### ISSUE TITLE
How to show message just on active browser's tab?

### ISSUE THREAD

**Issue by hamid80386** [pusher/pusher-js#506]
I want to show receiving messages from pusher sever, just on active tab.
For example when i have 3 same pages, just show the message on focused tab or on a page  which focusing first.

I have using channel.bind function like below:

```
channel.bind('myEvent', function(data) {

    var a = (JSON.stringify(data));

    var b = $.parseJSON(a);

    console.log(b.message);

});
```

Is any way to achieve that?

**Comment by ben-pusher** [comment]
It seems you are looking for implementation advice and don't have an issue with the library - as such I will close this issue. If you need further support then please contact our support team at https://support.pusher.com/hc/en-us.
The behaviour you describe may be possible through use of onBlur and onFocus events, using this to determine whether the tab is in focus or not and then handling the event accordingly. 
See https://stackoverflow.com/questions/7389328/detect-if-browser-tab-has-focus for info.
