### ISSUE TITLE
how to show message just when client focus in to browser tab?

### ISSUE THREAD

**Issue by hamid80386** [pusher/pusher-js#507]
Normally when the pusher server sending message to client channel, the message will show immediately  after receive.
I want to change it to **show message after client focus in on browser** and until that, browser just show **notification red point in browser tab**.

Actually, I experienced this environment once, but was an accident and I don't know how it was occurred.

In the above case, the JavaScript listened to the channel, but didn't publish the messages immediately, displaying them only when the user focused on the tab.
My code looked like this:
```
Pusher.logToConsole = true;

var pusher = new Pusher(PUSHER_key, {
    cluster: PUSHER_cluster
});
var channel = pusher.subscribe('my-channel-'+userID);
channel.bind('myEvent', function(data) {

    var a = (JSON.stringify(data));

    var b = $.parseJSON(a);

    console.log(b.message);

});
```

Can anyone tell me how this happened?

**Comment by ben-pusher** [comment]
It seems you are looking for implementation advice and don't have an issue with the library - as such I will close this issue. If you need further support then please contact our support team at https://support.pusher.com/hc/en-us.
The behaviour you describe may be possible through use of onBlur and onFocus events, using this to listen for when the tab regains focus and then displaying the events accordingly.
See https://stackoverflow.com/questions/7389328/detect-if-browser-tab-has-focus for info.
