### ISSUE TITLE
 android os not work  "connecting -> unavailable

### ISSUE THREAD

**Issue by eng-osman** [pusher/pusher-js#508]
### That problem is weird Pusher works fine on ios but on android OS everything stops is there a suggestion

"react": "16.13.1",
 "react-native": "0.63.3",
 "pusher-js": "^7.0.0",
 "laravel-echo": "^1.9.0",
 "@react-native-community/netinfo": "^5.9.7"

**pusher :  : ["State changed","connecting -> unavailable"]**

**Comment by ben-pusher** [comment]
Have you given permission to access internet in the manifest file?
```
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
```

If this doesn't work, please get in touch with us at https://support.pusher.com/hc/en-us where our support team will be able to help further. This doesn't appear to be a library issue so I'll close here. 
Thanks!

**Comment by eng-osman** [comment]
@ben-pusher 
I'm already using it in the manifest file. I still haven't come up with a solution

**Comment by fansilva1991** [comment]
@moGeekHex, try to add 

```xml
android:usesCleartextTraffic="true"
```

Inside the <application> tag in your AndroidManifest file.

**Comment by aminBanelhaq** [comment]
someone has found a solution, or the cause of the problem, because I also continue to receive in the Pusher logs

> Pusher :  : ["State changed","connecting -> unavailable"]


although in the AndroidManifest file I have both 

> <uses-permission android:name="android.permission.INTERNET" />
> <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

and 

> android:usesCleartextTraffic="true"



`"expo": "~52.0.39",
"laravel-echo": "^2.2.0",
"pusher-js": "^8.4.0",
"react": "18.3.1",
"react-native": "0.76.7",`
