### ISSUE TITLE
Caching of successful responses from an authentication endpoint for Presence Channels

### ISSUE THREAD

**Issue by akovalev** [pusher/pusher-js#510]
**What are the potential implications of caching successful responses from an authentication endpoint for Presence channels?**

In our application we subscribe to Presence channels whose lifetime might be pretty short. For example. you can imagine the presentation app where for each slide a new Presence channel scoped to a particular slide is created when user navigates to a given slide. Taking into account that users might navigate back and forth between, for example, slide A and B quite frequently, ideally we would like to avoid an additional latency that is introduced by a request to an authentication endpoint.

Given that we already use a custom authorizer function in our app, we thought that we could cache successful responses from an authentication endpoint in, say, LRU Cache where each entry is keyed by a value derived from both `socket-id` and a channel name. Even though we do set TTL of 60 seconds on each cache entry, it seems that an auth response never expires unless the websocket connection is re-established, say, after being offline for a while in which case the auth process will be started again for each channel with a new socket id and a previously stored auth response for a given channel will be simply ignored since the key on which it was stored was different (derived using old socket id)

This approach seems to work and we haven't noticed any problems with it so far, but could you please comment on the statement that an auth response never expires and in general provide us with some comments regarding the technique described above?

In order to help you to understand the approach we are considering to use, we provide the following code snippet illustrating an approximate implementation of our custom authorizer function. 

```js
function memoize(fn, {maxSize, maxAge, keyFn}) {
  const lru = new LRU({maxSize});

  return function memoizedFn() {
    const key = keyFn.apply(null, arguments);
    const {result, createdAt} = lry.get(key) || {};
    if (result && ((Date.now() - createdAt) < maxAge)) {
      return Promise.resolve(result);
    } else {
      return fn
        .apply(null, arguments)
        .then(function (result) {
          lru.set(key, {
            result: result,
            createAt: Date.now()
          });
          return result;
        })
    }
  }
}

function authPusher(params) {
  return apiClient.authPusher(params);
}

function makeCustomAuthroizer(channel) {
  const memoizedAuth = memoize(authPusher, {
    maxSize: 100,
    maxAge: 60 * 1000,
    keyFn: ({ socketId, channelName } => [socketId, channelName].join('_'))
  });

  return {
    authorize: function (socketId, callback) {
      return memoizedAuth({
        socketId: socketId,
        channelName: channel.name
      })
        .then((resp) => callback(null, resp))
        .catch((e) => callback(err, null))
    }
  }
}
```

**Comment by leesio** [comment]
Hi there,
I don't see any issue with with approach. Tphe auth string should remain valid for a `channel_name:socket_id` pair so as long as your cache treats a `socket_id` change as a cache miss, it should be fine. Since you're using this for presence channels I'll point out that you run the risk of some of your `user_data` being stale but it's better for you to judge how likely that is to be a problem for you 😄 

This is a nice solution, it would be cool if we could offer it as an option in the library one day.

Thanks

**Comment by akovalev** [comment]
@leesio thank you for such a quick response. 

> I'll point out that you run the risk of some of your user_data being stale, but it's better for you to judge how likely that is to be a problem for you

We use Presence channels in order to build so-called Presence Map capturing a remote data/state of a given client and we already clean up stale data of members as soon as they are disconnected. So I believe we are safe with that regard...
