### ISSUE TITLE
Long delay before a connection state is updated when going to offline mode

### ISSUE THREAD

**Issue by akovalev** [pusher/pusher-js#511]
In the application we are working on we pay a lot of attention to offline scenarios and try to handle situation like transitions from online to offline gracefully.

We noticed that it takes a rather long period of time (based on our experience it ranges from 30 seconds up to 2 minutes) until `state_change` event is fired so that a client code is notified and handles the state of Pusher/WebSocket connection in a desired way.

Why is it important? Consider the following scenario, when in a presentation app creates a dedicated Presence channel for each slide:

 - User is online and opens a presentation on Slide 1.
 - After some time they lose Network connection, basically they are offline
 - While still being offline they go to the next slide so that a new presence  channel is created:
   - we try to subscribe/authenticate a newly created channel with some back-off strategy and give up after, say, 5 attempts since we are offline and cannot reach the authentication endpoint)
   - at the same time we add a listener to a `state_change` event in order to schedule another attempt to subscribe to a Presence channel when WebSocket connection is back.
 - User goes back online   

The problem we ran into boils down to the case when the time interval between last 2 steps is pretty short (it might happen in theory when one switches between WiFi networks or merely has an unstable/flaky connection). In other words, If the period of time when user is offline is pretty short and the initial attempt to subscribe to a Presence channel was performed when they were already offline, it might be the case that no `state_change` event is fired and no attempt to re-subscribe will take place.

At the moment we work around this problem by listening to both
 - `state_change` event dispatched by Pusher
 - `online` event dispatched by a browser

The latter rules out the case when no new attempt to re-subscribe to a previously created channel will take place, but ideally we expect Pusher SDK to fire `state_change` event with a shorter delay and actually having looked through the source code we noticed that there're [some settings][1] that seem to control the current behaviour. Having tried to tweak `pongSetting` in particular (we set it to 1000 ms), we've got an impression that it does affect how soon WebSocket/Pusher connection is considered lost and when `state_change` callback is invoked.

Given that all those connection settings are undocumented params, could you please outline what are the implications of adjusting the default values?

[1]: https://github.com/pusher/pusher-js/blob/462df72db70072dc77152e4d75caf175765dde87/src/core/defaults.ts#L43-L45

**Comment by ben-pusher** [comment]
Hi! Channels uses a [Ping/Pong](https://pusher.com/docs/channels/library_auth_reference/pusher-websockets-protocol#ping-and-pong-messages) mechanism to determine connection state, however there can be a delay in how long it takes between a connection issue and the Channels connection state change event as you have found. The activityTimeout and PongTimeout parameters can be used to reduce this delay, which you have identified. These are documented at: 
https://github.com/pusher/pusher-js#activitytimeout-integer
https://github.com/pusher/pusher-js#pongtimeout-integer

The risk of setting these too aggressively is that your client will be falsely disconnected if there is a slight latency delay.

**Comment by akovalev** [comment]
Thank your for very detailed answer @ben-pusher 
For some reason I thought that both `activityTimeout` and `pongTimeout` were undocumented settings as I was trying to find information about them on pusher website rather than here. At the same time it's kinda nice to see that our understanding/assumptions were almost correct and that is why I think it makes sense to close this issue.

**Comment by ben-pusher** [comment]
No problem at all! Where an option/setting is only available in some libraries we refrain from documenting it on the main documentation as it can cause some confusion, however unfortunately it looks like this approach also causes some confusion. Glad to have been able to help clear it up on this occasion.

**Comment by akovalev** [comment]
Sure, another observation that we've made while looking into how Pusher JS SDK handles different offline scenarios is that it turned out that once network connection is back Pusher automatically tried to re-authenticate only those channels whose subscription was successfully obtained before, which means that we need to manually schedule another attempt if the initial one failed because API was not reachable. 

I mean it all makes sense, but it took some time to figure out this subtle detail in the Pusher implementation.
