### ISSUE TITLE
TypeScript Error: AuthInfo type does not exist

### ISSUE THREAD

**Issue by anthony-j-castro** [pusher/pusher-js#512]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I'm using `pusher-js/with-encryption` in a TypeScript project. When I attempt to compile, I get the following error:
```shell
node_modules/pusher-js/with-encryption/index.d.ts:2:3 - error TS2305: Module '"../types/src/core/auth/options"' has no exported member 'AuthInfo'.

2   AuthInfo,
    ~~~~~~~~
```

It looks like the `AuthInfo` type definition was removed in v7.0.0 (see https://github.com/pusher/pusher-js/commit/96aab17f993be499ce1b49ef0649e4f749ac9e81#diff-dbc910045a791a925c9af7c217c3abae2cff6d78d9df1f443188b7103b3cc2b7L10), but it's still being referenced.

**Proposed solution:** Removing the export of `AuthInfo` from https://github.com/pusher/pusher-js/blob/9daa2ee8afcd1ad70e31288652fd24e2ec49c241/with-encryption/index.d.ts#L2 and https://github.com/pusher/pusher-js/blob/8b2c1ba76323abee0ce9f9e75f52767013c27744/react-native/index.d.ts#L2 should resolve the issue.

**Comment by leesio** [comment]
I created a PR for this: #513

**Comment by leesio** [comment]
I just pushed a release. Let me know if you're still experiencing issues with 7.0.2.

**Comment by anthony-j-castro** [comment]
7.0.2 looks good, thanks for the quick fix!
