### ISSUE TITLE
Pusher not triggering events form client side.

### ISSUE THREAD

**Issue by codeHysteria28** [pusher/pusher-js#516]
I just opened my app today to have a look. Tried few pusher calls but suddenly not working getting response error. I've Checked debug console so my client side is connecting successfully and also when I try to send test event from event creator my client is receiving it. But any action taken from client is not working. I checked routes for fetch if I'm proving correct routes but they're correct. I'm using pusher 7.0 I just seen the version 7.2 was released. Could that make a problem ? Thanks

**Comment by ben-pusher** [comment]
Version 7 will continue to work and will not be impacted by the v7.0.2 release. 
Can you share the error/response you are receiving, and the code you are using when getting this error. 

Just to cover bases: this js lib is only able to sent client events. There a few things to be aware of when triggering client events: 

- Client Events are turned off by default, you will need to enable them in the [Pusher dashboard](https://dashboard.pusher.com/).
- Client events can only be sent via private or presence channels. 
- Client Events are rate limited to only 10 per second. 
Please ensure your application meets the criteria above.

**Comment by ben-pusher** [comment]
Hi, 
There hasn't been any updates here recently so I will close this out. If you need any further support please reach out via https://support.pusher.com/hc/en-us/requests/new
