### ISSUE TITLE
Jest Test: Fetch is not a function

### ISSUE THREAD

**Issue by eliobricenov** [pusher/pusher-js#517]
**Do you want to request a *feature* or report a *bug*?**
*Bug*

**What is the current behavior?**
I'm using a pusher-js in a react native app, everything works fine but after I try to run some jest tests I get the following error:

![image](https://user-images.githubusercontent.com/38574891/102213589-55855d80-3ead-11eb-8dfd-49833db82922.png)

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

1. Add pusher-js as a dependency in the react-native project.
2. Run a jest test.

**What is the expected behavior?**

To pass the test successfully.

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**

`"react-native": "0.63.3"`,
`"pusher-js": "^7.0.2"`

**Comment by ben-pusher** [comment]
You may be required to use [jest-fetch-mock](https://github.com/jefflau/jest-fetch-mock), a package that adds Fetch capabilities to Jest.

**Comment by ben-pusher** [comment]
Hi,
There hasn't been any updates here recently so I will close this out. If you need any further support please reach out via https://support.pusher.com/hc/en-us/requests/new
