### ISSUE TITLE
Usage with MobX store (class)

### ISSUE THREAD

**Issue by spsaucier-bakkt** [pusher/pusher-js#521]
Is there a way to `bind` or otherwise respond to a channel push without overwriting the context of the handler function?

I'm trying to use pusher to update a MobX store, which is a Class. The method called relies on `this` to get the existing state data and to update it.

```
channel.bind('updated', updateFromSockets);
```

```
class ConversationsStore {
  conversations = [];

  updateConversation(conversationUpdate) {
    console.log(this.conversations); // This is undefined
  }
}
```

It says you can [pass in an alternate `context`](https://pusher.com/docs/channels/using_channels/events#binding-with-optional-this-context) for the call, but `this` then seems to end up `undefined` no matter what.
How can I include that class's internal context, or avoid that need altogether?

**Comment by spsaucier-bakkt** [comment]
I believe it's possible to update the MobX state externally to the `@action`:
```
import {configure} from "mobx";
configure({enforceActions: "never"})
```
That should resolve this issue, but I wasn't able to get that to update the UI when the state changed, and I've switched to PubNub instead for now.

**Comment by leesio** [comment]
I'm sorry to hear you weren't able to get this working.

FWIW I just tried this with a simple js Class and it passing a context arg to the bind function seems to work fine

```
class SomeClass {
  constructor(key) {
    this.key = key;
  }

  handleEvent() {
    console.log("this: ", this, "this.key:", this.key);
  }
}
const pusher = new Pusher(key, opts);
const channel = pusher.subscribe("my-channel");
const someClass = new SomeClass("some-value");
channel.bind("my-event", someClass.handleEvent, someClass);
```

Prints 

```
12:16:35.136 script.js:14 this:  SomeClass {key: "some-value"}key: "some-value"__proto__: Object this.key: some-value
```

**Comment by leesio** [comment]
I'm going to close this issue now, feel free to drop a comment if you're able to provide more information to help debug
