### ISSUE TITLE
Bug: Auth endpoint only called once.

### ISSUE THREAD

**Issue by AlaaZorkane** [pusher/pusher-js#524]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Auth endpoint is being called only once over multiple pusher instances. Even when the first instance is destroyed.

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
- Make a pusher instance with auth params **X**
- Disconnect and destroy the first pusher instance
- Make a _second_ pusher instance with auth params **Y**
- The second pusher instance is connected (pusher dashboard logs) but not authorized (auth endpoint not being called)

**What is the expected behavior?**
The auth endpoint should be called on each pusher instance, since they're isolated from eachother, the authorization flows should also be isolated.

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
Latest/All

**Comment by ben-pusher** [comment]
Hi, 

The auth endpoint will be called when you attempt to subscribe to a private or presence channel. Does your code subscribe to such a channel after the second instance has been created?

**Comment by AlaaZorkane** [comment]
Hello!

You're right! The auth endpoint only gets called after I try to subscribe. My bad! Issue closed.

**Comment by ahmetkca** [comment]
Pusher is using the default user authentication endpoint even thought I am overriding with `/api/pusher/user-auth`
