### ISSUE TITLE
Bundle size

### ISSUE THREAD

**Issue by MartinMalinda** [pusher/pusher-js#526]
Hello!

I'm considering using Pusher and the only thing holding me back a bit is the bundle size - 17Kb. It's a lot of JS to get a little bit of real time functionality on the background.

I could be wrong but even if I only need the basic pub/sub, the lib will give me code for HTTP and maybe even browser push notification support, right?

Is there a way around this?

Thanks!

**Comment by knyttl** [comment]
Basically it would be great to split the JS file for `channels` and `beams` as we are only going to use `channels`, there is no need to download the pieces we will never use.

**Comment by ben-pusher** [comment]
The library doesn't include any Beams support for Push Notifications - you would need to use the separate library for this https://github.com/pusher/push-notifications-web 

It is not possible to reduce the library size by dropping support for some protocols without also making changes to our API. We don't have any plans to make such changes at this stage.

**Comment by MartinMalinda** [comment]
When I have some time I'll try to install the library to see if the code can be code split with Rollup. Maybe the `sideEffects: false` could be added to package.json? 

https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free

**Comment by mattleonowicz** [comment]
I was also surprised that whole package gets bundles.
Reducing that bundle size with ability of treeshaking could score you some points in the eyes of clients that care about bundle size
