### ISSUE TITLE
Incorrect types for channels with typescript

### ISSUE THREAD

**Issue by nickland03** [pusher/pusher-js#529]
**Do you want to request a *feature* or report a *bug*?**
I assume it is both.

**What is the current behavior?**
When we create a presence channel, it is of type Channel instead of PresenceChannel and we can't access its fields in typescript.

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

When we subscribe to a private channel, it should be of type PrivateChannel. When we subscribe to a presence channel, it should be of type PresenceChannel.

```typescript
// an error will be thrown, subscribe returns Channel instead of PresenceChannel
const channel: PresenceChannel = pusher.subscribe('presence-chat-room')
// we don't have access to members: TS2339: Property 'members' does not exist on type 'Channel'.
console.log(channel.members)
```

**Which versions of Pusher, and which browsers / OS are affected by this issue?**
Latest version

**Comment by ben-pusher** [comment]
Have you tried manually importing the necessary types? See https://github.com/pusher/pusher-js#typescript

**Comment by freezey** [comment]
I'm seeing the same issue.  I am using .subscribe('presence-' + channelName) to subscribe to a presence channel, but the returned Type is a Channel instead of a PresenceChannel, resulting in tslint tossing the error "TS2739: Type 'Channel' is missing the following properties from type 'PresenceChannel': members, handleInternalEvent"

I'm using pusher-js installed via nvm "^7.0.3"

**Comment by nickland03** [comment]
It's been a while since I posted this, but here is a workaround that I used to satisfy typescript.
```typescript
import PrivateChannel from 'pusher-js/types/src/core/channels/private_channel';
import PresenceChannel from 'pusher-js/types/src/core/channels/presence_channel';
import Pusher from 'pusher-js';

const pusher = new Pusher('', {})
const privateChannel = pusher.subscribe('private-channel-name') as PrivateChannel
const presenceChannel = pusher.subscribe('presence-channel-name') as PresenceChannel
```

I saw that internally it chooses the correct type of channel using factory, but the thing is that typescript probably complains about that line: `subscribe(channel_name: string): Channel` inside `pusher-js/types/src/core/pusher.d.ts`.

**Comment by jamilabreu** [comment]
@nickland03 I tried your solution on v7.1.1-beta and get this:

> Type 'Channel' is missing the following properties from type 'PresenceChannel': members, handleInternalEventts(2739)

**Comment by shellord** [comment]
I have the same issue.

**Comment by mrlectus** [comment]
> @nickland03 I tried your solution on v7.1.1-beta and get this:
> 
> > Type 'Channel' is missing the following properties from type 'PresenceChannel': members, handleInternalEventts(2739)

how did you fix it?
