### ISSUE TITLE
Receiving data twice for the same event

### ISSUE THREAD

**Issue by lipecss** [pusher/pusher-js#532]
I'm working with node and vue js. My route is triggering only one event (I have already validated it), but on your platform there are 2 events being triggered for each one. 

Follow my settings, I've used the cdn, components and all are listed in two events on the platform

![image](https://user-images.githubusercontent.com/40566871/108640268-633ffc00-7477-11eb-8821-1331edb33338.png)

I've tried everything, but nothing removes these two events

**Comment by ben-pusher** [comment]
The primary cause for such behaviour is typically that your client application is opening two connections and subscriptions, with each subscription handling the event independently. You should check your client behaviour to ensure only a single connection is made. 

You can use the Debug Console in the [Pusher Dashboard](https://dashboard.pusher.com/) to see, in realtime, what is happening in your app when the client starts and events are published hopefully this will help identify where the error lies. 

This doesn't appear to be a library specific issue, so I will close this. If you need further assistance please raise a ticket with our [Support Team.](https://support.pusher.com/hc/en-us/requests/new)

**Comment by babucarr32** [comment]
To solve this, you need to unbind the channel before binding.

pusherClient.subscribe(1234);
pusherClient.bind(1234);
pusherClient.bind("incoming-message", (text) => {
  console.log(text);
});

See [here](https://github.com/pusher/pusher-js#binding-to-events) for more info
