### ISSUE TITLE
Add a dynamic header to the request

### ISSUE THREAD

**Issue by bissolli** [pusher/pusher-js#533]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
I can set a fixed header but not a dynamic one - which would change every request

Basically I am working on a task to correlate requests cross-project, and to accomplish it, I am assigning a unique ID called `X-Transaction-ID` to every single request, and with that, when I get a bug I can track it from my frontend up to my backend since I can correlate this request and see what happened with my service.

Problem is that, when I am subscribing to a private channel, the lib doesn't allow me to pass a function or something like that in order to generate this id for every request.

Just to be clear, the request I want to assign is the one Pusher does to my own API to retrieve a token to be able to subscribe to a private channel.

I can set the unique ID with something like this: 
`pusher.config.auth.headers['X-Transaction-ID'] = myGenerator()`

But the issue is that it doesn't generate a new one on every request but uses the same as I can't pass a function to be executed while the request is being created.

So any way of get it working?

**Comment by leesio** [comment]
It should be possible to do this with a custom authorizer function

https://github.com/pusher/pusher-js#authorizer-function

That should give complete control over the auth. request. Does that help?
