### ISSUE TITLE
Prebuilt version fails on tls handshake

### ISSUE THREAD

**Issue by Rubensei** [pusher/pusher-js#534]
I'm trying to connect to a custom host from Node.js but i always get unavailable state
> Pusher :  : ["State changed","initialized -> connecting"]
> Pusher :  : ["Connecting",{"transport":"ws","url":"wss://my-domain.com:443/app/MY_APP_KEY?protocol=7&client=js&version=7.0.3&flash=false"}]
> Pusher :  : ["State changed","connecting -> unavailable"]

I found out that the client automatically closes the TCP session as soon as the TLS handshake finishes
No error is thrown on client and there are no logs at all on the server, 
Here the wireshark capture of the tcp handshake and immediate disconnection (the ip ending in 40 corresponds to my device, being the leftmost column the destination address of the packet)
![image](https://user-images.githubusercontent.com/8256351/109843439-57102780-7c4b-11eb-9fc6-4e0a280e6b19.png)

I've been able to connect to the same ws endpoint with the same uri using `pusher-client` and `ws` npm packages.

The code i'm using right now:
```js
let pusher = new Pusher(APP_KEY, {
	wsHost: WS_ENDPOINT,
	forceTLS: true,
	enableStats: false,
	enabledTransports: ['ws'],
})
```

**Using**
Client
 * Pusher-js 7.0.3
 * Nodejs 14.15.5
 * Windows 10 19042.844

Server
 * Nginx with reverse proxy for ws endpoint
 * laravel-websockets

**Comment by Rubensei** [comment]
Seems to be some issue with certificate validation similar to [this](https://github.com/pusher/pusher-js/issues/319#issuecomment-458645168). Other clients can still connect fine though

**Comment by Rubensei** [comment]
I've been doing some more tests and i've found out that building locally and using that build allows to connect without any error
* Cd to `pusher-js` folder inside `node_modules` and download the dependencies with `yarn install`
* `make build_all` to build the new files

**Comment by ben-pusher** [comment]
I believe the issue here is related to the setup on your websocket host. 
Does the pre-built library connect ok to official Pusher clusters?

**Comment by Rubensei** [comment]
Yes, it does connect to the official clusters.

The weird thing is that I tested other ws clients like `ws`, `pusher-client` and `faye-websocket` and all can connect without any issue to the same endpoint using the pre-built lib. While `pusher-js` can't connect unless I use a locally built version (without any modification at all) as commented before.

**Comment by shehi** [comment]
Better create a ticket on Pusher support, linking this issue there. Otherwise they won't look into issues.

**Comment by benw-pusher** [comment]
Thanks for reporting this. We supply our client libraries for connecting to the official Pusher service and do not guarantee support for custom websocket hosts. We are not able to provide a resolution to this issue for this reason.
