### ISSUE TITLE
pusher and laravel-echo  cant subscribe automaticaly to private channel

### ISSUE THREAD

**Issue by farshidahmadianpin** [pusher/pusher-js#536]
- Echo Version: 1.10.0
- Laravel Version: 8.4.0
- PHP Version: 7.4
- NPM Version: 6.14.6
- Node Version: 4.1.0
- pusher/pusher-php-server: 4.1.5
- pusher-js: 7.0.3

### Description:
I use pusher and laravel-echo to create chat app in laravel. public Channels work properly. 

I use [pusher.com debug console](https://dashboard.pusher.com/apps) and I realized in PrivateChannel laravel-echo can't subscribe users to Available private channels automaticaly.
notice that commented codes is for public channel.

`App\Events\ChatBroad.php` is:

```
    public function broadcastOn()
    {
        //        return new channel('recieve-chat.' . $this->chat['reciever_id']);
        return new PrivateChannel('recieve-chat.' . $this->chat['reciever_id']);
    }
```

`routes/channels.php` is:
```
Broadcast::channel('recieve-chat.{reciever_id}', function ($user , $reciever_id) {
      return true;
   // return $user->id == $reciever_id;

});
```
and in `App\Providers\BroadcastServiceProvider` i use this middleware:

`Broadcast::routes(['middleware' => ['auth']]);
`

`bootstrap.js ` is:
```
import Echo from 'laravel-echo'

window.Pusher = require('pusher-js');

window.Echo = new Echo({
    broadcaster: 'pusher',
    key: '83b97539662b786ffabb',
    cluster: 'eu',
    forceTLS: true,
    authEndpoint: '/broadcasting/auth',
    csrfToken: $('meta[name="csrf-token"]').attr('content'),
});
```

blade view file:

```
        <script src="{{asset('js/app.js')}}"></script>
        <script>
            {{--window.addEventListener('DOMContentLoaded' , function () {--}}
            {{--    Echo.channel('recieve-chat.{{Auth::id()}}' )--}}
            {{--        .listen('ChatBroad', (e) => {--}}
            {{--            window.livewire.emit('recieve:' + e.chat.bid_id , e.chat);--}}
            {{--            $(chatScrollDown('.chat'+ e.chat.bid_id ));--}}
            {{--        });--}}
            {{--});--}}

```
            window.addEventListener('DOMContentLoaded' , function () {
                Echo.private('recieve-chat.{{Auth::id()}}' )
                    .listen('ChatBroad', (e) => {
                        window.livewire.emit('recieve:' + e.chat.bid_id , e.chat);
                        $(chatScrollDown('.chat'+ e.chat.bid_id ));
                    });
            });
        </script>

**Comment by ben-pusher** [comment]
Do you know if your auth endpoint is being correctly invoked? Do you have any logging there? 
Are any error messages returned in your client when subscribing to the private channels?

**Comment by farshidahmadianpin** [comment]
@ben-pusher
hey there,
yes I checked all of this. i explained all of my codes in [here](https://github.com/laravel/echo/issues/302)
i will be gratefull to helpme

**Comment by farshidahmadianpin** [comment]
hey there,
if  auth endpoint has problem. irecieve 500 error in console.
i checked all of this. and i describe the problem and some additional data in [here](https://github.com/laravel/echo/issues/302) .
thank you 
🌺

**Comment by farshidahmadianpin** [comment]
in `App\Providers\BroadcastServiceProvider.php`

```
 public function boot()
    {
        Broadcast::routes();

        require base_path('routes/channels.php');
    }
```
we dont need any middleware!!
