### ISSUE TITLE
Bad code bad workflow

### ISSUE THREAD

**Issue by RollinSafary** [pusher/pusher-js#537]
Hi there.
I took a look into your code and got to the point, that the developers of this project made everything to make it coded without keeping any standard, any logic, or principle. The TypeScript knowledge sucks, to say the least. Seems that you didn't even try to make a normal project. So much hardcoded and fucked up logic, I really going to become crazy. 
The lazy developer decided to use Runtime in place of making an understandable logic of the shit he had written in this repo.

I'm now working on making normal repo from this and really during whole my experience I've never seen anything worse than this is.

I hope that you will draw conclusions from what I have written and you will become better.
I don't even want to say "thanks for the done work".

P.S. Sorry for the aggressivity but it's really bad.

**Comment by leesio** [comment]
I’m sorry this SDK had such a negative impact on your day.

I hope you have more luck with your own implementation.
