### ISSUE TITLE
Pusher not working with jquery when using presence channel in laravel.

### ISSUE THREAD

**Issue by Zeeshan-H** [pusher/pusher-js#540]
This is my laravel controller method: 
    public function index()
    {
        $users = User::where('id', '!=', auth()->user()->id)->get();
        broadcast(new CheckOnlineStatus(auth()->user()->id));
        return view('users.index', compact('users'));
    }

This is my jquery code:

   Pusher.logToConsole = true;

        var pusher = new Pusher('{{env("MIX_PUSHER_APP_KEY")}}', {
            cluster: '{{env("PUSHER_APP_CLUSTER")}}',
            encrypted: true,            
            
        });

        var channel = pusher.subscribe('test-channel');
        var channel2 = pusher.subscribe('presence-check-online');
        channel.bind('App\\Events\\NewMessage', function(data) {
            // getLatestMessage(data.message.content);
            getLatestMessage(data);
        }); 

This is channels.api file:
Broadcast::channel('presence-check-online', function ($user) {
    return $user;
});

        channel2.bind('online-event', function(data) {
            alert('Hi');
        });

This is my event code: 
class CheckOnlineStatus implements ShouldBroadcast
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public $id;
    /**
     * Create a new event instance.
     *
     * @return void
     */
    public function __construct($id)
    {
        $this->id = $id;
    }

    /**
     * Get the channels the event should broadcast on.
     *
     * @return \Illuminate\Broadcasting\Channel|array
     */
    public function broadcastOn()
    {
        // return ['check-online'];
        return new PresenceChannel('check-online');

    }

    public function broadcastAs()
    {
        return 'online-event';
    }

Even it gets debug into pusher console but not showing alert using channel2.bind. Please help.

**Comment by ben-pusher** [comment]
Could you clarify the issue here - when you mention 'it gets debug into pusher console' are you referring to the debug console in the dashboard or instead the browser dev tools console?

**Comment by benw-pusher** [comment]
I'll close this out now as you haven't responded - if you need further support please get in touch with our Support team via https://support.pusher.com/hc/en-us/requests/new
