### ISSUE TITLE
Pusher ^6.0 with php 7.1

### ISSUE THREAD

**Issue by shivvani-patel** [pusher/pusher-js#542]
Hello,

I am having php 7.1 on my server. I have install "pusher/pusher-php-server" with version 6.1 but I am getting this error when use pusher trigger function :
**Return value of Pusher\\Pusher::trigger() must be an instance of Pusher\\object, instance of StdClass returned** 
_(Pusher.php line no : 450)_
so I downgrade pusher version to 4.1 then it is working fine. On my local PHP version is 7.4 then it working fine with version 6.1.

Thank you

**Comment by benw-pusher** [comment]
The issue you describe is expected. The [changelog](https://github.com/pusher/pusher-http-php/blob/master/CHANGELOG.md#600) for pusher-htttp-server shows that PHP 7.1 support was removed in v6.0.0. You have a couple options to prevent this error:

-downgrade the Pusher package to an earlier release
-upgrade your php version to a later release. 

You have raised this issue against the pusher-js library - you can see the php library you have issues with at https://github.com/pusher/pusher-http-php.
