### ISSUE TITLE
Offline Mode

### ISSUE THREAD

**Issue by cpgb85** [pusher/pusher-js#543]
I don't have a bug just wonder if there is a feature.  When i put a device into airplane mode to emulate if the device lost connection, I get piles of errors. Is there any way to turn this off?

**Comment by benw-pusher** [comment]
What are the errors you are receiving? Have you set [logToConsole](https://github.com/pusher/pusher-js#pusherlogtoconsole-boolean) to true? If so you should set it to false to suppress logging.

**Comment by benw-pusher** [comment]
As we've had no response I will close this issue. If you need anything more please get in touch with out support team at https://support.pusher.com/hc/en-us/requests/new
