### ISSUE TITLE
XHR Error POST

### ISSUE THREAD

**Issue by calvinmuller-wi** [pusher/pusher-js#546]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
We use datadog RUM to monitor our applications on Angular and in the error logs within we see lots and lots of.
```
https://sock64-eu.pusher.com/pusher/app/xxxx/xxx/xxxxx/xhr?protocol=7&client=js&version=6.0.3&t=1624538231085&n=897
504 GATEWAY TIMEOUT
```
```
Failed to load
```
It seems to originate from the domain `pusher.com`

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
```
this.pusherClient = new Pusher(this.environment.pusher.key, {
      authEndpoint: this.environment.resourceServer.reportsUrl + 'pusher/auth',
      cluster: 'eu',
      forceTLS: true,
      auth: {
        headers: {
          Authorization: `Bearer ${auth.getAccessToken()}`
        }
      }
    });
```

**What is the expected behavior?**
We seem to experience intermittent drops in pusher messages so just checking if this could be related or not.

**Which versions of Pusher, and which browsers / OS are affected by this issue?
```
"pusher-js": "^6.0.3",
MacOSX
Chrome
```

**Comment by benw-pusher** [comment]
Could you provide a couple of timestamp from when you have received the mentioned error so we can check our internal logs?

**Comment by calvinmuller-wi** [comment]
@benw-pusher  please see attached (time is GMT+2) SAST.

<img width="1464" alt="Screenshot 2021-06-24 at 16 02 08" src="https://user-images.githubusercontent.com/64589914/123276559-9073e800-d505-11eb-8034-1d1e9e473518.png">

**Comment by benw-pusher** [comment]
Thanks @calvinmuller-wi 
We've looked into our monitoring and logging here and we can't see any evidence of 504 errors. I wonder if there is a proxy or other service between your clients and our service that might be emitting these errors?

**Comment by benw-pusher** [comment]
I'll close this out now as we haven't had a response, as mentioned above it does appear that the issue may lie between the clients and our endpoint.
