### ISSUE TITLE
Pusher auth endpoint gives me a 404 error

### ISSUE THREAD

**Issue by ardalan-nhd** [pusher/pusher-js#547]
I am using `pusher-js` in react. My frontend is served at app.xxx.com and my backend is served at api.xxx.com. We have a private notification websocket channel to push notiifcations through app.xxx.com. What i'm trying to achieve is using the auth endpoint on backend. But no matter what i do, pusher will always request to the base URL of frontend plus auth endpoint. In my case it will be `https://app.xxx.com/broadcasting/auth` but i want it to be `https://api.xxx.com/broadcasting/auth`. What should i do? Here's my pusher config:
```
pusher = new Pusher(APP_ID, {
                httpsHost: process.env.REACT_APP_WS_HOST,
                authEndpoint: '/broadcasting/auth',
                auth: {
                    params: {
                        id: userData.id,
                    },
                    headers: {
                        'X-CSRF-Token': '{{ csrf_token() }}'
                    }
                },
                cluster: 'ap2',
                wsHost: process.env.REACT_APP_WS_HOST,
                wsPort: 6001,
                wssPort: 6001,
                forceTLS: true,
            })
```
The value of `process.env.REACT_APP_WS_HOST` is `api.xxx.com`

I even tried adding an `authHost` key but nothing changed.

**Comment by benw-pusher** [comment]
Have you tried using the full URL to the endpoint: 
`authEndpoint: 'https://api.xxx.com/broadcasting/auth'`

**Comment by ardalan-nhd** [comment]
Yes i tried that. and gives me something like this: https://app.xxx.com/https://api.xxx.com 404 error

**Comment by ardalan-nhd** [comment]
Oh my bad...
 Apparently my pusher -js package version was 4.4.0
 I updated it to 7.0.3 and everything seems fine now.
 Sorry about that

**Comment by benw-pusher** [comment]
No worries, it happens.
