### ISSUE TITLE
Problems  after extended period of time.  

### ISSUE THREAD

**Issue by cpgb85** [pusher/pusher-js#548]
When a user starts my app up, the pusher service connects.  Everything works for a while but it seems after a few days, when i send messages via PHP to the pusher service and have them sent out to my app, it won't work.   it keeps trying to send updates to my app, and returns random letters like "h" and stuff. But It won't actually trigger.   Could the problem be a bad  internet connection?  If pusher disconnects, does pusher have problems until i reconnect?

**Comment by benw-pusher** [comment]
Could you elaborate on some of the things you have mentioned here? 
What does 'and returns random letters like h and stuff' mean? What is returning these letters? Is it your triggering server? 
Do you see the triggered events in your debug console (available at dashboard.pusher.com)?

The JS library does attempt to reconnect in the event of a network issue. You shouldn't need to manually reconnect. You can monitor the client behaviour around this by [listening for connection state changes](https://pusher.com/docs/channels/using_channels/connection#binding-to-all-state-changes).

**Comment by benw-pusher** [comment]
I haven't received a response here so I will close this issue. If you nee further support please raise a request at https://support.pusher.com/hc/en-us/requests/new
