### ISSUE TITLE
No error code for WebSocketError

### ISSUE THREAD

**Issue by tiemevanveen** [pusher/pusher-js#55]
When the client tries to subscribe to a previously subscribed channel the client receives an error event. 

```
{
    "type": "WebSocketError",
    "error": {
        "type": "PusherError",
        "data": {
            "code": null,
            "message": "Existing subscription to channel presence-ABCDE"
        }
    }
}
```

The code is null which makes it hard to respond to the error.

Could there be an error code attached to this event?

**Comment by hph** [comment]
Hi @tiemevanveen,

I'm going to close this issue since the PR you linked has been closed and your issue seems to have been resolved. Please let us know if that is not the case.

**Comment by tiemevanveen** [comment]
😅 3 years later.. 

But yeah that's fine. Thanks!
