### ISSUE TITLE
Unique Authentication for Every Channel Subscription

### ISSUE THREAD

**Issue by PrescottJRynewicz** [pusher/pusher-js#552]
## Feature Request
**Allow different authentication options when subscribing to a channel instead of during class construction.**

### What is the current behavior?
The pusher-js sdk only allows configuration of authentication options when instantiating a class. This causes conflicts with how pusher measures concurrent connections if you want different channels to have different authentication options.

i.e. Every pusher class instance counts as a concurrent connection but you are only able to specify one authentication method.  

**What is the expected behavior?**
Ideally, I would be able to do...

```
import Pusher from 'pusher-js';

export const pusher = new Pusher('app_key', {
  authEndpoint: `${website}/default/auth/url`,
});

const channel = pusher.subscribe('channel_name', {
  authEndpoint: `${website}/unique/authUrl`,
});
```

where the `subscribe` function would have a signature like...

``` 
subscribe(channel_name: string, config: { 
  auth?: AuthOptions;
  authEndpoint?: string;
  authTransport?: AuthTransport;
  authorizer?: AuthorizerGenerator;
}): Channel

```

**Comment by benw-pusher** [comment]
As the channel name is passed to the auth endpoint as part of the authentication process you may be able to have custom auth process per channel with a single endpoint. Once the request is received by the endpoint you would run the appropriate code based on the channel name received.

**Comment by benw-pusher** [comment]
Additionally you may be able to build the logic you are looking for with a custom authorizer. See https://github.com/pusher/pusher-js#authorizer-function for an example of this, using the Fetch api. 

I'll close this due to the above two workarounds.

**Comment by PrescottJRynewicz** [comment]
Thanks for the quick responses @benw-pusher !
