### ISSUE TITLE
Connection fails after second disconnection

### ISSUE THREAD

**Issue by lucadegasperi** [pusher/pusher-js#553]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

- First page load pusher connects `initialized -> connecting`
- `connecting -> connected`
- Disconnect Wi-Fi
- `Pusher :  : [{"type":"PusherError","data":{"code":1006}}]`
- `connected -> connecting`
- `connecting -> unavailable`
- Reconnect Wi-Fi
- `unavailable -> connecting`
- `connecting -> connected`
- Disconnect Wi-Fi
- `Pusher :  : [{"type":"PusherError","data":{"code":1006}}]`
- `connected -> failed`

No longer reconnects even if I try with a timeout

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

**What is the expected behavior?**

I need a way to have a long running page (days, weeks or years at a time) be able to always receive events despite the unstable connections. Is there a way to achieve this?

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**

Using pusher 7.0.3 with Firefox 91.0 on MacOS  but the same issue happens in all the other browsers as well

**Comment by bertbijnens** [comment]
I have the same issue, it also occurs on long running pages on every browser.

**Comment by lucadegasperi** [comment]
@amad I was using Pusher with a custom web sockets server that does not support all the fallbacks pusher has. Had to use a fork of Pusher which does not fall-back to protocols other than websockets.

**Comment by benw-pusher** [comment]
Thanks @lucadegasperi 
For the future, you can disable other protocols using the [disabledTransports](https://github.com/pusher/pusher-js#disabledtransports-array) configuration option.

**Comment by lucadegasperi** [comment]
@benw-pusher that won't solve the issue as pusher saves the connection and attempts inside localStorage. This is the fork I'm using: https://github.com/findmate/pusher-js-websocket-only

**Comment by benw-pusher** [comment]
You would need to delete the cache to overcome this, but for any new device/browser connecting it should work
