### ISSUE TITLE
Pusher.trigger throws ETIMEDOUT with PusherRequestError before request ever makes it to Pusher

### ISSUE THREAD

**Issue by jchiatt** [pusher/pusher-js#555]
**Do you want to request a *feature* or report a *bug*?** 
Bug 🐛 

**What is the current behavior?**
Intermittently, `pusher.trigger` is throwing a `PusherRequestError` with a reason of `connect ETIMEDOUT x.xx.xxx.xxx:443`. 

![Screen Shot 2021-09-22 at 10 01 27 AM](https://user-images.githubusercontent.com/2353845/134687086-884f550f-121d-4de3-afb3-2a32126a0d87.png)

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
I have not yet figured out how to reproduce this consistently. I can provide a code sample when I figure that out. Posting this in advance to see if anyone else has seen this issue so we can compare notes and narrow down possible culprits.

Currently I'm investigating two possible culprits: 

- Character encoding: some of the payloads being sent may have characters that can't be encoded properly
- Maxed out threadpools - I attempted to increase `UV_THREADPOOL_SIZE` but that didn't seem to fix the issue yet. But seeing as the error seems to happen somewhere around the DNS phase of the request, I thought it could have something to do with resource capacity.

**What is the expected behavior?**
`pusher.trigger` requests should always reach Pusher, or at least provide a better error of _why_ the request couldn't be sent.

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
Currently I'm seeing this on Ubuntu 18.04 and Debian 10, running as a node process. I never saw this error in `5.0.0`, though I can't say which newer versions also worked at this time. I just recently began seeing this error this week, after upgrading dependencies.

**Comment by benw-pusher** [comment]
Hi, thanks for reporting this. Just to confirm, is this issue happening in our JS library, or our [NodeJS library](https://github.com/pusher/pusher-http-node)? 

I've done some digging on this and it does seem that increasing `UV_THREADPOOL_SIZE` is a common solution for timeouts around the DNS phase of requests, but you have already increased that. 
Does the issue occur during particularly busy periods where you might be publishing a large volume of events in a short pace of time? 

From our side it looks as though the us2 cluster has been performing as expected over recent days with no latency or error spikes. Do you have any timestamps of these errors so I can dig deeper?
