### ISSUE TITLE
I keep getting this issue when trying to use this package with Laravel-Echo. 

### ISSUE THREAD

**Issue by pneves001** [pusher/pusher-js#562]
**Do you want to request a *feature* or report a *bug*?**

Bug
"pusher-js": "^7.0.3",

**What is the current behavior?**

pusher.js:3083 Uncaught TypeError: Cannot read properties of null (reading 'map')
    at Object.<anonymous> (pusher.js:3083)
    at __nested_webpack_require_319__ (pusher.js:29)
    at Object.<anonymous> (pusher.js:5012)
    at __nested_webpack_require_319__ (pusher.js:29)
    at Object.<anonymous> (pusher.js:2862)
    at __nested_webpack_require_319__ (pusher.js:29)
    at Object.<anonymous> (pusher.js:4086)
    at __nested_webpack_require_319__ (pusher.js:29)
    at Module.<anonymous> (pusher.js:9685)

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

**What is the expected behavior?**

An extensive internet search has giving me no results on how to fix this issue.

I expect it to work as a dependency with Laravel-Echo.  

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
MacOS Big Sur, 
Chrome, Brave

**Comment by benw-pusher** [comment]
Could you share the code that is causing this issue so we can investigate?

**Comment by pneves001** [comment]
Ok I think I fixed it. The pusher-js package in node has more than one pusher.js files. The one that it was referencing was the one for node and not the browser based file. So it was failing to find a library. Once I pointed the require statement correctly it started working.

**Comment by benw-pusher** [comment]
Thanks for confirming the fix
