### ISSUE TITLE
[Vuejs] init Pusher after vue is initalised

### ISSUE THREAD

**Issue by FrancoisDucobu** [pusher/pusher-js#571]
Hello Everyone,

It's not really an issue but a support question.

We developped a vuejs app.
This app is intended to use with multi tenant.

We want to use different credential per customer.
I think the best way is to store the apikey in the database and retrieve the apikey when the app is loaded.

But in the docs, Pusher needs to be initialised before calling the init method of vue. so before any apicall...

Is there a way to initialised pusher after the init of vuejs ?

Regards,

François

**Comment by benw-pusher** [comment]
Hi! For support queries you can head over to https://support.pusher.com/hc/en-us and log a ticket. 
In any case, it should be possible to initialise Pusher at any point, it does not have to be on app load. Vue provides https://vuejs.org/v2/api/#mounted which is 'Called after the instance has been mounted' - you should be able to query the DB and initialise Pusher from here. 

If this doesn't work please get in touch with us via support at the above link.
