### ISSUE TITLE
Data exchange between different language over channels

### ISSUE THREAD

**Issue by ali2210** [pusher/pusher-js#576]
**Do you want to request a *feature* or report a *bug*?** 
Yes

**What is the current behavior?**
something went wrong

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

When I run my project following instruction return 

**`Pusher :  : ["Event recd",{"event":"pusher_internal:subscription_succeeded","channel":"encrypted_analyticaAmino","data":{}}]`**

The above code handle event affect after trigger
I will not understand that why data return empty. However, I run same example with Debug console. On Event creator data will generate like that 
{key : "A", value : 2},{...}
on the other hand server code

`**pusherClient.TriggerMulti([]string{"encrypted_analytica"},"dashboard", data)**`

**What is the expected behavior?**
{key : "A", value : 2},{...}

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
Chrome

**Comment by benw-pusher** [comment]
The event you have shared is an [internal event](https://pusher.com/docs/channels/using_channels/events/#pushersubscription_succeeded-846777246) that shows that subscription to the channel `encrypted_analyticaAmino` has been successful. It is not an event that shows the receipt of the data sent either via the Debug Console or your server code. 

To correctly listen for events sent via the debug console or your server you will need to bind to the event. See https://pusher.com/docs/channels/using_channels/events/#binding-on-the-channel. 

Finally, I notice that your server appears to be publishing to the channel `encrypted_analytica` while your client is subscribing to `encrypted_analyticaAmino`. You will need to ensure your client and server are using the same channel name to correctly send and receive events.

**Comment by ali2210** [comment]
Thankyou @benw-pusher
