### ISSUE TITLE
Allow only specific members to trigger client events

### ISSUE THREAD

**Issue by Luismahou** [pusher/pusher-js#58]
Hi, I have the following use case:
- A private channel is created for a set of users.
- One member is responsible for broadcasting events.
- The rest of the members only receive events.

This is what I'm doing currently to trigger an event:
- An ajax call is made to my server.
- The server checks that the user is allowed to broadcast.
- If user is allowed, pusher server api is used to broadcast the event to all users.

What I'm doing is a bit slow (average 1-2 seconds) due to latency, server warm up, etc.

Using [client events](http://pusher.com/docs/client_api_guide/client_events#trigger-events) would make the whole process faster. The problem with client events is that there is no way to specify which members are allowed to broadcast events.

**Would you consider extending the security model around client events?**

As a first idea, I propose to extend the authentication mechanism:
- When the server responds to `/pusher/auth/` [step 6 of your diagram](http://pusher.com/docs/authenticating_users), add a field to specify the channel names where the user can trigger client events. The field will be hashed like the `auth` field.
- Then, when a user tries to trigger a client event, pusher server validates that is allowed to do so.

**Comment by darkyen** [comment]
+1 On this model, although it seems to be a limited use-case.

**Comment by hph** [comment]
Since there hasn't been any activity on this issue for more than a year, and, more importantly, there are no plans to implement this at this time (it involves more than just pusher-js), I'm closing this issue.

**Comment by joshmaines** [comment]
Isn't this a feature of Chatkit now?
