### ISSUE TITLE
Respect user specified value for forceTLS option

### ISSUE THREAD

**Issue by callmiy** [pusher/pusher-js#585]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If the client's protocol is `https`, `forceTLS` option will be ignored. In my case, while developing, I connect to my app over `https`, but, for some technical reasons, need to connect to the websockets server over `http://localhost:<port>`. This is currently impossible.

The `README.md` says, about `forceTLS`, "When set to `false` the library will attempt non-TLS connections first.". But this is not the case. When the browser's protocol is `https`, `forceTLS` is ignored all together.

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
The bug is in `src/core/config.ts`, lines 112-118 in `shouldUseTLS` function. Probably we should do this:
```js
function shouldUseTLS(opts: Options): boolean {
  const { forceTLS } = opts;

  // Respect user's forceTLS option if specified
  if (forceTLS !== undefined) {
    return !!forceTLS;
  }

  return Runtime.getProtocol() === "https:";
}
```

**What is the expected behavior?**
Respect user specified value for `forceTLS` option

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**

**Comment by benw-pusher** [comment]
Are you using any of the other configuration parameters to override the host/port or enabled transports here?

**Comment by callmiy** [comment]
Thanks for replying. Below is my `options` object:

```javascript 
const options = {
  broadcaster: "pusher",
  key: "some-key",
  wsHost: "localhost",
  wsPort: 5013,
  wssPort: 5013, // without this, I get wss://localhost without the port
  wsPath: "/custom-path",
  forceTLS: false,
  disableStats: true,
  enabledTransports: ["ws"], // without this, I get error: Access to XMLHttpRequest at ... has been blocked by CORS policy: Response to preflight request doesn't pass access control check,
};
```

**Comment by benw-pusher** [comment]
Thanks for sharing. Are you using a custom websocket server instead of the official Pusher service? Does the library work when connecting to the Pusher service?

**Comment by benw-pusher** [comment]
Closing as I've had no response. Please update with the requested information, or get in touch with us via support - support.pusher.com.

**Comment by jappi00** [comment]
Hello @benw-pusher,

I have the exact same problem. I'am using a custom web socket server. I don't believe pusher allows unsecure websocket connections?
