### ISSUE TITLE
Use secure random generator instead of pseudo-random generator

### ISSUE THREAD

**Issue by thegoncalomartins** [pusher/pusher-js#586]
Hello 👋

I've opened a [PR](https://github.com/pusher/pusher-js/pull/584) some days ago. The goal of the PR is to change the way random numbers are generated. The motivation for this is because my team built a library that uses pusher as a dependency and that library was analyzed by a SAST tool which alerted that using pseudo-random numbers for session IDs is not secure enough. I was wondering if you could review the PR and give your opinion on this matter.
Thanks in advance.

**Do you want to request a *feature* or report a *bug*?**

- Feature

**What is the current behavior?**

- Using `Math.random()`

**What is the expected behavior?**

- Using `crypto.randomInt()` or `crypto.getRandomValues()` 

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**

- All

**Comment by benw-pusher** [comment]
Reopening as this has not been resolved

**Comment by benw-pusher** [comment]
This has been resolved in version 7.4.0
