### ISSUE TITLE
Server Side get infos

### ISSUE THREAD

**Issue by JonhnyDev** [pusher/pusher-js#592]
I'm getting server in route error 404 on this side
code: 

const Pusher = require('pusher')
const Env = use('Env')

const pusher = new Pusher({
    appId: Env.get('PUSHER_APP_ID'),
    key: Env.get('PUSHER_APP_KEY'),
    secret: Env.get('PUSHER_APP_SECRET'),
    cluster: Env.get('PUSHER_APP_CLUSTER'),
    useTLS: true
})

    const res = await pusher.get({path: `/apps/1325870/channels`});
or: 
    const res = await pusher.get(`/apps/1325870/channels`);
Error:
    at new RequestError (C:\Users\Jonathan\Desktop\Trabalho\CHATCOMPOSER\CHATCOMPOSER-PRODUCAO\node_modules\pusher\lib\errors.js:13:16)
    at C:\Users\Jonathan\Desktop\Trabalho\CHATCOMPOSER\CHATCOMPOSER-PRODUCAO\node_modules\pusher\lib\requests.js:61:17
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async EventEmitter.<anonymous> (C:\Users\Jonathan\Desktop\Trabalho\CHATCOMPOSER\CHATCOMPOSER-PRODUCAO\start\events.js:20:18) {
  name: 'PusherRequestError',
  message: 'Unexpected status code 404',
  url: 'https://api-sa1.pusher.com/apps/1325870/apps/1325870/channels?auth_key=<key>&auth_timestamp=1650448860&auth_version=1.0&auth_signature=<signature>',
  error: undefined,
  status: 404,
  body: '404 NOT FOUND\n'

link doc:
https://pusher.com/docs/channels/library_auth_reference/rest-api/#get-users

**Comment by benjamin-tang-pusher** [comment]
Getting application state with the HTTP api needs to be done from a server library such as [this Node one](https://github.com/pusher/pusher-http-node), not a client library such as pusher-js. Are you trying to do this in a server library?

**Comment by JonhnyDev** [comment]
yes i am used this tutorial:

https://pusher.com/tutorials/adonis-realtime/

**Comment by benjamin-tang-pusher** [comment]
You have ended up adding "apps/1325870/" twice to your url (you can see this in your error message: "url: '[https://api-sa1.pusher.com/apps/1325870/apps/1325870/channels?](https://api-sa1.pusher.com/apps/1325870/apps/1325870/channels?auth_key=)"  The library will already add this for you.

Can you try pusher.get({ path: "/channels" }) instead of pusher.get({path: "/apps/1325870/channels"})?
