### ISSUE TITLE
Pusher connection object behavior

### ISSUE THREAD

**Issue by kapso** [pusher/pusher-js#596]
In my react web app does the following code create 2 connections or is it still counted as 1 connection from the Web app? (asking from a pricing point of view - https://pusher.com/channels/pricing)

```js
const pusher1 = new Pusher(pusherKey, { cluster: cluster });
const pusher2 = new Pusher(pusherKey, { cluster: cluster });
```

In case, the library versions matter...

```
"pusher-js": "7.0.6"
"react": "18.1.0"
```

**Comment by benw-pusher** [comment]
That will create two connections. You can read more about concurrent connections at [How Are Concurrent Connections Counted?](https://support.pusher.com/hc/en-us/articles/4412239949969-How-Are-Concurrent-Connections-Counted-?source=search&auth_token=eyJhbGciOiJIUzI1NiJ9.eyJhY2NvdW50X2lkIjo1MjIxNjUsInVzZXJfaWQiOjE5MDgzMjgyMjI2NzMsInRpY2tldF9pZCI6NDY5ODk1LCJjaGFubmVsX2lkIjo2MywidHlwZSI6IlNFQVJDSCIsImV4cCI6MTY1NDg0Njg5N30.-21Ew9cGbFz5zZbsFGbpkaUsIFxZQsgRfEbstj4DXIk)
