### ISSUE TITLE
How to manually ping

### ISSUE THREAD

**Issue by joshfester** [pusher/pusher-js#602]
I have functions that I only want to run when I can guarantee that Pusher is connected. Querying the connection state isn't accurate enough due to delays between state changes.

Is there an accepted way to manually ping to get the current state? I found that this function seems to work:

`pusher.connection.retryIn(0);`

Is this too much of a hack? Is there a better solution?

**Comment by benjamin-tang-pusher** [comment]
Let us know if you encounter any issues with that method. I will close this issue for now.
