### ISSUE TITLE
Pusher missing messages after connect to or disconnect from VPN

### ISSUE THREAD

**Issue by tianhuat** [pusher/pusher-js#603]
Hi,

Please refer to the logging message with illustration here:
https://www.loom.com/share/08668e6021e5435eb7a41c755a1ef0c3

To summarize, we have two situations which will result in loss of messages:
a. connect to vpn - detected fast, and few seconds of message loss
b. disconnect from vpn - no detection at the start and result in 1-2 minutes loss

Let me know is there a workaround for that?

Thanks!

**Comment by CodySchaaf** [comment]
Seeing the same thing. After about 2 minutes of no new messages you get a new websocket connection and a new `socket_id`.

 I can create a new Pusher instance right when I detect a loss of connection and get a new websocket going right away as a work around.

**Comment by benw-pusher** [comment]
Closing this out with the above explanation and configuration options.
