### ISSUE TITLE
react native background

### ISSUE THREAD

**Issue by SokolovRU** [pusher/pusher-js#604]
Hello. I have a question, can I use pusher in background mode?
Now it stops working when I minimize the application.
If there is no ready-made solution, then you can look at this library and help combine your pusher and work in the background - https://github.com/Rapsssito/react-native-background-actions

**Comment by fbenevides** [comment]
Hi @SokolovRU, good news! 

We've just launched our official [React Native SDK](https://github.com/pusher/pusher-websocket-react-native). Could you check if it fits your needs? 

Thanks

**Comment by SokolovRU** [comment]
cool. I will study it in the near future. I'll close the topic for now
