### ISSUE TITLE
Export ChannelAuthorizer function so it can be used to extend functionality on a ChannelAuthorizationHandler

### ISSUE THREAD

**Issue by gcrespi** [pusher/pusher-js#610]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
I want to use the custom ChannelAuthorizationHandler configuration to be able to refresh the actual accessToken on my application (if needed) before the API call is made to authorize a channel with the backend.
The problem with that is I have to rewrite the whole logic that the function `ChannelAuthorizer` already does on my side.
So it would be nice to have access to it in order to do something like:

```
const authOptions: AuthOptions<any> = {
    endpoint: `endpoint`,
    transport: 'ajax',
    headers: {key: value},
};
const pusher = new Pusher(appKey, {
    channelAuthorization: {
        ...authOptions,
        customHandler: (params, callback) => {
            getValidSessionOrRefresh()
                .then((activeSession) => {
                    const staticHeaders = authOptions.headers || {};
                    const headers = { ...staticHeaders, Authorization: `Bearer ${activeSession}` };
                    const newAuthOptions = { ...authOptions, headers };
                    ChannelAuthorizer(newAuthOptions)(params, callback);
                })
                .catch(() => {
                    //...
                });
        }
    },
});
```

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
version of pusher-js 7.2.0

**Comment by benw-pusher** [comment]
Hi @gcrespi. Just to confirm what you are looking for here. First, your use case doesn't use static header values and so using the `channelAuthorization.headers` config param isn't viable as it only allows you to set the headers once. 
You would like to be able to combine the custom handler feature with the in built authentication mechanism so that you can customise the headers of the HTTP auth request with but without needing to also implement the HTTP auth request itself.
Is that correct?

**Comment by kre8or69** [comment]
I'm not sure if its the same intention as @gcrespi, but thats my use case. 

Essentially I have to attach and Auth header to the request and if we have to refresh the auth token or the token is changed from what was used on creation of the pusher connection this isn't really possible anymore as the ability to update `config.auth.headers` or `channelAuthorization.headers` isn't possible post v7.0.6. 

Being about to specify a custom handler would allow us to regain that functionality.

**Comment by benw-pusher** [comment]
Thanks for clarifying. I have shared this internally and we agree that being able to change the auth options after initialisation is certainly a useful capability. However, at this stage we can't commit to a release or time frame for release. We advise that you use the workaround to create a custom handler that updates the headers and handles the POST request to the auth endpoint.

**Comment by kre8or69** [comment]
Thanks for the update!!

**Comment by benw-pusher** [comment]
We recently released the new `headersProvider` param which allows you to specify a function tht returns the headers to be sent when the auth endpoint is called. See https://github.com/pusher/pusher-js#channelauthorization-object for details. This should meet the request here.
