### ISSUE TITLE
Authentication should support CORS

### ISSUE THREAD

**Issue by ryansmith3136** [pusher/pusher-js#62]
I am going to be brief with my bug report. If you need a more thorough description, let me know.

I am assuming that to properly handle the client's request to `/pusher/auth` I need to use cookies.

I expected that I could have pusher-js authenticate against my backend HTTP service across origins. I realized that the requests to `/pusher/auth` did not contain any cookies. Upon further inspection, I found that the pusher-js makes a new XHR object to send to the authentication endpoint of my service. This XHR object does not touch the `withCredentials` field which, I believe, is required for CORS.

My request is that you provide support for authenticating across origins. Perhaps that is by setting the `withCredentials` field.

**Comment by chris-martin** [comment]
I just spent a while tracking this down. The documentation perhaps could make it a little more clear that jsonp is the *only* supported way to do cross-origin auth.

**Comment by fiatjaf** [comment]
Today you would have to do

```javascript
Pusher.Runtime.createXHR = function () {
  var xhr = new XMLHttpRequest()
  xhr.withCredentials = true
  return xhr
}
```

**Comment by tadas-s** [comment]
Hello,

Are there any plans to implement this? 4 years later, IE9 is largely irrelevant browser.

Cheers guys
