### ISSUE TITLE
Timo 

### ISSUE THREAD

**Issue by Muhammad1230** [pusher/pusher-js#622]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

**What is the expected behavior?**

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**

**Comment by Muhammad1230** [comment]
Hi how are you

**Comment by benw-pusher** [comment]
Hi, can you let us know what the problem you are facing is?

**Comment by benw-pusher** [comment]
As we haven't had a response and there isn't any info in the report I will close this. Please reopen with more detail if you need support.
