### ISSUE TITLE
How to handle duplicate tabs causing duplicate events

### ISSUE THREAD

**Issue by RohitSaroj** [pusher/pusher-js#632]
I'm in a scenario wherein I need to auto-print invoice as soon as new orders lands up on web browser, this I'm doing using pusher to get a new-order event.
The issue here is when the current tab is duplicated, all of those tab calls for print resulting in duplicate prints.
I need to make sure only print is done even though there are multiple tabs with multiple pusher instances.
Is there any way to handle this via pusher?

**Comment by benw-pusher** [comment]
To get around this you could implement a shared worker, which allows you to share resources across multiple tabs. The shared worker would handle the Pusher connection and subscription, and also receive the Channels events. You could then look at handling the event only once, which should cause only a single print job to be created. 

I've shared a _super_ simple example of a shared worker setup with the 

```
//sharedw.js
importScripts('https://js.pusher.com/7.0/pusher.worker.min.js')
  // An array of the clients/tabs using this worker
  const clients = [];

  console.log('init')

  self.addEventListener("connect", function(evt){

    // Add the port to the list of connected clients
    var client = evt.ports[0];
    clients.push(client);
  
    // Start the worker.
    client.start();
  });
  
  
var pusher = new Pusher('APP_ID', {
      cluster: 'CLUSTER'
    })

   var channel = pusher.subscribe('new-invoice')

   ///bind to event and then print
    channel.bind('new-doc', event => {
      console.log('new-doc')
      clients.forEach(client => {
        client.postMessage(event)
      });
    });
```
 
```
//app-sw.js

(function() {
   

      if (typeof(window.SharedWorker) === 'undefined') {
        throw("Your browser does not support SharedWorkers")
      }
      
      var worker = new SharedWorker("./sharedw.js");
      
      //receive events from shared worker
      worker.port.onmessage = function(evt){
        console.log(evt.data);
        
      };
      
      worker.onerror = function(err){
        console.log(err.message);
        worker.port.close();
      }

      worker.port.start();

})();
```

**Comment by RohitSaroj** [comment]
`if (typeof(window.SharedWorker) === 'undefined') {
        throw("Your browser does not support SharedWorkers")
      }`

This is an issue. We need to support all browsers except IE, Currently SharedWorkers is not supported by many browsers.

**Comment by benw-pusher** [comment]
I'll close this out as it isn't a bug with the pusher-js library. If you need further assistance please get in touch with us via [support](https://support.pusher.com/hc/en-us/requests/new).
