### ISSUE TITLE
Pusher suddenly cant receive events.

### ISSUE THREAD

**Issue by purefml** [pusher/pusher-js#637]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Pusher not receiving any events coming from laravel backend.

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

here are the following configs: 

``
 this.pusher = new Pusher("pusherkey", {
        forceTLS: false,
        cluster: 'mt1',
        wsHost: 'auth.wsHost',
        wsPort: 6001,
        disableStats: true,
        authEndpoint: 'auth.endpoint',
        auth: {
          headers: {
            Authorization: `${auth.authSession.token.token_type} ${auth.authSession.token.access_token}`,
          },
        },
      })
      this.pusher.subscribe(`private-session-tracker.${auth.authSession.data.data.id}`)
      this.pusher.subscribe(`private-order-tracker.${auth.authSession.data.data.id}`)

      const callback = (eventName: any, data: any) => {
        console.log(eventName, "EVENTNAME", data, "DATA")
        if (eventName === `App\\Events\\OrderStatusChanged` && data) {
          // push data to redux.
          if (auth.isSiteNotificationsEnabled) {
            setOngoingOrders(data)
            toggleUnreadNotificationToTrue()
            if (JSON.stringify(NavigationService.getCurrentRoute(NavigationService.getNavigator().state.nav)) === `"Notifications"`) {
              getNotifications()
            }
          }
        }
        if (eventName === `App\\Events\\TokenRevoked` && data) {
          if (data.token_revoked) {
            logout()
            Alert.alert(
              'Oops!',
              `New session detected. you will be logged out.`,
              [
                {
                  text: 'Okay',
                },
              ],
              { cancelable: false },
            )
          }
        }
      };
      this.pusher.bind_global(callback)
``

**What is the expected behavior?**
Once and event was triggered by the backend, following callback functions/conditions should run.

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**

 "pusher-js": "^7.2.0", no we haven't updated our pusher package eversince we got it to work 3 months ago.

**Comment by purefml** [comment]
Additional logs 

``
 LOG  Pusher :  : ["Event recd",{"event":"pusher_internal:subscription_succeeded","channel":"private-session-tracker.mia-at-gmailcom"}]
 LOG  Pusher :  : ["No callbacks on private-session-tracker.mia-at-gmailcom for pusher:subscription_succeeded"]
 LOG  Pusher :  : ["Event recd",{"event":"pusher_internal:subscription_succeeded","channel":"private-order-tracker.mia-at-gmailcom"}]
 LOG  Pusher :  : ["No callbacks on private-order-tracker.mia-at-gmailcom for pusher:subscription_succeeded"]
 ``

**Comment by benw-pusher** [comment]
You should not need to specify the host or port when connecting to the official Pusher service. Can you remove these parameters? 
Can you share what the behaviour to trigger an event is.- is there any error encountered when triggering an error? It appears the client is subscribing correctly so the issue may be with triggering events. Do they show in the Debug Console? You can access the Debug Console by navigating to dashboard.pusher.com, logging in and selecting the Channels app in question. From there you can click the Debug Console link.

**Comment by purefml** [comment]
No errors when logging, Removing params does not work either. Expected behavior, is that when user logs in from another device that event would trigger and send out a boolean = true in order for the previous device to be logged out. Used to work last week then suddenly i can no longer receive the event/payload, we also haven't touched any of our configs or codes for 3 months.

Laravel Snippet Code:
``
//Token Revoked
class TokenRevoked implements ShouldBroadcast
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    public User $user;
    /**
     * Create a new event instance.
     *
     * @return void
     */
    public function __construct(User $user)
    {
        $this->user = $user;
    }

    /**
     * Get the channels the event should broadcast on.
     *
     * @return \Illuminate\Broadcasting\Channel|array
     */
    public function broadcastOn()
    {
        return new PrivateChannel('session-tracker.' . $this->user->getRouteKey());
    }

    public function broadcastWith()
    {
        return [
            'token_revoked' => true,
        ];
    }
}
``
``
//Token Function
if ($tokens->isNotEmpty()) {
            event(new TokenRevoked($user));

            $tokens->each->revoke();

            foreach ($user->carts as $cart) {
                if (
                    $cart->model->isApcCardBuy1Take1Valid() &&
                    !empty($cart->extra->apc_card) &&
                    !$cart->model->isDoubleDealProduct()
                ) {
                    $originalCart = clone $cart;
                    $cart->forceDelete();
                    event(new RepositoryEntityDeleted(app(CartRepository::class), $originalCart));
                }
            }
        }
``
``
//Route
Broadcast::channel(
    'session-tracker.{id}',
    fn ($user, $id) => (string) $user->getRouteKey() === (string) $id,
    ['guards' => 'api']
);
``
