### ISSUE TITLE
User is not authenticated 

### ISSUE THREAD

**Issue by renteriadev** [pusher/pusher-js#640]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Hi
I'm trying to authenticate my user but the only thing that I get this
`signin_requested: false`
`user_data:  null`

I do not know if i have wrong config or I'm missing something else

![pusher-not-auth-user](https://user-images.githubusercontent.com/94961292/200147663-23ea71c1-db27-48c2-9faf-9dfa089088b3.png)

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

It's my current config of Pusher class (client):
```
        const pusher = new Pusher'PUSHER_KEY, {
            cluster: PUSHER_CLUSTER,
            userAuthorization: {
                customHandler: async (payload, callback) => {
                    const {socketId, channelName} = payload;
                    const body = new URLSearchParams({
                        'socket_id': socketId,
                        'channel_name': channelName
                    });
                    const response = await fetch('URL_SERVER, {
                        method: 'post',
                        body,
                        headers: {
                            "Authorization": "Bearer TOKEN",
                        },
                    })
                        .catch(error => {
                            console.log(error)
                        })
                    callback(response.json());
            }
        });
```

**What is the expected behavior?**
In this variable `signin_requested: false`, `user_data:  null`
be able to see something like:

```
{
  "auth": "7b52860750200c41a3ad:db93361ff794f5ba6834a4651cf85095afb1069a3c957d48cfa1fd2bbb1bcced",
  "channel_data": "{\"user_id\":\"12345\",\"user_info\":{\"id\":\"12345\",\"user_info\":{\"name\":\"John Smith\"}}}"
}
```

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
The current version that I'm using is: `7.2.0/pusher.min.js`
Thanks

**Comment by MeenaAlfons** [comment]
Hi @renteriadev,

One thing I noticed in the config you shared is that you are using an option `userAuthorization`. The correct option to use is called `userAuthentication`. Here is the documentation for [User Authentication](https://pusher.com/docs/channels/using_channels/user-authentication/).

I hope this resolves the issue. Let me know how it goes after changing this option name.

**Comment by MeenaAlfons** [comment]
There is another thing that needs to be fixed in the code you shared. The callback method needs to be called with `callback(error, data)`. So you need to pass the data as a json object to the second parameter like `callback(null, data)`.

In your case, the result of `response.json()` is a promise not a JSON object. You need to call `response.json().then(data => {})` in order to get the JSON object of the body in the variable `data`.

Here is how this is done:
```js
            response.json().then(data => {
                callback(null, data);
            });
```

I hope this helps.

**Comment by benjamin-tang-pusher** [comment]
Due to the lack or response to Meena's suggestions, I'm going to close this issue.
