### ISSUE TITLE
When AuthToken is updated in the project, the AuthToken used in the pusher instance is not updated.

### ISSUE THREAD

**Issue by UmitNazim** [pusher/pusher-js#659]
The Pusher instance is as follows. My problem is;
When AuthToken is updated in the project, the AuthToken used in the pusher instance should be updated.

```
    let pusher = new Pusher(process.env.VUE_APP_PUSHER_KEY, {
      cluster: 'eu',
      channelAuthorization: {
        transport: 'ajax',
        headers: { Authorization: AuthToken },
        endpoint: `${process.env.VUE_APP_API_BASE_URL}/user/pusher/auth`,
      },
    })
```
**is there anyway to do that ?**

-  Version : ^7.3.0
- Framework : Vue.JS (Version 3)

**Comment by benjamin-tang-pusher** [comment]
Hi, our newer version of pusher-js 8.0.1 now has a `headersProvider` function, where you can get your new AuthToken if it has changed after initialization. Does it solve your use case?

**Comment by benjamin-tang-pusher** [comment]
I will close this ticket, please see the latest version of our library if it lets you update one of your authorization headers.
