### ISSUE TITLE
WebSocket connection to wss failed

### ISSUE THREAD

**Issue by erickneverson** [pusher/pusher-js#678]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
`WebSocket connection to wss://mydomain.com:6001/app/appkey failed`. With Postman, I can connect and receive messages successfully with the same protocol.
**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
My soketi.app websockets server is paired with my Laravel app (self hosted Pusher) in the cloud. The application sits behind a load balancer which enforces https protocol so we need to enable wss for the socket server. 
**What is the expected behavior?**
Successful connection via pusher-js library in the browser for my web application.
**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
pusher-js v7.2.0
Google Chrome 108.0.5359.124
OS Mac and Ubuntu 20
```
new Pusher(pusherKey, {
      wsHost: wsHost,
      wsPort: 6001,
      wssPort: 6001,
      forceTLS: true,
      encrypted: false,
      disableStats: true,
      enabledTransports: ['ws', 'wss'],
      channelAuthorization: {
        endpoint: importUrl + 'broadcasting/auth',
        headers: {
          Authorization: 'Bearer ' + getAccessToken(),
        },
      },
    }
```
Apologies if this is the wrong platform to raise such issues.

**Comment by erickneverson** [comment]
Update:
This behavior appears in Chrome browser.  I was able to successfully connect to my soket server and receive broadcast messages.  Investigating...

**Comment by benw-pusher** [comment]
Our library is designed for use with the official Pusher service and we aren't able to guarantee support for, or provide assistance with, using self hosted websocket servers.
