### ISSUE TITLE
cannot use in react-native 

### ISSUE THREAD

**Issue by geoff8888** [pusher/pusher-js#688]
Hi, trying to port it to RN 0.71.X

There's no error message, but just using "new Pusher" in the code will cause the whole class to fail.  You cannot instantiate it.

```
import Pusher from 'pusher-js/react-native';
...
const client = new Pusher(options.key, options);   //instantiating new class containing this will fail, haven't run this line yet

//Changed it to confirm the problem
const client:any = {};   //OK!

```

Thanks!

**Comment by geoff8888** [comment]
> Hi, trying to port it to RN 0.71.X
> 
> There's no error message, but just using "new Pusher" in the code will cause the whole class to fail. You cannot instantiate it.
> 
> ```
> import Pusher from 'pusher-js/react-native';
> ...
> const client = new Pusher(options.key, options);   //instantiating new class containing this will fail, haven't run this line yet
> 
> //Changed it to confirm the problem
> const client:any = {};   //OK!
> ```
> 
> Thanks!

Ok, apparently, it has been moved to https://github.com/pusher/pusher-websocket-react-native/
it works on 7.1.1-beta

/
[pusher-websocket-react-native](https://github.com/pusher/pusher-websocket-react-native)

**Comment by Stevemoretz** [comment]
That is even more useless than this one
https://github.com/pusher/pusher-websocket-react-native/issues/75

**Comment by fbenevides** [comment]
hey all, can you please update to the latest version (8.0.2)?

**Comment by geoff8888** [comment]
> hey all, can you please update to the latest version (8.0.2)?

Thanks a lot!
