### ISSUE TITLE
Can't Subscribe to Presence Channel

### ISSUE THREAD

**Issue by MehulZR** [pusher/pusher-js#691]
**Do you want to request a *feature* or report a *bug*?**
This issue is to report a bug.

**What is the current behavior?**
Client Side is not able to subscribe to Presence Channels. Except that everything is working as Intended.
The request for the authorization reaches My backend and the request is authorized successfully but the Connection request( only for the presence channel) doesn't reach the Pusher Server.

**Client Side Code**
```javascript
const pusher = new Pusher(API_KEY, { cluster: APP_CLUSTER });
const presenceChannel = pusher.subscribe("presence-chat");
presenceChannel.bind("message", (data) => console.log(data));
```

**Server Side Code**
```javascript
app.post("/pusher/auth", async (req, res) => {
  const socket_id = req.body.socket_id;
  const channel_name = req.body.channel_name;
  const authResponse = pusher.authorizeChannel(socket_id, channel_name);
  res.send(authResponse);
});
```

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
 I am a first time user of Pusher and I am using Chrome with Fedora 37
 Version of Pusher Library : 5.1.2

**Comment by benw-pusher** [comment]
When authenticating presence channel you need to also include user information - see https://pusher.com/docs/channels/server_api/authorizing-users/#channel-subscription-authorization for info. For example, 

```app.post("/pusher/auth", function (req, res) {
  const socketId = req.body.socket_id;
  const channel = req.body.channel_name;
  const presenceData = {
    user_id: "unique_user_id",
    user_info: { name: "Mr Channels", twitter_id: "@pusher" },
  };
  const authResponse = pusher.authorizeChannel(socketId, channel, presenceData);
  res.send(authResponse);```
