### ISSUE TITLE
Hi everyone ! if anyone have code example @pusher/pusher-websocket-react-native integration with laravel-echo please share the code

### ISSUE THREAD

**Issue by TasbeelZahid** [pusher/pusher-js#696]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

**What is the expected behavior?**

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**

**Comment by HaidarZ** [comment]
@TasbeelZahid  have you found a solution or done any progress regarding this issue?

**Comment by benjamin-tang-pusher** [comment]
This was answered in https://github.com/pusher/pusher-websocket-react-native/issues/76. Echo is not supported.

I will close this issue.
