### ISSUE TITLE
hoping headerProviders in pusher-js to capable of async/await

### ISSUE THREAD

**Issue by richieteh94** [pusher/pusher-js#699]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
headersProvider in channel client channelAuthorization (Object) does not await any function passed in.

**What is the expected behavior?**
allow to headersProvider to await function.

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
pusher-js v7.6.0

**Comment by sunrick** [comment]
I have this use case as well. I need to use an access token that can only be fetched asynchronously.

[This is the location in the code.](https://github.com/pusher/pusher-js/blob/1a5ab73dd9fd412a85113bab329e650db0ae31b3/src/runtimes/worker/auth/fetch_auth.ts#L25))

I'd be be happy to submit a PR if needed. I'm not sure of downstream effects of making this change though.

**Comment by marcosmartinez7** [comment]
Same issue here, whats the idea of that function if you cannot call an async method? 🤔

**Comment by trymbill** [comment]
This was closed as complete, but was it ever implemented? Is there a way to add authorization headers asynchronously? How did you end up getting around this @marcosmartinez7?

**Comment by marcosmartinez7** [comment]
> This was closed as complete, but was it ever implemented? Is there a way to add authorization headers asynchronously? How did you end up getting around this @marcosmartinez7?

Workaround: 

Provided a function that returns the token value. Refresh the token value every 5 minutes with a cronjob 

```
 this.pusher = new Pusher(this.appKey, {
      cluster: this.cluster,
      channelAuthorization: {
        endpoint: `${url}/mm/pusher`,
        headersProvider: () => {
          return this.authToken;
        },
        transport: 'ajax',
      },
    });

  @Cron(ExtendedCronExpression.EVERY_3_MINUTES)
  async login() {
    try {
      const data = await this.pusherLogin();
      this.authToken = data.data.access_token;
    } catch (e) {
      this.logger.error('Error when running login cron job', e);
      throw e;
    }
  }


```

Since its

**Comment by AndreSilva1993** [comment]
I don't think implementing a CRON should be necessary for this instead of simply allowing async functions to be passed through.
