### ISSUE TITLE
Presence channel is stuck on subscriptionPending when using xhr_streaming

### ISSUE THREAD

**Issue by bartw** [pusher/pusher-js#706]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
When we use `xhr_streaming` and try to connect to a presence channel, `subscriptionPending` is stuck on true.
It doesn't succeed or error.

When we use `ws` and try to connect to the same presence channel, everything works as expected.

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

**What is the expected behavior?**
Connecting to a presence channel using `xhr_streaming` works like it does for `ws`.

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**

**Comment by stueynet** [comment]
> **Do you want to request a _feature_ or report a _bug_?** Report a bug
> 
> **What is the current behavior?** When we use `xhr_streaming` and try to connect to a presence channel, `subscriptionPending` is stuck on true. It doesn't succeed or error.
> 
> When we use `ws` and try to connect to the same presence channel, everything works as expected.
> 
> **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
> 
> **What is the expected behavior?** Connecting to a presence channel using `xhr_streaming` works like it does for `ws`.
> 
> **Which versions of Pusher, and which browsers / OS are affected by this issue? Did this work in previous versions of Pusher? If so, which?**

Hey just curious, when you are in this state are triggered events and channel occupancy working correctly? Or is the subscription also borked?

**Comment by bartw** [comment]
Triggered events are working correctly. I didn't test occupancy.

**Comment by benw-pusher** [comment]
Hi @bartw 
We recently pushed a server side update to try and improve behaviour in this area - do you still experience this issue?
