### ISSUE TITLE
pusher auth call fails.

### ISSUE THREAD

**Issue by saran141998** [pusher/pusher-js#718]
I am using pusher-js 7.0.6
Initially when the page loads all the auth calls got succeeded and the channels got subscribed successfully.
But when I keep the tab idle for sometime pusher auth calls not reaching to the servers and those auth calls are terminated.

<img width="739" alt="Screenshot 2023-05-04 at 12 32 08 PM" src="https://user-images.githubusercontent.com/27149207/236133200-7a68cec8-6571-484a-bb5c-b26af8fa3ae2.png">
[](url)
[pusherLogs.txt](https://github.com/pusher/pusher-js/files/11394542/pusherLogs.txt)

**Comment by benw-pusher** [comment]
Calls from your client to the auth server happen directly and don't pass through our service, so this would indicate a connection issue between the client and server, or potentially a bad response from the auth server. Does the request complete with an error response or does it timeout/fail to connect?

**Comment by saran141998** [comment]
As per the screenshot there is no error/success status code. There is no trace for this api call in the server logs.
It is failed to connect.

**Comment by benw-pusher** [comment]
Thanks Saran. As mentioned, this means the client is unable to reach the specified auth server. You should verify the settings are correct and that the server is reachable from the client. The auth request happens directly - so the connection issue is directly between the client and server.

**Comment by saran141998** [comment]
@benw-pusher 
curl 'https://sockjs-mt1.pusher.com/pusher/app/469d71c5a25513823ddf/115/2vvg9in3/xhr_send?t=1683783812815&n=103' \
  -H 'Accept: */*' \
  -H 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8,ta;q=0.7,ar;q=0.6,te;q=0.5' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Origin: http://localhost:4998' \
  -H 'Pragma: no-cache' \
  -H 'Referer: http://localhost:4998/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: cross-site' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Google Chrome";v="113", "Chromium";v="113", "Not-A.Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --data-raw '["{\"event\":\"pusher:subscribe\",\"data\":{\"auth\":\"469d71c5a25513823ddf:bc8c36e8ca0401e304b0d3ab0cdec69e838fd1e31525058bae76fac0e0b690d2\",\"channel_data\":\"{\\\"user_id\\\":\\\"saravanansr@tekion.com\\\"}\",\"channel\":\"private-5c051e21-7b26-4929-b9ea-0cc56fd6243b\"}}"]' \
  --compressed
![Screenshot 2023-05-11 at 1 12 57 PM](https://github.com/pusher/pusher-js/assets/27149207/14658841-0800-43fb-a2b7-8927308ed647)

the above api call also failes multiple times
