### ISSUE TITLE
Unexpected status code 401

### ISSUE THREAD

**Issue by chrhi** [pusher/pusher-js#741]
Title: Getting 401 Error on Server-Side Pusher Authentication in Next.js Application

**Issue Description:**

I am encountering a 401 Unauthorized error when trying to trigger events on the server using Pusher in my Next.js application. Strangely, the client-side is working perfectly fine, and I have confirmed that my Pusher configuration is correct. I'm using Next.js version 13 with a custom "pages" directory and integrating Pusher with trpc.

**Environment:**
- Next.js Version: 13
- Pages Directory: Custom "pages" directory
- trpc: Integrated with Next.js

**Relevant Code:**

**Environment Variables:**
```
PUSHER_APP_ID=PUSHER_APP_ID
PUSHER_APP_KEY=PUSHER_APP_KEY
NEXT_PUBLIC_PUSHER_APP_KEY=NEXT_PUBLIC_PUSHER_APP_KEY
PUSHER_APP_SECRET=PUSHER_APP_SECRET
```

**pusher.ts:**
```typescript
import Pusher from "pusher";
import PusherClient from 'pusher-js';

export const pusherServer = new Pusher({
  appId: process.env.PUSHER_APP_ID!,
  key: process.env.PUSHER_APP_KEY!,
  secret: process.env.PUSHER_APP_SECRET!,
  cluster: 'eu',
  useTLS: true,
})

export const pusherClient = new PusherClient(
  process.env.NEXT_PUBLIC_PUSHER_APP_KEY!,
  {
    cluster: 'eu',
  }
)
```

**Server Code:**
```typescript
import { TRPCError } from 'trpc';
import { pusherServer } from './pusher';

// Inside an async function
await pusherServer.trigger("chat", 'incoming-message', { message: "this is working" })
  .catch(err => {
    throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: `Failed to send the message. Pusher error: ${err.message}` });
  });
```

**Additional Information:**

I have double-checked my environment variables, and they seem to be correctly set. The client-side integration with Pusher is working without any issues. The problem seems to be related to server-side authentication with Pusher.

I have already verified my Pusher dashboard settings and ensured that the CORS (Cross-Origin Resource Sharing) settings are set up correctly.

**Expected Behavior:**

I expect the `pusherServer.trigger` call to work successfully and trigger the "incoming-message" event on the "chat" channel without any authentication errors.

**Actual Behavior:**

Instead, I receive a 401 Unauthorized error when attempting to trigger the event on the server.

**Steps to Reproduce:**

1. Set up a Next.js application with a custom "pages" directory.
2. Integrate Pusher using the provided `pusher.ts` file.
3. Attempt to trigger a Pusher event on the server-side using `pusherServer.trigger`.
4. Observe the 401 Unauthorized error in the server logs.

**Additional Notes:**

I have thoroughly reviewed the Pusher documentation and searched for similar issues, but none of the solutions seem to resolve my problem. I suspect the issue might be related to the server-side authentication process, but I haven't been able to pinpoint the exact cause.

Any help or guidance in resolving this issue would be greatly appreciated. Thank you!

**Comment by benjamin-tang-pusher** [comment]
Hi, can you reproduce this issue from your local machine? Is your server side code running from a Vercel serverless function, or from a machine hosted in AWS?

**Comment by benw-pusher** [comment]
We haven't had a response her so will close.
