### ISSUE TITLE
{"type":"PusherError","data":{"code":2010,"message":"Another connection still open"}}

### ISSUE THREAD

**Issue by sobrinho** [pusher/pusher-js#745]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Unstable connections are emitting this error.

<img width="888" alt="Screen Shot 2023-07-26 at 12 59 31" src="https://github.com/pusher/pusher-js/assets/26460/c035c049-debb-43cd-be22-e67111e579a5">

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
Not easy to reproduce.

**What is the expected behavior?**
No error or if there's another connection, re-use it.

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
8.0.2

**Comment by nicitaacom** [comment]
Please make sure that your current plan icludes that
I mean that your plan support pusher abilities you use
To check it just check your email - usually pusher messege you if you rate limit out of your current plan

**Comment by sobrinho** [comment]
We are far behind the rate limit, doesn't seem related.

**Comment by benw-pusher** [comment]
This error is a SockJS specific error and is defined in the protocol at https://github.com/sockjs/sockjs-protocol/blob/4d5c49a5e523b801af33845d581fc92d085b69df/sockjs-protocol.py#L467. 
This error is emitted when the client attempts to initiate multiple connections. The close error is only emitted to the new connection, with the existing connection being maintained.
