### ISSUE TITLE
Allow to pass an AbortSignal to channelAuthorizer

### ISSUE THREAD

**Issue by sobrinho** [pusher/pusher-js#747]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
No support

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
N/A

**What is the expected behavior?**
I would like to be able to cancel channel authorization calls since I can predict then on my app.

```js
var controller = new AbortController
var pusher = new Pusher('...', {
  channelAuthorization: {
    signal: controller.signal
  }
})
pusher.subscribe("my-channel")
controller.abort() // assuming that the request is still running
```

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
8.0.2

**Comment by sobrinho** [comment]
Looks like pusher-js is using `XMLHttpRequest` instead of `fetch`.

Adding support for `AbortSignal` is still possible, though (pseudo code):

```js
const xhr = new XMLHttpRequest();
const method = "GET";
const url = "https://developer.mozilla.org/";
xhr.open(method, url, true);
xhr.send();

if (authOptions.signal) {
  authOptions.signal.addEventListener("abort", () => { if (xhr.readyState != 4) { xhr.abort() } })
}
```

Another option is to add support for the `fetch` transport which is widely supported these days and support the `signal` option only on it.

**Comment by benjamin-tang-pusher** [comment]
Hi, I will pass upgrading to fetch instead of XMLHttpRequest to the team. I can't provide a timeline for when this will be implemented, but I will bring it to their attention.

Thanks for bringing this up, I will close this issue.
