### ISSUE TITLE
Pusher not reconnecting and stucked, need to manually refresh token

### ISSUE THREAD

**Issue by marcosmartinez7** [pusher/pusher-js#752]
Hello, 

Im using `pusher-js` version   `8.2.0` into a Node.js (Nest.js) application. 

It is a simple component that when starts it subscribe to some channels. 

```
@Injectable()
export class GameEventsSubscriberService implements OnModuleInit {
  private pusher: Pusher;
  private publicChannel: Channel;
  private publicChannelData;

  constructor(
    private readonly httpService: HttpService,

  ) {}


  async connect() {
    // FIRST WE CREATE THE INSTANCE OF THE SDK
    this.pusher = new Pusher(process.env.PUSHER_APP_KEY, {
      cluster: process.env.PUSHER_APP_CLUSTER,
      channelAuthorization: {
        // FIXME is this ok? why magui used another fields?
        transport: 'ajax',
        endpoint: `${process.env.PUSHER_URI}/mm/pusher`,
        headers: {
          Authorization: `Bearer ${await this.getAuthToken()}`,
        },
      },
    });

    // BINDINGS

    this.pusher.connection.bind('error', async function (err) {
      console.log('Pusher error! calling disconnect', err);
    });

    this.pusher.connection.bind('state_change', function (states) {
      console.log('Pusher state change!', JSON.stringify(states));
    });

    this.pusher.connection.bind('disconnected', () => {
      console.log('BIND Disconnected');
    });

    // WHEN CONNECTED, HIT THE API TO GET CHANNELS
    this.pusher.connection.bind('connected', async ({ socket_id }) => {
      console.log(' PUSHER Connected');
      const {
        data: { data },
      } = await this.httpService.axiosRef.post(
        `${process.env.PUSHER_API}/mm/pusher`,
        { socketId: socket_id },
        {
          headers: {
            Authorization: `Bearer ${await this.getAuthToken()}`,
          },
        },
      );

    // FOR EACH CHANNEL, SUBSCRIBE
      for (const authChannel of data.authorized_channel) {
        if (authChannel.channel_name.includes('broadcast')) {
          this.publicChannelData = authChannel;
        }
      }

      this.publicChannel = this.pusher.subscribe(
        this.publicChannelData.channel_name,
      );

      this.publicChannelData.binding_events.forEach((element) => {
          this.publicChannel.bind(element.name, (data) => {
            const logData = {
              ...data,
              payload: JSON.parse(base64.decode(data.payload)),
            };
            
            this.storeInCache(logData);
          });
        }
    });
  }
```

What im experimenting is: 
1. App run correctly and i can see the state changes and events for a while (lets say 30 minutes, 1 hour) 
2. After some time i get an error, I log that error on the `bind('error')` hook 
3. Pusher stops receiving events 

The error i receive is A CONNECTION RESET, followed by `{ type: 'PusherError', data: { code: 1006, message: undefined } }` 

`Network error: [wss://ws-us2.pusher.com:443/app/30f867796adefdeecb75?protocol=7&client=js&version=8.3.0&flash=false](wss://ws-us2.pusher.com/app/30f867796adefdeecb75?protocol=7&client=js&version=8.3.0&flash=false): read ECONNRESET',`

And it seems, that Pusher has some internal retry mechanism that make it retry the connection: 

```
Pusher state change! {"previous":"connected","current":"connecting"}`-> connecting
Pusher state change! {"previous":"connecting","current":"connected"} -> connected
Pusher error! {
  type: 'PusherError',
  data: { code: 4009, message: 'Connection not authorized within timeout' }
}
```

Looking at the documentation and other issues, the `4009` code is related with authentication and authorization, so one potential explanation to this issue is:

1. token expired 
2. network error
3. when pusher tries to reconnect, the token is expired -> 4009

Im wondering many things:
1) shouldnt be pusher-js refreshing the token automatically? what should i expect here? i need to manage the refresh of the token manually? 
2) is this a scenario that makes sense to be failing? To be honest i found a lot of similar issues (https://github.com/pusher/pusher-js/issues?q=reconnect) but there doesnt seems to be an answer about what is causing the `4009` error and if we need, as developers, to manually 'refresh' the pusher instance and how 

As a side note, i have tested https://github.com/deepbrook/Pysher (Python implementation) and seems to reconnect normally

Im open to any comments or info needed as this is an important issue for us

Kind Regards

EDIT: 
- i have implemented a cronjob that every 10 minutes it refresh the token and reinstanciate pusher and seems to work (at least for now) 
- i think it would be nice to EXPLICIT that on the documentation 📝 
- another sugestion is that given the dev provides the auth endpoint, it could be periodically refreshed internally by pusher 

thoughts?

**Comment by benw-pusher** [comment]
There is no requirement to manually refresh the tokens. When the client reconnects and attempts to resubscribe to the channels it will first request new tokens from the specified auth endpoint. 

Are you able to enable `Pusher.logToConsole = true` and share the full logs for the scenario you describe so we can check the behaviour? 

Do you see a request to the specified endpoint after the client has reconnected?

**Comment by marcosmartinez7** [comment]
> There is no requirement to manually refresh the tokens. When the client reconnects and attempts to resubscribe to the channels it will first request new tokens from the specified auth endpoint.
> 
> Are you able to enable `Pusher.logToConsole = true` and share the full logs for the scenario you describe so we can check the behaviour?
> 
> Do you see a request to the specified endpoint after the client has reconnected?

Thanks @benw-pusher 

Yes i can test that and provide the logs. Will post it here soon. 

Btw, can you indicate where does pusher implement that 'reconnection' mechanism with token refresh? I was taking a look to the pusher-js code to troubleshoot this and didnt find anything

Thanks for your quick response

**Comment by benw-pusher** [comment]
I believe it is done at [this](https://github.com/pusher/pusher-js/blob/ed900f8d4fc121cb2c7e20809a3cac8e3249d812/src/core/pusher.ts#L200) line, which is invoked when the connection state changes to connected. If there were any previously subscribed channels then the library will now subscribe to them again, the process of which involves requesting a new token from the auth endpoint provided.

I attach a Chrome console log for a period covering an initial connect and then a reconnection with Pusher.logToConsole enabled. On line 4 you'll see the auth token in use is `"auth":"REDACTED:242cd0994d5efb4f32dc90fb26aea71232a9af9d90cb58d0d4cb5bf01d81d2bc` while on line 23, after the reconnection, the token is `"auth":"REDACTED:eecc19f2db93e6f96b95bd288ee90540bed465db0ea8066bf55ac997422f8743`. This shows that a new token is being used.

**Comment by marcosmartinez7** [comment]
Here are the logs, the ones with `Pusher : : ` are from pusher.logToConsole, the rest are bindings to state changes and errors

```
Pusher :  : [{"type":"PusherError","data":{"code":4201,"message":"Pong reply not received"}}]
Pusher error! calling disconnect {
  type: 'PusherError',
  data: { code: 4201, message: 'Pong reply not received' }
}
Pusher :  : [{"type":"WebSocketError","error":{"type":"PusherError","data":{"code":4201,"message":"Pong reply not received"}}}]
Pusher error! calling disconnect {
  type: 'WebSocketError',
  error: {
    type: 'PusherError',
    data: { code: 4201, message: 'Pong reply not received' }
  }
}
Pusher :  : ["State changed","connected -> connecting"]
Pusher state change! {"previous":"connected","current":"connecting"}
Pusher :  : ["Connecting",{"transport":"ws","url":"wss://ws-us2.pusher.com:443/app/30f867796adefdeecb75?protocol=7&client=js&version=8.3.0&flash=false"}]
Pusher :  : ["State changed","connecting -> connected with new socket ID 49623.900689"]
Pusher state change! {"previous":"connecting","current":"connected"}
 PUSHER Connected
Pusher :  : ["Error: Unable to retrieve auth string from channel-authorization endpoint - received status: 401 from https://apiname/partner/feature/pusher. Clients must be authorized to join private or presence channels. See: https://pusher.com/docs/channels/server_api/authorizing-users/"]
Pusher :  : ["No callbacks on private-broadcast-service=3-device_type=5 for pusher:subscription_error"]
Pusher :  : [{"type":"PusherError","data":{"code":4009,"message":"Connection not authorized within timeout"}}]
Pusher error! calling disconnect {
  type: 'PusherError',
  data: { code: 4009, message: 'Connection not authorized within timeout' }
}
Pusher :  : [{"type":"WebSocketError","error":{"type":"PusherError","data":{"code":4009,"message":"Connection not authorized within timeout"}}}]
Pusher error! calling disconnect {
  type: 'WebSocketError',
  error: {
    type: 'PusherError',
    data: { code: 4009, message: 'Connection not authorized within timeout' }
  }
}
Pusher :  : ["State changed","connected -> disconnected"]
Pusher state change! {"previous":"connected","current":"disconnected"}
BIND Disconnected

```

What i understand: 

1. pong reply not received: this happens between i just discconected and reconnected my wifi, its expected
2. Pusher :  : ["State changed","connected -> connecting"] -> i think is trying to connect again 
3. Pusher :  : ["State changed","connecting -> connected with new socket ID 49623.900689"] -> its connected
4. Pusher :  : ["Error: Unable to retrieve auth string from channel-authorization endpoint - received status: 401 from https://apiname/partner/feature/pusher. Clients must be authorized to join private or presence channels. See: https://pusher.com/docs/channels/server_api/authorizing-users/"] -> This is weird .. ⚠️  

After that it throws the 4009 error, and set the state disconnected

As a side note, it does not try to reconnenct again, logs end there 

Do you have any ideas of why im getting (4) "Unable to retrieve auth string from channel-authorization endpoint" ? 

Thanks in advance

**Comment by marcosmartinez7** [comment]
@benw-pusher , can this be related with the token not being refreshed? 

i discovered `headersProvider` https://github.com/pusher/pusher-js/issues/699 

But is seems it doesnt work when you need to fetch the token async

**Comment by benw-pusher** [comment]
Thanks for confirming the resolution @marcosmartinez7 . 

In terms of `channelAuthorization` and `userAuthentication` these are separate topics, with [docs for the former here](https://pusher.com/docs/channels/server_api/authorizing-users/) and for [the latter here](https://pusher.com/docs/channels/server_api/authenticating-users/). You are correct to be using channelAuthorization.  I do note that these don't provide an early indication of precisely what feature they relate to so I will look to update these. 

Using the headersProvider is also the correct way to go - sorry that I wasn't able to respond with this before you found the solution. I'll add the explicit mention of this to the docs as you suggest.
