### ISSUE TITLE
https://js.pusher.com/8.0.1/pusher.min.js blocked by AdBlock (net::ERR_BLOCKED_BY_CLIENT)

### ISSUE THREAD

**Issue by dtinth** [pusher/pusher-js#753]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
AdBlock extension seems to be blocking Pusher. This is affecting our users.

```js
<script src="https://js.pusher.com/8.0.1/pusher.min.js"></script>
```

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**

1. Install AdBlock
2. Enable these filters
   <img width="789" alt="image" src="https://github.com/pusher/pusher-js/assets/193136/dd591805-7fc0-43eb-a4bb-f40e43812c0f">
3. Go to a website with Pusher

**What is the expected behavior?**
Pusher.js should load correctly.

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
Version 3.1 is also affected.

**Comment by benw-pusher** [comment]
I'm not able to reproduce this with adblock. Can you try disabling individual lists and let me know which one appears to be the culprit? I can then investigate the list source directly.

**Comment by dtinth** [comment]
@benw-pusher Thanks for the suggestion. I tried as suggested and it turns out it’s not the filter lists that blocked the Pusher SDK.

Turns out, it’s the [**Distraction Control**](https://helpcenter.getadblock.com/hc/en-us/articles/9738477836435-About-Distraction-Control) feature available to AdBlock Premium (which costs $2/mo). I think this feature recently rolled out. I did not remember enabling it, so I guess it may be enabled by default for paying customers.

<img width="1332" alt="image" src="https://github.com/pusher/pusher-js/assets/193136/46c6a859-43a0-48da-b0b7-9a2fa4a67f0f">

Since it is a paid feature, I also opened a support ticket to AdBlock side and will update when I hear back.

**Comment by benw-pusher** [comment]
Thanks @dtinth . I suspect this is not something that AdBlock will change, as that would be circumventing the purpose of distraction control. 
One workaround for this could be to[ self serve the files](https://github.com/pusher/pusher-js#self-serving-js-files), hosting them on your domain instead of a Pusher domain and potentially preventing the block - however I can't guarantee this is a solution as I'm not certain how the distraction control works.

**Comment by dtinth** [comment]
Yes, you are right, received this response from AdBlock:

> Thank you for your patience. 
>
> After consideration, the Distraction Control team has opted to continue blocking Pusher as it uses push notifications.

We may have to self host it then. Thanks for the suggestion 🙏
