### ISSUE TITLE
Please provide a package

### ISSUE THREAD

**Issue by qcth** [pusher/pusher-js#754]
Please provide a package

① Packages that rely on Node.js built-in libraries are not supported

② Packages that rely on browser built-in objects are not supported

③ Packages that rely on C++plugins are not supported

thanks

**Comment by benw-pusher** [comment]
Could you share more about what it is you are looking for here, and where these support stipulations (e.g _Packages that rely on Node.js built-in libraries are not supported_) originate?

**Comment by qcth** [comment]
NPM Package Restrictions for WeChat Mini Programs in China



https://developers.weixin.qq.com/miniprogram/dev/devtools/npm.html

https://developers.weixin.qq.com/miniprogram/dev/devtools/npm.html￼



￼

**Comment by benw-pusher** [comment]
At this time we aren't able to provide a package for WeChat integration and this isn't on the roadmap for the product at this time. 
Sorry that we can't help further.
