### ISSUE TITLE
Receiving data multiple times 

### ISSUE THREAD

**Issue by habTeqPaul** [pusher/pusher-js#755]
I am facing issue while using authenticated pusher events.
When I get any event from pusher, in network tab I see only one event, but when I log inside my code, I get multiple log statements.

My code looks something like this

        window.Echo.channel('laravalchat').listen('.chatting',(e)=>{
            console.log(e)
        })

**Comment by benw-pusher** [comment]
If you only see a single event in the network tab then it suggests you are binding to the event multiple times - are you able to check your code for this?

**Comment by habTeqPaul** [comment]
Thanks for contacting

I solved the issue
