### ISSUE TITLE
Pusher issue when packaged with custom NPM module

### ISSUE THREAD

**Issue by Naveenkhasyap** [pusher/pusher-js#758]
@can2112

 **Do you want to request a *feature* or report a *bug*?**
When bundled pusher as dependency  getting linkage error , below is the package built
https://www.npmjs.com/package/@onmeta/react-native-sdk?activeTab=readme

**What is the current behavior?**
The package 'pusher-websocket-react-native' doesn't seem to be linked

**If the current behavior is a bug, please provide the steps to reproduce and
npm i @onmeta/react-native-sdk

**What is the expected behavior?**
pusher error should not come and communication messages should be exchanges without errors.

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
Pusher : 1.2.2
react-native-cli
os tested in : Mac

**Comment by benw-pusher** [comment]
To run the react native package in an Expo environment you will need to follow the instructions provided by Expo for adding packages with non-native code. You will need to run this using the prebuild command as part of the run process.  See https://docs.expo.dev/workflow/customizing/#adding-custom-native-code-with-development-builds

I'll close this as it is raised against the wrong repository - the correct repo is https://github.com/pusher/pusher-websocket-react-native
