### ISSUE TITLE
Subscribing to channel fails without error or event in local development

### ISSUE THREAD

**Issue by stewartknapman** [pusher/pusher-js#76]
When working on an app in development locally I'm having issues with pusher not subscribing to channels. We are not seeing this issue in staging or production.

I've added a log method to the pusher object (https://github.com/pusher/pusher-js/blob/77aca8e9dd935d74511583d112679c1206f20a16/src/pusher.js#L89-L90) and I can see that the `pusher:subscribe` event is being sent, but there is nothing following it:

    Pusher : Event sent : {"event":"pusher:subscribe","data":{"channel":"my-channel"}}

When viewing the pusher.com debug console no `subscribed` event is logged from `Origin: http://0.0.0.0:3000` but I am seeing them for staging and production.

It's like its just getting lost somewhere along the way.

I tried following through the code to see if I could see anything obvious that might cause this but got lost in the connection_manager.js

**Comment by LinKassem** [comment]
@stewartknapman did you solve this issue? my application was working yesterday but today the events are simply not triggered with no errors or anything.
@pl any help?
Thanks!

**Comment by leggetter** [comment]
@LinKassem Can I please request that you go via support with this? When you do, providing logging details from http://test.pusher.com/ would be a great way of helping us diagnose the problem.

One thing to check - and I don't see it listed above - would be to force an encrypted connection. We recommend this anyway now. Proxies/Firewalls don't tend to mess with SSL connections in the same way they can with non-SSL.
