### ISSUE TITLE
WebSocket Compression

### ISSUE THREAD

**Issue by nicorichard** [pusher/pusher-js#761]
Which versions of this library support the recently announced change to [enable websocket compression](https://pusher.com/blog/websocket-compression-pusher/) ?

Will my app continue to function if I am using this library? If I am using an old version of this library?

What protocols does this library support?

**Comment by maclonghorn** [comment]
According to the email:  "As of this date [Oct 18, 2023] we will continue to support v13 (the most recent and recommended protocol)".  We are using client version 7.6.0 and when I look at the console request to pusher.com, I see this in the request headers:
```
Sec-WebSocket-Version: 13
```
So I assume that means I'm okay.

**Comment by phillipkey** [comment]
https://github.com/pusher/pusher-js/blob/8827097cf755919dc6ff6ee26bb429d64dea3a52/dist/node/pusher.js#L1317

**Comment by phillipkey** [comment]
We are using client version 6.0.3. We were able to find in the source where this value is set. Link below in case anyone else wants to confirm.

https://github.com/pusher/pusher-js/blob/8827097cf755919dc6ff6ee26bb429d64dea3a52/dist/node/pusher.js#L1317

**Comment by benw-pusher** [comment]
I have tested version 3.0.0 of this library which also supports v13 of the Websocket Protocol. 

I'll leave this open for a while so others can discover this thread. Thanks @phillipkey and @maclonghorn for your investigations here 🙌

**Comment by bbqaaq** [comment]
My project is using pusher v4.2.2 and I have no idea on how to check whether I need to upgrade or not.
Can someone share how I can check my pusher-js version is fine or not? Thanks!

**Comment by domstubbs** [comment]
For my own peace of mind I also tested our old 3.x instance and confirmed that, although the WS/HYBI version doesn’t seem to be explicitly referenced in the source for this version of the library, it does pass the `Sec-WebSocket-Version: 13` request header.

Saying that, I suspect my browser is generating that rather than the library itself.

If so, looking at the [list of web socket versions](https://www.iana.org/assignments/websocket/websocket.xml#version-number), v13 is the latest and still dates back to 2011. It’s also been supported by all major browsers as far back as IE10, so it’s probably safe to assume that unless you’re running an app with a huge focus on legacy support you probably don’t need to care about this.

It would’ve been helpful if the Pusher blog post/notification email clarified some of this, as I was left thinking I might have to urgently jump on a library upgrade before the 2 week deadline expires. Most of us are probably using Pusher in large part so that we don’t need to know/care about lower level aspects of WS versions.

**Comment by hz-sanaullah** [comment]
As @phillipkey said, go to node_modules/pusher-js/dist/node/pusher.js and search for "Hybi.VERSION =", you'll know what version you're using.

**Comment by hz-sanaullah** [comment]
> My project is using pusher v4.2.2 and I have no idea on how to check whether I need to upgrade or not. Can someone share how I can check my pusher-js version is fine or not? Thanks!

As @phillipkey said, go to node_modules/pusher-js/dist/node/pusher.js and search for "Hybi.VERSION =", you'll know what version you're using.

**Comment by bbqaaq** [comment]
> > My project is using pusher v4.2.2 and I have no idea on how to check whether I need to upgrade or not. Can someone share how I can check my pusher-js version is fine or not? Thanks!
> 
> As @phillipkey said, go to node_modules/pusher-js/dist/node/pusher.js and search for "Hybi.VERSION =", you'll know what version you're using.

Yes, I do read the previous replies, and tried to look for it in my version. Unfortunately, seems "Hybi.VERSION" isn't appearing in version before v5.0.0.

**Comment by hz-sanaullah** [comment]
> > > My project is using pusher v4.2.2 and I have no idea on how to check whether I need to upgrade or not. Can someone share how I can check my pusher-js version is fine or not? Thanks!
> > 
> > 
> > As @phillipkey said, go to node_modules/pusher-js/dist/node/pusher.js and search for "Hybi.VERSION =", you'll know what version you're using.
> 
> Yes, I do read the previous replies, and tried to look for it in my version. Unfortunately, seems "Hybi.VERSION" isn't appearing in version before v5.0.0.

If I'm not wrong then inside the same file, you'll find a variable called "Defaults" somewhere around line#836. Check what is written against "PROTOCOL" key inside the "Defaults" variable.

**Comment by adriano-falcao-jet** [comment]
> > > My project is using pusher v4.2.2 and I have no idea on how to check whether I need to upgrade or not. Can someone share how I can check my pusher-js version is fine or not? Thanks!
> > 
> > 
> > As @phillipkey said, go to node_modules/pusher-js/dist/node/pusher.js and search for "Hybi.VERSION =", you'll know what version you're using.
> 
> Yes, I do read the previous replies, and tried to look for it in my version. Unfortunately, seems "Hybi.VERSION" isn't appearing in version before v5.0.0.

Same for me. Version 4.2.2 and no "Hybi.VERSION" ref

**Comment by benw-pusher** [comment]
I've tested version 3.0.0 and 1.12.2 and both use Websocket Protocol v13. You should be fine on any version of this library. 
If you want to test you can create a Channels app in any of the ap3, ap4, us2, us3 and eu clusters and then run a test connection using the new app credentials. 
If the connection is successful then you aren't impacted.

**Comment by bbqaaq** [comment]
> I've tested version 3.0.0 and 1.12.2 and both use Websocket Protocol v13. You should be fine on any version of this library. If you want to test you can create a Channels app in any of the ap3, ap4, us2, us3 and eu clusters and then run a test connection using the new app credentials. If the connection is successful then you aren't impacted.

Thank you so much for the hint, and I just found the article mentioning these cluster.
I just tested my v4.2.2 version and work totally fine with `ap3`.

https://support.pusher.com/hc/en-us/articles/19131120873361-Deprecation-of-legacy-versions-of-WebSocket-protocol-FAQ?fbclid=IwAR3HUNTX6GpN1uAYteI4NxDDeVT7nptjSXD1VFHBN3gEjGpAwlR5F67ia4w

**Comment by benw-pusher** [comment]
We have now completed the deprecation activity.
