### ISSUE TITLE
Checking a client message has sent

### ISSUE THREAD

**Issue by rbhalla** [pusher/pusher-js#78]
Currently the library seems to be returning true if the connection is "open", but in my own testing I've found this isn't a reliable indicator of whether a client message actually sent correctly.

What would be the best way of doing this?

**Comment by kabudu** [comment]
+1 This feature would be really useful!

**Comment by rpc4mv** [comment]
+1 This would make handling failure cases much easier. The best-effort nature of pusher has been our only issue using pusher thus far. Getting real-time feedback of whether an event was successfully received by the other client(s) would be tremendously helpful.

**Comment by hph** [comment]
I'm closing "feature request" issues, including this one. This does not mean that the feature will not be implemented, we just want to reserve open GitHub issues to bugs that need to be addressed.

Feel free to comment here to keep the discussion going. People watching the repository will still receive notifications.
