### ISSUE TITLE
Bug: Webhook not triggered after subscribe and unsubscribe event

### ISSUE THREAD

**Issue by BGDanny** [pusher/pusher-js#784]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
For 1 particular user, the pusher webhook is not trigged after subscribe/unsubscribe event. No issue for all other users so far.

**If the current behavior is a bug, please provide the steps to reproduce and
if possible a minimal demo of the problem via https://jsfiddle.net or similar.**
I was not able to replicate the bug myself because it only happens to 1 particular user. It started after the pusher outage on September 6th, 2023.

**What is the expected behavior?**
Webhook should be triggered properly after subscribe/unsubscribe event for all users.

**Which versions of Pusher, and which browsers / OS are affected by this issue?
Did this work in previous versions of Pusher? If so, which?**
Pusher version is `5.0.0`. We didn't have any upgrade to pusher in the past 4 years.

**Comment by benw-pusher** [comment]
As this is only happening for a single user we will likely need to dig deep into your app, including sharing the user/channel name.  As such I recommend you contact us via support - you can log a ticket at https://messagebird.com/support-center/Pusher-request-new.
