### ISSUE TITLE
Not actuall stats

### ISSUE THREAD

**Issue by nicitaacom** [pusher/pusher-js#807]
Bug

**Not actuall info**
![image](https://github.com/pusher/pusher-js/assets/39565703/a737c0b4-b883-4f20-bc72-e8c922af429f)

To reproduce - don't use pusher and go to [stats](https://dashboard.pusher.com/stats?period=day)
**What is the expected behavior?**
I wait that it will 0 - because I don't use pusher (I don't send any messages)

**Comment by benw-pusher** [comment]
You mention that you aren't sending any messages, and that is in line with the graphs you have shared. The top graph shows connections, the next graph shows messages - which we can see is empty. 

It is likely that you have a client somewhere initiating connections.  You will be able to monitor for these events in the [debug console](https://pusher.com/docs/channels/getting_started/debugging/). 
If you believe the app credentials could have leaked and a third party is creating connections to your app then you can rotate your app keys. 

 Please note that the debug console and getting started tabs within an app on the Pusher Dashboard also initiates a connection which will show in the graphs. If you have visited these pages then it may explain the usage.

**Comment by nicitaacom** [comment]
> It is likely that you have a client somewhere initiating connections.

As I understood if somebody jsut visit my website - it means that 'somebody' initiating connections?

**Comment by benw-pusher** [comment]
This depends on your implementation, but typically yes you would see a connection when someone visits your site. See https://docs.bird.com/pusher/channels/channels/limits/how-are-concurrent-connections-counted for info. 

The direct link to the debug console and getting started pages changes depending on the app, so I can't link to them directly. However, you can access them as following: 

1. Log in to dashboard.pusher.com
2. Click **Manage** in the Channels box
3. Click **Apps**
4. Click the app you are interested in 
5. On the left you will see links to **Getting Started** and **Debug Console**

**Comment by nicitaacom** [comment]
On [this](https://docs.bird.com/pusher/channels/channels/limits/how-are-concurrent-connections-counted) page I see this
![image](https://github.com/pusher/pusher-js/assets/39565703/59405468-abc8-48e5-b5e5-4b26bc29e5ff)

I want to reduce amount of connections when people visit my website

As I understand right now I can do it by not using new Pusher("APP_KEY") (I mean by not initializing pusher)

I have lib for pusher [here](https://github.com/nicitaacom/23_store/blob/development/app/libs/pusher.ts)

Is it correct if I remove [here](https://github.com/nicitaacom/23_store/blob/development/app/components/SupportButton/SupportButton.tsx#L63) this `pusherClient.subscribe('some_channel')` - new connections will not be created?

**Comment by benw-pusher** [comment]
https://github.com/nicitaacom/23_store/blob/47c1e51abb600a0608d25800c96328869c5b3dcd/app/libs/pusher.ts#L12 this is what creates the connection, so this is what would need to be moved to better control the connection counts.

**Comment by nicitaacom** [comment]
I close this issue for a while
I come back when I will do something with [this](https://github.com/users/nicitaacom/projects/5/views/1?sortedBy%5Bdirection%5D=desc&sortedBy%5BcolumnId%5D=59471618&pane=issue&itemId=54874121) task
