### ISSUE TITLE
Unexpected token <

### ISSUE THREAD

**Issue by Moussawi7** [pusher/pusher-js#81]
Hi @pl ,
I faced the following issue yesterday(Happened 266 time):

Uncaught SyntaxError: Unexpected token <
http://sagembox.home/?org_url=js.pusher.com

Where it happened for one user only having:
OS: 4.2.2
Device: EAGLE7_3G
Browser: Android 4.2

note that the my HTML5 mobile app. is wrapped into webview using PhoneGap.
Thanks.

**Comment by evanjmg** [comment]
I'm getting this as well when my custom authorizer fails in React Native
