### ISSUE TITLE
Cannot call method 'handlesActivityChecks' of null

### ISSUE THREAD

**Issue by Moussawi7** [pusher/pusher-js#82]
Hi, 
I detected yesterday the following error :
"Cannot call method 'handlesActivityChecks' of null"
which happened with some users having mobile phones with the following specifications:
OS:Android 4.4.2 
Browser: Chrome Mobile 30.0 
Device:GT-N7100 

Log:
TypeError

Cannot call method 'handlesActivityChecks' of null

    /android_asset/www/js/pusher.min.js ? in b.c.resetActivityCheck at line 100:218

    /android_asset/www/js/pusher.min.js ? in activity at line 101:92

    /android_asset/www/js/pusher.min.js ? in b.a.emit at line 33:77

    /android_asset/www/js/pusher.min.js ? in b.activity at line 91:28

    /android_asset/www/js/pusher.min.js ? in b.a.emit at line 33:77

    /android_asset/www/js/pusher.min.js ? in b.c.onActivity at line 69:98

    /android_asset/www/js/pusher.min.js ? in c.a.supportsPing.a.socket.onactivity at line 69:378

    /2.2.2/xhr.min.js ? in c.e.onActivity
        this.xhr=null)};a.onChunk=function(a,d){for(;;){var c=this.advanceBuffer(d);if(c)this.emit("chunk",{status:a,data:c});else break}this.isBuff {snip}
        (function(){var c={getRequest:function(a){var b=new window.XMLHttpRequest;b.onreadystatechange=b.onprogress=function(){switch(b.readyState){ {snip}
        (function(){function c(f,a){this.hooks=f;var b=Math.floor(1E3*Math.random())+"/",c;c=[];for(var e=0;8>e;e++)c.push(Math.floor(32*Math.random {snip}
        b);throw"Cross-origin HTTP requests are not supported";}var d=0,g=1,e=c.prototype;e.send=function(a){return this.sendRaw(JSON.stringify([a]) {snip}
        this.readyState=3;if(this.onclose)this.onclose({code:a,reason:b,wasClean:c})};e.onChunk=function(a){if(200===a.status){if(1===this.readyStat {snip}
        {snip} s.onmessage({data:a})};e.onActivity=function(){if(this.onactivity)this.onactivity()};e.onError=function(a){if(this.onerror)this.onerror(a)};
        e.openStream=function(){var c=this;c.stream=b("POST",a(c.hooks.getReceiveURL(c.location,c.session)));c.stream.bind("chunk",function(a){c.onC {snip}
        c}).call(this);(function(){var c={getReceiveURL:function(a,b){return a.base+"/"+b+"/xhr_streaming"+a.queryString},onHeartbeat:function(a){a. {snip}
        (function(){var c={getReceiveURL:function(a,b){return a.base+"/"+b+"/xhr"+a.queryString},onHeartbeat:function(){},sendHeartbeat:function(a){ {snip}

    /2.2.2/xhr.min.js ? in c.e.onChunk
        (function(){function c(b,a,c){Pusher.EventsDispatcher.call(this);this.hooks=b;this.method=a;this.url=c}var a=c.prototype;Pusher.Util.extend( {snip}
        this.xhr=null)};a.onChunk=function(a,d){for(;;){var c=this.advanceBuffer(d);if(c)this.emit("chunk",{status:a,data:c});else break}this.isBuff {snip}
        (function(){var c={getRequest:function(a){var b=new window.XMLHttpRequest;b.onreadystatechange=b.onprogress=function(){switch(b.readyState){ {snip}
        (function(){function c(f,a){this.hooks=f;var b=Math.floor(1E3*Math.random())+"/",c;c=[];for(var e=0;8>e;e++)c.push(Math.floor(32*Math.random {snip}
        b);throw"Cross-origin HTTP requests are not supported";}var d=0,g=1,e=c.prototype;e.send=function(a){return this.sendRaw(JSON.stringify([a]) {snip}
        {snip} function(a){if(200===a.status){if(1===this.readyState)this.onActivity();switch(a.data.slice(0,1)){case "o":a=JSON.parse(a.data.slice(1)||"{} {snip}
        "[]"),this.onClose(a[0],a[1],!0)}}};e.onOpen=function(a){if(this.readyState===d){if(a&&a.hostname){var b=this.location;a=a.hostname;var c=/( {snip}
        e.openStream=function(){var c=this;c.stream=b("POST",a(c.hooks.getReceiveURL(c.location,c.session)));c.stream.bind("chunk",function(a){c.onC {snip}
        c}).call(this);(function(){var c={getReceiveURL:function(a,b){return a.base+"/"+b+"/xhr_streaming"+a.queryString},onHeartbeat:function(a){a. {snip}
        (function(){var c={getReceiveURL:function(a,b){return a.base+"/"+b+"/xhr"+a.queryString},onHeartbeat:function(){},sendHeartbeat:function(a){ {snip}

    /2.2.2/xhr.min.js ? in ?
        (function(){var c={getRequest:function(a){var b=new window.XMLHttpRequest;b.onreadystatechange=b.onprogress=function(){switch(b.readyState){ {snip}
        (function(){function c(f,a){this.hooks=f;var b=Math.floor(1E3*Math.random())+"/",c;c=[];for(var e=0;8>e;e++)c.push(Math.floor(32*Math.random {snip}
        b);throw"Cross-origin HTTP requests are not supported";}var d=0,g=1,e=c.prototype;e.send=function(a){return this.sendRaw(JSON.stringify([a]) {snip}
        this.readyState=3;if(this.onclose)this.onclose({code:a,reason:b,wasClean:c})};e.onChunk=function(a){if(200===a.status){if(1===this.readyStat {snip}
        "[]"),this.onClose(a[0],a[1],!0)}}};e.onOpen=function(a){if(this.readyState===d){if(a&&a.hostname){var b=this.location;a=a.hostname;var c=/( {snip}
        {snip} .location,c.session)));c.stream.bind("chunk",function(a){c.onChunk(a)});c.stream.bind("finished",function(a){c.hooks.onFinished(c,a)});c.str {snip}

**Comment by pl** [comment]
We haven't seen a report of this exception for a while, is this still an issue?

**Comment by Moussawi7** [comment]
Hi @pl,
No Thank you, everything gonna fine.

**Comment by pl** [comment]
Thanks, closing the issue then.

**Comment by davidhariri** [comment]
Hi @pl just saw this one in Sentry... Here's the event:

https://sentry.io/share/issue/3133313234392e323039303633303231/

**Comment by hph** [comment]
This issue has been fixed in version 4.2.0 and above. See [this comment](https://github.com/pusher/pusher-js/issues/233#issuecomment-339451132) for details.
