### ISSUE TITLE
Is pusherjs still under active development?

### ISSUE THREAD

**Issue by KayakinKoder** [pusher/pusher-js#833]
We are paying customers, but looking at your releases, the last was nearly 8 months ago. That doesn't bode well, not even having some small releases for bug fixes/package updates.

Is pusherjs still under active development? If so, why are updates so rare? Thanks.

**Comment by isaachinman** [comment]
I raised similar concerns in #702.

If anyone is aware of an alternative client-side package that is compatible with the Pusher protocol and/or Soketi, please let me know.

**Comment by hichemfantar** [comment]
@isaachinman Ably is pusher compatible

**Comment by isaachinman** [comment]
I'm aware, but it is even more bloated than the Pusher package.

**Comment by hichemfantar** [comment]
Is your issue with the bundle size?

**Comment by isaachinman** [comment]
Yes, see #702.

> I offered actionable and relatively easy steps to substantially improve the package you are distributing to your paying customers.
> Is this repository actively maintained?

**Comment by hichemfantar** [comment]
I understand but as long as everything is working smoothly then shaving off a few kbs isn't really worth the extra headache. Good server side compression and caching headers should be enough. Maybe throw in lazy loading if first paint is critical.

**Comment by KayakinKoder** [comment]
@isaachinman yes it seems this repo is not actively maintained.

On the side note you and @hichemfantar were discussing, Ably looks pretty great. It's 2024, there are _far_ more important things to worry about  (such as "is the company actively improving their product"...) than KBs of javascript.

**Comment by hichemfantar** [comment]
The 60kB is uncompressed, its 17.7kB with gzip and even less with brotli.
almost every server in existence comes with gzip or brotli.

https://bundlephobia.com/package/pusher-js@8.3.0

![image](https://github.com/user-attachments/assets/871ae27f-1c5c-473a-b84c-cd80053c044c)

**Comment by isaachinman** [comment]
If neither of you are interested in the bundle size discussion, why continue to discuss it in an unrelated issue?

**Comment by hichemfantar** [comment]
@isaachinman never said I wasn't interested, I'm discussing solutions until the maintainers push an update.

**Comment by evgeniibreikin** [comment]
Hey guys! After a tiny rebuild and "recompilation" the pusher team is back, we will carefully process every support/issue ticket, give us a bit of time, please :)
