### ISSUE TITLE
NS_ERROR_UNEXPECTED errors

### ISSUE THREAD

**Issue by jorilallo** [pusher/pusher-js#87]
Since Aug 29th we been seeing a steady flood of `NS_ERROR_UNEXPECTED` errors originating from this line: https://github.com/pusher/pusher-js/blob/master/dist/pusher.js#L2160 This seems to only affect latest Firefox browsers. Any idea what could be behind this or is it safe to ignore?

**Comment by ajb** [comment]
I'm seeing this as well... I can try and set up a page with a test case, but in the meantime, it might be worth looking into still :/

I can add these screenshots from Bugsnag for now: [1](http://take.ms/4HBG9) [2](http://take.ms/A7ruj)

**Comment by pl** [comment]
I'd really like to get to the bottom of this, but unfortunately, that's not enough info to debug the problem. Especially since it looks like a bug in Firefox and I can hardly find anything about anything similar on the Internet :/

**Comment by ajb** [comment]
Thanks @pl, that's understandable -- if anyone from the Firefox team is out there, it would be great to get some eyes on this.

**Comment by piquadrat** [comment]
Not sure if this is of any help, but here's a fully sourcemapped stack trace of the error we're seeing:

https://www.dropbox.com/s/fx3hff0kpklv9wf/Screen%20Shot%202016-02-10%20at%2014.18.45.png?dl=0

**Comment by LeZuse** [comment]
I can confirm the stack trace with this:
```
NS_ERROR_UNEXPECTED
1 File https://js.pusher.com/2.2/pusher.min.js line 67 col 480 in c.send/<
2 File https://js.pusher.com/2.2/pusher.min.js line 16 col 412 in Pusher.Timer/<
3 File https://js.pusher.com/2.2/pusher.min.js line 16 col 181 in a/this.timer<
```
Happening in Firefox regardless of OS platform.

**Comment by jackfranklin** [comment]
@LeZuse does this happen if you update to Pusher 3?

**Comment by briedis** [comment]
Experiencing (client errors logged) this with 3.0 client on Firefox 46/47.0

**Comment by jackfranklin** [comment]
@briedis does this happen in 3.1?

As @pl noted above this seems to be a very FF specific bug so not one we're going to be able to track down at the moment. People should try updating to 3.1 on the chance that that fixes it but unfortunately we're not really sure what's going on here.

**Comment by briedis** [comment]
Yup, still happens with 3.1
Googled a bit, and it looks like it has to do something with DOM/iframe manipulations, but that's as far as I got :))

**Comment by vimes1984** [comment]
Why is this Closed? 
If it's a FF issue then where is the bug report from FF ? 
Can we get more details on this? 
Chris

**Comment by stueynet** [comment]
Subscribing. Got this for the first time with this browser: 

Firefox
browserVersion
51.0.0
locale
en-US
osName
Windows 8.1
userAgent

**Comment by rvirani1** [comment]
Also getting this error with Firefox 51 on Windows 8.1

**Comment by emwalker** [comment]
Seeing this error for Pusher v3.1.0 for FF 45, 48, 50, 52, 53 and 54, on various versions of Windows and Mac.

**Comment by emwalker** [comment]
Seeing this for Pusher v4.1.0 for FF 45 and 53.

**Comment by hakunin** [comment]
Been getting this as well, trace:

```
TransportConnection</TransportConnection.prototype.send/<
OneOffTimer/<
Timer/this.timer<
```

FF 54, Pusher 3.1.x.

Here seems to be a relevant FF issue.
https://bugzilla.mozilla.org/show_bug.cgi?id=977020

They say you can get this error when sending onto a closed WS connection.

The error needs to be caught on Pusher's side of things according to their explanation.
