### ISSUE TITLE
feature - add method to remove callback registered on channel with bind_all from global_callbacks

### ISSUE THREAD

**Issue by joeenzminger** [pusher/pusher-js#92]
channel.bind_all allows you to register a per channel callback that listens for all events on a channel.

I would expect that channel.unbind_all would unregister a callback registered with bind_all, but it doesn't.  Looking at the code, it seems to expect an eventName as well.

I think there should be a way to remove a callback from global_callbacks.

**Comment by jasonkriss** [comment]
Did this not make it into the 3.0 release?

**Comment by leggetter** [comment]
@jasonkriss - yep, I think we dropped the ball on this one and completely forgot about the `unbind_all` fix. Sorry about that.

@pl - will this need to go into 4.0 ?

**Comment by pl** [comment]
Yeah, it's still a breaking change.

**Comment by jasonkriss** [comment]
Darn. Too bad. Thanks for confirming though guys. We'll work around it.

**Comment by leggetter** [comment]
I've created a 4.0 milestone to keep track of this for the 4.0 release https://github.com/pusher/pusher-js/milestones/4.0

**Comment by hph** [comment]
We [released](https://github.com/pusher/pusher-js/releases/tag/v4.0.0) a new major version with some breaking changes related to this.
