### ISSUE TITLE
trigger exists on Channel when it should really on be on PrivateChannel

### ISSUE THREAD

**Issue by leggetter** [pusher/pusher-js#95]
I just noticed that `trigger` exists on the `Channel` definition but I'm sure this should only exist on `PrivateChannel` and therefore be inherited by `PresenceChannel`.

Let me know if there's a reason for this. If not, we can keep this on the backlog and fix in the future.

**Comment by pl** [comment]
Yeah, good catch, thanks. We should move it in the next major release.

**Comment by pl** [comment]
Actually, there was a reason why I put it there - it was to make the interface consistent. You get channels by calling `subscribe` on `Pusher` objects, the type depends on the name of the channel. Moving `trigger` to `PrivateChannel` would mean that sometimes you'd get an object without that method and that could cause some nasty exceptions.

We should provide separate subscribe methods for public, private and presence channels, but we're not going to do that in the next major release.

What should we do with this issue? Close or reword to add new methods for the future?

**Comment by zimbatm** [comment]
Voting to close. It's good that we have the same basic interface on all kind of channels.

**Comment by pl** [comment]
Closing for now, we can create a separate issue for per-channel-type methods.
