### ISSUE TITLE
can i get extra data after authentication???

### ISSUE THREAD

**Issue by liu-yuhuan** [pusher/pusher-js#97]
my situation is i wanna to subscribe a private channel for user who already login
and my pusher/auth will return data like 
{"auth":"dfe787bea9db81dd21b1:442d0eb76668223396598fed367bec9e2251eb0fbf564605c7e84b731f9826b8","channel_data":"{\"user_id\":\"2\",\"user_info\":{\"name\":\"John\"}}"}

but i don't know how to get the data after authentication and before subscribe channel..

because i wanna to use the user_id for register private channel

**Comment by pl** [comment]
Hi, `channel_data` is supposed to be used only for presence channels, so there's no direct way to extract that info for private channels. For presence channels you can get it via `members.me` once the subscription is successful:

https://pusher.com/docs/client_api_guide/client_presence_channels

If you just need the user_id and it's constant for the session on your page, it will probably be easier to just embed it in inline script tag, as it shouldn't change between the page load and the auth request.

**Comment by liu-yuhuan** [comment]
thanks for reply.
but i just worry about if other user trying to register somebody's user id
so i am afraid to embed user id in script tag

**Comment by pl** [comment]
If you don't use client events, there's no problem with security:

- your servers know user's id after he/she logs in,
- when authenticating private channels, pusher-js will send the auth request to your server and then you can validate whether the user should be authorized to use the requested channel,
- if users are able to send messages to channels, they should go through your servers, which should attach the correct user id to the message and then send it to Pusher using the publishing API.

There is no need to use user's id on the client side for communicating via Pusher.

I hope that clears things up a bit. If you need more help with your use-case, our support is a better channel to get some assistance from us :)

**Comment by liu-yuhuan** [comment]
thank you so much for clear things up for me
it's really help ~ thank you
