### ISSUE TITLE
Dependency loading doens't work out of the box with chrome extension

### ISSUE THREAD

**Issue by szwacz** [pusher/pusher-js#98]
Hello,
I'm using Pusher with Chrome extension and stumbled upon a problem with loading dependencies. No matter what Pusher tries to load them through http protocol (not https) what is actually blocked by chrome in extensions and will fail.

The problem is here (comments are mine)
```js
prototype.getRoot = function(options) {
var cdn;
// protocol in my case returns "chrome-extension:"
var protocol = Pusher.Util.getDocument().location.protocol;
// options wasn't passed in DependencyLoader, so encrypted is not set
if ((options && options.encrypted) || protocol === "https:") {
cdn = this.options.cdn_https;
} else {
cdn = this.options.cdn_http; // code will always pick this option
}
};
```

Quick fix (a little dirty) define your own Pusher.Dependencies:
```js
Pusher.Dependencies = new Pusher.DependencyLoader({
cdn_http: "https://js.pusher.com/", // just add "https" here
cdn_https: "https://js.pusher.com/",
version: Pusher.VERSION,
suffix: Pusher.dependency_suffix
});
```

This simple thing is surprisingly difficult to fix once and for all, so I'm leaving it to you guys. Passing option `{ encrypted: true }` from Pusher instance to DependencyLoader is a bad idea because we are setting singleton value from multiton thing.

I thought about defaulting to https:
```js
if ((options && options.encrypted) || protocol !== "http:") { // changed from: protocol === "https:"
cdn = this.options.cdn_https;
}
```
But this is almost certainly breaking change.

**Comment by pl** [comment]
Hi,

This is actually a bug in the dependency loader - it should load dependencies via HTTPS when using `encrypted` is set to true. I'll get it fixed as soon as possible. Thanks for reporting.

**Comment by pl** [comment]
Published the new version (2.2.4) today, can you confirm everything is ok now?

**Comment by szwacz** [comment]
Yes, v2.2.4 works as you said it suppose to. Thanks a lot!

**Comment by pl** [comment]
Awesome, thanks for catching it.
