### ISSUE TITLE
Add `withCredentials` flag to auth params

### ISSUE THREAD

**Issue by pl** [pusher/pusher-js#99]
See #62 for discussion and a workaround.

**Comment by Andygmb** [comment]
Any updates on this or a workaround?

**Comment by pl** [comment]
Hi @Andygmb, we're not planning to fix it in the near future, but the workaround from the description should still work fine. We'll keep this issue open for tracking.

**Comment by shwhl** [comment]
It's been a year since last comment, and I think this is something really should have, although we can use the workaround from that description.

**Comment by hph** [comment]
I'm closing "feature request" issues, including this one. This does not mean that the feature will not be implemented, we just want to reserve open GitHub issues to bugs that need to be addressed.

Feel free to comment here to keep the discussion going. People watching the repository will still receive notifications.

**Comment by sandstrom** [comment]
AFAIK this was solved by #211 (hph's message above makes it sound like it hasn't been fixed)

**Comment by hph** [comment]
@sandstrom It hasn't been released yet -- it will be released next week 😄
